### ISSUE TITLE
Allow osd-prepare to skip scanning certain devices not in filter

### ISSUE THREAD

**Issue by Timoses** [rook/rook#10340]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently, it appears that even though as an example `deviceFilter="^sda$"` is set, the `osd-prepare` pods on each node scan all devices. This is very time consuming (especially during debugging).

Before scanning devices, the filters could be applied to rule out devices that need not be scanned.

In my case this would reduce scanning time by a factor of approximately 30 (skipping `loop0-7`, `ram0-15` and 6 partitions on `/dev/mmcblk0`). 

**What is use case behind this feature:**
Potentially very high reduction in run-time of osd-prepare (plus potentially run times of hours; which I have seen issue reports on where scanning certain devices simply causes overly long time scanning).

**Environment**:

Ceph. No specific environment conditions.

**Comment by parth-gr** [comment]
@Timoses can you provide logs(osd-pepare pod), where you saw it's scanning for all devices even after the device filter is added.

**Comment by Timoses** [comment]
@parth-gr Difficult, unfortunately. I decided not to go with rook/ceph as it's too much overhead on the RPi cluster. If I break my cluster I can take a look into it before disaster recovery ; ).

**Comment by Javlopez** [comment]
Hey everyone, after conducting research, I have found a solution to fix the issue. The root cause is due to the filter not being passed to the **clusterd.DiscoverDevices(context.Executor)** function in **pkg/daemon/ceph/osd/daemon.go:206**. To solve the issue, we need to follow these steps:

1.- Iterate over agents to obtain the configuration for each data device:

```go
for i := range agent.devices {
    rawDevice, err = clusterd.DiscoverDevices(context.Executor, agent.devices[i])
    if err != nil {
        return err
    }
    rawDevices = append(rawDevices, rawDevice)
}
```

2.- Update the signature in **pkg/clusterd/disk.go:59** to support the device parameter:

`func DiscoverDevices(executor exec.Executor, dataDevice osd.DesiredDevice) ([]*sys.LocalDisk, error) {`

3.- Apply the filter only if it is set. Check if the filter is set, and then execute another function, **sys.ListDevicesWithFilter(executor, dataDevice.Name)**, which will support a string parameter to make the filter.

4.- Update the function sys.ListDevicesWithFilter in **pkg/util/sys/device.go:123** to the following:

```go
// ListDevicesWithFilter lists all devices available on a machine
func ListDevicesWithFilter(executor exec.Executor, filterName string) ([]string, error) {
	devices, err := executor.ExecuteCommandWithOutput("lsblk", "--all", "--noheadings", "--list", "--output", "KNAME", "|", "grep", filterName)
	if err != nil {
		return nil, fmt.Errorf("failed to list all devices: %+v", err)
	}
	return strings.Split(devices, "\n"), nil
}
```

With this solution, we can keep the filtering when the lsblk command is making the search to avoid overhead.
