### ISSUE TITLE
In Ceph - the upgrade should set noout, nodeep-scrub and noscrub and unset when upgrade will complete

### ISSUE THREAD

**Issue by vumrao** [rook/rook#10619]
Ceph upgrade should set noout, nodeep-scrub, and noscrub and unset when the upgrade will complete

- This was the case when we used to use ceph-ansible
- This is a kind of feature parity b/w ceph-ansible and cephadm

- This feature can be designed as optional with default as True so if some users/admins do not want then can set it to false.

Benefits:

1. Less load from scrubbing during the upgrade when we expect to have recovery in the cluster
2. If an OSD is taking longer to reboot -> boot due to different issues[1](https://tracker.ceph.com/issues/56670#fn1) or slow boot

[1] For example, PG dups issue - https://tracker.ceph.com/issues/53729 - it takes approx 7 to 8 minutes for an NVMe OSD to boot with 50M dups and approx 12-15 minutes for hybrid HDD OSDs
and if an OSD takes more than 10 minutes the Monitor marks the down OSD out and we will have backfill/recovery in the cluster when the upgrade is running and we do not want that
There can be multiple examples hence running the upgrade with the following flags is recommended:

noscrub
nodeep-scrub
noout

Please check the Ceph Orchestrator tracker for cephadm - https://tracker.ceph.com/issues/56670.

**Comment by travisn** [comment]
Setting `noout` and related flags has been discussed in the past around several scenarios such as during upgrades, or during node upgrades. 

 The PDB management does currently set `noout` when a node is draining as mentioned in the [design doc](https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md):
"When an node is drained, we will also delay it's DOWN/OUT process by placing a noout on that node. We will remove that noout after a timeout."

The complexity around setting these flags during upgrade is that the operator could be restarted in the middle of a reconcile, which would disrupt the flow of setting and then unsetting noout. But in the interest of helping with the common case during upgrades, perhaps we can keep it simple with the following approach during reconcile of the OSDs in the cluster controller:
1. If the flags are set (noscrub, nodeep-scrub, noout), reset them (in case the operator was restarted in the middle of an upgrade)
1. Detect if the ceph image is changed in the cluster CR
1. If the ceph image changed, enable the flags 
1. Proceed with the OSD updates
1. After the OSDs are all upgraded, reset the flags

In corner cases such as the operator restarting, the operator would err on the side of reseting the flags instead of allowing them to stay in a state that could be bad data maintenance if they remain set indefinitely. In other words, if the operator is restarted before all OSDs are upgraded, the flags would be reset during the upgrade of the remaining OSDs.

We could expose the setting in cephcluster CR, which is false by default:
```yaml
  # Whether to skip setting the flags during OSD upgrade: noscrub, nodeep-scrub, noout
  # If these flags are skipped, OSDs taking too long to upgrade could cause data backfill
  # and related data maintenance actions by Ceph.
  skipSetOSDUpgradeFlags: false
```

**Comment by vumrao** [comment]
Thank you, @travisn. The proposed approach looks good to me. When all the related tests would pass with ```skipSetOSDUpgradeFlags: true` then the default can be changed to `true`? I will open a downstream RFE bug also so we can verify it end-to-end downstream also!

**Comment by vumrao** [comment]
Downstream bug - https://bugzilla.redhat.com/show_bug.cgi?id=2115558

**Comment by travisn** [comment]
> Thank you, @travisn. The proposed approach looks good to me. When all the related tests would pass with `skipSetOSDUpgradeFlags: true` then the default can be changed to `true`? I will open a downstream RFE bug also so we can verify it end-to-end downstream also!

Reading through this again, perhaps the setting is overkill, or at least setting the default to `true` seems reasonable.

**Comment by vumrao** [comment]
> Reading through this again, perhaps the setting is overkill, or at least setting the default to `true` seems reasonable.

Ahh, I did not read the option correctly now when I read it again :) I think the default `false` means that flags will be set during the upgrade. I understood the opposite sorry,  that is why I was asking the default to change to `true`. In any case in general we want these flags to be true during the upgrade but to start with we can go with default as `true` and when the tests would be fine and maybe in downstream docs we can explain this option that clusters that are larger in size can change this option to `false`.

**Comment by travisn** [comment]
Per discussion with @BlaineEXE, an improvement on the proposal would be to only mark the specific OSD IDs as `noout` for which upgrade is actively in progress. If an OSD has not yet been upgraded or is completed upgrade, `noout` should not apply to it. 

Once implemented, this seems like a reasonable behavior and I don't know why we would need to make a setting available to disable it. One case could be if someone wants full control over the noout, noscrub behavior from the toolbox instead of rook reconciling it. But unless we hear feedback that it's really necessary to have manual control (without starting the operator), I'm inclined to say we don't need a setting.

@BlaineEXE thoughts?

**Comment by BlaineEXE** [comment]
Yes. I was thinking a bit more, and it may be good for Rook to look at the ceph config dump and unset any `noout`, `nodeep-scrub`, and `noscrub` settings set for individual OSDs before every OSD reconcile so that we avoid any corner cases where the operator might crash immediately after updating an OSD but before the `noout` etc are unset and accidentally leave them all set.

**Comment by BlaineEXE** [comment]
I wonder if managing `noout` from OSD reconciliation and PDB management will have race interference if we do this.

**Comment by travisn** [comment]
Agreed on those points to make sure the noout does not stay enabled, and we will need to coordinate between the OSD and PDB reconciles.

**Comment by vumrao** [comment]
Thank you, @travisn and @BlaineEXE for your feedback here. Looks like we planning to use the OSD level noout flag as compared to the cluster-wide noout flag, if I understand the workflow it would be something like following:
https://docs.ceph.com/en/quincy/rados/troubleshooting/troubleshooting-osd/#stopping-w-out-rebalancing

1. Detect the OSD that needs to be upgraded - (restart/reconcile will happen for this OSD)
2. Set noout flag to this before going for the upgrade
`ceph osd add-noout osd.x`
4. Wait for this OSD upgrade to finish
5. upgrade successful unset the noout flag for this OSD
`ceph osd rm-noout osd.x`

If yes sounds good to me because in this case also if OSD is taking more than 10 minutes to boot(stays in the down state from the monitor's point of view) monitor will not mark this OSD out because it will have OSD level noout flag! I think this will work.

Coming to noscrub/nodeep-scrub these options are available either at the global cluster level or per pool basis.

**Comment by vumrao** [comment]
Closing this one, for more details please check the comment - https://bugzilla.redhat.com/show_bug.cgi?id=2115558#c9.
