### ISSUE TITLE
hostNetwork not a spec.gateway setting in CephObjectStore CRD

### ISSUE THREAD

**Issue by jansmets** [rook/rook#10649]
A recent feature introduced the ability to enable/disable hostnetworking for the rgw (perfect timing!)
However the hostNetwork setting should be under spec.gateway instead of spec in the ObjectStore CRD.

https://github.com/rook/rook/blob/release-1.9/pkg/apis/ceph.rook.io/v1/types.go#L1289-L1329

https://rook.io/docs/rook/v1.9/CRDs/Object-Storage/ceph-object-store-crd/#gateway-settings

Thanks

**Comment by thotz** [comment]
@jansmets, do you want to fix the documentation? @zhucan can PTAL ?

**Comment by jansmets** [comment]
> @jansmets, do you want to fix the documentation? @zhucan can PTAL ?

I'd think it's the other way around. It"s a gateway setting, so i'd be tempted to say the crd would need adjusting.

**Comment by travisn** [comment]
> > @jansmets, do you want to fix the documentation? @zhucan can PTAL ?
> 
> I'd think it's the other way around. It"s a gateway setting, so i'd be tempted to say the crd would need adjusting.

Agreed, let's move the setting under the gateway type. It's a new enough feature that the change is worth it. @zhucan Sound ok?

**Comment by zhucan** [comment]
good suggesstion, do you want to fix it? @jansmets

**Comment by zhucan** [comment]
@travisn  sound ok for me.

**Comment by taxilian** [comment]
Ahh, I've been trying to use this feature... I guess now I know why it isn't working :-(  The 1.9 documentation claims `hostNetwork` is in the gateway section but it doesn't seem to do anything.

Since it sounds like this will be changing I put the key both under `spec` and under `gateway` and it looks to be working now! yay!

**Comment by zhucan** [comment]
We plan move it from spec to spec.

**Comment by taxilian** [comment]
Was that supposed to ber "from spec to spec.gateway"? That's what I understood from the comments.

It should be noted though that right now the documentation is wrong, since it says that it is already under spec.gateway and it isn't. I guess this is a new feature, so maybe it's not worth worrying about yet, but it does seem like a somewhat less than ideal situation.

**Comment by travisn** [comment]
@zhucan Would you mind fixing it in the expected place in the spec? thanks

**Comment by zhucan** [comment]
ok
