### ISSUE TITLE
We need to find a way to mount the ceph file system created by rook

### ISSUE THREAD

**Issue by Alan-huan** [rook/rook#10734]
we try to mount the FS outside of Kubernetes, it will not work.
Our first idea was to change the type of service from ClusterIP to NodePort, But when we tried to mount the FS again. Unfortunately it did not work.
We need to find a way to mount the ceph file system created by rook.

**Comment by zhucan** [comment]
set howtNetwork=true to the cluster.yaml, you can try it. @Alan-huan

**Comment by Alan-huan** [comment]
Is there any other way besides using hostNetwork?
I do not want to change it to hostNetwork.

**Comment by Alan-huan** [comment]
Is there any other way besides using hostNetwork? @zhucan 
I do not want to change it to hostNetwork.

**Comment by zhucan** [comment]
I don't know other way. It not same as s3.

**Comment by travisn** [comment]
Since the cluster network is not available outside K8s, the only way really is with host networking enabled. 
Note that configuring with host networking needs to be enabled in a new cluster. An existing rook cluster with the default cluster networking cannot be configured to host networking.

**Comment by taxilian** [comment]
Depending on which CNI you are using and what your setup is you may be able to make it work, but you'd need to make it possible for your machines outside of kubernetes to access the networks inside kubernetes. There are likely a lot of ways to do that, but the one that I've used is to use BGP peering with calico (other CNIs may also be able to do this).

In my setup I have my router (running OPNSense) set up to do BGP peering with all the kubernetes nodes; from there it's just a question of setting up firewall rules to allow traffic from my LAN to route to the kubernetes subnets.

I haven't actually tried mounting ceph stuff this way, since my rook cluster is configured using host networking, but I don't know of any reason this wouldn't work.

It's actually really nice to have the bgp peering set up that way -- I can VPN through the data center router and access pod IP addresses manually. The specifics are a bit off topic for this project, but you can find more info on using calico to do that at https://projectcalico.docs.tigera.io/networking/bgp

**Comment by parth-gr** [comment]
Any reasons why you don't want `hostNetwork` enabled?

**Comment by taxilian** [comment]
> Any reasons why you don't want `hostNetwork` enabled?

I'm not the one without `hostNetwork` enabled, but I can think of a few reasons off the top of my head:

1. If you install your rook cluster without `hostNetwork` enabled there is no easy way AFAIK to change it -- you're stuck unless you can rebuild your cluster

2. There are still at least some things which simply aren't yet fully usable with `hostNetwork` -- specifically I'm thinking of #10749 which is currently keeping me from being able to use CephNFS because I *am* using hostNetwork and there is no way to make the cephNFS pod use regular network when the cluster uses hostNetwork -- they need to be more separate because there is no reason that all sub services should be hostNetwork just because the core cluster is, but currently if one type is hostNetwork (for stability / performance, so you can access it outside of the cluster, or whatever) then nearly everything has to be set to hostNetwork. It's only very recently that they fixed the RGW pods so they can disable it which made it finally possible for me to use them.

**Comment by travisn** [comment]
> * If you install your rook cluster without `hostNetwork` enabled there is no easy way AFAIK to change it -- you're stuck unless you can rebuild your cluster

Note that with #11211 (included in v1.10.5), Rook will allow the host networking setting to be updated. More validation of this conversion would be helpful if you have a test cluster you want to try it on.

> 2\. There are still at least some things which simply aren't yet fully usable with `hostNetwork` -- specifically I'm thinking of [CephNFS - allow setting hostNetwork: false #10749](https://github.com/rook/rook/issues/10749) which is currently keeping me from being able to use CephNFS because I _am_ using hostNetwork and there is no way to make the cephNFS pod use regular network when the cluster uses hostNetwork -- they need to be more separate because there is no reason that all sub services should be hostNetwork just because the core cluster is, but currently if one type is hostNetwork (for stability / performance, so you can access it outside of the cluster, or whatever) then nearly everything has to be set to hostNetwork. It's only very recently that they fixed the RGW pods so they can disable it which made it finally possible for me to use them.

@BlaineEXE Like RGW, makes sense to allow configuration of only the nfs daemon to use host networking if desired. 
@Alan-huan If nfs supported host networking without the entire cluster using host networking? If so, let's update the title of this issue to be clear about the solution.
