### ISSUE TITLE
rook-ceph upgrade fails on kubernetes 1.25 with 1.9.10

### ISSUE THREAD

**Issue by ruckc** [rook/rook#10826]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Upgrade won't succeed

**Expected behavior:**

Upgrade will succeed

**How to reproduce it (minimal and precise):**
1. With kubernetes cluster at version 1.24
2. Install rook-ceph 1.9.9
3. Upgrade kubernetes to 1.25
4. Attempt upgrading rook-ceph to 1.9.10

**Logs to submit**:

```
helm upgrade -i -n rook-ceph --repo https://charts.rook.io/release --values rook-ceph.yaml --version 1.9.10 rook-ceph rook-ceph
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "00-rook-privileged" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04
* Kernel (e.g. `uname -a`): Linux pi01 5.15.0-1013-raspi #15-Ubuntu SMP PREEMPT Mon Aug 8 06:33:06 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
* Cloud provider or hardware configuration: Raspberry PI 4
* Rook version (use `rook version` inside of a Rook Pod): 1.9.9
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.0
* Kubernetes version (use `kubectl version`): 1.25.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm

**Comment by ruckc** [comment]
Seems like this is due to helm trying to compare the prior state (which included the PSP) so it can remove it.

**Comment by travisn** [comment]
@ruckc Did you find a workaround? Not sure what we could do here other than document a workaround.

**Comment by ruckc** [comment]
I have not yet.  Should definitely make recommend upgrading to 1.9.10 prior to upgrading to 1.25.  Still digging into a workaround, so far i'm thinking i'll have to modify the helm release secret to forget about the PSP.

**Comment by parth-gr** [comment]
@travisn 
For a workaround can the users degrade to k8s1.24 and then upgrade the rook and k8s version?

Maybe this can have a fix but we need another patch in which we would fix this, so instead of that, I thought this workaround.

**Comment by taxilian** [comment]
I'm in the same boat, trying to upgrade from v1.10.1 to v1.10.2 and I get the same error

**Comment by taxilian** [comment]
https://github.com/helm/helm/issues/11287 -- related

**Comment by taxilian** [comment]
so I guess the issue is that helm tries to compare previous state (as mentioned above) but because PodSecurityPolicy is no longer a real thing it can't get that, which causes that to fail... huh. that's ... frustrating

**Comment by quetdn** [comment]
Is there any advance on this issue? I am locked in 1.9.9 and I cannot upgrade.

**Comment by quetdn** [comment]
> Several people have now reported that they were able to remove the helm secrets and then re-install with helm and everything worked fine; see [helm/helm#11287](https://github.com/helm/helm/issues/11287) for examples. I haven't tried it yet myself.

Yes @taxilian , I saw that, but I am not sure if it is safe to do it with no risk of losing pools and data.
If you try it, please share it. I have not a test environment to do it.
Also, I hope that rook people will provide us with a proven and safe solution.

**Comment by taxilian** [comment]
I have had several people report no issues doing it. I'll try it soon

**Comment by travisn** [comment]
@taxilian Thanks for the verification!

**Comment by quetdn** [comment]
> I just tried it and had no issues:
> 
> ```shell
> # First delete all sh.helm.release.* secrets
> kubectl -n rook-ceph get secret | grep -i 'sh.helm.release' | awk '{print $1}' | xargs kubectl -n rook-ceph delete secret
> 
> # Next reinstall the helm chart
> helm  upgrade --install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph -f values.yaml
> ```
> 
> The thing to remember is that the helm chart only installs the rook _operator_ -- it doesn't install or mess with your cluster. (at least the way I did it). Your cluster resource is what controls that, so as long as that doesn't change this will just redeploy the operator and it will see the existing cluster, check that everything is good, and life will go on.

@taxilian , I executed those commands and they worked fine. You were right. Yo can add another success on this workaround. Thanks !!!

**Comment by zcourts** [comment]
So we had the same issue (automatic upgrade by cloud provider forced our hand before we were ready) and attempted to remove the helm secret with

```
    kubectl -n rook-ceph get secret | grep -i 'sh.helm.release' | awk '{print $1}' | xargs kubectl -n rook-ceph delete secret
```

As documented this does remove the secret and helm then attempts the install but it failed with:

```
   Release "rook-ceph" does not exist. Installing it now.
   Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "rook-ceph-osd" in namespace "rook-ceph" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rook-ceph"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "rook-ceph"
```

In the end CustomResourceDefinition,ServiceAccount,ClusterRole,ClusterRoleBinding,Role,RoleBinding and others did not have the right labels so helm wouldn't accept responsibility for them.

I use a script to re-label all the resources

```shell
#!/bin/bash

set -e
#set -o pipefail
set -o xtrace
HELM_RELEASE='rook-ceph'
HELM_RELEASE_NAMESPACE='rook-ceph'

kubectl -n rook-ceph get secret | grep -i 'sh.helm.release' | awk '{print $1}' | xargs kubectl -n rook-ceph delete secret


for CRD in $(kubectl get all -n rook-ceph -o=name)
do
    kubectl -n $HELM_RELEASE_NAMESPACE label ${CRD} app.kubernetes.io/managed-by=Helm --overwrite
    kubectl -n $HELM_RELEASE_NAMESPACE annotate ${CRD} meta.helm.sh/release-name=${HELM_RELEASE} --overwrite
    kubectl -n $HELM_RELEASE_NAMESPACE annotate ${CRD} meta.helm.sh/release-namespace=${HELM_RELEASE_NAMESPACE} --overwrite
done
#Note that there are cluster wide resources here and we don't filter our rook specific resources for those
#Above doesn't patch
for CRD in $(kubectl  -n rook-ceph get CustomResourceDefinition,ServiceAccount,ClusterRole,ClusterRoleBinding,Role,RoleBinding -o=name)
do
    kubectl -n $HELM_RELEASE_NAMESPACE label ${CRD} app.kubernetes.io/managed-by=Helm --overwrite
    kubectl -n $HELM_RELEASE_NAMESPACE annotate ${CRD} meta.helm.sh/release-name=${HELM_RELEASE} --overwrite
    kubectl -n $HELM_RELEASE_NAMESPACE annotate ${CRD} meta.helm.sh/release-namespace=${HELM_RELEASE_NAMESPACE} --overwrite
done
```

Pay attention to the note given - there are cluster resources unrelated to rook that get the rook labels added by this script which may not be acceptable for you so change it to suit but otherwise it works as is. Following this the `helm upgrade --install` command given above works.

**Comment by holmesb** [comment]
`Unable to continue with install: ServiceAccount "rook-ceph-osd" in namespace "rook-ceph" exists and cannot be imported`

Seems the [rook-ceph-cluster](https://github.com/rook/rook/blob/2291d00a1cdc228721b6313417f31e26add8b860/deploy/charts/rook-ceph/templates/cluster-rbac.yaml#L10) chart tries to install the same resources (eg service accounts) as the [rook-ceph](https://github.com/rook/rook/blob/2291d00a1cdc228721b6313417f31e26add8b860/deploy/charts/rook-ceph-cluster/templates/rbac.yaml#L6) chart. 

One solution would be to make the [names ](https://github.com/rook/rook/blob/2291d00a1cdc228721b6313417f31e26add8b860/deploy/charts/library/templates/_cluster-serviceaccount.tpl#L9)unique to the release. Currently they're [hard-coded](https://github.com/rook/rook/blob/2291d00a1cdc228721b6313417f31e26add8b860/deploy/charts/library/templates/_cluster-serviceaccount.tpl#L9).

**Comment by travisn** [comment]
Did you set the `operatorNamespace` property in the cluster chart? The overlapping resources shouldn't be created by the cluster chart if the operator namespace is the same as the cluster namespace. For example, see how the resources are skipped [here](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/templates/rbac.yaml#L1-L6) depending on the `operatorNamespace`.

**Comment by Alexis-Commits** [comment]
Hello everyone,

I had the same/similar issue

With rook ceph: v1.5.x, I bumped at k8s v1.25.x  and v1.26.x without looking back and then  ***I realised that we have a problem.***

Due to higher `k8s version >= 1.25.x` the `PodSecuriyPolicy` is [depracated and removed](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/). Creates conflicts until Rook-Ceph [`v1.9.10`](https://github.com/rook/rook/releases/tag/v1.9.10)

```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "00-rook-privileged" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

Because I was deploying without helm chart, I could comment out from `common.yaml` a region

Following the [guide](https://rook.io/docs/rook/latest/Upgrade/rook-upgrade/) respectively for each version

### from v1.5.x to v1.6.11
common.yaml

`# OLM: BEGIN CLUSTER POD SECURITY POLICY`

to..

`## OLM: END CLUSTER POD SECURITY POLICY BINDINGS`

### from v1.6.11 to v1.7.11 
common.yaml (same)

`# OLM: BEGIN CLUSTER POD SECURITY POLICY`

to..

`## OLM: END CLUSTER POD SECURITY POLICY BINDINGS`


### from v1.7.11 to v1.8.10
common.yaml

We commented out a region in common.yaml about `PodSecurityPolicy`
https://github.com/rook/rook/blob/v1.8.10/deploy/examples/common.yaml#L777 to L847 

### from v1.8.10 to v1.9.13
***was staight forward***

**Comment by taxilian** [comment]
> With rook ceph: v1.5.x, I bumped at k8s v1.25.x and v1.26.x without looking back and then _**I realised that we have a problem.**_
> 
> Due to higher `k8s version >= 1.25.x` the `PodSecuriyPolicy` is [depracated and removed](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/). Creates conflicts until Rook-Ceph [`v1.9.10`](https://github.com/rook/rook/releases/tag/v1.9.10)
> 

@Alexis-Commits  Yeah, this sounds like the exact same issue others have. This is somewhat of a fundamental problem with helm and not something that (as far as I know) there is any way for the rook team to fix; check some messages up for the workaround, you need to basically remove the records of the previous helm install and then install with the same settings over top of it; since the actual cluster configuration isn't touched, only the operator and dependencies, that should not cause any data loss.
