### ISSUE TITLE
Revise RGW health checker

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#11031]
**Is this a bug report or feature request?**
* Bug Report (kind of)

In a discussion @cbodley @thotz @alimaredia and I had, Casey expressed some concerns about the health checker. He especially expressed concern that metadata operations on clusters in a multisite configuration are much more expensive than in standalone clusters due to the replication.

Casey suggested that a simple HTTP probe should be sufficient since RGW tests many assumptions when it is running. He also suggested that the current health check that creates a bucket and writes data to it might not fully catch when buckets might not be able to be created by OBC (or soon COSI). I will let @cbodley provide more detail in comments.

Additionally, issues with the CephObjectStore health checker are not uncommon. I have fixed at least 2 in the last 2 years, and this one is currently open: https://github.com/rook/rook/issues/10515. Removing the health checker or greatly simplifying it would help with long-term maintenance where the checker can be broken by side-effects of other modifications.

As a final small note, I don't believe it is the intention of the controller-runtime project that a continuously running goroutine should be updating the status of a resource. In a slack discussion I had with a developer of controller-runtime, he suggested that if a resource needs checked regularly, there is a built-in ability to re-reconcile after a delay (for example, of 30 seconds or 15 minutes) even after a successful reconcile. This would be a more natural way to check health regularly, and I think it would have fewer issues with side-effects breaking the health routine. We could use an `observedGeneration` status to decide if the whole spec/deployments should be checked or if we should only check health.

(@travisn FYI about this conversation being started here upstream.)

**Comment by thotz** [comment]
We do have liveness probe check and readiness probe check for RGW pod IMO that's sufficient which generally whether RGW is accessible and ready to consume than bit heavy this health check routine of creating user then the bucket and deleting them. 
CCing @satoru-takeuchi into this loop

**Comment by satoru-takeuchi** [comment]
IMO {startup, liveness,readiness}Probe mechanish is enough for health check of RGW and rit's nice to remove Rook's own health checker (create bucket, put an object, and delete this bucket).

**Comment by alimaredia** [comment]
@BlaineEXE just to go into a little more detail about where Casey was coming from. 

Sending a curl request to the RGW invokes the same processing of a http request down the rgw_op code paths  and returning a response to the client as creating a user or a bucket. It's just in the curl case http requests aren't to create a bucket or object and the client receiving the response isn't the aws-go-sdk.

For that reason I agree with him that a health check for an RGW doesn't need to be more than a curl to the endpoint.

**Comment by BlaineEXE** [comment]
Thanks everyone for chiming in. Given the complexity of this task and that I have a bit of time right now, I am going to take this on, hopefully quickly.

**Comment by leseb** [comment]
The simple HTTP check looks much simpler indeed, it feels weaker too. I can think of a scenario where the HTTP succeeds because the radosgw process is running but the backend (OSDs) are not ready or failing. So yes the gateway is up and running but all the requests will fail. That's why checking for data creation is ideal and yes perhaps expensive. There is a liveness probe already IIRC but it does not affect the CR status, it is just for Kubelet.
So I believe there is still a scenario where we mark the controller as ready to accept requests but in fact, it's not. Also, keep in mind that many external components rely on that status, so we need to be careful.

To conclude, perhaps this is an extra conservative check and one could argue that we don't do such a thing in Rook for the other components. For instance, we don't create RBD images and write data to them once the OSDs are up and running, the same for CephFS, etc. However, the bucket/user creation + data code we have is a precedent (that doesn't mean it's correct) and definitely more reliable than a simple HTTP on a given path. One additional point is that this code also checks the entire datapath since it goes from the service endpoint.

I hope that helps.

**Comment by BlaineEXE** [comment]
@alimaredia these are the probes on the RGW deployment. Do these look correct for what we want to rely on here, or should they be changed?

- Startup should tell when the RGW has started successfully.
- Liveness should tell if the RGW stops responding, meaning Kubernetes will kill the pod to have it rescheduled. (This is currently the same check as startup.)
- Readiness determines if the RGW is responding to network requests. If it isn't kubernetes will stop directing user HTTP requests to that RGW for a time.

    Liveness:   tcp-socket :8080 delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8080/swift/healthcheck delay=10s timeout=1s period=10s #success=1 #failure=3
    Startup:    tcp-socket :8080 delay=10s timeout=1s period=10s #success=1 #failure=18
