### ISSUE TITLE
upgrade order

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#11040]
* Bug Report

**Deviation from expected behavior:**
ceph has a particular recommended upgrade order. rook doesn't seem to be honoring it:

**Expected behavior:**
The recommendation is followed.

**How to reproduce it (minimal and precise):**
I upgraded from octopus to pacific using rook 1.8.10. The mds's upgraded way too early in the process:
```
rook-ceph-mds-cephfs-a-687bdc55b9-4grh5                1/1     Running       0          5m22s
rook-ceph-mds-cephfs-b-f5c466745-7q5lz                 1/1     Running       0          4m51s
rook-ceph-mgr-a-7b4c7b5bd6-zg7tp                       1/1     Running       0          4m52s
rook-ceph-mon-a-777f58b4fb-frwmm                       1/1     Running       0          6m19s
rook-ceph-mon-e-7fc9d75f69-lm829                       1/1     Running       0          7m12s
rook-ceph-mon-f-5cb9f4f44c-bd2fw                       1/1     Running       0          5m40s
```

even before the osds/mgr.

**Comment by vumrao** [comment]
Thank you, @kfox1111! 

@travisn Looks like rook is not following set order, first MGR, then MONs, and then OSDs and then clients like RGWs, MDSs!

**Comment by travisn** [comment]
There has been much discussion about the ordering in the past, though it's not fully captured...

Originally in Rook all of the reconciles were essentially sequential with mons, mgr, osd, mds, rgw. In #5319 and follow-up fixes, Rook updated the usage of the controller runtime and the controllers started behaving more in parallel. 
- There is still a single controller for the mons, mgr, and osds, and they are still created/updated sequentially in that order. 
- The MDS and RGW controllers have a check for the upgrade scenario, to wait for the mons to be upgraded first, as seen for [MDS](https://github.com/rook/rook/blob/release-1.10/pkg/operator/ceph/file/controller.go#L306-L314) and for [RGW](https://github.com/rook/rook/blob/release-1.10/pkg/operator/ceph/object/controller.go#L324-L333). All of the mon daemons must be updated before mds and rgw are updated. However, they do not wait for the mgr or OSDs. 

The recommendation to update mgr first is really for cephadm since that's where the orchestration lives. I remember conversations with Sage on the ordering that mons first made sense for Rook. As far as other ordering in question, I can't find the discussion that particularly affects mds and rgw. @leseb Do you recall the details of that discussion about the mds and rgw not needing to wait for the mgrs and osds to upgrade?

@kfox1111 Did you observe any issue with the mds being upgraded before the mgr/osds, or this is just precautionary to ensure that there are no side effects to rook's upgrade ordering?

**Comment by kfox1111** [comment]
I had a rook managed cephfs go down and need repairing once. So may or may not be related. I then started paying more attention to watching the upgrades and noticed it doing the different order, and knowing that the manual upgrade notes don't do it that way. But I have no hard proof its a problem.

**Comment by leseb** [comment]
I don't think we had any solid rationale as to why rgw/mds don't wait for osd to be updated. I think it might be on the verge of something like, they are stateless services. There is probably a bit of legacy here as well and this could be a good opportunity to change the upgrade sequence if needed. However, we don't really have proof that the current process is harmful. 

Reading this [page](https://docs.ceph.com/en/quincy/cephadm/upgrade/), it indicates:

> The upgrade order starts with managers, monitors, then other daemons.

So Rook is essentially doing that, like @travisn mentioned Rook doesn't need to start with the mgr.
