### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [rook/rook#11156]
The use-case here is quite simple.

There, is little to no documentation on how to properly take backups of rook-ceph's DATA.

Searching through the documentation site, I found this: https://rook.io/docs/rook/v1.10/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/?h=backup#backup-restore

However, there are indeed, no actual steps for backing up Physical data. 

My ask is simple- document a simple way, for myself and others to backup the data stored in rook-ceph.

As a bonus ask- it would be fantastic if a CRD existed to allow a "snapshot policy" to be configured.

Ie, take a snapshot every day, keep 3 weeks of snapshots. etc.

**Comment by parth-gr** [comment]
Yes there is snapshot functionality available https://rook.io/docs/rook/v1.10/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/#rbd-snapshots
For rbd and cephfs

@Rakshith-R do you wanna add smtg more to it.

**Comment by XtremeOwnageDotCom** [comment]
@Rakshith-R  My goal is to quite simply- have a way to backup the data stored in rook-ceph.

Ideally- in a way, that doesn't involve sending data to another ceph cluster.

I have spent quite a bit of time looking for a method to simply- backup the data over NFS, and, so far, I have came up pretty empty handed.

For me- I have a decent TrueNAS Server with tons of spare capacity for backing up things. It has automatic snapshots, automatic replication offset, everything needed.

If I could figure out a way to backup both the ceph FS, and RDB data to that server via NFS, I would be gold. However, apparently its not a simple task. 

https://backy2.com/ was apparently one of the better solutions for this use-case, however, it is borderline unsupported. 

- https://github.com/wamdam/backy2/blob/master/README.rst#whats-the-state-of-this-project

Benji backup, seems to be a newer fork of this.

- https://benji-backup.me/

However, I would need to figure out how to integrate this with rook-ceph. 


In an ideal world, I would expect rook to expose a CRD, allowing automatic scheduling of snapshots, with a configurable retention policy. 

I suppose, since the CRD does exist, I could start trying to polish up my non-existent bash skills to figure out a way to automate taking snapshots, and removing snapshots past retention.

**Comment by XtremeOwnageDotCom** [comment]
Although, I will note, while doing research during the writing of the above post- I did stumble upon....

https://benji-backup.me/container.html

this seems like it can meet the use-case, and does support rook-ceph.

**Comment by parth-gr** [comment]
@XtremeOwnageDotCom do you want us to integrate https://benji-backup.me/container.html with Rook operator?

**Comment by XtremeOwnageDotCom** [comment]
@parth-gr  to be honest- I am not sure exactly what I am asking for- Just started learning K8s a few weeks ago.

But- my intended goal- is to have an easy method of backing up this data, to an external location.

Coming from my previous experiences- I half-way expected rook-ceph to have some backups functionality, which is what brought me here.

Longhorn, has this feature, for example- https://staging--longhornio.netlify.app/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target/

I guess- my ask- was to have similar functionality within rook-ceph. Ideally, I would imagine it should be a built-in thing, and not another external dependency such as backy2/benji/etc.

**Comment by Madhu-1** [comment]
@XtremeOwnageDotCom Please check do you want whole ceph cluster backup or you want some rbd/cephfs volumes backup?

**Comment by XtremeOwnageDotCom** [comment]
I would prefer having the entire cluster backed up.

**Comment by travisn** [comment]
@XtremeOwnageDotCom Backing up a volume is much different from backing up a storage platform. Ceph has many moving parts so it's much more complicated than backing up a volume. Consider these points:
- Ceph provides redundancy and data safety within a cluster through replication, snapshots, toleration for failure in a topology configuration (whole zones or nodes can go down without affecting the data). 
- Mirroring to another cluster effectively provides off-site backup since the data is copied to another cluster (rbd mirroring, cephfs mirroring, rgw multisite)
- Backup of individual volumes is possible with tools such as Velero.
- If you really want to try backing up the entire ceph platform, we do have [this doc on disaster recovery](https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#backing-up-and-restoring-a-cluster-based-on-pvcs-into-a-new-kubernetes-cluster). It is not meant as a backup solution, but is more about how to restore the storage platform when moving to a completely new K8s cluster. But you can give it a shot and maybe it will work for your backup needs.

**Comment by XtremeOwnageDotCom** [comment]
@travisn  Understood, I do appreciate the feedback received here-

Having spent the last week or two digging, and researching- 

I think either Velero, or Veeam should provide the backup capabilities I am looking for.
