### ISSUE TITLE
ceph-immutable-object-cache

### ISSUE THREAD

**Issue by use-epoll** [rook/rook#11162]
rook version: 1.9.10
How do I use ceph-immutable-object-cache in rook

**Comment by parth-gr** [comment]
This will be a good feature idea, that Rook should have it.

**Comment by use-epoll** [comment]
Thanks, I look forward to your good news!

**Comment by travisn** [comment]
Reading through the ceph docs on [immutable cache](https://docs.ceph.com/en/pacific/man/8/ceph-immutable-object-cache/) and an [RCHS 5 explanation](https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/5/html/block_device_guide/management-of-ceph-immutable-object-cache-daemons#doc-wrapper), I don't see how it could be configured with Rook. The client would need to connect via libceph to the immutable cache daemon on the local node through a socket. The only way to do this in a containerized environment would be if the common path is mounted both in the client pod and in the immutable cache daemon. Rook could easily enough configure the daemon, but how to connect from the clients is the challenge. 
@Madhu-1 Perhaps this has come up with the csi driver?

**Comment by use-epoll** [comment]
Just a suggestion, for example, if I deploy rook-ceph with immutable cache enabled, the ceph_immutable_cache_daemon can be started on the corresponding or tagged node and the socket files can exist in the host's file system namespace in the form of a host mount directory. The ceph_immutable_cache_daemon can also be configured via ceph.conf

**Comment by parth-gr** [comment]
> Just a suggestion, for example, if I deploy rook-ceph with immutable cache enabled, the ceph_immutable_cache_daemon can be started on the corresponding or tagged node and the socket files can exist in the host's file system namespace in the form of a host mount directory. The ceph_immutable_cache_daemon can also be configured via ceph.conf

>if I deploy rook-ceph with immutable cache enabled
BUt how should rook do this if you can explain, What I see in the [docs](https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/5/html/block_device_guide/management-of-ceph-immutable-object-cache-daemons#explanation-of-ceph-immutable-object-cache-daemon_block) is we need to run this cmd on host `[root@ceph-host1 ]# vi /etc/ceph/ceph.client.ceph-immutable-object-cache.user.keyring` so how would it be done for rook-ceph system on minikube??

**Comment by travisn** [comment]
I'm thinking the following approach is our best hope:
- Rook starts a daemonset for the immutable cache daemon. It mounts a host path that other clients can access.
- The client application pod mounts the same host path
- The client's ceph.conf is updated with the needed ceph settings for librbd to connect to the cache. I would hope this would work with the [CSI ceph.conf](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-configuration/#custom-csi-cephconf-settings).

**Comment by BlaineEXE** [comment]
I wonder if it could also be run as part of Ceph-CSI. It could be a sidecar for the driver (not provisioner), and then Rook wouldn't have to create a new daemon type or coordinate where to mount the files on the host: they would just be in the CSI driver pod.

**Comment by nixpanic** [comment]
There are two CSI-driver DaemonSets, one for RBD and one for CephFS. Could the "immutable cache daemon" be included in both?

**Comment by humblec** [comment]
considering this is client side or where app mounts are present its good to club with CSI DeamonSet Pods.  One doubt I have here is , does the enablment of this deamon cause inconsistent read outputs to applications which consume RWX volumes on different nodes ? I see pretty much short explanation about this feature in the referenced doc, so trying to clarify.

**Comment by parth-gr** [comment]
> I wonder if it could also be run as part of Ceph-CSI. It could be a sidecar for the driver (not provisioner), and then Rook wouldn't have to create a new daemon type or coordinate where to mount the files on the host: they would just be in the CSI driver pod.

There can be some settings that can be changed later for this cache like cache size(which should have an option in CR) etc, so how we can configure that,
As I know we use the ENV variable to configure csi.

**Comment by parth-gr** [comment]
> There are two CSI-driver DaemonSets, one for RBD and one for CephFS. Could the "immutable cache daemon" be included in both?

I think it is only for RBD, https://docs.ceph.com/en/pacific/man/8/ceph-immutable-object-cache/
Not sure btw

**Comment by parth-gr** [comment]
> > > I wonder if it could also be run as part of Ceph-CSI. It could be a sidecar for the driver (not provisioner), and then Rook wouldn't have to create a new daemon type or coordinate where to mount the files on the host: they would just be in the CSI driver pod.
> > 
> > 
> > There can be some settings that can be changed later for this cache like cache size(which should have an option in CR) etc, so how we can configure that, As I know we use the ENV variable to configure csi.
> 
> Configmap?
Yes, But do we expose this to users to update this?
I see We just document CRs, right?

**Comment by parth-gr** [comment]
> Considering this is client side or where app mounts are present - its good to club with CSI DeamonSet Pods. One doubt I have here is , does the enablement of this cache deamon cause inconsistent read outputs to applications which consume RWX volumes on different nodes ? I see pretty much short explanation about this feature in the referenced doc, so trying to clarify.

I guess it would be consistent, 
But we can perform a demo....

**Comment by BlaineEXE** [comment]
> > * Rook starts a daemonset for the immutable cache daemon. It mounts a host path that other clients can access.
> 
> But how to enable the daemon, it should be done from the host

@parth-gr , the way CSI works, one instance of a CSI driver is run for each Node. The CSI driver also acts as the client. If a volume is mounted multiple times on the same node, CSI only creates a single mount which is shared by multiple pods. We don't expect Kubernetes applications to connect directly to Ceph themselves, but instead request PVCs that get fulfilled by CSI. Because of all this, I think it makes sense that the immutable cache daemon would run alongside CSI. It would then effectively be a (potentially optional) feature of the CSI driver that allows speeding up CSI volume access via caching.

Unfortunately, Ceph's docs about how the cache is intended to be used are not as useful as Red Hat's docs. There is a really great diagram here: https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/5/html-single/block_device_guide/index#management-of-ceph-immutable-object-cache-daemons

![image](https://user-images.githubusercontent.com/3989526/202266082-c57b8e11-5d78-434e-a877-17fd2817ce48.png)

In this image, we see a user application (QEMU) that uses `librbd` to access Ceph block devices. When the application requests `librbd` for an image, `librbd` can look in the cache for an image. If the image is not present, `librbd` can then connect to the Ceph cluster via `librados` to fetch it. When the image is returned, if the image is immutable (read-only), it `librbd` caches it for the next access.

This situation is not describing a daemon that runs on the Ceph cluster. Instead it runs on client nodes. For example, this might run on VMWare nodes to allow creating commonly-used virtual machines more quickly, without having to transfer images over the network as often.

This diagram further solidifies to me that if this is implemented in Rook, the proper place for it is alongside the only client component we have, which is CSI.

If there are any user applications that manually use `librbd` to access a Ceph cluster (e.g., OpenStack), I think we can reasonably expect those applications to run their own immutable cache daemon since they as clients understand their architecture, and Rook cannot.

From looking at the block diagram, it seems like CSI itself probably doesn't have to do much, if anything to support this daemon. Instead, Rook will need to configure CSI daemonsets to run the cache as a sidecar as needed.

-----

> One doubt I have here is , does the enablement of this cache deamon cause inconsistent read outputs to applications which consume RWX volumes on different nodes ?

@humblec , I hope this won't be an issue, but this is a great question. From what I understand from the Red Hat doc (above), this cache only applies when RBD images are cloned from a parent image. IIRC, RBD image clones can only be made from image snapshots (which are read-only), so "parent image" here should be equivalent to "image snapshot". I think what that all means is that the cache stores copies of RBD image clones.

If I'm right and the immutable object cache only applies for image clones, I think it also means that there is no reason to run the daemon if image cloning is not enabled.

Caching is probably best done by storing cached images persistently via a `hostPath` volume so the images survive daemon reboots. And because users may have nodes where space is a premium, I  think the image cache feature should be optional and disabled by default.

------

> There are two CSI-driver DaemonSets, one for RBD and one for CephFS. Could the "immutable cache daemon" be included in both?

From what I've seen playing with CephFS, it doesn't use RBD images for storing info. I think that means that we only need to run the immutable cache daemon with the RBD driver.

**Comment by parth-gr** [comment]
Thanks Blaine for the description

**Comment by idryomov** [comment]
> From what I've seen playing with CephFS, it doesn't use RBD images for storing info. I think that means that we only need to run the immutable cache daemon with the RBD driver.

Correct, CephFS doesn't use ceph-immutable-object-cache daemon in any way.

Currently ceph-immutable-object-cache is hooked up only in librbd and it's only useful for a hypervisor-like use case where a few golden/base images get cloned repeatedly and accessed from the same node.

**Comment by use-epoll** [comment]
Okay, can I know where to configure csi-rbdplug's ceph configuration so that I can install cache-daemon on the required compute node and mount the socket to csi-rbdplug so that it can communicate with the cache via socket when operating the mounted system volume?

**Comment by nixpanic** [comment]
On Thu, Nov 17, 2022 at 08:06:24AM -0800, Blaine Gardner wrote:
> > This might be a nice feature, but I'd put the priority very low, and maybe investigate what kind of workloads benefit from it, and what additional requirements there are.
> 
> I think that sounds like a good analysis. Currently, I think kubevirt VMs starting up from an RBD clone are likely to be the most common use-case.
> 
> For that to pass through CSI, it seems like kubevirt would have to use the PVC source, that uses the volume cloning APIs. https://github.com/kubevirt/containerized-data-importer/blob/main/doc/datavolumes.md#pvc-source

KubeVirt just uses PVCs indeed. So this would only be useful if the
KubeVirt deployment configures a RBD StorageClass with `rbd-nbd` and not
the default `krbd`. Cloning PVCs is a very common operation for KubeVirt
users, so they might have a benefit from it.

**Comment by awels** [comment]
We (CDI) are working on a cloning mechanism based on snapshots that keeps the snapshot around after the clone is complete, then if you clone the same source again, we won't make a new snapshot and re-use the original one. This is specifically for the use case of some golden images being cloned repeatedly. We found that creating the snapshot was the most expensive operation in a snapshot clone. So eliminating the snapshot did give us a nice improvement in making clones.

**Comment by nixpanic** [comment]
From the Kubernetes Slack #virtualization channel:
![image](https://user-images.githubusercontent.com/400257/202731122-42478443-161e-4de1-b992-12fb79515136.png)

CDI takes a generic approach, and only uses CSI operations, nothing Ceph specific. It might be possible to improve performance even more with `ceph-immutable-object-cache`, but I'd suggest to wait for results with the new CDI feature.

**Comment by idryomov** [comment]
> It might be possible to improve performance even more with `ceph-immutable-object-cache`, but I'd suggest to wait for results with the new CDI feature.

Yeah, the current N-snapshots-for-N-clones scheme is horribly inefficient -- any `ceph-immutable-object-cache`-related improvements would pale when compared to moving to 1-snapshot-for-N-clones scheme.

**Comment by awels** [comment]
One more thing, you can configure CDI to use CSI clone as the preferred clone method. so it won't do snapshots at all. For the short term that might be good enough for the original reported.

**Comment by parth-gr** [comment]
@pkalever we should keep it open or close it,
I remember you were working on it
