### ISSUE TITLE
rook-operator.yaml start failed

### ISSUE THREAD

**Issue by beatlejuse** [rook/rook#1120]
after `kubectl create -f rook-operator.yaml` i have 3 pods with status
```
po/rook-agent-b6wkp rpc error: code = 2 desc = failed to start container "5130c81443510309dd11a274f9720c2919d203177814f1261192b3d82f7b5656": Error response from daemon: {"message":"mkdir /usr/libexec/kubernetes: read-only file system"}
```

how can i change use directory /usr/libexec/kubernetes to another (with read-write rights) ?

**Comment by galexrt** [comment]
@beatlejuse The `/usr/libexec/kubernetes` is the Kubernetes directory for volume plugins. Rook tries to install the rook flexvolume plugin but fails because the directory is read-only on your node(s).
Are you using CoreOS on your node(s)? Then their needs to be a changed done to the kubelet flags. The change is to change the flexvolume plugin path to a read-writeable directory on your node(s), like `/etc/kubernetes/volumeplugins`.
The flag for changing the path is: `--volume-plugin-dir` (also see https://stackoverflow.com/questions/43615185/kubelet-coreos-flexvolume-plugin).

**Comment by beatlejuse** [comment]
@galexrt  yes, i'm using CoreOS (1409.7.0) ))
thank you for answer!
i'm added the key "--volume-plugin-dir" but it doesn't help for me ((

**Comment by galexrt** [comment]
@beatlejuse Does the user you are deploying with has enough permissions to create ClusterRoles? It seems that the user you are trying to deploy rook with, doesn't have enough permissions, see the error message explanation here: https://github.com/kubernetes/kubernetes/issues/26909#issuecomment-315106868.

**Comment by beatlejuse** [comment]
@galexrt yes, i'm deploy by admin.
i'm rebuild my cluster and it started to work))
Thank you!
