### ISSUE TITLE
ObjectBucketClaim user can conflict with previously created users

### ISSUE THREAD

**Issue by haslersn** [rook/rook#11345]
When creating an ObjectBucketClaim with name `name` in namespace `namespace`, Rook will create a user called `obc-namespace-name`. This username might conflict with existing users, e.g.

- if an ObjectBucketClaim with the same name in the same namespace once existed and was deleted or
- ~if an ObjectBucketClaim with the same name in the same namespace exists in a different K8s cluster (multi-site).~ (fixed in #11665)

In particular, in the first case, if the old ObjectBucketClaim was deleted with `reclaimPolicy: Retain`, Rook will fail to create the new bucket with the following error, because the user already owns a bucket.

```
rook-ceph-operator-56f946595-djgv7 rook-ceph-operator 2022-11-23 15:20:36.672025 I | op-bucket-prov: Provision: creating bucket "test-bucket-626a4eb9-6fb3-414b-854e-059619c2cb38" for OBC "test-bucket"
rook-ceph-operator-56f946595-djgv7 rook-ceph-operator 2022-11-23 15:20:36.672072 I | op-bucket-prov: creating Ceph user "obc-test-test-bucket"
rook-ceph-operator-56f946595-djgv7 rook-ceph-operator 2022-11-23 15:20:36.683362 I | op-bucket-prov: successfully created Ceph user "obc-test-test-bucket" with access keys
rook-ceph-operator-56f946595-djgv7 rook-ceph-operator 2022-11-23 15:20:36.687323 I | ceph-object-controller: creating bucket "test-bucket-626a4eb9-6fb3-414b-854e-059619c2cb38"
rook-ceph-operator-56f946595-djgv7 rook-ceph-operator E1123 15:20:36.691341       1 controller.go:204] error syncing 'test/test-bucket': error provisioning bucket: error creating bucket "test-bucket-626a4eb9-6fb3-414b-854e-059619c2cb38": failed to create bucket "test-bucket-626a4eb9-6fb3-414b-854e-059619c2cb38": TooManyBuckets: 
```

Proposed solution: Rook should append a random unique identifier to generate the username and track the generated username in the ObjectBucketClaim spec/status.

**Environment**:
* Rook version: v1.10.6
* External Ceph cluster, Rook has `client.admin` credentials.

**Comment by thotz** [comment]
Another solution is for existing buckets(brownfield) and obc-user-name also exists, rotate keys of obc-user-name and give access to existing bucket via policy(if obc-user-name is not the owner) via bucket policy

**Comment by haslersn** [comment]
I just realized that the same naming scheme is used for the ObjectBucket resources, so there the conflict needs to be resolved, because the ObjectBucket is retained, too.

> rotate keys of obc-user-name

That sounds like a bad idea for me, because maybe somebody uses the retained bucket with existing credentials.

> give access to existing bucket via policy(if obc-user-name is not the owner) via bucket policy

Are you suggesting that the user has access to both the old and then new bucket? I don't like that, because creating an ObjectBucketClaim in the default (greenfield) case should yield credentials that only provide access to the newly provisioned bucket.

**Comment by haslersn** [comment]
Still not fixed

**Comment by haslersn** [comment]
Not stale

**Comment by thotz** [comment]
Initially, this was a random name with the prefix `ceph-user` Later, @BlaineEXE changed the user name into this format. So @BlaineEXE comment on the proposed solution 
Here underlying issue, the user was created with the first OBC which has to retain the policy. So the user is not removed with the bucket as well, to protect the owner of the bucket. We are also setting `MaxBucket` for that user to 0 after the creating bucket. So the end won't able to create a new Bucket from their app. 
Now when the second OBC request comes, since u have used `genBucketname` in ur StorageClass, the same user is create the bucket again for the obc request with a different name, since the user was restricted to the bucket, the request fails.
IMO cleaner way to solve this make the bucket owner different to OBC user, so that when we can delete the OBC user with OBC request. 

Please note OBC user includes `ceph fsid` as well, so it won't collide with multisite use case which u have mention in this issue

**Comment by haslersn** [comment]
Not stale

**Comment by haslersn** [comment]
#11665 fixed the conflict for users between different clusters. But the username will still conflict in case a bucket was retained (`reclaimPolicy: Retain`). @BlaineEXE how about we instead use a random username or a username based on the ObjectBucket's uid?
