### ISSUE TITLE
Install `cephfs-top` in toolbox's image

### ISSUE THREAD

**Issue by ibotty** [rook/rook#11350]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Install `cephfs-top`.

**Environment**:

**Comment by travisn** [comment]
The toolbox runs a [ceph image](https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml#L21), which is built by the [ceph-container repo](https://github.com/ceph/ceph-container). I'd suggest opening an issue in that repo since Rook doesn't control the image. Alternatively, you could create your own image on top of the ceph image that pulls in all the tools you need.

**Comment by ibotty** [comment]
Thank you.  You are totally right.  I opened a corresponding issue.

**Comment by bumarcell** [comment]
Hi, I can find `cephfs-top` in the toolbox pod but when I run it I get `error connecting to cluster: [errno 1] RADOS permission error (error connecting to the cluster)`

Did you manage to get it to work? could I be missing some arg?

**Comment by ibotty** [comment]
I missed the notification.  Most likely too late for you, but for reference:

```
cephfs-top --id admin
```

**Comment by aeleks** [comment]
> I missed the notification. Most likely too late for you, but for reference:
> 
> ```
> cephfs-top --id admin
> ```

Thank you!!! I searched so long for this
