### ISSUE TITLE
Wait for all pgs to become active+clean in upgrade

### ISSUE THREAD

**Issue by tahajahangir** [rook/rook#11352]
**Is this a bug report or feature request?**
* Bug Report (or Bad Behavior!)

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**
Currently the rook operator stops upgrade when only cluster is in ERROR state ([link](https://github.com/rook/rook/blob/2965373ea9b45a475222a84c17fd4fb9008ffb03/pkg/daemon/ceph/client/status.go#L290)). But when a PG is degraded, it's not safe to restart another OSD.

Currently the operator restart the next osds, when some pgs are not clean (e.g. `active+recovering+undersized+degraded+remapped`). I think the operator should wait for all pgs to become `active+clean`. In a busy workload with many objects or slow disks, this can take several minutes or even an hour.

**Environment**:
* OS (e.g. from /etc/os-release): Debian 10 Buster
* Kernel (e.g. `uname -a`): 4.19.0-20-amd64
* Rook version (use `rook version` inside of a Rook Pod): v1.10.5
* Storage backend version (e.g. for ceph do `ceph -v`): 1.6.10
* Kubernetes version (use `kubectl version`): 1.20
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare Metal

**Comment by travisn** [comment]
@tahajahangir Do you have the default settings for `skipUpgradeChecks: false` and `continueUpgradeAfterChecksEvenIfNotHealthy: false`? See this example [cluster.yaml](https://github.com/rook/rook/blob/release-1.10/deploy/examples/cluster.yaml#L36-L39). If these are both false, the operator  is expected to wait indefinitely until it is safe to update the OSDs.

**Comment by tahajahangir** [comment]
‌Yes, I have both. But the problem is definition of *safe*. Operator assumes HEALTH_WARN state as safe, but not all HEALTH_WARN states are safe (e.g. when we have degraded pgs)

**Comment by travisn** [comment]
As long as those settings are false, Rook checks if each osd is `ok-to-stop`, and waits until an osd is safe to stop before updating. Ceph will indicate it's safe to stop an OSD if none of the replicas for PGs on that OSD are unclean. This means that rook is able to potentially update all OSDs in the same failure domain (e.g. zone) since none of those OSDs have overlapping replicas. Does that answer your concern? Or are you seeing that OSDs are being updated even when they are not `ok-to-stop`?
