### ISSUE TITLE
Use AdmissionWebhook to prevent deletion of cephcluster resources

### ISSUE THREAD

**Issue by zeaone** [rook/rook#11354]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

1.Use Admission Webhook to prevent the deletion of cephcluster resources, and prevent the entire cluster from crashing due to deletion of cephcluster resources when administrators make misoperations.
2.How to enable this feature, how it can be disabled, if it's controlled by an operator env var, etc.

**What is use case behind this feature:**

It blocks some commands to delete cephcluster, Like `kubectl delete cephcluster rook-ceph -nrook-ceph`

**Comment by parth-gr** [comment]
We use different finalizers for this,
But what I understand from the above use case is the we need to block deletion cmds.
@travisn thoughts?

**Comment by travisn** [comment]
The expected design has always been to use the finalizers to prevent accidental deletion. That said, it is a pain when the CR is accidentally deleted because then you have to go through a [recovery procedure](https://rook.github.io/docs/rook/v1.10/Troubleshooting/disaster-recovery/#restoring-crds-after-deletion). 

So I could see the desire to prevent the deletion of the CR completely with the [admission controller](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/cluster.go#L66), for example based on an operator env var.

**Comment by zeaone** [comment]
Yes, I encountered this problem in the production environment, causing all resources related to cephcluster to be deleted, so I had to manually pull up the ceph cluster temporarily. Therefore, it is hoped that there can be a webhook that can intercept and delete cephcluster resources, and whether to perform deletion operations can be determined by whether there is a corresponding label on the cephcluster resources. Or some other implementation.

**Comment by willemm** [comment]
If recommend using something like kyverno, where you can quite easily add a policy to prevent deletion of any kubernetes object you wish to protect.

**Comment by zeaone** [comment]
> If recommend using something like kyverno, where you can quite easily add a policy to prevent deletion of any kubernetes object you wish to protect.

Thank you for your answer, I will take a look at Kyverno, but there seems to be no opinion on using Kyverno
