### ISSUE TITLE
External cluster warnings

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#11470]
**Is this a bug report or feature request?**
* Bug Report

Found some warnings and errors which should be looked upon

```
2022-12-21 14:40:30.176720 W | telemetry: failed to set telemetry key "rook/cluster/mon/stretch/enabled". failed to set "rook/cluster/mon/stretch/enabled" in the mon config-key store. output: Error EACCES: access denied: exit status 13
2022-12-21 14:40:30.572253 E | ceph-object-controller: failed to reconcile CephObjectStore "openshift-storage/ocs-external-storagecluster-cephobjectstore". invalid object store "ocs-external-storagecluster-cephobjectstore" arguments: object store name cannot be longer than 38 characters

```

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by BlaineEXE** [comment]
The check that results in this line is present to prevent bugs due to generating other resource names that are longer than 64 chars. The user must rename the object store. It's redundant to call a CephObjectStore resource `*-cephobjectstore`, so I would suggest removing `-cephobjectstore`. 

`2022-12-21 14:40:30.572253 E | ceph-object-controller: failed to reconcile CephObjectStore "openshift-storage/ocs-external-storagecluster-cephobjectstore". invalid object store "ocs-external-storagecluster-cephobjectstore" arguments: object store name cannot be longer than 38 characters`
