### ISSUE TITLE
Rook website is down

### ISSUE THREAD

**Issue by travisn** [rook/rook#11499]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The [rook.io](rook.io) website is not responding. The site is redirected unexpectedly to https://rook-github-io.koor.dev/.

The DNS entry is correct, pointing to [d5oss06co1n9q.cloudfront.net](d5oss06co1n9q.cloudfront.net). Going to this site directly will also result in the site being redirected to rook-github-io.koor.dev.

@galexrt Was there some change in the  mkdocs publishing today? This issue seemed to start around the time the docs were published today after merge of #11127. But I don't see any unexpected changes in the [ghpages](https://github.com/rook/rook.github.io/commits/gh-pages) branch. 

**Expected behavior:**
The Rook website should be up.

**How to reproduce it (minimal and precise):**

Go to [rook.io](rook.io)

**Comment by travisn** [comment]
To find documentation while the website is down, see the docs in github: https://github.com/rook/rook/tree/release-1.10/Documentation

**Comment by galexrt** [comment]
Not on Rook's side, I have unpublished the GitHub pages of our koor-tech/rook.github.io fork (to prevent the old fork, that was used for the mkdocs changes some time ago, to pop-up in search results as well) but no changes to the rook/rook.github.io repo.

I'm still looking for why we have this is at the moment but without AWS access I can't say for sure what might have changed at the moment.
@travisn please ping me on Slack when you are available

**Comment by galexrt** [comment]
Update: Just started up my work computer and checked rook.io there, it seems to be available again (in both normal and private tabs).

@travisn had mentioned that when he `curl`s the website he also gets sent the redirect, but I didn't during testing on other devices. As written please clear the whole Cloudfront rook.io website caches.

***

I think I might know where the issue is/ was coming from.
The `CNAME` file in the `rook/rook.github.io` repo was set at `rook-github-io.koor.dev` for some time it seems, meaning GitHub Pages would "try" to use that domain but that was in use. After we have deleted our fork `koor-tech/rook.github.io` fork that "subdomain" was freed up in GitHub Pages system so it seems that this is why we got this weird redirect going on.

I have removed the `CNAME` file for now, though I would recommend us that we look into removing the whole Cloudfront caching layer as it adds quite some complexity to "hosting" the website + docs from my perspective.

To mitigate this I will for now look into setting up a redirect from the affected `rook-github-io.koor.dev` subdomain to the working `rook.github.io` GitHub pages hosted page, in hopes to decrease the ongoing issue.

**Comment by travisn** [comment]
I see, the cname file was removed in [this commit](https://github.com/rook/rook.github.io/commit/469a65ad70bd44a884e3751b11ecdb43d5ea1df1). It wasn't obvious where to find since it wasn't a PR. Thanks for fixing! I'll close this for now and we can discuss the caching separately.
