### ISSUE TITLE
ceph: patching cephclusters got Forbidden error

### ISSUE THREAD

**Issue by gaord** [rook/rook#11537]
ceph Quincy + rook 1.10.1

running the following ends up with error. The default common.yaml was deployed. It looks like patch should be included under verbs tag. 

bash-4.4$ ceph orch apply mon --placement=5
Error EINVAL: Failed to update cephclusters/rook-ceph: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 13 Jan 2023 05:15:24 GMT', 'Content-Length': '398'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cephclusters.ceph.rook.io \"rook-ceph\" is forbidden: User \"system:serviceaccount:rook-ceph:rook-ceph-mgr\" cannot patch resource \"cephclusters\" in API group \"ceph.rook.io\" in the namespace \"rook-ceph\"","reason":"Forbidden","details":{"name":"rook-ceph","group":"ceph.rook.io","kind":"cephclusters"},"code":403}

**Comment by travisn** [comment]
You're trying to increase the mon count to 5? For now I'd recommend editing the CephCluster CR directly to increase the count. The orch module really doesn't support updates to the CephCluster CR well. Are you also using other `ceph orch` commands? We need to have an understanding of the scenario to support `ceph orch` commands since editing the CRs directly is the expected approach in Rook. The dashboard is the primary scenario to support the orchestrator module, rather than CLI updates, although it will be possible to use the `ceph orch` from the CI if the dashboard requires those commands.
@jmolmo fyi

**Comment by gaord** [comment]
just submit a PR for this issue:
https://github.com/rook/rook/pull/11538

it should works just fine.
@travisn @jmolmo

**Comment by jmolmo** [comment]
@gaord, as @travisn commented, if you are managing the cluster from CLI the right way to do is to modify the cluster CRD directly to apply any change to the cluster configuration. 
If you use the Orchestrator (thanks for fixing the bug) the modification is not going to be set in your cluster CRD. Is this important for you?
can you describe a little bit more your use case ? why are you using the rook orchec¡strator?

**Comment by gaord** [comment]
@jmolmo  in my case, ceph cluster was deployed with rook and rook should be the orchestrator then if necessary. Lots of functionalities (nfs export, managing daemons like mon, mgr etc. and many more) of ceph CLI depends on orchestrator backend. So in this case the rook as orchestrator backend becomes a necessity.
another point is, it would be nice for rook as orch backend to give operator the same toolset experience as cephadmin. I know both backends' functionalities are not equally developed, however those in place would rather be behaving the same as the peer backend. Thus would save ceph cluster operators's energy no bothering with the k8s stuff underneath.

**Comment by travisn** [comment]
> @jmolmo in my case, ceph cluster was deployed with rook and rook should be the orchestrator then if necessary. Lots of functionalities (nfs export, managing daemons like mon, mgr etc. and many more) of ceph CLI depends on orchestrator backend. So in this case the rook as orchestrator backend becomes a necessity. another point is, it would be nice for rook as orch backend to give operator the same toolset experience as cephadmin. I know both backends' functionalities are not equally developed, however those in place would rather be behaving the same as the peer backend. Thus would save ceph cluster operators's energy no bothering with the k8s stuff underneath.

That is an interesting perspective. Rook's goal is to make Ceph work well with K8s, and to hide the complexities of Ceph. Now you have a different approach, which is to have a consistent approach to manage Ceph, while trying to hide complexities of K8s. 

The challenges we have found with the rook mgr modules include:
1. Versioning: If all the management layer stays in Rook, Ceph can remain the data layer. This is a clean separation for versioning since Rook and Ceph have separate timelines. But since the mgr orchestrator module is part of the Ceph repo, there are more versioning concerns since you are putting some of the management layer into the Ceph repo. 
   a. Test validation is complex. Rook tests multiple versions of Ceph, but Ceph doesn't test multiple versions of Rook. 
   a. If you merge a fix to Ceph, it generally takes a lot longer to be released. 
2. Finding developers who have time to improve the module. We really need someone full time and dedicated to the rook mgr module if it is going to become stable.

Not saying it can't be done, just that it hasn't been prioritized.

**Comment by gaord** [comment]
IMO, rook could be a good operating tool for ceph in deploying, upgrading, removing and some operating stuff with ceph cluster. Anyway, people love to run things in k8s for good reasons. For things of daily operation of ceph cluster, ceph cli is unsubstitutable for editing CR in k8s demands knowledge of low level about ceph itself quite often. Here rook mgr module as orchestrator can do good to it. As you say rook has much to do to catch up with cephadmin. I'll see how to contribute it overtime. Hope it helps.
