### ISSUE TITLE
Having issues with accessing ceph mon externally

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [rook/rook#11632]
I have created a ceph cluster that uses host networking and created a block pool for storage. Everything is working fine from within the same cluster and on clusters that share the network.

Although the nodes are private, as intended other consumers that are connected to the same network can access ceph. The issue however is that I want to also expose this ceph mons to external networks. 

I tried creating NodePort/LoadBalancer services, did NATing to forward request from public to private mon IPs but nothing seems to work.

From within the ceph pod I get this:

```
bash-4.4$ curl <PUBLIC_IP>:3300
ceph v2
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.

bash-4.4$ rbd ls --pool=my-pool --id=my-id --key=my-key --namespace=test -m=192.168.4.4:3300
csi-vol-1d094567-a6ee-11ed-9db3-7e4893b6a397

bash-4.4$ rbd ls --pool=my-pool --id=my-id --key=my-key --namespace=test -m=<PUBLIC_IP>:3300
2023-02-07T14:30:55.792+0000 7fc0a4e56700  0 --2- 192.168.4.1:0/1513756814 >> v2:<PUBLIC_IP>:3300/0 conn(0x55eeaefaa090 0x55eeaefaa4e0 unknown :-1 s=AUTH_CONNECTING pgs=0 cs=0 l=0 rev1=1 crypto rx=0 tx=0 comp rx=0 tx=0).send_auth_request get_initial_auth_request returned -2
2023-02-07T14:30:56.000+0000 7fc0a4e56700  0 --2- 192.168.4.1:0/1513756814 >> v2:<PUBLIC_IP>:3300/0 conn(0x7fc094001d80 0x7fc094004200 unknown :-1 s=AUTH_CONNECTING pgs=0 cs=0 l=0 rev1=1 crypto rx=0 tx=0 comp rx=0 tx=0).send_auth_request get_initial_auth_request returned -2
```

I think RGW won't work in my case either since I'm using block storage instead of object storage. Are there any workarounds for this?

**Comment by travisn** [comment]
The Ceph mons must be addressable by the same IP that is used internally or externally to the cluster. Setting up the cluster with host networking is usually the simplest way to do this. There are also other solutions such as multus that may help. You can't setup the nodeport or loadbalancer since Ceph will reject the requests that don't come on the expected IP. You'll need to use the host network that is addressable from external. 

If you're using object storage, the RGW service can have a load balancer in front of it. But if you need block storage, this is a requirement for the IP address to be addressable.

**Comment by ahmedwaleedmalik** [comment]
Thanks @travisn, it makes sense now.

**Comment by TS-33** [comment]
If you want external nodes to access Ceph's storage resources, I recommend assuming a VPN tunnel between the two.
