### ISSUE TITLE
Rook pods crashing on Windows node

### ISSUE THREAD

**Issue by smoms** [rook/rook#11670]
Hi,

I am running a K8s cluster (RKE2) on an Hyper-V Windows Server 2022.
I have 2x Linux VMs Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux and the Rook cluster is running just fine.
However I have added another node Windows Server 2019. And it seems to start having problems.
First a Windows application pod (RavenDB) does not start giving the error:

`Warning  FailedMount             3s (x4 over 7s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-9fbb5156-7731-46e0-ab7b-ddd37360cffb" : [kubernetes.io/csi](http://kubernetes.io/csi): attacher.MountDevice failed to create newCsiDriverClient: driver name [rook-ceph.cephfs.csi.ceph.com](http://rook-ceph.cephfs.csi.ceph.com/) not found in the list of registered CSI drivers`

I noticed also that the Rook cluster pods:

![image](https://user-images.githubusercontent.com/10290444/218782770-f40c09bb-acae-496a-9609-05d612092bd4.png)

`csi-cephfsplugin` and `csi-rbdplugin` supposed to run on the Windows node are failing (`ImagePullBackOff`) with error:

`9036 connection.go:173] Still connecting to unix:///csi/csi.sock`

Sorry if the question is trivial, as I am new to it but am I right that it is because Rook is not supported on Windows? If so, is there any plan for it?

thanks

**Comment by travisn** [comment]
It's not supported, you’ll need to add node affinity so that the [csi drivers](https://github.com/rook/rook/blob/release-1.10/deploy/examples/operator.yaml#L181-L256) and [ceph daemons](https://github.com/rook/rook/blob/release-1.10/deploy/examples/cluster.yaml#L147-L156) don’t run on the windows nodes. 

I understand there is a ceph driver for windows, but not sure it's even experimental yet. 
@Madhu-1 Is there an issue tracking Windows node support in the csi driver?
