### ISSUE TITLE
Ceph-fuse support for --client-quota

### ISSUE THREAD

**Issue by hacor** [rook/rook#1183]
Hello,

As stated in #1015 there will be a future implementation for the ceph-fuse client to mount cephfs. 
This way I want to ask if it could be possible to implement the `--client-quota` option for the fuse client, so the  [quota option from CephFS](http://docs.ceph.com/docs/jewel/cephfs/quota/) could be used in pods using the @galexrt  proposed method on Slack using [postStart handles](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/)

Thanks in advance!
Best regards,

Hacor

**Comment by galexrt** [comment]
An implementation to tell the `ceph-fuse` to use the `--client-quota` arg could be to add an arg/paramter to the flexvolume mount "specification".

When the CephFS is mounted by rook and the arg from above is added/set one could use a) an K8s privileged init container in the manifest to set the quota or b) a logic on rook' side to automatically set a quota on a path.

**Comment by kokhang** [comment]
@hacor quota is not yet supported but im formulating a design to get filesystem dynamically provisioned. https://github.com/rook/rook/pull/1152

This will add quota support for Filesystem. The quota would be designed similar https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/cephfs, which is setting the `ceph.quota.max_bytes`.

**Comment by hacor** [comment]
@kokhang Thanks for the reply! It sounds very interesting!
I read in #1152 that the current milestone is 0.7. Any idea about the release date?

Best regards!

**Comment by kokhang** [comment]
@hacor we are aiming 0.7 to be available right after the kubecon

**Comment by amitkumarj441** [comment]
@kokhang I am willing to take up this task (if it's not assigned) and I guess existing Ceph kernel client has the following drawbacks:

•	Kernel client does not support client-enforced quotas.
•	Kernel CephFS doesn't support quota or capacity, capacity requested by PVC is not enforced or validated.
•	Kernel CephFS doesn't work with SELinux, setting SELinux label in Pod's security context will not work.

Ceph-fuse support in the command to display the specified secret, it may take some time to support, because it involves `LibFUSE`. Whereas, ceph-fuse has stability, quota function, expansion, upgrade and other advantages. Although ceph-fuse only supports the secret file way, but pushing it into the community makes a very meaningful thing.

I'll find someone around `rook_io` booth in KubeCon to discuss more.

**Comment by bassam** [comment]
@amitkumarj441 that would be great! adding fuse support will help tremendously.

**Comment by kokhang** [comment]
@amitkumarj441 yes. Feel free to take it. I started experimenting with ceph-fuse. But you do need to have [mount propagation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation) enabled in order for agents to perform and mount and become visible in the nodes. This feature is gated since it is alpha so users will have to enable it.

**Comment by hacor** [comment]
I was wondering whether there was some evolution on this matter?
