### ISSUE TITLE
It should be possible to scale rook-ceph-operator to 0 replicas via helm deployment

### ISSUE THREAD

**Issue by TomHellier** [rook/rook#11927]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
According to the documentation, it is occasionally necessary to scale the rook-ceph-operator to 0 replicas while performing administrative actions. See [rook/ceph-osd-mgtmt.md](https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Advanced/ceph-osd-mgmt.md). This should be possible to achieve using helm overrides.

**What is use case behind this feature:**
I used argocd to provide gitops to my deployments, this means that I can often be fighting what argocd believes the true state of the cluster should be. Running this command invalidates what argocd thinks should be deployed, so argocd attempts to scale the replicas back up.
```
kubectl -n rook-ceph scale deployment rook-ceph-operator --replicas=0
```

**Environment**:

kubernetes 1.25
argocd
rook-ceph 1.11.1

**Comment by travisn** [comment]
@TomHellier If we made the [operator replica count](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/deployment.yaml#L10) configurable via values.yaml, this would satisfy argocd, right? 

Though this presents a challenge for the [krew plugin](https://github.com/rook/kubectl-rook-ceph) commands that may automatically scale down the operator since the plugin isn't aware of the helm deployment. If there is some other way to get argcd to ignore that value temporarily that would be ideal. @subhamkrai fyi

**Comment by TomHellier** [comment]
@travisn It is possible in several ways to get argocd to temporarily ignore the "sync" status of resources, you can temporarily disable the sync feature, and also selectively ignore differences with the desired state. 

I haven't used the krew plug in yet as I always use the ceph toolbox pod.

I guess a boolean for "rookOperatorPodEnabled" would solve the problem as I don't think it is valid to have more than one replica of the operator.

I'm happy to make the helm change that I'm looking for, but we can close this entirely if you think it would cause issues with the krew plugin.
