### ISSUE TITLE
pool:  support to create pool with assigned pgs and can disable "autoscale_mode"

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11964]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**
https://github.com/rook/rook/discussions/9950

**Environment**:

**Comment by zxl716** [comment]
I also disabled the operation pool before, pg_autoscaler cannot be disabled, since it exists, it should be disabled.

bash-4.4$ ceph osd pool autoscale-status
POOL                           SIZE  TARGET SIZE  RATE  RAW CAPACITY   RATIO  TARGET RATIO  EFFECTIVE RATIO  BIAS  PG_NUM  NEW PG_NUM  AUTOSCALE  BULK
........
.nfs                          5452                 3.0        30720M  0.0000                                  1.0      32              on         False
.......

bash-4.4$ ceph osd pool set .nfs pg_autoscale_mode off
set pool 12 pg_autoscale_mode to off
bash-4.4$ ceph osd pool autoscale-status
POOL                           SIZE  TARGET SIZE  RATE  RAW CAPACITY   RATIO  TARGET RATIO  EFFECTIVE RATIO  BIAS  PG_NUM  NEW PG_NUM  AUTOSCALE  BULK
......
.nfs                          5452                 3.0        30720M  0.0000                                  1.0      32              off        False
......

**Comment by zhucan** [comment]
```
[root@rook-node01 deeproute]# ceph osd pool autoscale-status | grep test2
test2                                          0                 3.0        600.0G  0.0000                                  1.0      32              on         False  
[root@rook-node01 deeproute]# ceph osd pool set test2 pg_autoscale_mode off
set pool 17 pg_autoscale_mode to off
[root@rook-node01 deeproute]# ceph osd pool autoscale-status | grep test2
test2                                          0                 3.0        600.0G  0.0000                                  1.0      32              off        False  
```
so your question is？

**Comment by zxl716** [comment]
Why did the toolbox operation fail?

**Comment by zhucan** [comment]
> I also disabled the operation pool before, pg_autoscaler cannot be disabled, since it exists, it should be disabled.
> 
> bash-4.4$ ceph osd pool autoscale-status POOL SIZE TARGET SIZE RATE RAW CAPACITY RATIO TARGET RATIO EFFECTIVE RATIO BIAS PG_NUM NEW PG_NUM AUTOSCALE BULK ........ .nfs 5452 3.0 30720M 0.0000 1.0 32 on False .......
> 
> bash-4.4$ ceph osd pool set .nfs pg_autoscale_mode off set pool 12 pg_autoscale_mode to off bash-4.4$ ceph osd pool autoscale-status POOL SIZE TARGET SIZE RATE RAW CAPACITY RATIO TARGET RATIO EFFECTIVE RATIO BIAS PG_NUM NEW PG_NUM AUTOSCALE BULK ...... .nfs 5452 3.0 30720M 0.0000 1.0 32 off False ......

The prints show it's ok to diable  the autoscale mode, isn't it?

**Comment by zxl716** [comment]
> 

I want to know why it fails and I want to understand why. do you know thank you

**Comment by zhucan** [comment]
@zxl716 https://github.com/ceph/ceph/blob/b5d6ca7a8fbfb16c8867accaa777ca2a79bd8717/src/mon/MgrMonitor.cc#L73 Please take a deep look at this code, it's always enable in the modules of ceph mgr, we can not disbable it.

**Comment by zhucan** [comment]
The "always_on_modules" can not disable.
```
[root@node01 deeproute]# ceph mgr module ls 
{
    "always_on_modules": [
        "balancer",
        "crash",
        "devicehealth",
        "orchestrator",
        "pg_autoscaler",
        "progress",
        "rbd_support",
        "status",
        "telemetry",
        "volumes"
    ],

```

**Comment by zxl716** [comment]
Thanks

**Comment by microyahoo** [comment]
I think we can mark this one as done now

**Comment by travisn** [comment]
Discussion in #11967 is that this is possible with `parameters` on the pool CR, so we can close this
