### ISSUE TITLE
How to reduce number of OSDs per drive?

### ISSUE THREAD

**Issue by echel0n-TR** [rook/rook#12144]
Hi,

How can someone reduce the number of OSDs per drive using the latest stable version of rook-ceph?

We tried just changing `osdsPerDevice` in the rook-ceph-cluster helm chart values from 5 to 1 but that didn't seem to reduce them, we have 30 NVMe drives with 5 OSDs per drive, each server has 80GB dedicated network card and we seem to be hitting some kind of bottleneck, we use all default settings, would reducing the number of OSDs even help resolve the bottleneck?

Thanks!

**Comment by sp98** [comment]
Rook does not remove OSDs automatically when osdsPerDevice count is reduced. If the admin decides they really need to remove OSDs they should do it as a one-time action that they intentionally run rather than the operator attempting to manage the deletion with desired state.

You can refer this [doc](https://github.com/rook/rook/blob/eaf3e3662d49d0c3734295ccb9de05ba4158e3e6/Documentation/Storage-Configuration/Advanced/ceph-osd-mgmt.md#remove-an-osd) on various ways to remove the osds. 

You can also reach out to rook slack channel for more such discussions.

**Comment by thenamehasbeentake** [comment]
You can remove 5 osds on an Nvme drive and create one 1 osd with drives to reduce number. But you'd better figure out where the bottleneck is first.

**Comment by echel0n-TR** [comment]
closing this issue out as we managed to reduce the OSDs from 5 to 1, just was a lot of work wiping drives 1 node at a time and letting them recover.
