### ISSUE TITLE
Manage OSD resources by CRD

### ISSUE THREAD

**Issue by pengln** [rook/rook#12330]
Thank you so much for having rook's help, it makes using ceph with kubernetes so much easier and more efficient to manage. 
Although he is so convenient, I still encountered difficulties in using it. That is, when managing the OSD. As you know in a production environment, it's very normal to add new drives to existing nodes. Especially when there are hundreds of servers, it can be painful and dangerous. It has to be done very carefully, and without the opportunity for validation. 
The power of rook lies in its standardized management, so I hope rook can add osd's management features.

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Manage OSD resources by CRD

**What is use case behind this feature:**
1. We can use a crd to add new disk to osd resources.
2. We can display osds from cli like `kubectl get cephosd` 
3. We can delete osd resource if resouce is add from crd
5. We can use `kubectl get` command to get osd's status. eg: usage, max, node, pgp ...

**Environment**:

debian:     11.6
kubernetes: 1.25.10
ceph:       1.10.6

**Comment by sp98** [comment]
This is something that rook krew plugin should be able to handle. https://github.com/rook/kubectl-rook-ceph
@pengln What do you think?  I would suggest to open a feature request in rook krew plugin project.

**Comment by pengln** [comment]
The way you mentioned the CLI is also a very good suggestion. It might be a little different than what I had in mind though. If OSD maintenance could be combined with GitOps in a cloud-native way, so that the storage part of the base setup becomes a service provided to the cluster, the management of the cluster would be clearer and more visual, wouldn't it?

**Comment by travisn** [comment]
OSDs are the most complex resource that Rook creates in Ceph. Maintainers have had multiple design discussions about the possibility of managing OSDs with their own CRD. There could be advantages as you mentioned in this issue, but still we have kept the OSD management designed to be a part of the CephCluster CR for many reasons such as:
1. Upgrading OSDs must be done with a very specific ordering, so that only OSDs in the same failure domain are down at a time, to keep data available. 
2. Managing individual devices with a CR would be a lot of overhead if you have many OSDs. 
3. OSDs have many configuration options and factoring out the code to a new controller is just not ever going to happen unless we are extremely convinced of the new design approach. 
4. When a new disk is added, you can trigger the creation of the OSD either by restarting the operator or by running the discovery daemon (disabled by default). New OSDs are prioritized over updating existing OSDs, so the new OSD should be created quickly. Other OSDs are not expected to restart since they would have no updates. 
5. While a full reconcile of the cephcluster CR is required to create or reconcile OSDs, it is more predictable for OSDs in case of upgrades (update mons first, then mgr, then OSDs), update OSDs by failure domain, etc.
6. To query individual OSD status, it will be better to query a `ceph` command for most accurate info. If Rook updated status on an OSD CR, the status may not be as accurate. 
7. Removing OSDs automatically is intentionally not ever done by Rook. If you deleted an OSD CR, would you expect the OSD to be cleaned up and wiped? That could lead to data loss. But if Rook didn't clean up the OSD when the CR is deleted, it wouldn't make sense either.
8. Another option to manage individual disks is to create individual local PVs for each disk (either with static PVs and no-provisioner, or an operator like Local Storage Operator or TopoLVM to create the PVs). Then you can use `storageClassDeviceSets` to increase the number of desired OSDs, and Rook will then bind a new OSD to that new PV.

While an interesting idea, I don't see the Krew plugin as a realistic option to create OSDs. Creating OSDs is just too complicated.

**Comment by pengln** [comment]
> OSDs are the most complex resource that Rook creates in Ceph. Maintainers have had multiple design discussions about the possibility of managing OSDs with their own CRD. There could be advantages as you mentioned in this issue, but still we have kept the OSD management designed to be a part of the CephCluster CR for many reasons such as:
> 
> 1. Upgrading OSDs must be done with a very specific ordering, so that only OSDs in the same failure domain are down at a time, to keep data available.
> 2. Managing individual devices with a CR would be a lot of overhead if you have many OSDs.
> 3. OSDs have many configuration options and factoring out the code to a new controller is just not ever going to happen unless we are extremely convinced of the new design approach.
> 4. When a new disk is added, you can trigger the creation of the OSD either by restarting the operator or by running the discovery daemon (disabled by default). New OSDs are prioritized over updating existing OSDs, so the new OSD should be created quickly. Other OSDs are not expected to restart since they would have no updates.
> 5. While a full reconcile of the cephcluster CR is required to create or reconcile OSDs, it is more predictable for OSDs in case of upgrades (update mons first, then mgr, then OSDs), update OSDs by failure domain, etc.
> 6. To query individual OSD status, it will be better to query a `ceph` command for most accurate info. If Rook updated status on an OSD CR, the status may not be as accurate.
> 7. Removing OSDs automatically is intentionally not ever done by Rook. If you deleted an OSD CR, would you expect the OSD to be cleaned up and wiped? That could lead to data loss. But if Rook didn't clean up the OSD when the CR is deleted, it wouldn't make sense either.
> 8. Another option to manage individual disks is to create individual local PVs for each disk (either with static PVs and no-provisioner, or an operator like Local Storage Operator or TopoLVM to create the PVs). Then you can use `storageClassDeviceSets` to increase the number of desired OSDs, and Rook will then bind a new OSD to that new PV.
> 
> While an interesting idea, I don't see the Krew plugin as a realistic option to create OSDs. Creating OSDs is just too complicated.

It is very encouraging to see your detailed answer. Thank you for your detailed and patient answers. I would like to give you some of my thoughts on your answer. 

Disk additions may not be fully managed by CR's autodiscovery, for example we may need to add a disk to the host log and it may be added to the OSD by mistake.

We don't need to use OSD's CRD to handle all OSD operations, we just need to implement a CRD that notifies OSD of a new request when a new disk is added to local storage. We also need a CRD that can remove the OSD device from the cluster by deleting it. But we don't actually need to delete the OSD's data. It doesn't make sense to update an OSD's CRD. It's more like a simple wrapper for the ceph osd command in ceph-tool.

**Comment by zhucan** [comment]
@pengln maybe you can develop a management platform base on rook

**Comment by travisn** [comment]
> Disk additions may not be fully managed by CR's autodiscovery, for example we may need to add a disk to the host log and it may be added to the OSD by mistake.

To create OSDs there multiple ways for Rook to discovery them, with `useAllDevices: true`, or `deviceFilter` based on device name, or if `useAllNodes: false`, you can specify individual device names in the `nodes` section. Have you tried adding individual devices in the `nodes` section? Or using the `deviceFilter`? Or please explain more how the existing options don't help with your scenario.

> We don't need to use OSD's CRD to handle all OSD operations, we just need to implement a CRD that notifies OSD of a new request when a new disk is added to local storage. 

So you mainly need to trigger the OSD creation on a specific disk? The `nodes` section already has this ability for specific disks on specific nodes. 

> We also need a CRD that can remove the OSD device from the cluster by deleting it. But we don't actually need to delete the OSD's data. It doesn't make sense to update an OSD's CRD. It's more like a simple wrapper for the ceph osd command in ceph-tool.

To remove an OSD, there is an [OSD purge job](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-osd-mgmt/#purge-the-osd-with-a-job) or a [Krew plugin command](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-osd-mgmt/#purge-the-osd-with-krew). Have you tried these?

**Comment by pengln** [comment]
Looks like I'll have to tune the cluster disk allocation issue via CR.
