### ISSUE TITLE
watch-active service in mgr sidecar using more than allocated limit, causing crashes

### ISSUE THREAD

**Issue by ideepika** [rook/rook#12463]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
had to adjust the limit to 2GB and still seeing crashes
**Expected behavior:**
should use 100 MB allocated limit for watch-active service

CPU spikes and crashes observation, logs lost due to crash
![image (3) (1)](https://github.com/rook/rook/assets/22215384/5529a50c-bb09-4009-8e9b-dcf7c7bf09d9)

**Comment by guillaume1987** [comment]
I observe the same behavior. How did you finally fix this @ideepika ?

**Comment by travisn** [comment]
A few questions, since we don't have many details of what is happening, and I haven't seen a repro.
- What version of Rook? 
- What version of Ceph?
- How quickly does the memory usage grow?
- Does it help to increase the sidecar resource limits, or the memory will anyway keep growing until it restarts?
