### ISSUE TITLE
Add watcher for rgw pods

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12526]
**Is this a bug report or feature request?**
* Feature Request

There is no status update if rgw pod is down,
Only re-starting the operator reconcile the cluster and brings back the rgw pod

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by parth-gr** [comment]
@thotz do we need this

**Comment by BlaineEXE** [comment]
I'm not sure about this. I've been thinking about this for quite some time. In the past, the status of the CephObjectStore was set based on the internal health checker that we removed due to its impact on the RGW. We moved to treat the readiness probe as the source of truth. 

We do need to revisit the RGW liveness probe (which is disabled due to advice we got from the RGW team in the past) to implement a probe similar to the one recently made for the MDS.

I'm not sure if we should pass through the RGW deployment status to the CephObjectStore though. 

On one hand, users can the information directly from the RGW deployment, and we don't need to maintain complex code to copy the deployment status to the CephObjectStore. We don't do this for MDS for the CephFilesystem, nor NFS-Ganesha for CephNFS. Or other daemons.

On the other hand, it might be good for Rook to do a better job of status reporting status like this for all resources. And it would be a lot of work. More than you would expect, unless there are ways to use something like the downward API to reference one status from another status.
