### ISSUE TITLE
Deleting old (non-flexvolume) volume causes panic

### ISSUE THREAD

**Issue by Ulexus** [rook/rook#1252]
There is no checking that the FlexVolume is actually populated, [here](https://github.com/rook/rook/blob/master/pkg/operator/provisioner/provisioner.go#L144).   FlexVolume happens to not be populated if the PersistentVolume in question was created using the pre-0.6.0 rook.

**Comment by kokhang** [comment]
@bassam @jbw976 @travisn. This is a result of an API change in Rook. This happens when Rook provisioned a volume to use the old rbd-plugin (0.5.x or older), and after upgrade, the same volume is trying to delete.

Since Rook is still alpha, which means API changes could still happen and since 0.6.x is the first version of Rook to be upgradable, should this issue be solved? If so, Rook would have to check if the volume to be deleted was created to be used with the old rbd-plugin. Please advice.

**Comment by jbw976** [comment]
@kokhang in general, while we are still in alpha, it is not necessary to add logic for how to handle legacy conditions.  However, for this issue, the result is a panic which crashes the operator.  The fix @Ulexus added in #1253 to simply check for nil and avoid panicking looks good enough to me.
