### ISSUE TITLE
Insecure privileged mode in Rook's OSD pods

### ISSUE THREAD

**Issue by liumiaomiaoIntel** [rook/rook#12557]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Turn off privileged mode of Rook's OSD pods when running, at least for OSD pods on PVC. And use [device plugin](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) to schedule and allocate devices to OSD pods when needed. In my humble opinion, according to [Rook](https://github.com/rook/rook/blob/master/design/ceph/dedicated-osd-pod.md), Device Discovery DaemonSet and Device Provisioner pod may need to be as privileged to discover and provision devices on hosts, but Ceph OSD Pods don't need to run in privileged mode.
 
**What is use case behind this feature:**
So far,  the OSD pods run as privileged, which will cause the OSD pods to access all of the host’s device resources and kernel capabilities. This will cause some security issues, and attackers can run a command in the context of the OSD pods to escape and access the host’s resources. 
For another,  Ceph OSD is responsible for storing data, handling data replication, recovery, rebalancing... To improve Ceph performance, like throughput, Ceph has leverage serval devices to accelerate data compress and encryption when storing/handling data. When deploying Ceph cluster in Kubernetes, OSD pods in privileged mode can access arbitrarily all of the devices on host. However, if the devices have been scheduled and allocated to other unprivileged pods by [device plugin](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) (e.g. [Intel device plugin](https://github.com/intel/intel-device-plugins-for-kubernetes)), these unprivileged pods may not be able to use the allocated devices because these devices may already be occupied by the privileged OSD pods. There will be a conflict.

**Environment**:

**Comment by travisn** [comment]
@liumiaomiaoIntel Do you have an example of what changes could be made to the OSD pods to use the device plugins? Or a working prototype would be really helpful towards making this change, thanks!

**Comment by mythi** [comment]
(Intel device plugin maintainer here :wave:)

@travisn The challenge that triggered this issue is that OSD pods seem to run privileged. What that means is if we build the Ceph container with HW accelerator capabilities and deploy in a privileged container, it essentially breaks the resource management for the accelerator since the privileged container will hog *all* of the accelerator resources it sees.

To get OSD pods to consume device plugin resources is as simple as adding the necessary resource requests in `osdProps.resources` (?) but this is pointless as long as the OSD pods run privileged. So the original question we wanted to check here was: can it run without privileged in some/all cases and what would be the conditions?

The use of privileged mode in various places triggered me another question: would the use of a "storage device plugin" help to reduce the need to run containers privileged even more? A device plugin or if more complex resource scheme is necessary, a [DRA based setup](https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/) can care of `/dev/` disc discovery and handle device/hostpath mounts to containers that need to operate on them. With that, even [going to non-root uid/gid might also work](https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/) in some cases?

**Comment by travisn** [comment]
Most of the privileged work takes place in the OSD prepare job. What would be interesting first to investigate is we can start the OSD daemon deployments unprivileged with the device plugin, even if the OSD prepare job stays privileged. At the point the OSD daemon runs, it is aware of the exact device it needs to consume, so if the device plugin gives the capability to access the specific device, there may be hope to get it running without being privileged. 
@leseb Did you perhaps investigate this possibility in the past?
@satoru-takeuchi Are you interested in investigating this?

**Comment by satoru-takeuchi** [comment]
@travisn It's easy to verify whether OSD on PVC can run as a unprivileged mode by twraking small code snippet and pass integration tests. Is this investigation enough for now? Then I'll do it. Correct me if I'm wrong.

**Comment by leseb** [comment]
> Most of the privileged work takes place in the OSD prepare job. What would be interesting first to investigate is we can start the OSD daemon deployments unprivileged with the device plugin, even if the OSD prepare job stays privileged. At the point the OSD daemon runs, it is aware of the exact device it needs to consume, so if the device plugin gives the capability to access the specific device, there may be hope to get it running without being privileged. @leseb Did you perhaps investigate this possibility in the past? @satoru-takeuchi Are you interested in investigating this?

I haven't gone any further than that: https://github.com/rook/rook/pull/9175.
AFAIR, the OSD still needs to run privileged, can you clarify what you mean by the device plugin? Do you mean `v1.Container.VolumeDevices`?

**Comment by mythi** [comment]
> can you clarify what you mean by the device plugin? Do you mean `v1.Container.VolumeDevices`?

For containers to use devices, they must be [explicitly allowed to do so](https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#allowed-device-list). In a kubernetes environment, a device plugin makes that possible.

**Comment by travisn** [comment]
> @travisn It's easy to verify whether OSD on PVC can run as a unprivileged mode by twraking small code snippet and pass integration tests. Is this investigation enough for now? Then I'll do it. Correct me if I'm wrong.

@satoru-takeuchi We would need prototype with the device plugin, likely more time than you have currently. Could you just comment on where the code? Then if needed someone else can take a look, thanks.

**Comment by mythi** [comment]
> Could you just comment on where the code? Then if needed someone else can take a look, thanks.

I can also help and provide feedback but I'd first need to understand what Rook/Ceph expects so any pointers would be helpful.

**Comment by liumiaomiaoIntel** [comment]
> > @travisn It's easy to verify whether OSD on PVC can run as a unprivileged mode by twraking small code snippet and pass integration tests. Is this investigation enough for now? Then I'll do it. Correct me if I'm wrong.
> 
> @satoru-takeuchi We would need prototype with the device plugin, likely more time than you have currently. Could you just comment on where the code? Then if needed someone else can take a look, thanks.

I have an environment that can be used for testing Ceph deployed by Rook and [Ceph compression accelerators](https://docs.ceph.com/en/quincy/radosgw/qat-accel/) allocated by [Intel device plugin](https://github.com/intel/intel-device-plugins-for-kubernetes). I'm always available to help if needed.

**Comment by satoru-takeuchi** [comment]
> @satoru-takeuchi We would need prototype with the device plugin, likely more time than you have currently. Could you just comment on where the code? Then if needed someone else can take a look, thanks.

@travisn OK, here it is.

https://github.com/rook/rook/blob/52c9cfea9fe3c7e30f044040d468399f008379d5/pkg/operator/ceph/cluster/osd/spec.go#L464-L475

Please note that this security context is used not only in main "osd" container but also in other init containers. In addition, the following comment (left by @leseb ) describes why osd pods must be run as privileged containers.

```
	// We cannot go un-privileged until we have a bindmount for logs and crash
	// OpenShift requires privileged containers for that
	// If we remove those OSD on PVC with raw mode won't need to be privileged
	// We could try to run as ceph too, more investigations needed
```

Good luck!

**Comment by travisn** [comment]
For prototyping, it would be very interesting to just remove the hostpath for logs and crash collector to see if the OSD will fundamentally at least work with the device plugin.

The fix for the logs would be to put them in a PVC, as described in #5006.

For the crash collector, not sure of a fix. For scenarios where running unprivileged is most critical, perhaps it's an acceptable tradeoff to disable the crash collector and crash dumps even if it means the crashes are not available.

**Comment by liumiaomiaoIntel** [comment]
Hi all, I'm currently trying to turn off privileged mode for OSD pods on a PVC and temporarily remove the host paths for the logs and crash collectors. If the previous step was successful, which means the OSD fundamentally at least work with the device plugin, I'll try to put the logs into the PVC and figure out what to do with the crash collector.
