### ISSUE TITLE
Add a seprate directory structure for external cluster examples manifests

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12599]
**Is this a bug report or feature request?**
* Feature Request

Currently most of the yamls are common for external and internal clusters, and as the external cluster runs over two namespaces generally one for the operator and one for cephcluster so we should separate them in a separate folder

External Examples yamls should work seamlessly without changing anything for testing

**What should the feature do:**

The feature will ease the steps of cluster creation.

**What is use case behind this feature:**

For creating rgw it becomes very confusing what namespace to use and even we need to change the default ones to make them work
So it will less time consuming

**Environment**:

**Comment by smoshiur1237** [comment]
Hi @parth-gr, I would like to work on this issue. Can I assign it to myself?

**Comment by parth-gr** [comment]
sure use this https://rook.io/docs/rook/latest-release/Contributing/development-flow/#self-assign-issue

**Comment by travisn** [comment]
@parth-gr @smoshiur1237 Before a PR is opened, could we discuss here what the proposed structure will be?

**Comment by smoshiur1237** [comment]
@travisn @parth-gr My initial thought is to have a separate directory named `external` under `deploy/examples/ ` directory where we can keep those manifests which are meant for external configuration. After that we can do changes/updates the path of the directory in different places where the external manifests are called. 
Please share your opinion and would appreciate your input for the solution.

**Comment by parth-gr** [comment]
@smoshiur1237 Yes having a separate directory for the external cluster works, with specific external files, and you need to update all the documentation were we link this doc.

@travisn any other recommendations?

**Comment by travisn** [comment]
Most commonly, users have either an internal or external cluster, but not both. While it's possible to have both, it would be good to create the examples for the common case. Since the common case is to use the `rook-ceph` namespace, perhaps we should change the external cluster examples to use the `rook-ceph` namespace instead of `rook-ceph-external`. The CI would need to be updated to change the namespace since it does require the different namespace for the external cluster.

But before we make that change, an important consideration is how existing users will be impacted. It might be too painful to change the namespace of the existing examples. In this case, we could keep the existing examples and then add the subfolder for the new examples that use the `rook-ceph` namespace.

**Comment by parth-gr** [comment]
Okay that fit perfectly

**Comment by smoshiur1237** [comment]
Thanks for your suggestion and I will start to work on it.

**Comment by parth-gr** [comment]
> Most commonly, users have either an internal or external cluster, but not both. While it's possible to have both, it would be good to create the examples for the common case. Since the common case is to use the `rook-ceph` namespace, perhaps we should change the external cluster examples to use the `rook-ceph` namespace instead of `rook-ceph-external`. The CI would need to be updated to change the namespace since it does require the different namespace for the external cluster.
> 
> But before we make that change, an important consideration is how existing users will be impacted. It might be too painful to change the namespace of the existing examples. In this case, we could keep the existing examples and then add the subfolder for the new examples that use the `rook-ceph` namespace.

For upgrades, maybe we can have a document step to replace the namespace at certain places with whatever namespace they are using, let's discuss.
