### ISSUE TITLE
Add a `managePodBudgets` mode to allow non "active+clean" states

### ISSUE THREAD

**Issue by cupnes** [rook/rook#12612]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If `.spec.disruptionManagement.managePodBudgets` is enabled, PDBs are updated only if all PGs are "active+clean". However, for example. if some PGs are in "remapped" state, there are desired number of replicas. This feature is to add a mode to allow these states.

**What is use case behind this feature:**
Current implementation may takes too long time to restart multiple nodes, especially if there are massive amounts of client I/Os. If users admit other states (typically remapped as I described above), the total rebooting time becomes much shorter. In my cluster, all nodes are rebooted periodically to confirm availability and to update firmware.

**Environment**:

**Comment by travisn** [comment]
Makes sense to consider some PG states as valid for allowing the PDBs to be updated.

**Comment by sp98** [comment]
@cupnes What's the PGs status for your cluster? Is it `active+clean+remapped`?

**Comment by sp98** [comment]
@travisn Apart from active+clean and remapped, I don't think there are other PG statuses where the user would like to allow PDBs to be updated. Is that correct?

We can either update the `PDB` spec with a new `allowed PG status` option. Users can provide which PG status are expectable. 

Or just hard cord `remapped` status along with active+clean since there are no other statuses where the user might want to continue with PDB update. 

Another question is what would be appropriate status for `remapped` pgs 
- `active+clean+remapped`  or
- `active+remapped`

**Comment by sp98** [comment]
currently we have following statuses where we consider PGs to be `OK` and we continue with the PDB update:
``` 	activeClean              = "active+clean"
	activeCleanScrubbing     = "active+clean+scrubbing"
	activeCleanScrubbingDeep = "active+clean+scrubbing+deep"```

**Comment by sp98** [comment]
`backfilling` could mean that the data is still recovering.  IMO, the PDBs should not be updated for this state.

**Comment by sp98** [comment]
@travisn or @cupnes  any further thoughts on this?

**Comment by travisn** [comment]
Agreed that `backfilling` cannot be ignored

**Comment by satoru-takeuchi** [comment]
My team will handle this later.
