### ISSUE TITLE
Restart all ceph daemons when Encryption Compression(any Network.Connections options) change

### ISSUE THREAD

**Issue by malayparida2000** [rook/rook#12622]
Encryption settings are set in client-osd traffic & osd-osd traffic. When the settings change for the new settings to take effect 2 things are required, 
1. remapping of an RBD block device or remounting of a CephFS filesystem with the appropriate ms_mode option.
2. Restart ceph daemons to pick up the new settings.
In the encryption case, we want the entire cluster to move to a new setting -- including the manager, MDS daemons, etc as in-transit encryption is generally considered an all-or-nothing thing.

Compression settings take effect between osd-osd traffic. When the settings change for the new settings to take effect 1 thing is required.
1. Restart ceph daemons to pick up the new settings.

Requiremsgr2 if it is set we should disable the v1 6789 port & only have the 3300 port, or if it's not enabled we should have both ports available. So when this setting changes either from on to off or off to on
1. we need to restart ceph daemons like the ceph mons

**In all three cases whenever any option changes we need a restart of ceph daemons**. So that's a common goal.
Specifically for encryption case we also require remapping of an RBD block device or remounting of a CephFS filesystem, but we have to consider if it's technically feasible & doable.

**Comment by travisn** [comment]
To cause daemons to restart, for the implementation an env var can be added to all ceph daemons such as:
```
ROOK_MSGR2=requiremsgr2_encryption_compression
```
It's just a simple string with the different possible settings concatenated. If any of them changes, it would cause the daemons to restart with the normal reconcile of the cluster since it would cause an update to the pod spec.

Restarting the volumes will need to be an exercise left to the admin since Rook doesn't own the apps and would be disruptive for the apps to remount. The admin should decide when this needs to be done. Generally it should not be recommended to change this setting so it wouldn't be commonly needed.

**Comment by Madhu-1** [comment]
@travisn agree and we need to have steps documented to restart the application pods as Rook doesn't own them.
