### ISSUE TITLE
NFS HA: Kubernetes-provided NFS high-availability

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#12719]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Current CephNFS provides active-active Ganesha servers. However, this implementation is technically more for scale-out than for high availability. Ganesha grace period handling is coarse at best, and the CephFS backend provides no support for moving NFSv4 clients from server to server without interruption. After much research and many meetings, we have come to the conclusion that Rook itself cannot provide active-active HA for NFS clusters.

The best HA we can implement currently is what Kubernetes is able to provide for us via Pod restart and rescheduling. To that end, we can take some lessons learned from the MDS/dashboard failover to ensure Ganesha server failover can be as quick as possible. We will target this work for backport to Rook v1.12.z.

**Comment by BlaineEXE** [comment]
Trying to establish some more clear direction for this
-----

Juan Mi made some changes some time ago to help Kubernetes restart mon/mgr pods more quickly in the event of a Kubernetes node going into NotReady state. Restart time (from NotReady to kickoff of restart) is reportedly 50 seconds or less after those changes.

That PR is here: https://github.com/rook/rook/pull/4343

-----

It would also be good to add some sort of Liveness probe to the ganesha container so that we can be more certain that the server is listening to clients. I think a basic TCP check of the endpoint:port would be sufficient, but I'm not certain.

@synarete may have insights as to whether Ganesha has a dedicated liveness probe it offers as a metric.

HAProxy (which I don't believe is aware of the NFS protocol) has some sort of built-in mechanism for detecting if backend nodes are alive or not, and that worked out of the box with ganesha when I did some personal testing of it. HAProxy's code might be a good thing to look to for inspiration if this proves harder than expected.

-----

I think it would also be good to investigate the actual behavior during different failure conditions to help us verify that HA is robust. 

Bringing the node with the NFS server pod on it offline unexpectedly would be an easy one and the only one I can come up with off the top of my head currently.

**Comment by synarete** [comment]
@BlaineEXE IMHO, the best way to probes liveness of nfs-ganesha server is via `rpcinfo`. As for the metrics option, there isn't any explicit liveness metrics, but it is possible to detect it indirectly: when nfs-ganesha is compiled with monitoring enabled (`-DUSE_MONITORING=ON`), it exports a set of [Prometheus metrics](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/monitoring/monitoring.cc#L106-L236) via port TCP 9587. In particular, the pair of [rpcs_received_total](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/MainNFSD/nfs_rpc_dispatcher_thread.c#L1552) and [rpcs_completed_total](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/MainNFSD/nfs_rpc_dispatcher_thread.c#L1607) could provide a hint that something is wrong with the server: if the diff between the two is increasing over time, it implies that some rpc requests are unable to complete due to some internal error. As far as I can tell, this is the best we can do with current set of metrics.

**Comment by derekbit** [comment]
@BlaineEXE
I'm interested in NFS HA topic.
Would you be able to elaborate more on the statement `After much research and many meetings, we have come to the conclusion that Rook itself cannot provide active-active HA for NFS clusters.`?  Why is this method not feasible?
Thank you.
