### ISSUE TITLE
Allow more than 2 mgr instances

### ISSUE THREAD

**Issue by anthonyeleven** [rook/rook#12812]
In a message to ceph-users@ on 2023/7/6 I wrote:

>mgrs are limited to 2, apparently Sage previously said that was all anyone should need.  I would like to be able to deploy one for each mon. 

based on a prior conversation with @travisn .

So my RFe here is for Rook to allow more than 2 mgr instances.  I'm a bit puzzled as to why Rook enforces such a low limit, said conversation with Sage notwithstanding.  Ceph historically has been all about giving us all the rope we need to hang ourselves, so why stop now ;)

Travis responded:

>Is there a specific need for 3? Or is it more of a habit/expectation?

From my perspective, perhaps half and half.  When I was running ~20 Luminous clusters I found mgrs silently dying all too often, sometimes all of them such that mgr-related functions stopped working, which was initially what clued me into them having become ex-parrots.  While I don't doubt that recent Ceph releases are more stable, I'm still a bit paranoid about having more than one standby.  After all, we strongly advise people to not run replicated pools with `size=2` for reasons that aren't entirely orthogonal to mgrs.

And, yes it is something of a habit as well.  There's a certain symmetry to deploying an mgr alongside every mon instance -- and for production clusters I do like to run 5 mons.  Granted the mgrs aren't multi-active / quorum like mons, but still I like to have greater redundancy.  I haven't run a stretch cluster yet myself, but I also wonder if an argument could be made for at least 4, 2 at each site.

If Rook does have a legit reason to limit the number of mgrs (does it limit mons?), say to avoid runaways or something, I humbly request that number be at least count(mons), or 5 if you want a constant.  It's rare for a cluster to run more than 5 mons, you get a lot more K-complete traffic for diminishing returns.

**Comment by travisn** [comment]
I can't think of a specific reason it was limited to two, other than to simplify testing and reduce the moving parts when the active mgr changes. Rook has to update the labels on the mgr pods whenever ceph fails over the active mgr so that the services (prometheus, dashboard, etc), will point to the active one. 

For example, the [watch-active sidecar implementation](https://github.com/rook/rook/blob/7b942b455c9b2fda2543cf8f9f9e4d5f36e69dac/pkg/operator/ceph/cluster/mgr/mgr.go#L218-L261) would need to be tested to make sure it can handle more than two.
