### ISSUE TITLE
design/ceph: clean up osd-migration.md 

### ISSUE THREAD

**Issue by anthonyeleven** [rook/rook#12813]
Improve wording, punctuation, spelling, etc.

**Comment by travisn** [comment]
> Thank you, good sir. I'm curious, though, why the decision to not let one revert the OSD backend.

RADOS team has said it is not supported to revert specifically from this `bluestore_rdr` back to `bluestore` format. I am not clear why that is the case since each OSD store is independent, so it's good feedback to understand if it's specific to this feedback or if it might apply to future conversions such as seastore.

**Comment by anthonyeleven** [comment]
Indeed.  My understanding is that BlueStore_rdr is intended to backport experimental OSD code.  w/e.

I found the bit about automated reprovisioning especially interesting.  That has potential applications beyond switching the OSD backend, notably rebuilding with a different `min_alloc_size`, either to align with novel media, or if one is running OSDs created before, say, later releases of Octopus or Pacific.  In such cases one might have OSDs created with a`min_alloc_size` of as high s 64KB, which can result in substantial space amplification, especially on RGW bucket and/or EC pools.   https://docs.google.com/spreadsheets/d/1rpGfScgG-GLoIGMJWDixEkqs-On9w8nAUToPQjN8bDI/edit#gid=358760253
