### ISSUE TITLE
Multiple RGW pools and storageclasses

### ISSUE THREAD

**Issue by anthonyeleven** [rook/rook#12824]
I don't _think_ this duplicates https://github.com/rook/rook/issues/12772 though it may be adjacent.

We're using Rook via Helm to deploy Ceph with the below `cephObjectStore`.  As I understand it -- and please enlighten me if I'm wrong -- Rook can only handle a single RGW bucket pool and associated storageclass.  If I add a second `cephObjectStores` entry, say `-name: ceph-objectstore-2`, my understanding is that would create a whole second and independent cluster, which would be confusing for users.  And I have no idea how targeting one or the other would work wrt the toolbox pod / shell.

Am I missing something?  Is this only a limitation of Helm and not Rook itself? Can I use a custom CRD to add a second bucket pool+storageclass?

@I don't _think_ this duplicates https://github.com/rook/rook/issues/12772 though it may be adjacent.

We're using Rook via Helm to deploy Ceph with the below `cephObjectStore`.  As I understand it -- and please enlighten me if I'm wrong -- Rook can only handle a single RGW bucket pool and associated storageclass.  If I add a second `cephObjectStores` entry, say `-name: ceph-objectstore-2`, my understanding is that would create a whole second and independent cluster, which would be confusing for users.  And I have no idea how targeting one or the other would work wrt the toolbox pod / shell.

Am I missing something?  Is this only a limitation of Helm and not Rook itself? Can I use a custom CRD to add a second bucket pool+storageclass?

Say I want a replicated bucket pool on TLC for small objects and an EC bucket pool on HDDs or QLC for large objects, each with a concommitant storageclass, one of which is the default.

@mohitrajain 

```
  cephObjectStores:
    - name: ceph-objectstore
      spec:
        metadataPool:
          failureDomain: host
          replicated:
            size: 3
          deviceClass: ssd
        dataPool:
          failureDomain: host
          erasureCoded:
            dataChunks: 4
            codingChunks: 2
          deviceClass: hdd
        preservePoolsOnDelete: true
        gateway:
          port: 80
          resources:
            limits:
              cpu: "2000m"
              memory: "2Gi"
            requests:
              cpu: "1000m"
              memory: "1Gi"
          # securePort: 443
          # sslCertificateRef:
          instances: 3
          priorityClassName: system-cluster-critical
        healthCheck:
          bucket:
            interval: 60s
      storageClass:
        enabled: true
        name: ceph-object-hdd-ec
        reclaimPolicy: Delete
        # see https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#storageclass for available configuration
        parameters:
          # note: objectStoreNamespace and objectStoreName are configured by the chart
          region: us-east-1```

**Comment by travisn** [comment]
The `cephObjectStores` is a list of multiple object stores. Multiple object stores can be created via this list, where each object store can be created with different replicated or EC settings for the pools, and each object store will also have its own storage class. The object stores will be created in the same ceph cluster. If you want more flexibility than that, you can do it directly with a CephObjectStoreCR or storage class instead of using the helm chart. 

Does this answer your question? Otherwise, please share details about what errors or issues you hit when you tried to create these object stores.

**Comment by anthonyeleven** [comment]
But will those object stores share the same RGW instances?

**Comment by travisn** [comment]
> But will those object stores share the same RGW instances?

No, each object store will have separate pools and rgw instances

**Comment by anthonyeleven** [comment]
That's the blocker -- that would mean that clients have to direct requests to different endpoints.  The idea of S3 storageclasses is to have multiple pools of storage accessible via a single endpoint.  When they are two entirely disjoint domains, that prevents users from using lifecycle policies to move objects between them, from using `x-amzn-storageclass` headers to direct objects to one or the other, and from using Lua scripting to assign objects to a pool on the server side.

Having multiple S3/RGW storageclasses each with a different Ceph pool within the same RGW zone is something upstream Ceph can do.

https://www.youtube.com/watch?v=w91e0EjWD6E

**Comment by travisn** [comment]
@thotz Thoughts on how to get this working with Rook?

**Comment by BlaineEXE** [comment]
It seems to me that Rook is missing some ability to natively configure the S3 storage class, as Anthony is describing. Because pool configs are also present in CephObjectZone CRs, I suspect that whatever needs to be done will need to be designed to fit into the multisite paradigm well. I had a quick chat with @alimaredia about this, and we are in agreement that there will need to be some planning for the how and where.

I find it interesting how this topic seems to be the inverse of the feature request for multiple RGWs that all share the same pools, isolated by namespaces (https://github.com/rook/rook/issues/11411). I think it would be germane to plan work on this feature such that we aren't making work on namespace isolation more difficult in the future.

**Comment by anthonyeleven** [comment]
That RFE 11411 is not something I've ever seen someone want to do before.  I just want multiple pools and storageclasses within the same RGW instance, one storageclass naturally will be default, and the other named.  I have to imagine I could do this the usual way from the Ceph CLI but I'd much rather be able to encode the config in the Rook values.yml

**Comment by travisn** [comment]
Looks like the [rgw pool consolidation with rados namespaces](https://docs.ceph.com/en/quincy/radosgw/pools/#pool-namespaces) has been around since luminous, so it seems a natural fit to use that approach to share pools and keep object stores isolated for multi-tenancy.

@anthonyeleven If you can find the steps to configure the storage classes, it will help understand better how to configure it in Rook. I'd like to think it is a separate scenario than the approach to use rados namespaces, so we can keep those designs separate.

**Comment by anthonyeleven** [comment]
Sure.  First create a pool in the usual way then associate a storageclass / placement with it.

ceph osd pool create qlc_pool 1024
ceph osd pool application enable qlc_pool rgw

https://github.com/ceph/ceph/blob/main/examples/rgw/lua/storage_class.md
https://docs.ceph.com/en/latest/radosgw/placement/#adding-a-storage-class

I'm asking my collaborator on the QLC work for his Python scripts that set up his PoC demo; I'll forward them if/when I get them.

I agree that this is orthogonal to RADOS namespaces, though I'll be curious how the RADOS namespace stuff works out.  I can see where it'd perhaps be useful for multiple librados clients.

**Comment by anthonyeleven** [comment]
bump

**Comment by anthonyeleven** [comment]
bump

**Comment by anthonyeleven** [comment]
Bogus.

**Comment by thotz** [comment]
This change is required by https://github.com/rook/rook/issues/13777 as well IMO

**Comment by parth-gr** [comment]
Does this fixes by recent chnges of adding rados-namesapce?

**Comment by anthonyeleven** [comment]
Namespaces have nothing to do with storageclasses and multiple bucket pools.

**Comment by BlaineEXE** [comment]
Still in backlog.

**Comment by anthonyeleven** [comment]
Bump

**Comment by BlaineEXE** [comment]
Indirectly tracked via #14441, and design in progress in #14455

**Comment by anthonyeleven** [comment]
bump

**Comment by BlaineEXE** [comment]
I think we can mark this as completed (in master branch) with #14588 actually. 

Likely, there are still some bugs to iron out, but the feature is ready for testing and feedback at least. Happy to reopen if something critical is missing.

CC: @anthonyeleven
