### ISSUE TITLE
OpenShift:  Error getting claim "openshift-ansible-service-broker/etcd"

### ISSUE THREAD

**Issue by leseb** [rook/rook#1313]
**Bug Report**

What happened:
.
rook-operator log:

```
 controller.go:584] Error getting claim "openshift-ansible-service-broker/etcd"'s StorageClass's fields: StorageClass "" not found
```

What you expected to happen:

Find the StorageClass field

How to reproduce it (minimal and precise):

Just start the rook-operator pod on OpenShift.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
* Kernel (e.g. `uname -a`): Linux k8s-master.example.com 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: VM 1 CPU, 4GB RAM
* Rook version (use `rook version` inside of a Rook Pod): v0.6.0-80.g3dfb151
* Kubernetes version (use `kubectl version`): v1.7.6+a08f5eeb62
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): no cluster yet

**Comment by fabianvf** [comment]
The error here is because the etcd pvc is created with no StorageClass, which means that it won't consume any PVC that has a StorageClass set. Even if you set the default StorageClass to your rook storage, it won't update the existing PVCs out there. AFAIK, the only way to get the etcd pvc to consume your rook storage is to update it or delete/recreate it with the proper StorageClass set.

**Comment by travisn** [comment]
@leseb I believe this is working now, but please reactivate if something was missed
