### ISSUE TITLE
 Improvement on the behaviour of ContinueUpgradeAfterChecksEvenIfNotHealthy flag

### ISSUE THREAD

**Issue by malayparida2000** [rook/rook#13167]
Rook has the flag ContinueUpgradeAfterChecksEvenIfNotHealthy in the CephCluster which is meant to stop any further updates when ceph is not healthy. 

Two issues that we need to confirm or fix in the implementation of the ContinueUpgradeAfterChecksEvenIfNotHealthy flag when false:

1. The mgrs should also check for the flag (currently only mon, osd, mds, and rgw are checking the flag)
2. If the daemon pod is left pending (for example because of insufficient resources), the reconcile should not continue.

**Comment by sp98** [comment]
> The mgrs should also check for the flag (currently only mon, osd, mds, and rgw are checking the flag)

I believe this comes directly from [ceph](https://docs.ceph.com/en/quincy/dev/cephadm/host-maintenance/#the-check-option).  The doc says: `mgr (not included in ok-to-stop checks)` 


If the daemon pod is left pending (for example because of insufficient resources), the reconcile should not continue.
> Currently implementation should take care of it.  Rook [waits for the updated deployment](https://github.com/rook/rook/blob/77db655558bf8516c64ed120088aa6ca8e26e103/pkg/operator/k8sutil/deployment.go#L107) to start before upgrading the next deployment.

**Comment by travisn** [comment]
The main change needed looks like for the mgr reconcile to return an error [here](https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/mgr/mgr.go#L155) instead of just logging the issue and returning. But we only want to return error if `ContinueUpgradeAfterChecksEvenIfNotHealthy` is false.
