### ISSUE TITLE
refactor the external cluster script(move it to a proper python framework)

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#13219]
can we move from Python to golang/python with some framework for external script as well? it looks so complicated and IMO it might become a maintenance /complexity problem in the future.

cc @travisn @parth-gr @sp98

**Comment by rkachach** [comment]
In terms of complexity I don't think there's a big difference between using Python or golang TBH. The script is in fact very long (~2000 lines). I think we can either keep using python bu divide it in more smaller files for modularity and introduce some quality checks such as usage of typing, flake, etc for sanity checks or move it to golang and build/ship it as part of the rook project. In terms of dividing it in smaller python modules we had already did that for cephadm which was ~8000 lines long. Now we use zipapp to build the final "binary.

**Comment by parth-gr** [comment]
@rkachach So in this case we need to run the Python file with user input flags, how can we design so user can directly use the binary at ceph standalone cluster

**Comment by travisn** [comment]
We need to keep the python script, it was created this way to make it more portable to run it on the external ceph cluster. But sounds good to find a better way to package it for long term maintainability.

**Comment by parth-gr** [comment]
Refactor:

1) Have a separate file for rgw, file and block 

2) have a proper build way 

3) Testing should be done more deeply

4) Handel upgrade nicely, currently it needs to remember the flags

5) maybe store the flags in config map, or have a way to re-store the flags that is used during running the script.

**Comment by obnoxxx** [comment]
I see two  different conceptual proposals here:

1. rewrite the tool in golang 
2. refactor the existing python code improving the structure and maintainability 


note that  writing the tool newly using a different language is rewriting and not refactoring.
Refactoring means to change existing code, usually one small step at a time, where the whole refactoring consists of many such steps, an each of these steps leaves the behavior of the code entirely unchanged. Since each small refactoring step has this property, the same applies to the overall change. This is about the most important aspect of refactoring: improving the code quality without introducing semantic or behavior  changes.

To add my 2 cents to this discussion:

*  I am generally opposed to rewriting working software for the sake of improving code quality, irrespective of whether it is done in the same or a different language. In my experience, rewrites are just too error-prone. In particular, I am not in favor of rewriting this tool in golang.
* refactoring with many small refactoring steps (each  step ideally a separate commit)  is the way to ho, IMHO:  This way, it is less error prone as it is easier to validate each intermediate step with manual and automated steps.

So I'd vote to refactor the existing python code.

First,  let's agree on the desired end result (like sketched by @parth-gr  in the previous comment)

In my experience, the steps toward that result will usually follow naturally as the developer starts working toward that goal

E. G. separating out code files for the different components (file,  block, and rgw) will offer themselves almost automatically as mini-step commits.

**Comment by BlaineEXE** [comment]
:+1: to what Michael said. Rewriting a piece of software completely is generally a poor decision.

We chose to rewrite the kubectl plugin from bash to Golang because bash was proving to be unwieldy for the complex things we needed it for. But for this tool, Python is in no way lacking in functionality.

Before I began working with Rook, I was a Python developer. I can tell you from experience, it is many times harder to write clean, maintainable Python code than Golang, but it doesn't make Python a bad language or a poor choice for this tool.

To make the tool more maintainable, I would suggest that we can dedicate a subdirectory to it and separate it into files. Further, we can look to see if there are other/additional linters or python dev tools that will help us aggressively improve the readability and test coverage of the code.

In my experience with python, creating good test coverage tends to encourage better encapsulation and thus better legibility as well.
