### ISSUE TITLE
Support NFS with external cluster

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13277]
**Is this a bug report or feature request?**
* Feature Request
NFS should be supported with external cluster

**What should the feature do:**
External cluster can also use the features of NFS
@BlaineEXE what are your thoughts for this?

**What is use case behind this feature:**

**Environment**:

**Comment by BlaineEXE** [comment]
External NFS is likely already supported. Either by configuring CSI properly for an external NFS, or by giving Rook a Ceph admin key for creating a local CephNFS for an external Ceph cluster.

**Comment by BlaineEXE** [comment]
I don't have steps to use an external NFS from CSI, but they should be very similar to CephFS since the CSI code for NFS is built largely on the pre-existing CephFS base.

The biggest thing is that the CSI client needs to be able to sent `ceph nfs export ...` commands to the ceph cluster.

Doing this automatically via python scripts sounds like a good improvement.

**Comment by travisn** [comment]
Reopening since #13876 is still in review
