### ISSUE TITLE
Monitoring Rules - Multiple Rook Clusters to Same Prometheus Instance - CephPoolGrowthWarning, CephPGsInactive, CephPGsUnclean

### ISSUE THREAD

**Issue by tman5** [rook/rook#13274]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The following [builtin alerts](https://github.com/jdloft/rook/blob/master/deploy/examples/monitoring/localrules.yaml#L738) have issues with multiple rook clusters: CephPoolGrowthWarning, CephPGsInactive, CephPGsUnclean

In an environment with multiple rook clusters reporting to the same prometheus, errors occur with the following errors in the prometheus query:
```
Error executing query: found duplicate series for the match group {pool_id="2"} on the left hand-side of the operation: [{__replica__="replica-0", app="rook-ceph-mgr", app_kubernetes_io_component="cephclusters.ceph.rook.io", app_kubernetes_io_created_by="rook-ceph-operator", app_kubernetes_io_instance="a", app_kubernetes_io_managed_by="rook-ceph-operator", app_kubernetes_io_name="ceph-mgr", app_kubernetes_io_part_of="rook-ceph", ceph_daemon_id="a", ceph_daemon_type="mgr", cluster="dev1-generic", environment="development", job="kubernetes-pods", mgr="a", mgr_role="active", namespace="rook-ceph", pod_template_hash="549fc5c476", pool_id="2", rook_cluster="rook-ceph", rook_io_operator_namespace="rook-ceph"}, {__replica__="replica-0", app="rook-ceph-mgr", app_kubernetes_io_component="cephclusters.ceph.rook.io", app_kubernetes_io_created_by="rook-ceph-operator", app_kubernetes_io_instance="a", app_kubernetes_io_managed_by="rook-ceph-operator", app_kubernetes_io_name="ceph-mgr", app_kubernetes_io_part_of="rook-ceph", ceph_daemon_id="a", ceph_daemon_type="mgr", cluster="dev1-generic", environment="development", job="kubernetes-pods", mgr="a", mgr_role="active", namespace="rook-ceph", pod_template_hash="98988cf8c", pool_id="2", rook_cluster="rook-ceph", rook_io_operator_namespace="rook-ceph"}];many-to-many matching not allowed: matching labels must be unique on one side
```

**Expected behavior:**

The query should not error out and just report as required when there are multiple rook clusters into a single prometheus 

**How to reproduce it (minimal and precise):**
Have multiple rook clusters reporting to a single prometheus instance

**Comment by briend** [comment]
This gets a little tricky.  I thought I could just jam `namespace` there in any of the queries that do aggregation or joins (count(), on(), etc).  For instance, for `CephMonDown`:

```
(count by (namespace) (ceph_mon_quorum_status == 0) 
<= (count by (namespace) (ceph_mon_metadata) 
- floor(count by (namespace) (ceph_mon_metadata) / 2) + 1))
```

or `CephOSDFlapping`:

```
(
rate(ceph_osd_up[5m])
* on(ceph_daemon,namespace) group_left(hostname) ceph_osd_metadata
) * 60 > 1
```
etc

However,  now if you deploy those rules for each ceph cluster, you'll get duplicated alerts since the rules match any ceph cluster, even if they are properly namespaced.  There are two obvious solutions:

- Only deploy one set of Prometheus rules (perhaps for the first ceph cluster you deploy) .  This seems "wrong" since you may have different versions of Ceph with different rules, and you might end up with no Alerts if you remove a ceph cluster.
- Add the release-specific `namespace` to each Alert rule, like `ceph_health_status{namespace="{{ .Release.Namespace }}"}`

The second option isn't possible though, since the rules are not currently templated: https://github.com/jdloft/rook/blob/44fb239334e6054c6e91d810395289505934ee94/deploy/charts/rook-ceph-cluster/templates/prometheusrules.yaml#L30

**Comment by briend** [comment]
Oh, I didn't realize there was `rulesNamespaceOverride` to let you consolidate your rules in one namespace, so that's a bit better.

https://github.com/rook/rook/blob/a19860bab0566f4d7c31170aa9191eed02a4c4cc/deploy/charts/rook-ceph-cluster/values.yaml#L57-L60

**Comment by tman5** [comment]
Wanted to re-open this. We have a custom label that is added named `cluster` by the grafana alloy agent on the k8s cluster, we tried for this alert to add it to the group_by but it always says there is an imbalance on all the clusters:

```
abs(((ceph_osd_numpg > 0) - on (job) group_left () avg by (job) (ceph_osd_numpg > 0)) / on (job) group_left () avg by (job) (ceph_osd_numpg > 0)) * on (ceph_daemon, cluster) group_left (hostname) ceph_osd_metadata > 0.3
```
