### ISSUE TITLE
Agent cannot discover flexvolume directory in K8s 1.9

### ISSUE THREAD

**Issue by dangula** [rook/rook#1330]
**Bug Report**

What happened:
 Cannot mount volumes on k8s 1.9.0. Rook Flexvolume is not being installed on k8s 1.9.0. Integration smoke test  is failing on k8s 1.9.0. Please see attached kubelet and rook pod logs. 
For the logs it looks like rook operator pod is not finding the flexvolume dir. 
[kubelet.log](https://github.com/rook/rook/files/1570014/kubelet.log)
[Operator.log](https://github.com/rook/rook/files/1570015/Operator.log)
[rook-api.log](https://github.com/rook/rook/files/1570016/rook-api.log)

What you expected to happen:
Block and File Storage volumes should be mounted successfully on k8s 1.9.0 

How to reproduce it (minimal and precise):

1. Install K8s 1.9.0 via kubeadm
2.  Start rook operator and rook cluster.
3. Create a PVC and mount the volume on a pod
(or run integration smoke test)

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu
* Kernel (e.g. `uname -a`):Linux ubuntu 4.4.0-103-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): master
* Kubernetes version (use `kubectl version`): 1.9.0
* Ceph status (use `ceph health` in the [Rook toolbox] - rook and ceph status are good

(https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by jbw976** [comment]
I wonder if the format of the configz response changed again, or if there is a new type that captures the volume plugin dir.  I hope this doesn't have the same root cause as #1282, where the Kubelet root dir isn't returned at all anymore.

We should be able to debug this fairly easily by hitting the configz endpoint manually, or by adding some temp logging to https://github.com/rook/rook/blob/c1a87fac6174219b75c813136e30b123198d03bc/pkg/operator/agent/agent.go#L224 to see what the configz endpoint is returning.

@dangula do you already have a PR opened to add 1.9 to our CI pipeline that this issue is blocking? or have you only reproduced this locally with minikube?

**Comment by kokhang** [comment]
I brought up a k8s 1.9.x and was able to verify that the volume gets mounted by the agent. There is an issue thought. @jbw976 the auto-discoverability of the flexvolume dir broke on 1.9. I reopened https://github.com/rook/rook/issues/1162.

Perhaps that is what @dangula is running into. @dangula did you change the flexvolume dir to a different one in the kubelet settings?

**Comment by jbw976** [comment]
Thanks @kokhang, I'd prefer to track this k8s 1.9 issue in just one issue, so I'm going to leave this one open and close #1162 again.

**Comment by elemental-lf** [comment]
I also ran into this and it seems that the configz endpoint doesn't include the volume directory any more. This is with K8s 1.9.1 on CoreOS 1576.5.0. I had to resort to setting FLEXVOLUME_DIR_PATH as well.

So the question is if this as been removed on purpose or if it just went missing due to further changes for the DynamicKubeletConfig feature and could be readded. The documentation at https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ suggests to generate the current kubelet configuration by dumping the configz endpoint so I'd think that it went missing by accident because currently the generated configuration would be incomplete. I currently don't have the time to delve into the kubelet source code and version history to get a definitive answer.

```
curl -sSL http://localhost:8001/api/v1/proxy/nodes/master1.frontend/configz | jq
{
  "kubeletconfig": {
    "configTrialDuration": "10m0s",
    "podManifestPath": "/etc/kubernetes/manifests",
    "syncFrequency": "1m0s",
    "fileCheckFrequency": "20s",
    "httpCheckFrequency": "20s",
    "manifestURL": "",
    "manifestURLHeader": null,
    "enableServer": true,
    "address": "0.0.0.0",
    "port": 10250,
    "readOnlyPort": 10255,
    "tlsCertFile": "",
    "tlsPrivateKeyFile": "",
    "authentication": {
      "x509": {
        "clientCAFile": "/etc/kubernetes/ca.crt"
      },
      "webhook": {
        "enabled": false,
        "cacheTTL": "2m0s"
      },
      "anonymous": {
        "enabled": false
      }
    },
    "authorization": {
      "mode": "AlwaysAllow",
      "webhook": {
        "cacheAuthorizedTTL": "5m0s",
        "cacheUnauthorizedTTL": "30s"
      }
    },
    "allowPrivileged": true,
    "hostNetworkSources": [
      "*"
    ],
    "hostPIDSources": [
      "*"
    ],
    "hostIPCSources": [
      "*"
    ],
    "registryPullQPS": 5,
    "registryBurst": 10,
    "eventRecordQPS": 5,
    "eventBurst": 10,
    "enableDebuggingHandlers": true,
    "enableContentionProfiling": false,
    "cAdvisorPort": 4194,
    "healthzPort": 10248,
    "healthzBindAddress": "127.0.0.1",
    "oomScoreAdj": -999,
    "clusterDomain": "cluster.local",
    "clusterDNS": [
      "10.3.0.10"
    ],
    "streamingConnectionIdleTimeout": "4h0m0s",
    "nodeStatusUpdateFrequency": "10s",
    "imageMinimumGCAge": "2m0s",
    "imageGCHighThresholdPercent": 85,
    "imageGCLowThresholdPercent": 80,
    "volumeStatsAggPeriod": "1m0s",
    "kubeletCgroups": "",
    "systemCgroups": "",
    "cgroupRoot": "",
    "cgroupsPerQOS": true,
    "cgroupDriver": "cgroupfs",
    "cpuManagerPolicy": "none",
    "cpuManagerReconcilePeriod": "10s",
    "runtimeRequestTimeout": "2m0s",
    "hairpinMode": "promiscuous-bridge",
    "maxPods": 110,
    "podCIDR": "",
    "resolvConf": "/etc/resolv.conf",
    "cpuCFSQuota": true,
    "maxOpenFiles": 1000000,
    "contentType": "application/vnd.kubernetes.protobuf",
    "kubeAPIQPS": 5,
    "kubeAPIBurst": 10,
    "serializeImagePulls": true,
    "evictionHard": {
      "imagefs.available": "15%",
      "memory.available": "100Mi",
      "nodefs.available": "10%",
      "nodefs.inodesFree": "5%"
    },
    "evictionSoft": null,
    "evictionSoftGracePeriod": null,
    "evictionPressureTransitionPeriod": "5m0s",
    "evictionMaxPodGracePeriod": 0,
    "evictionMinimumReclaim": null,
    "podsPerCore": 0,
    "enableControllerAttachDetach": true,
    "protectKernelDefaults": false,
    "makeIPTablesUtilChains": true,
    "iptablesMasqueradeBit": 14,
    "iptablesDropBit": 15,
    "failSwapOn": true,
    "systemReserved": null,
    "kubeReserved": null,
    "enforceNodeAllocatable": [
      "pods"
    ]
  }
}
```

**Comment by kokhang** [comment]
@elemental-lf good observation. It seems that the `volume-pluging-dir` field was purposely excluded due to the the author thinking that flexvolume was "alpha". Flexvolume is now GA (as of 1.9) https://github.com/kubernetes/kubernetes/pull/57075

Here is the change that broke it: https://github.com/kubernetes/kubernetes/pull/55562

@elemental-lf could you file an issue in Kubernetes and have them add (or feel free to do it yourself) the volume-plugin-dir field to KubeletConfiguration? It should be a reasonable ask given that Flexvolume is GA.

**Comment by elemental-lf** [comment]
@kokhang I've opened https://github.com/kubernetes/kubernetes/issues/58151.

**Comment by mtaufen** [comment]
Re-posting here as it seems a lot of people aren't aware: configz has never carried any sort of API guarantee and is intended for debugging/testing only. It should not be used as a source of information for *any* production component.

**Comment by mtaufen** [comment]
Can you just expose a configuration knob for that and make sure it's set the same as the Kubelet's? 

I'm sorry, I'm not very familiar with rook's architecture, so I'm not sure what you need to auto-detect and when you need to do it, so the simplest thing that comes to mind is just to pass in the data you need.

**Comment by kokhang** [comment]
@mtaufen that is the workaround we have now. However, in most cases, users will not now (or it would be hard to figure out) what this value should be. I think having this field added back to the KubeletConfiguration will solve our use case since Rook can configure this automatically on behalf of the user.

**Comment by jbw976** [comment]
We have addressed this with a documentation update and the ability to lookup the volume plugin path at runtime from kubelet config appears to be no longer supported.
