### ISSUE TITLE
OSD prepare job stuck (hangs) due to atari partitions

### ISSUE THREAD

**Issue by nics90** [rook/rook#13332]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

We have disks of size > 1TiB in our production setup and we are using OSD raw partitions. We found that after creating ceph cluster on raw disks, atari partitions gets created. Further when OSD prepare job runs it gets stuck in **Running** state since it tries to perform operations the atari partitions.

**Expected behavior:**
Ceph OSD prepare job should ignore the atari partitions

**How to reproduce it (minimal and precise):**

a) Rook Ceph setup on server with disk size > 1TiB
b) Rook Version: v1.11.10
c) Ceph Version: v16.2.7
d) Partitions as follow gets created:
sdg         8:96   0   3.5T  0 disk
├─sdg2      8:98   0    48G  0 part
└─sdg3      8:99   0   6.3M  0 part
sdh         8:112  0   3.5T  0 disk
├─sdh2      8:114  0    48G  0 part
└─sdh3      8:115  0   6.2M  0 part

e) OSD Prepare job stucks with below logs:
**2023-12-05 18:32:06.991135 D | exec: Running command: ceph-volume inventory --format json /dev/sdh2**

**File(s) to submit**: N/A

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary : N/A

**Logs to submit**: 
2023-12-05 18:32:06.973348 D | exec: Running command: lsblk /dev/sdh2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME,MOUNTPOINT,FSTYPE
2023-12-05 18:32:06.991057 D | sys: lsblk output: "SIZE=\"51539607552\" ROTA=\"0\" RO=\"0\" TYPE=\"part\" PKNAME=\"/dev/sdh\" NAME=\"/dev/sdh2\" KNAME=\"/dev/sdh2\" MOUNTPOINT=\"\" FSTYPE=\"\""
2023-12-05 18:32:06.991135 D | exec: Running command: ceph-volume inventory --format json /dev/sdh2

**Cluster Status to submit**:

NAME        DATADIRHOSTPATH   MONCOUNT   AGE    PHASE   MESSAGE                        HEALTH        EXTERNAL   FSID
rook-ceph   /var/lib/rook/    3          126d   Ready   Cluster created successfully   HEALTH_WARN              de770eed-b929-4acb-9c62-7bbb674d55cf

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

* Kernel (e.g. `uname -a`):

Linux la-cloudlyte-sr11 5.4.0-167-generic #184-Ubuntu SMP Tue Oct 31 09:21:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
Dell PowerEdge R750

* Rook version (use `rook version` inside of a Rook Pod):
v1.11.10

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)

* Kubernetes version (use `kubectl version`):
v1.22.9

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On-Prem

**Comment by BlaineEXE** [comment]
None of the outputs I can discern are showing errors, and I don't see the full output of `ceph status` (or `kubectl rook-ceph ceph status`) to inspect the HEALTH_WARN condition.

I don't see how this (below) is a problem. The OSDs should be in Running state.
> stuck in Running state

If there are errors, please provide the full log outputs for us to debug problems as requested in the issue template. That includes the OSD logs, and please identify which pod logs are coming from.

BI should also mention that this issue gets reported constantly, and Rook+Ceph have already implemented fixes so that they can operate in these environments. See these links, and if you still have questions, post them here:
- https://github.com/rook/rook/discussions/13018
- https://github.com/rook/rook/issues/9831#issuecomment-1058515443
- https://github.com/rook/rook/issues/9831#issuecomment-1124232940
- https://github.com/rook/rook/issues/11408

**Comment by BlaineEXE** [comment]
Got it. Thanks for clarifying @nics90 . 

> a) Issue is not with the OSD Pods as they should be in running state, it's actually with the OSD Prepare job which should be completed once it traverse all partitions. But the job gets stuck in running state while executing " ceph-volume inventory --format json /dev/sda2" command where /dev/sda2 is atari partition.
b) Due to this, although ceph cluster show healthy but some of the volumes become inaccessible.

This does seem like it might be some kind of regression. I helped fix the issue in ceph-volume a couple years back.

> c) Once we reboot the server then the job gets completed and Ceph becomes stable.

This is also good to know, that there is a workaround.

**Comment by BlaineEXE** [comment]
I created a Ceph issue based on this here: https://tracker.ceph.com/issues/63763

**Comment by BlaineEXE** [comment]
This **might** be fixed here: https://github.com/ceph/ceph/pull/54514/files

You can try out that fix in a dev build of ceph: `quay.io/ceph/daemon-base:latest-quincy-devel`

Please try using that Ceph version to see if the issue is resolved.

**Comment by BlaineEXE** [comment]
@nics90 any update on the suggestion?

**Comment by nics90** [comment]
@BlaineEXE : We will test the above build and let you know.
