### ISSUE TITLE
Tools Deployment via Operator

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#13403]
* Feature Request

The tools deployment should be kept up to date with the rest of the cluster, but is currently unmanaged. Could it be added as an option to the operator so it can be automatically managed along with the rest of the cluster?

**Comment by travisn** [comment]
This has long been on my mind as a possibility. But instead of investing more in the toolbox, the recommended troubleshooting tool is now the [kubectl plugin](https://github.com/rook/kubectl-rook-ceph). The plugin does not require running the toolbox since it uses the operator pod as the environment where commands are executed. Have you tried the plugin?

**Comment by kfox1111** [comment]
Lost track of this a bit....

There are times when we shutoff the operator and its still useful to be able to execute ceph commands?

**Comment by travisn** [comment]
Understood, there are still scenarios for using the toolbox. You're not installing with the helm chart, right? I'd expect at least deployments via helm to update the toolbox automatically.

**Comment by travisn** [comment]
Note that for the last few releases the toolbox is based on the ceph image. So whatever process is used to upgrade the Ceph image in the CephCluster CR (if not using helm), the same process could also update the toolbox. I'm not against the operator managing the toolbox, it will likely just require a PR by a community member who wants the feature implement it.
