### ISSUE TITLE
osd: use one osd per pod

### ISSUE THREAD

**Issue by leseb** [rook/rook#1341]
**Feature Request**

Are there any similar features already existing: yes, in ceph-helm

What should the feature do: bootstrap one osd per pod

What would be solved through this feature: debugging an osd would be easier, we will just `kubectl exec <pod>` and get into the container

Does this have an impact on existing features: a migration procedure is needed

**Comment by liewegas** [comment]
This is probably a pre-req for #1342 and #1345?

**Comment by kokhang** [comment]
Wouldnt this make it hard to manage on large clusters with multiple hosts and each hosts with multiple devices? We could have 100s of pods on just regular 3-5 node-clusters each with ~20 devices. 

How about running one osd per container?. That way we can group all the osd containers in one pod.

Another reason we run one osd pod per host is to have the support for auto-discoverability of devices. Otherwise we will need to know how many devices/directories to use ahead of time. Or can the fix of https://github.com/rook/rook/issues/1345 alleviate this issue?

**Comment by liewegas** [comment]
Note that we need device enumeration that is visible to external agents no matter what.  The dashboard will want to present devices and allow a user to manage them (deploy osds, replace failed or failing devices, etc.).  Doing this within the osd pod was probably a convenient shortcut to avoid that until now, but makes less sense going forward.

**Comment by jpds** [comment]
> We could have 100s of pods on just regular 3-5 node-clusters each with ~20 devices.

I don't think this is an issue either, https://github.com/kubernetes/community/blob/master/sig-scalability/goals.md states that the goal for pods per machine is 500.

**Comment by jpds** [comment]
This would also tie in nicely with a bug I reported a while back about drive initialization errors (#718) where Rook can't directly detect drives failing within an 'jumbo' OSD pod managing multiple drives. A pod managing one drive could go into `Error` state while the rest of the pods on the hosts could carry on as normal.
