### ISSUE TITLE
osd: use ceph-volume to bootstrap osd

### ISSUE THREAD

**Issue by leseb** [rook/rook#1342]
**Feature Request**

Are there any similar features already existing: no

What should the feature do:

What would be solved through this feature: we should use the `ceph-volume` utility to bootstrap the osds instead of the manual method currently in place

Does this have an impact on existing features: yes, rework the way Rook knows its devices (no more 'ROOK' partlabel)

**Comment by leseb** [comment]
Plus I just noticed that OSDs are not 'portable', basically, Rook does not use the OSD disk to store OSD's metadata (key, type, fsid, block paths etc) but only relies on `HostPath` from the host running the OSD pod. That's a serious blocker if the machine dies, disks could normally move to another machine and just restart the OSD on their own.

**Comment by travisn** [comment]
thanks @leseb we definitely need to make sure the OSD disk is used to store the metadata. That has been a worry of mine as well. I see now in the [bluestore config doc](http://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/) that we should create a partition for the data dir.

**Comment by dmick** [comment]
Looked a bit at this tonight; one thing to be fixed is that ceph-volume currently assumes it can read cepn.conf to find the cluster fsid.

**Comment by travisn** [comment]
Yes, the daemons should use the config in the default location as mentioned in #1347 if you want to take that issue on.

**Comment by hunter** [comment]
Since dmcrypt support was raised on Twitter in a larger discussion on Kubernetes storage encryption, it would be good to combine this with #923.

**Comment by alfredodeza** [comment]
@dmick @travisn do we need to allow a way to provide a custom (or non`ceph.conf` based) cluster fsid in ceph-volume? This wouldn't be that complicated, probably would mean an extra flag when bootstraping (`prepare` or `create` sub-commands)

**Comment by lbogdan** [comment]
So, I wanted to play around with `ceph-volume` and learn how it works, here are my findings:

### Initial setup
I have a one node test cluster with 2 4TB drives, `sda` and `sdb`. `sda` is split into 5 partitions, first 3 are used by the OS (`sda1` - boot, `sda2` - root, `sda3` - bios boot), and the last 2, aprox. 1.8TB each, are xfs formatted, mounted and used for directory OSDs (I split the remaining space into 2 so that I have 3 OSDs and be able to have erasure coded pools). `sdb` is used for a device OSD. So my cluster `storage` section looks like this:
```yaml
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter: "^sd[ab]"
    nodes:
    - name: "ceph-0"
      devices:
      - name: "sdb"
      directories:
      - path: "/mnt/sda4"
      - path: "/mnt/sda5"
      config:
        storeType: bluestore
```

### Goal
Change OSD 2 from directory to device, by removing it from the rook cluster and manually preparing it and adding it to the cluster using `ceph-volume`.

### What I did
- edit the k8s cluster definition and remove `/mnt/sda5`
  - nothing really happened, so I had to manually delete the `rook-ceph-osd-id-2` deployment
- (on ceph-0 host): `umount /mnt/sda5`, `wipefs -a /dev/sda5`
- exec into `rook-ceph-osd-id-0-xxx-yyy` pod (all the following steps are done there)
- copied `/var/lib/rook/osd0/rook-ceph.config` to `/etc/ceph/ceph.conf`
- added `fsid = ...` (the cluster id showed by `ceph -s`) to the `[global]` section of `/etc/ceph/ceph.conf`
- created `/var/lib/ceph/bootstrap-osd/ceph.keyring` with output of `ceph auth get client.bootstrap-osd`
- (optional) edited `/etc/lvm/lvm.conf` and changed `use_lvmetad` from `1` to `0` (otherwise lvm tools give a harmless `Failed to connect to lvmetad. Falling back to device scanning.` warning)
- prepared `/dev/sda5` for a new OSD using bluestore:
```
# ceph-volume lvm prepare --data /dev/sda5 --bluestore --no-systemd
Running command: /bin/ceph-authtool --gen-print-key
Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new b17119dc-0f22-4668-be03-651e01c60407
Running command: /usr/sbin/vgcreate --force --yes ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9 /dev/sda5
 stdout: Physical volume "/dev/sda5" successfully created.
 stdout: Volume group "ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9" successfully created
Running command: /usr/sbin/lvcreate --yes -l 100%FREE -n osd-block-b17119dc-0f22-4668-be03-651e01c60407 ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9
 stdout: Logical volume "osd-block-b17119dc-0f22-4668-be03-651e01c60407" created.
Running command: /bin/ceph-authtool --gen-print-key
Running command: /bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-2
Running command: /bin/chown -h ceph:ceph /dev/ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9/osd-block-b17119dc-0f22-4668-be03-651e01c60407
Running command: /bin/chown -R ceph:ceph /dev/mapper/ceph--ac1ca0e2--9683--4260--9ec9--14df55dd71a9-osd--block--b17119dc--0f22--4668--be03--651e01c60407
Running command: /bin/ln -s /dev/ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9/osd-block-b17119dc-0f22-4668-be03-651e01c60407 /var/lib/ceph/osd/ceph-2/block
Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-2/activate.monmap
 stderr: got monmap epoch 3
Running command: /bin/ceph-authtool /var/lib/ceph/osd/ceph-2/keyring --create-keyring --name osd.2 --add-key [redacted]
 stdout: creating /var/lib/ceph/osd/ceph-2/keyring
added entity osd.2 auth auth(auid = 18446744073709551615 key=[redacted] with 0 caps)
Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-2/keyring
Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-2/
Running command: /bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 2 --monmap /var/lib/ceph/osd/ceph-2/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-2/ --osd-uuid b17119dc-0f22-4668-be03-651e01c60407 --setuser ceph --setgroup ceph
--> ceph-volume lvm prepare successful for: /dev/sda5
```
- let's see what we have in `/var/lib/ceph/osd/ceph-2`:
```
# ls -al /var/lib/ceph/osd/ceph-2/
total 52
drwxrwxrwt 2 ceph ceph  300 Aug 14 09:13 .
drwxr-x--- 3 ceph ceph 4096 Aug 14 09:12 ..
-rw-r--r-- 1 ceph ceph  474 Aug 14 09:12 activate.monmap
lrwxrwxrwx 1 ceph ceph   93 Aug 14 09:12 block -> /dev/ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9/osd-block-b17119dc-0f22-4668-be03-651e01c60407
-rw-r--r-- 1 ceph ceph    2 Aug 14 09:13 bluefs
-rw-r--r-- 1 ceph ceph   37 Aug 14 09:13 ceph_fsid
-rw-r--r-- 1 ceph ceph   37 Aug 14 09:13 fsid
-rw------- 1 ceph ceph   56 Aug 14 09:12 keyring
-rw-r--r-- 1 ceph ceph    8 Aug 14 09:13 kv_backend
-rw-r--r-- 1 ceph ceph   21 Aug 14 09:13 magic
-rw-r--r-- 1 ceph ceph    4 Aug 14 09:13 mkfs_done
-rw-r--r-- 1 ceph ceph   41 Aug 14 09:13 osd_key
-rw-r--r-- 1 ceph ceph    6 Aug 14 09:13 ready
-rw-r--r-- 1 ceph ceph   10 Aug 14 09:13 type
-rw-r--r-- 1 ceph ceph    2 Aug 14 09:13 whoami
```
- `mkdir /var/lib/rook/osd2 && cp -d /var/lib/ceph/osd/ceph-2/* /var/lib/rook/osd2`
- copied `/var/lib/rook/osd0/rook-ceph.config` to `/var/lib/rook/osd2`, edited it, changed `run dir` to `/var/lib/rook/osd2`, removed `[osd.0]` section
- at this point everything is prepared, I got the `rook-ceph-osd-id-0` deployment yaml, edited it to change all OSD id occurrences from `0` to `2` and the uuid to `b17119dc-0f22-4668-be03-651e01c60407` (you can find it in the `ceph-volume` output), created a new `rook-ceph-osd-id-2` deployment, and there we go, we have a `ceph-volume` deployed OSD!

### Other mentions
- as we can see in `ceph-volume` output, it uses lvm in order to prepare a partition for a new OSD; let's list the created lvm objects:
```
# pvs
  PV         VG                                        Fmt  Attr PSize PFree
  /dev/sda5  ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9 lvm2 a--  1.83t    0
# vgs
  VG                                        #PV #LV #SN Attr   VSize VFree
  ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9   1   1   0 wz--n- 1.83t    0
# lvs
  LV                                             VG                                        Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  osd-block-b17119dc-0f22-4668-be03-651e01c60407 ceph-ac1ca0e2-9683-4260-9ec9-14df55dd71a9 -wi-ao---- 1.83t
```
- we notice that the lvm logical volume name is `osd-block-[uuid]` - the uuid of the new OSD
- `ceph-volume` only supports preparing block devices (partitions or full disks), not directories

**Comment by BlaineEXE** [comment]
I think it's also worth discussing that because supporting ceph-volume is such a huge task, figuring out a minimum-acceptable feature set to target for the first PR is a good idea. @dmick @travisn @liewegas @jcsp 

Minimal feature ideas:
- Able to prepare single-disk OSDs as well as disk+metadata-partition OSDs
- Prepare disks with the most minimal amount of tooling/setup needed. If disks can be prepared without LVM, for example, I think we should do that. Definitely leave disk encryption for later.
- The OSD purging as part of the volume preparation process you played around with feels like a very separate feature from initial support of ceph-volume
- Prepare blank (free) disks (ceph-volume may have a feature to test if a disk is free? @jcsp)
- I haven't quite decided if I feel like we should also target zapping and preparing disks which already have a partition table, but it is a notable option
- ???

**Comment by lbogdan** [comment]
Not everything in my write-up (like OSD purging) should go into this feature, I just wanted to document a full step-by-step process for replacing a rook prepared directory OSD to a `ceph-volume` prepared device OSD, on the same partition the directory used to be mounted.

I'd also add
- Able to prepare partitions (which is actually the thing I'm most interested in 🙂)

About your point
> If disks can be prepared without LVM

that's what `ceph-volume` does, although it has a plugin system, the only available plugin right now is [the LVM one](http://docs.ceph.com/docs/mimic/ceph-volume/lvm/#ceph-volume-lvm).

**Comment by alfredodeza** [comment]
ceph-volume doesn't create OSDs unless it is with LVM (for now). There are no current plans to support anything but LVM at the moment.
Preparing disks with dmcrypt means using `--dmcrypt` in ceph-volume, nothing else. Unsure what that means for rook internals though, happy to accommodate things to help out here.

**Comment by liewegas** [comment]
Yeah, I think if we do this right then enabling various ceph-volume features should just mean mapping properties to ceph-volume flags.  If there is additional magic needed to the rook side to make e.g. dmcrypt work then we're probably doing it wrong!

**Comment by jcsp** [comment]
> figuring out a minimum-acceptable feature set to target for the first PR is a good idea.

The minimum feature set would be just to implement whatever Rook can already do, but via ceph-volume, right?

**Comment by lbogdan** [comment]
@alfredodeza Is it possible to specify an existing path for the OSD config dir? Right now I see it mounts a tmpfs in `/var/lib/ceph/osd/ceph-ID`, and there's no command line arguments for changing that.

**Comment by alfredodeza** [comment]
@lbogdan we don't accept custom locations because it is easy to misconfigure and hard to do it robustly. This was a design decision from the start. Is it a hard requirement for rook?

**Comment by liewegas** [comment]
Maybe a combination of

- map /var/lib/rook/... to /var/lib/ceph in the container so that the "standard" paths are always presented to ceph tools and daemons
- add a ceph-volume option to skip the tmpfs mount and instead just write the files to the correct location.  the fact that we're inside a container serves essentially the same purpose the tmpfs did

**Comment by lbogdan** [comment]
> map /var/lib/rook/... to /var/lib/ceph in the container so that the "standard" paths are always presented to ceph tools and daemons

All ceph tools and daemons (except `ceph-volume`) take the path as an argument, so this is not really an issue,

> add a ceph-volume option to skip the tmpfs mount and instead just write the files to the correct location. the fact that we're inside a container serves essentially the same purpose the tmpfs did

This would be nice, but not a hard requirement; as I was saying above, we can just copy the files from where `ceph-volume` writes them to where we need them after preparing.

**Comment by liewegas** [comment]
On Thu, 16 Aug 2018, Bogdan Luca wrote:
> > map /var/lib/rook/... to /var/lib/ceph in the container so that the "standard" paths are always presented to ceph tools and daemons
> 
> All ceph tools and daemons (except `ceph-volume`) take the path as an argument, so this is not really an issue,

It's an issue for ceph-volume, though, and using default paths will simplify usage for the ceph tools, and avoid the possibility of a path dependency we just haven't noticed yet or one that is newly introduced in the future.

Is there a reason *not* to map to the standard location?

**Comment by lbogdan** [comment]
I guess it depends on what you mean by *map*.

**Comment by liewegas** [comment]
I'm probably using the wrong words.. I'm talking about a bind mount from /var/lib/rook/ceph/$cluster (or whatever it is) on the host to /var/lib/ceph inside the container.  I forget what docker and/or kubernetes call that :)

**Comment by travisn** [comment]
@leseb would be great to discuss this more when you are back online

**Comment by lbogdan** [comment]
Hey guys, I know I said I'm gonna look into this and then disappeared into thin air - I was busy working on the project I use rook for. 🙂 I'll have a bit of time next week, so please let me know how should I go about this.

**Comment by jan--f** [comment]
I have a few comments inline and thoughts regarding this. I'm fairly ignorant how rook deploys OSD's currently so feel free to tell me to rtfm if I'm missing crucial points.

> Here are a few thoughts around integrating ceph-volume to rook. Scenarios to consider while implementing these changes:
> 
>     * ceph-volume only supports devices/LVM
While ceph-volume supports raw block devices for some application (wal/db and journals) I think there is an argument to be made for limiting ourselves to LVM, mostly for ease of management. Imho it's easier to manage logical volumes then (also) mess around with partitions.
> 
>     * What about support for directories? At a minimum we need to continue to support directories for clusters that already exist. For testing it is also convenient to use a directory where a device is not available
Not sure what you mean by directory support, does this refer to ceph-disk deployed bluestore/filestore OSDs? If so ceph-volume can manage those with the [simple plugin](http://docs.ceph.com/docs/master/ceph-volume/simple/#ceph-volume-simple).
> 
>     * Should we support directories only pre-existing from an upgrade, and not for new clusters or new osds? Since LVM would now be supported, is there any production scenario that would require a directory?
See above....I'd argue LVM is the way to go.
> 
> 
> This work to integrate ceph-volume will mostly affect the sources inside the [osd daemon](https://github.com/rook/rook/tree/master/pkg/daemon/ceph/osd) directory. A lot of this code will now be simplified by calling ceph-volume, instead of Rook doing the work itself. Hopefully we can remove most of this code from Rook, but it depends on what we need to continue to support for backward compatibility as described below.
> 
>     * Partitioning a device
> 
>     * calling ceph-osd mkfs
> 
>     * configuring the wal and db on different devices (nvme/ssd) from the data device
> 
> 
> The entrypoint for rook to partition and prepare osds is found in the [Provision method](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/osd/daemon.go#L59). All code touched by execution of this method will need to be finely reviewed. This is running in the "osd-prepare" pod as a job on each node where osds are to be provisioned. This method iterates through all the devices and directories on the node and stores the resulting osd IDs in a configmap named "rook-ceph-osd--config". After this pod finishes, the operator will start an osd deployment for each osd to run independently. Thus, we need to pass the option to ceph-volume so that it will skip starting the daemon process since rook will start it independently.
Maybe it makes sense to split out the LVM management from the OSDs. The rough idea would be to put a single partition on every device that is to be used for ceph, mostly since LVM on raw block devices can be a hassle. Then add the necessary LVM stuff (pv, vg) and maybe even the lv for the to-be-created OSD (?). Pass the necessary lv's to the OSD pod and call ceph-volume or pass the vg's and have the OSD pod create its own lv's.
I think that makes management easier (and possible) especially for complex deployments (say several OSDs with wal/db on a solid state device, encryption and a LVM cache layer or so). We could also add LVM tags if we need some persistent information stored regarding any of the pieces (like ceph-volume does).
The drive groups proposal (https://docs.google.com/document/d/1iwTnQc8d9W3BpQHgGYTMZSKvN6J7s0z8kQaYNxYvLho/edit#heading=h.tupp5sz4xaqd , ping @jcsp if you need access) could (or should) probably also play a role here. While this is not quite hashed out yet, this structure could serve as the input to this LVM management layer.

**Comment by travisn** [comment]
As far as rook's creation of OSDs currently we kept it as simple as possible with two options. See [this section](https://rook.io/docs/rook/v0.8/ceph-cluster-crd.html#storage-selection-settings) for a few more details on these settings. The user can specify:
1. A raw device such as `sda`. Rook will partition it, call `ceph-osd mkfs` and start the osd. See the sample [with specific devices](https://rook.io/docs/rook/v0.8/ceph-cluster-crd.html#storage-configuration-specific-devices)
1. A directory on a formatted filesystem. Rook will call `ceph-osd mkfs` and start the osd. See the sample [with a directory](https://rook.io/docs/rook/v0.8/ceph-cluster-crd.html#storage-configuration-cluster-wide-directories). It's simply a path on the host mounted into the osd container.

For backward compatibility we would need to continue to support these at least for upgraded clusters. In that case we might skip ceph-volume invocations if that is necessary. 

With LVM being the mainline scenario, I'd like to understand how how we can make this simple for the user, while also flexible. Can/should we automatically setup LVM if a raw device is provided (option 1 above)? What does specifying an LV or drive group look like in the [cluster CRD](https://rook.io/docs/rook/v0.8/ceph-cluster-crd.html)? We need to put together a [design doc](https://github.com/rook/rook/tree/master/design) as we answer some of these questions.

**Comment by travisn** [comment]
After prototyping with ceph-volume in rook, I've started a design doc capturing the approach. @jan--f and everyone else on this issue, comments requested on #2242!
