### ISSUE TITLE
Update Prometheus from ancient v0.40.0

### ISSUE THREAD

**Issue by travisn** [rook/rook#13459]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The version of Prometheus in use by Rook docs and CI is ancient at v0.40.0. 
There are several references to https://raw.githubusercontent.com/coreos/prometheus-operator/v0.40.0/bundle.yaml, which is over three years old. 

The CI is showing warnings that old deprecated resources are being used because of this old version of prometheus such as from [this build](https://github.com/rook/rook/actions/runs/7269069825/job/19806093541):
```
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
```

**Expected behavior:**
The latest version of the [prometheus operator](https://raw.githubusercontent.com/coreos/prometheus-operator/v0.40.0/bundle.yaml) is v0.70.0. It's time to update!

**Comment by Sunnatillo** [comment]
I want to work on this. I could not assign issue to myself

**Comment by travisn** [comment]
@Sunnatillo Thanks for working on this. See the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#self-assign-issue) for getting started, and also the keyword to self-assign the issue.

**Comment by obnoxxx** [comment]
@Sunnatillo  wrote:
> I want to work on this. I could not assign issue to myself

I assigned it to you. But as @travisn  wrote, you should be able to self-assign as well. 
Thanks for looking into this!

**Comment by Sunnatillo** [comment]
We are facing following error when uplifting prometheus version. 

### Error: CustomResourceDefinition.apiextensions.k8s.io "prometheusagents.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

## Issue Description:

I attempted to upgrade Prometheus from version v0.40.0 to v0.71.1 in my Kubernetes cluster. The upgrade command used was:

```bash
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml
```

Encountered the following error:

```bash
Error from server (Invalid): error when creating "https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

## Explanation:
The error stems from the fact that `kubectl apply` command stores the `kubernetes.io/last-applied-configuration` annotation, even for new resources, Kubernetes has a restriction for the size of annotations, max 262144 bytes. To bypass this, a quick workaround is to use `kubectl create` instead of `kubectl apply`. However, this method may not work if Prometheus Operator is already present in the cluster.

## Workaround for New Installations:

If you do not have the Prometheus Operator in your cluster, use the following command:
```bash
kubectl create -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml
```

## Workaround for Upgrading from an Older Version:

When upgrading from an older version, using `kubectl create` might fail due to existing resources. In this case, the error would be:

```bash
Error from server (AlreadyExists): error when creating "https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml": deployments.apps "prometheus-operator" already exist.
```
For existing Prometheus Operator, use the following commands:

```bash
kubectl replace -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml
kubectl create -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml
```

Note: The similar errors produced by these commands can be ignored, as they pertain to specific resources not found or already existing.
kubectl replace error: 
```bash
Error from server (NotFound): error when replacing "https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml": customresourcedefinitions.apiextensions.k8s.io "alertmanagerconfigs.monitoring.coreos.com" not found
```
kubectl create error:
```bash
Error from server (AlreadyExists): error when creating "https://raw.githubusercontent.com/coreos/prometheus-operator/v0.71.1/bundle.yaml": customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists
```

This should help you successfully upgrade Prometheus Operator in your Kubernetes cluster.
