### ISSUE TITLE
make codegen can not generate deepcopy code

### ISSUE THREAD

**Issue by hejiwen** [rook/rook#13497]
I add a new CRD on rook with follow steps，
1. use kubebuilder to generator type.go,（kubebuilder init --domain ceph.io、kubebuilder create api --group ceph --version v1 --kind CephSMB）
2.  copy CephSMB definition of cephsmb_types.go to rook/pkg/apis/ceph.rook.io/v1/types.go
3. rm rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
4. make codegen(ROOK: tag 1.11.10) to generator deepcopy code， it doesn‘t print error， but haven't generate rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go file. 
[root@M36-1 rook]# make codegen
Generating deepcopy funcs
Generating clientset for ceph.rook.io:v1 at github.com/rook/rook/pkg/client/clientset
Generating listers for ceph.rook.io:v1 at github.com/rook/rook/pkg/client/listers
Generating informers for ceph.rook.io:v1 at github.com/rook/rook/pkg/client/informers

my question: 
1.  how to add a CRD on rook, is there som introduction document?
2. why  make codegen  does not work? 

my enviroment:
go version: 1.20.6
kubebuilder: 3.13

**Comment by zhucan** [comment]
"make codegen" can not work? the errors is?

**Comment by hejiwen** [comment]
no error, the output :
[root@M36-1 rook]# make codegen
Generating deepcopy funcs
Generating clientset for ceph.rook.io:v1 at github.com/rook/rook/pkg/client/clientset
Generating listers for ceph.rook.io:v1 at github.com/rook/rook/pkg/client/listers
Generating informers for ceph.rook.io:v1 at github.com/rook/rook/pkg/client/informers

**Comment by zhucan** [comment]
can you pasted the  cephsmb_types.go?

**Comment by hejiwen** [comment]
// CephSMBSpec defines the desired state of CephSMB
type CephSMBSpec struct {
        // INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
        // Important: Run "make" to regenerate code after modifying this file

        // Foo is an example field of CephSMB. Edit cephsmb_types.go to remove/update
        Foo string `json:"foo,omitempty"`
}

// CephSMBStatus defines the observed state of CephSMB
type CephSMBStatus struct {
        // INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
        // Important: Run "make" to regenerate code after modifying this file
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// CephSMB is the Schema for the cephsmbs API
type CephSMB struct {
        metav1.TypeMeta   `json:",inline"`
        metav1.ObjectMeta `json:"metadata,omitempty"`

        Spec   CephSMBSpec   `json:"spec,omitempty"`
        Status CephSMBStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// CephSMBList contains a list of CephSMB
type CephSMBList struct {
        metav1.TypeMeta `json:",inline"`
        metav1.ListMeta `json:"metadata,omitempty"`
        Items           []CephSMB `json:"items"`
}

**Comment by hejiwen** [comment]
I found that orgin rook does not work，what's wrong with my environment？
git clone https://github.com/rook/rook.git
git checkout v1.11.10
rm -rf rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
make codegen

**Comment by travisn** [comment]
Before implementing a new CRD, please open a PR for a design document with the proposed CRD, thanks.

**Comment by travisn** [comment]
btw run `make crds` to generate crds.yaml after updates are made to types.go

**Comment by zhucan** [comment]
@hejiwen also need to update  register.go, like this:
```
		&CephRBDMirrorList{},
		&CephFilesystemMirror{},
		&CephFilesystemMirrorList{},
		&CephFilesystemSubVolumeGroup{},
		&CephFilesystemSubVolumeGroupList{},
		&CephBlockPoolRadosNamespace{},
		&CephBlockPoolRadosNamespaceList{},
		&CephCOSIDriver{},
		&CephCOSIDriverList{},
		&CephSMB{},
		&CephSMBList{},
```

**Comment by BlaineEXE** [comment]
codegen may have an assumption that the code is present in `GOPATH`.

**Comment by travisn** [comment]
Note that the ceph team has been investing in a separate Samba project. See https://github.com/samba-in-kubernetes/samba-operator. We should have some discussion about the proper Samba integration so we don't have two separate projects for the same feature.

**Comment by hejiwen** [comment]
> codegen may have an assumption that the code is present in `GOPATH`.

add deepcopy-gen parameter "-v 1000", the output is :
ok/rook/pkg/apis/ceph.rook.io/v1.StretchClusterSpec
I0105 10:11:07.528782 2235798 deepcopy.go:586] Generating deepcopy function for type github.com/rook/rook/pkg/apis/ceph.rook.io/v1.StretchClusterZoneSpec
I0105 10:11:07.528928 2235798 deepcopy.go:586] Generating deepcopy function for type github.com/rook/rook/pkg/apis/ceph.rook.io/v1.TopicEndpointSpec
I0105 10:11:07.529169 2235798 deepcopy.go:586] Generating deepcopy function for type github.com/rook/rook/pkg/apis/ceph.rook.io/v1.ZoneSpec
I0105 10:11:07.529284 2235798 execute.go:67] Assembling file "../../../github.com/rook/rook/pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go"
I0105 10:11:07.556368 2235798 main.go:84] Completed successfully.

**Comment by hejiwen** [comment]
[log.txt](https://github.com/rook/rook/files/13837363/log.txt)
attach the full log

**Comment by phlogistonjohn** [comment]
Hi there! I'm one of the maintainers of the [samba-operator project](https://github.com/samba-in-kubernetes/samba-operator).  I'm also actively working to add "native" SMB support to Ceph, via cephadm orchestration. You might say I am really interested in smb & ceph and so some of the Rook team pointed me at this issue :-)


If you are looking to just use SMB services from within a K8S cluster I would probably recommend taking a look at samba-operator. It's been around a few years now and we have a small but active community of users. Our test platform uses Rook as a storage backend so that implies that samba-operator & rook ought to work well together. I haven't had a lot of time recently to work on the operator but if you are a Go programmer we'd probably be able to consider contributions if it doesn't do something you need.

On the other hand, due to requirements at $DAYJOB. I've been looking into adding smb support to non-kubernetes Ceph clusters using cephadm orchestration. Just last week I opened a draft pr to add a necessary set of minimal features to deploy a samba server instance. However, this is a very recent effort and don't know how many people know about it - I know the Cephadm PTL is and so is my team at work.

Speaking of that team we're also working on testing samba on ceph and improving ceph, samba and our own glue layers (samba-containers, sambacc) which are (will be) used for both kinds of deployment.

So, I am very curious that you intend to add a CephSMB to Rook and don't have much of an idea on what your plans for it are, or how you intend it to work.
I'm curious - did you look at samba-operator at all? If so, was there something missing that you need?


I'm happy to discuss more. Thanks!

**Comment by obnoxxx** [comment]
@hejiwen,

Thank you for raising this issue!

I think at this stage, it would be very helpful if you could explain a bit more what it really is that you are trying to achieve, conceptually, and on a higher level, for the community to be able to really help you:

* so you are trying to add a new CRD.
* is it a modification intended for your own use primarily ore are you intending to contribute this extension back to rook upstream if it is deemed generally useful?
* Is the SMB  in `CephSMB` meant to refer to the SMB file storage protocol (as provided by the Samba software for example) or is it referring to something else?


In any case, a pointer to a git branch with your changes would be helpful in allowing people to reproduce the issues you are facing and help fix them.

**Comment by hejiwen** [comment]
> Hi there! I'm one of the maintainers of the [samba-operator project](https://github.com/samba-in-kubernetes/samba-operator). I'm also actively working to add "native" SMB support to Ceph, via cephadm orchestration. You might say I am really interested in smb & ceph and so some of the Rook team pointed me at this issue :-)
> 
> If you are looking to just use SMB services from within a K8S cluster I would probably recommend taking a look at samba-operator. It's been around a few years now and we have a small but active community of users. Our test platform uses Rook as a storage backend so that implies that samba-operator & rook ought to work well together. I haven't had a lot of time recently to work on the operator but if you are a Go programmer we'd probably be able to consider contributions if it doesn't do something you need.
> 
> On the other hand, due to requirements at $DAYJOB. I've been looking into adding smb support to non-kubernetes Ceph clusters using cephadm orchestration. Just last week I opened a draft pr to add a necessary set of minimal features to deploy a samba server instance. However, this is a very recent effort and don't know how many people know about it - I know the Cephadm PTL is and so is my team at work.
> 
> Speaking of that team we're also working on testing samba on ceph and improving ceph, samba and our own glue layers (samba-containers, sambacc) which are (will be) used for both kinds of deployment.
> 
> So, I am very curious that you intend to add a CephSMB to Rook and don't have much of an idea on what your plans for it are, or how you intend it to work. I'm curious - did you look at samba-operator at all? If so, was there something missing that you need?
> 
> I'm happy to discuss more. Thanks!

I have been trying to do some storage containerization work  recently , I have implemented smb containerization by native smb deployment yaml  based on Rook+Ceph as  storage backend ，since ROOK already has NFS but no SMB,  so I am trying to add smb to rook。
I didn't find project before( samba operator), it‘s so great, I'll try it out recently to see if it meets my needs.

**Comment by hejiwen** [comment]
> @hejiwen,
> 
> Thank you for raising this issue!
> 
> I think at this stage, it would be very helpful if you could explain a bit more what it really is that you are trying to achieve, conceptually, and on a higher level, for the community to be able to really help you:
> 
>     * so you are trying to add a new CRD.
> 
>     * is it a modification intended for your own use primarily ore are you intending to contribute this extension back to rook upstream if it is deemed generally useful?
> 
>     * Is the SMB  in `CephSMB` meant to refer to the SMB file storage protocol (as provided by the Samba software for example) or is it referring to something else?
> 
> 
> In any case, a pointer to a git branch with your changes would be helpful in allowing people to reproduce the issues you are facing and help fix them.

I want to add samba(CIFS) to rook and plan to add ctdb and pdns to rook  to implement HA and DNS（load balance).
Right now，I am not sure how to implement HA and  loadbalance in K8S+ROOK on isolated environment, can you give me some help?

**Comment by BlaineEXE** [comment]
I agree with what Michael has suggested. A thorough description of requirements, and any planning that you have done so far will be a baseline necessity for moving forward with any of this work.

It is jumping too many steps ahead to just add a new CRD and controller into Rook. I think this work is very valuable, and I would like to see it become part of Rook's feature set, but we should slow down and talk about community and technical requirements first.

After a conversation with John Mulligan earlier this week, my understanding is this: 
SMB support in Ceph itself is still being explored and is very much in its infancy.

The Ceph SMB is new and unstable, and instability makes integration very hard. It also makes regular connection with the Ceph team critical. In practicality, this means that you (plus others, potentially) need to be actively engaged with the Ceph team doing the SMB work.

There are also a lot of well-intentioned people on the internet who will create a big feature, add it, and then leave. Rook is a community project and thrives on community involvement, and it harms the project when we have to remove a feature because the creator did not also sign up to help users with issues and bugs. Enough people should also be able to provide assurance that they can commit to investing in the work and maintaining it for at least 2 years while the project moves from its infancy into something that is more stable.

There is also still the matter of the existing SMB operator that John Mulligan and his team have worked on. After our experiences with NFS, I am tending to think that this existing operator may still be the best place for supporting "Ceph-backed SMB shares on Kubernetes." It would require design efforts in that project, but any work spent researching, prototyping, designing, and implementing HA and load balancing will support a much wider ecosystem than just Rook/Ceph. I can also say from some experience doing R&D and prototype work for load-balanced HA with NFS that those topics are HUGE efforts not to be taken lightly.

As one of the technical leads for the NFS-Ganesha work in Rook, I can see that the SMB work looks very similar to the NFS work, generally speaking. I have also seen how some of the design decisions made with CephNFS have been ongoing challenges for Rook, our maintenance, and for our users' experience of the feature.

IMO, a more sustainable architecture would be to first see what work can be done in the standalone SMB operator to enable Ceph-backend support. After that, on the Rook side, we can spend some time figuring out how to write a lighter-weight "adapter" to help Rook keep the standalone operator up-to date with CephCluster details. This would allow the two operators to function well alongside each other and allow each project to make the best use of their own domain experience.

So, as a follow-up, this work should start with Ceph and not with Rook. I would suggest that it would be good to start a dialogue with @phlogistonjohn on the Ceph slack channel (ref: https://ceph.io/en/community/connect/) to talk about getting involved with the Ceph efforts and expressing interest in bringing those to Kubernetes.
