### ISSUE TITLE
`useAllDevices: true` targets the wrong device after upgrading to `v1.13.2`

### ISSUE THREAD

**Issue by budimanjojo** [rook/rook#13564]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I upgraded to `v1.13.2` and suddenly one of my 3 nodes OSD (`osd-0`) is not starting up with `Init:Error` status. I did `k -n rook-ceph logs rook-ceph-osd-0-xxxx -c activate` and got this:
```
+ OSD_ID=0
+ CEPH_FSID=a7a469e6-2749-4ad7-9d7b-b5a790b93f96
+ OSD_UUID=1716a1ea-68db-4748-8393-549fcdf4fc47
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-0
+ CV_MODE=raw
+ DEVICE=/dev/sdb
+ cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
+ python3 -c '
import configparser

config = configparser.ConfigParser()
config.read('\''/etc/ceph/ceph.conf'\'')

if not config.has_section('\''global'\''):
    config['\''global'\''] = {}

if not config.has_option('\''global'\'','\''fsid'\''):
    config['\''global'\'']['\''fsid'\''] = '\''a7a469e6-2749-4ad7-9d7b-b5a790b93f96'\''

with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
    config.write(configfile)
'
+ ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.0]
        key = AQBkf/piq5gmNhAATvHyIShR2qpsG1A8Lp5BUQ==
+ [[ raw == \l\v\m ]]
++ mktemp
+ OSD_LIST=/tmp/tmp.LLr10BTmmg
+ ceph-volume raw list /dev/sdb
 stderr: lsblk: /dev/sdb: not a block device
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 174, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 130, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 99, in generate
    info_devices.append(disk.lsblk(dev, abspath=True))
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 245, in lsblk
    abspath=abspath)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 337, in lsblk_all
    raise RuntimeError(f"Error: {err}")
RuntimeError: Error: ['lsblk: /dev/sdb: not a block device']
```

As seen above, it can't find `/dev/sdb` which indeed doesn't exist. It should be `/dev/sda` and I don't know why. So, I decided to **not** use `useAllDevices: true` and use manual selecting devices by names instead. I edited the `CephCluster` to not use all devices and added `storage.nodes[]` to it and preparing to manually remove the OSDs and readd them because according to https://github.com/rook/rook/discussions/13357#discussioncomment-7823653 changing that doesn't do anything to existing cluster. But, magically just by editing the `CephCluster` fixed the `osd-0` problem, it weirdly picked the right device now. But, after a couple of minutes, `osd-2` ended up in the same state as `osd-0` which is finding a non existing `/dev/sdb` instead of `/dev/sda` and fails to start.

**Expected behavior:**

OSDs should be up just like before doing the upgrade.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
https://github.com/budimanjojo/home-cluster/blob/53838a50898326c793529988dee402206574272e/cluster/apps/rook-ceph/rook-ceph/cluster/helmrelease.yaml

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

```
  cluster:
    id:     a7a469e6-2749-4ad7-9d7b-b5a790b93f96
    health: HEALTH_WARN
            1 osds down
            1 host (1 osds) down
            Degraded data redundancy: 5941/17823 objects degraded (33.333%), 56 pgs degraded, 113 pgs undersized

  services:
    mon: 3 daemons, quorum n,q,r (age 100m)
    mgr: a(active, since 6h)
    osd: 3 osds: 2 up (since 31m), 3 in (since 34m)

  data:
    pools:   9 pools, 113 pgs
    objects: 5.94k objects, 19 GiB
    usage:   53 GiB used, 297 GiB / 350 GiB avail
    pgs:     5941/17823 objects degraded (33.333%)
             57 active+undersized
             56 active+undersized+degraded

  io:
    client:   101 KiB/s wr, 0 op/s rd, 2 op/s wr
```

**Environment**:
* OS (e.g. from /etc/os-release): Talos v1.6.0
* Kernel (e.g. `uname -a`): 6.1.67
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.1 (7fe91d5d5842e04be3b4f514d6dd990c54b29c76) reef (stable)
* Kubernetes version (use `kubectl version`): v1.28.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

**Comment by subhamkrai** [comment]
@budimanjojo how osd are backed? lso, pvc or?

**Comment by budimanjojo** [comment]
what is lso? It's a host based cluster with physical drives.

**Comment by travisn** [comment]
The OSDs are expected to keep a symlink to the device that would survive the node restarts in case the devices are renamed. But if that is not working in your env, try using the full udev path as described in the [Storage Selection settings](https://rook.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/#storage-selection-settings).

**Comment by budimanjojo** [comment]
@travisn Thanks for the reply!
I got it fixed by using `devices` and give it the full udev path. But my report is about `useAllDevices: true` not working as expected after this release (it was fine before upgrading). 
I don't quite understand understand the "expected to keep a symlink to the device". Is it something to do with the OS I'm using which is Talos?

**Comment by reefland** [comment]
@budimanjojo - the "expected to keep a symlink to the device" is likely in reference to the `/dev/sda` type names can point to different device upon reboot. These are pretty much assigned by who responds first to device discovery.  If a host has multiple devices, then there is no guarantee that `/dev/sda` will point to the same device on next reboot.

My apologies if you know this, but I'll write for whoever else comes across this...  Linux automatically creates symlinks for you which have consistent names and point the appropriate device.  Nothing you need to do other than use the correct path. There are multiple ones you can use located:

```
$ ls -l /dev/disk/

drwxr-xr-x 2 root root 540 Jan 16 16:03 by-id
drwxr-xr-x 2 root root 140 Jan 16 16:03 by-label
drwxr-xr-x 2 root root 200 Jan 16 16:03 by-partuuid
drwxr-xr-x 2 root root 340 Jan 16 16:03 by-path
drwxr-xr-x 2 root root 160 Jan 16 16:03 by-uuid
```

The `by-id` is the one I like to use, for me the the device and each partition on `/dev/sda` has multiple referenced symlinks:

```
$ ls -l /dev/disk/by-id/ | grep "sda"
lrwxrwxrwx 1 root root  9 Jan 16 16:03 ata-Samsung_SSD_860_EVO_M.2_1TB_S415NS0R506801N -> ../../sda
lrwxrwxrwx 1 root root 10 Jan 16 16:03 ata-Samsung_SSD_860_EVO_M.2_1TB_S415NS0R506801N-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Jan 16 16:03 ata-Samsung_SSD_860_EVO_M.2_1TB_S415NS0R506801N-part3 -> ../../sda3
lrwxrwxrwx 1 root root 10 Jan 16 16:03 ata-Samsung_SSD_860_EVO_M.2_1TB_S415NS0R506801N-part4 -> ../../sda4
lrwxrwxrwx 1 root root 10 Jan 16 16:03 ata-Samsung_SSD_860_EVO_M.2_1TB_S415NS0R506801N-part5 -> ../../sda5
lrwxrwxrwx 1 root root  9 Jan 16 16:03 wwn-0x5002538e3150c98a -> ../../sda
lrwxrwxrwx 1 root root 10 Jan 16 16:03 wwn-0x5002538e3150c98a-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Jan 16 16:03 wwn-0x5002538e3150c98a-part3 -> ../../sda3
lrwxrwxrwx 1 root root 10 Jan 16 16:03 wwn-0x5002538e3150c98a-part4 -> ../../sda4
lrwxrwxrwx 1 root root 10 Jan 16 16:03 wwn-0x5002538e3150c98a-part5 -> ../../sda5
```

So I can use `/dev/disk/by-id/ata-Samsung_SSD_860_EVO_M.2_1TB_S415NS0R506801N` or `/dev/disk/by-id/wwn-0x5002538e3150c98a` to always reference the same device.  Should `sda` and `sdb` swap locations no issues, these symlinks generated at boot will point to the correct one.

**Comment by Rudi3** [comment]
I think I'm having the same or a similar issue on talos. Using `by-id` does not seem to fix it for me.
https://github.com/rook/rook/discussions/14037

Also tried https://github.com/rook/rook/issues/10860#issuecomment-1304936287 but the `block` symlink is not created. Presumably because the pod crashes before getting to that stage?

@budimanjojo  did you do anything in addition to upgrading via helm and maybe `kubectl -n rook-ceph rollout restart deploy`? Or use another path?

**Comment by budimanjojo** [comment]
@Rudi3 I ended up with setting `useAllDevices: false` and define the devices like so: https://github.com/budimanjojo/home-cluster/blob/8398f1abea3dc431522386f45f75729a8ea9ae8c/cluster/apps/rook-ceph/rook-ceph/cluster/helmrelease.yaml#L88-L97

**Comment by Rudi3** [comment]
@budimanjojo Thanks!

After some more poking around, I noticed that `ROOK_BLOCK_PATH` was set in the deployment `rook-ceph-osd-0`.
Deleting it and letting the operator recreate it, fixed it for me: `kubectl -n rook-ceph delete deployment rook-ceph-osd-0`

Not sure if this is expected behaviour.

**Comment by occ** [comment]
I just hit this issue after an OS upgrade, on about half of the nodes, despite having specified:

```
    useAllDevices: false
    devicePathFilter: "^/dev/disk/by-partlabel/osd[0-2]"
```

While deleting the deployment (and letting the operator recreate remaining OSDs) worked, I see that newly created OSDs still have `ROOK_BLOCK_PATH` set to device names such as `/dev/nvme1n1p3`. Rebooting the nodes might lead to the same issue.

Additional context:

Our servers have 3x NVMes per node. First one has the OS installed on a smaller partition, the remaining 2 are dedicated to OSDs (i.e., `/dev/nvme0n1p3`, `/dev/nvme1n1p1`, and `/dev/nvme2n1p1`). I suspect this is happening across all drives. In our case, we're only hitting the issue because one of the drives happens to have the third partition dedicated to ceph (when nvm1 and 2 are swapped `ROOK_BLOCK_PATH` still points to a valid device, but not when nvme0 is swapped)

**Comment by bitfisher** [comment]
We hit this too!

Using explicit node and device configuration like 
```yaml
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: node-01
        devices:
          - name: /dev/disk/by-id/scsi-3600508b1001c8f492048c5852615315a
      - name: node-02
        devices:
          - name: /dev/disk/by-id/scsi-3600508b1001c7b9d2c062a3c6ecde98b
      - name: node-03
        devices:
          - name: /dev/disk/by-id/scsi-3600508b1001c2b2d7712ce1cab7447f8
```

`ROOK_BLOCK_PATH` and `block` symlink set to `/dev/sd*`.

All nodes running 
```
NAME="Fedora Linux"
VERSION="40.20240519.3.0 (CoreOS)"
PRETTY_NAME="Fedora CoreOS 40.20240519.3.0"
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='40.20240519.3.0'
```

**Comment by cameronraysmith** [comment]
> ```
> useAllDevices: false
> devicePathFilter: "^/dev/disk/by-partlabel/osd[0-2]"
> ```

this approach seems to have solved the same issue for me with Operator/Cluster `1.14.5` noting the correct key from the helm values for filtering in that case

https://github.com/rook/rook/blob/v1.14.5/deploy/charts/rook-ceph-cluster/values.yaml#L358-L361

is `deviceFilter` as opposed to `devicePathFilter`

```
        storage:
          useAllNodes: true
          useAllDevices: false
          deviceFilter: "^/dev/disk/by-partlabel/osd[0-2]"
```

**Comment by sethjones** [comment]
Hey everyone,
I'm trying to adjust my cluster to use the above filter, and I'm having the issue that due to the cluster being in an unhealthy state because its not finding disks correctly all of a sudden, it wont restart the osd pods with the corrected configuration. 

After adjusting the cluster config with the filter, the node prep jobs seem to give a correct list of storage devices. 

Anyone have any advice on how to allow the ods to update?

Thanks

**Comment by occ** [comment]
@sethjones our workaround is to delete the deployments and let the operator recreate them with the right device name

**Comment by cameronraysmith** [comment]
> @sethjones our workaround is to delete the deployments and let the operator recreate them with the right device name

@sethjones this is what I do as well, but, in addition to deleting the deployments, I find I also have to restart the operator to trigger it to recreate them.

**Comment by sp98** [comment]
ROOK_BLOCK_PATH has to be possible root cause.  In case of `update` scenario, the `ROOK_BLOCK_PATH` is fetched from the currently running OSD deployment. So even though the `/dev/by-id/*` is now pointing to, say, `/dev/sdb`, rook operator will set `ROOK_BLOCK_PATH` to, say, `/dev/sde` by reading it from the currently running OSD deployment. 

So we might have to change how `ROOK_BLOCK_PATH` is set in case of `Update` scenario.

**Comment by bitfisher** [comment]
Why don't use `/dev/disk/by-id/...` - as configured -  instead of following symlink and use `/dev/sd...`?

**Comment by sp98** [comment]
I'll take a look if that can be done.

**Comment by bitfisher** [comment]
I assumed rook is doing so currently because that's how i interpreted the doc section[ `Storage Selection Settings -> devices`](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#storage-selection-settings) ...
```
name: The name of the devices and partitions (e.g., sda). The full udev path can also be specified for devices, partitions, and logical volumes (e.g. /dev/disk/by-id/ata-ST4000DM004-XXXX - this will not change after reboots).
```

Especially the udev-part ... `this will not change after reboots`

**Comment by BlaineEXE** [comment]
Entries in `/dev/disk/by-id` are generally expected to be consistent across reboots in linux systems. They should only change if disk controllers or physical disks themselves change. I believe that is Rook's current assumption about the state of the hardware.

I have to imagine that these systems are virtual in some way. Is that right? Are there options in the VM management systems being used to keep disk controller IDs (and any other properties that affect /dev/disk/by-id) consistent across reboots?

As far as fixing this in Rook, it does seem reasonable to me that if the `rook-ceph-osd-prepare-...` job runs on a node, finds an OSD that belongs to the existing cluster, rook should be able to adjust the existing deployment to change the disk ID path if necessary. However, to change that, we must ensure that Rook can architecturally support changing the consistency assumption about by-id paths. It will be imperative that Rook only update the path when it can be guaranteed that the OSD.<id> is otherwise exactly the same.

**Comment by occ** [comment]
@BlaineEXE you're right, /dev/disk references are stable between reboots. However, rook seems to resolve /dev/disk/ references and store the resolved device name (e.g., /dev/nvme0n1p1). Because /dev/nvme links aren't guaranteed to be consistent, OSDs might fail to start.

In our case, these are bare-metal servers.

I suspect the only change needed is for rook to keep using the /dev/disk/ references (or whatever actually matched the filters) rather than the resolved ones like /dev/sd* or /dev/nvme*

**Comment by BlaineEXE** [comment]
@occ can you post some outputs to show what you mean? Rook uses the values returned by `ceph-volume`, so if there is some issue we want to know what to fix and how to coordinate with the Ceph project to do so.

**Comment by occ** [comment]
Adding an example to help clarify the issue. I will later post the logs as well.

We have 3 drives on all nodes:
* `/dev/disk/by-partlabel/osd0 -> /dev/nvme0n1p1`
* `/dev/disk/by-partlabel/osd1 -> /dev/nvme1n1p1`
* `/dev/disk/by-partlabel/osd2 -> /dev/nvme2n1p3` (note the partition number 3)

On boot, kernel might name any of these drives nvme{0,1,2}.
If nvme2 in the example above gets (re)named to nvm0, OSD fails to start, because `ROOK_BLOCK_PATH` is `/dev/nvme2n1p3` and that device doesn't exist. I _think_ this is a rook bug.

FWIW– At this point we can reproduce this issue fairly consistently (we have to manually intervene and delete/recreate OSDs in about ~1/3rd of the reboots)

**Comment by BlaineEXE** [comment]
@occ , we need to collect more and complete information to know what is happening on the Rook/Ceph side.

Please post output logs from `rook-ceph-osd-prepare-...` on one of your nodes. From one of the OSDs on that node that is behaving improperly, please provide output from `kubectl get -o yaml pod rook-ceph-osd-...`.

**Comment by occ** [comment]
I just restarted 3 nodes. Sure enough one of them got a failing OSD.

See attached for the OSD 21 failing to start on node oecs10.

[rook-ceph-osd-21-75477b6845-pnqrm.yaml.txt](https://github.com/user-attachments/files/15958775/rook-ceph-osd-21-75477b6845-pnqrm.yaml.txt)
[rook-ceph-osd-prepare-oecs10-k7c69.provision.log](https://github.com/user-attachments/files/15958776/rook-ceph-osd-prepare-oecs10-k7c69.provision.log)

**Comment by occ** [comment]
I just fixed the issue to avoid production impact (delete deployment, wait for the operator to recreate with the right environment variable).

Here is the yaml for the "fixed" pod: [rook-ceph-osd-21-7c64756987-xdcvn.yaml.txt](https://github.com/user-attachments/files/15958905/rook-ceph-osd-21-7c64756987-xdcvn.yaml.txt)

When I diff them, the only meaningful delta I see is:

```diff
     - name: ROOK_BLOCK_PATH
-      value: /dev/nvme1n1p3
+      value: /dev/nvme0n1p3
```

I will reboot a few servers, recreate a failure, and get the logs you asked for

**Comment by BlaineEXE** [comment]
Appreciate it. I suspect the issue may be in the `activate` container, but I guess it could be elsewhere. You may as well also collect output logs from all containers using `kubectl logs <osd> --all-containers` just in case.

**Comment by occ** [comment]
FWIW (and with my limited understanding of rook and ceph) this diff illustrates the problem nicely. 

Rook is starting OSDs with ROOK_BLOCK_PATH set to a device name (not the symlink my filters target). I _think_ the fix is: rook keeps/uses the full device name (that matches my filter). i.e., `/dev/disk/by-partlabel/osd0` instead of `/dev/nvme0n1p3`.

I've issued a rolling restart in the cluster. I'll post everything from the next (un)lucky OSD.

**Comment by occ** [comment]
Here's another one.

[rook-ceph-osd-33-646c99c647-btsdc.yaml.txt](https://github.com/user-attachments/files/15959249/rook-ceph-osd-33-646c99c647-btsdc.yaml.txt)
[rook-ceph-osd-33-646c99c647-btsdc.activate.log](https://github.com/user-attachments/files/15959250/rook-ceph-osd-33-646c99c647-btsdc.activate.log)

Other containers in the pod are still in PodInitializing state, so there are no logs from them.

I'll keep this OSD down for a while to get you more information. Please let me know if you need anything else

**Comment by BlaineEXE** [comment]
Right, though I am remembering now the issues I/we had in Rook 3 years ago when piecing this together that means we can't quite do that, even though it seems like it should be the best way to fix things. `ceph-volume` does not output the `/dev/disk/by-...` information. It only operates using the base `/dev/X` devices. 

I see that in your prepare pod logs here:

```
2024-06-22 16:43:31.743530 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list --format json
2024-06-22 16:43:32.104951 D | cephosd: {
    "058d8f88-8f6e-4c02-b2b6-8a57caa33449": {
        "ceph_fsid": "XYZ",
        "device": "/dev/nvme1n1p3",
        "osd_id": 21,
        "osd_uuid": "058d8f88-8f6e-4c02-b2b6-8a57caa33449",
        "type": "bluestore"
    },
    "6eb7f642-aa76-4fc9-a800-6ea4c1789813": {
        "ceph_fsid": "XYZ",
        "device": "/dev/nvme2n1p1",
        "osd_id": 29,
        "osd_uuid": "6eb7f642-aa76-4fc9-a800-6ea4c1789813",
        "type": "bluestore"
    },
    "ac79480a-ddbd-48a1-85d5-de0c1595d59d": {
        "ceph_fsid": "XYZ",
        "device": "/dev/nvme0n1p1",
        "osd_id": 10,
        "osd_uuid": "ac79480a-ddbd-48a1-85d5-de0c1595d59d",
        "type": "bluestore"
    }
}
```

Rook (relying on `ceph-volume` to report OSDs) never actually receives information about the paths. Even if Rook did keep info from `/dev/disk/by-id`, Rook would still need to handle the case where the path changed due to controller replacement or other issues. With that in mind, I don't think it would be best for code maintenance for Rook to try to collect or propagate more info about the `/dev/disk/by-id/...` pathing. It would add complexity for what would likely be a less-than-a-second OSD boot time improvement in cases like this.

Contextually, Ceph, outside of Rook and running directly on nodes, expects the node (on startup) to run `ceph-volume X list` in some capacity, and then for a process to start OSDs for each OSD listed. Rook, running deployment/pods/containers for each OSD, can't follow that same process, so Rook has to use the Ceph tools (ceph-volume) in roundabout ways, like here in the `activate` script.

I'm reviewing the OP's description again, and things are making coming together.

```
+ ceph-volume raw list /dev/sdb
 stderr: lsblk: /dev/sdb: not a block device
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 174, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 130, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 99, in generate
    info_devices.append(disk.lsblk(dev, abspath=True))
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 245, in lsblk
    abspath=abspath)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 337, in lsblk_all
    raise RuntimeError(f"Error: {err}")
RuntimeError: Error: ['lsblk: /dev/sdb: not a block device']
```

In hindsight, it's obvious that this command would fall over even when non-Rook block devices go missing on the node and no longer. I'm guessing that is the Rook-context source of the issue.

It will still be good to see your logs to make sure the behavior is the same. It seems like that is likely, but double checking will still be good.

I'm working on a fix for the activate script now. I can cause a repro in my environment by manually changing `ROOK_BLOCK_PATH` to /dev/vdf in my minikube env that doesn't have a /dev/vdf.

**Comment by BlaineEXE** [comment]
Getting real-world validation is always really great. It would be awesome to have someone test the fix. While the PR to resolve the issue is in review, you can try to use this rook-ceph-operator image: `quay.io/brgardne/rook-ceph:14374-amd64`

I did my best to build and x86_64 image on my arm-based laptop. I checked it as best I can, but there is always a chance of an issue.

You could try to build the Rook image for yourself from my fork if you want as well: https://github.com/BlaineEXE/rook/tree/fix-osd-block-device-name-change

**Comment by BlaineEXE** [comment]
The latest `rook/ceph:master` image has been built (x86 and ARM) and contains this fix. We've been able to simulate the issue, but we don't have a like-for-like repro environment. If any users are willing to test the image to ensure it also works in their environments, that would be great.

**Comment by occ** [comment]
I can test it later today and post an update here. Thank you @BlaineEXE!

**Comment by occ** [comment]
just wanted to confirm – is updating the operator sufficient to test this? do I need to change the cluster config to use this image?

**Comment by occ** [comment]
I just restarted our cluster without hitting the issue. I can confirm that the issue is fixed

**Comment by cameronraysmith** [comment]
After updating to `1.14.8` and creating a new cluster, whenever a node that hosted an OSD is recycled the activate init container for that OSD fails with

<details><summary>osd log</summary>
<p>

```pytb
activate + CEPH_FSID=e03644bf-cea9-4117-a812-6d193a2b9a99
activate + OSD_UUID=e6d9527c-a1ed-4cc9-8b58-59d1d3160170
activate + OSD_STORE_FLAG=--bluestore
activate + OSD_DATA_DIR=/var/lib/ceph/osd/ceph-1
activate + CV_MODE=raw
activate + DEVICE=/dev/sdb
activate + cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
activate + python3 -c '
activate import configparser
stream logs failed container "expand-bluefs" in pod "rook-ceph-osd-1-7c99c8445f-74tdk" is waiting to start: PodInitializing for rook-ceph-cluster/rook-ceph-osd-1-7c99c8445f-74tdk (expand-bluefs)
stream logs failed container "chown-container-data-dir" in pod "rook-ceph-osd-1-7c99c8445f-74tdk" is waiting to start: PodInitializing for rook-ceph-cluster/rook-ceph-osd-1-7c99c8445f-74tdk (chown-container-data-dir)
activate 
activate config = configparser.ConfigParser()
activate config.read('\''/etc/ceph/ceph.conf'\'')
activate 
activate if not config.has_section('\''global'\''):
activate     config['\''global'\''] = {}
activate 
activate if not config.has_option('\''global'\'','\''fsid'\''):
activate     config['\''global'\'']['\''fsid'\''] = '\''e03644bf-cea9-4117-a812-6d193a2b9a99'\''
activate 
activate with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
activate     config.write(configfile)
activate '
activate + ceph -n client.admin auth get-or-create osd.1 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
activate [osd.1]
activate     key = AQDjfYdm49RANBAAHIgyljiGqB/xhrwYz/Sdzg==
activate + [[ raw == \l\v\m ]]
activate ++ mktemp
activate + OSD_LIST=/tmp/tmp.joMfhApBMR
activate + ceph-volume raw list /dev/sdb
activate  stderr: lsblk: /dev/sdb: not a block device
activate Traceback (most recent call last):
activate   File "/usr/sbin/ceph-volume", line 11, in <module>
activate     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
activate     self.main(self.argv)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
activate     return f(*a, **kw)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
activate     terminal.dispatch(self.mapper, subcommand_args)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
activate     instance.main()
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
activate     terminal.dispatch(self.mapper, self.argv)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
activate     instance.main()
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 174, in main
activate     self.list(args)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
activate     return func(*a, **kw)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 130, in list
activate     report = self.generate(args.device)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 99, in generate
activate     info_devices.append(disk.lsblk(dev, abspath=True))
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 245, in lsblk
activate     abspath=abspath)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 337, in lsblk_all
activate     raise RuntimeError(f"Error: {err}")
activate RuntimeError: Error: ['lsblk: /dev/sdb: not a block device']
activate + echo ''
activate + cat /tmp/tmp.joMfhApBMR
activate 
activate + find_device
activate + python3 -c '
activate import sys, json
activate for _, info in json.load(sys.stdin).items():
activate     if info['\''osd_id'\''] == 1:
activate         print(info['\''device'\''], end='\'''\'')
activate         print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
activate         sys.exit(0)  # don'\''t keep processing once the disk is found
activate sys.exit('\''no disk found with OSD ID 1'\'')
activate '
activate Traceback (most recent call last):
activate   File "<string>", line 3, in <module>
activate   File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
activate     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
activate   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
activate     return _default_decoder.decode(s)
activate   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
activate     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
activate   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
activate     raise JSONDecodeError("Expecting value", s, err.value) from None
activate json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
activate + ceph-volume raw list
activate + cat /tmp/tmp.joMfhApBMR
activate {}
activate ++ find_device
activate ++ python3 -c '
activate import sys, json
activate for _, info in json.load(sys.stdin).items():
activate     if info['\''osd_id'\''] == 1:
activate         print(info['\''device'\''], end='\'''\'')
activate         print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
activate         sys.exit(0)  # don'\''t keep processing once the disk is found
activate sys.exit('\''no disk found with OSD ID 1'\'')
activate '
activate no disk found with OSD ID 1
activate + DEVICE=
Stream closed EOF for rook-ceph-cluster/rook-ceph-osd-1-7c99c8445f-74tdk (activate)
```

</p>
</details> 

This is on GKE and we still have

```yaml
cephClusterSpec:
...
        storage:
          useAllNodes: true
          useAllDevices: false
          deviceFilter: "^/dev/disk/by-id/google-pvc-.*"
```

in the cluster configuration.

**Comment by travisn** [comment]
@cameronraysmith I moved your comment to #14436, if we could follow up there for the fix, thanks for reporting.
