### ISSUE TITLE
Abnormal alarm when creating PVC

### ISSUE THREAD

**Issue by ywd1988** [rook/rook#13574]
Abnormal alarm when creating PVC
![image](https://github.com/rook/rook/assets/92080991/7a74a561-da13-46a7-a707-448c66efdc0e)
![image](https://github.com/rook/rook/assets/92080991/aeebd306-72ac-4b67-a820-4f83422bea58)

**Comment by zhucan** [comment]
https://github.com/ceph/ceph-csi/blob/200fbdbf28591c404a85888d8bfc9561fa23dbb8/internal/rbd/driver/driver.go#L107 @ywd1988 Because of the driver not support ControllerServiceCapability_RPC_PUBLISH_UNPUBLISH_VOLUME, so it will print the info, https://github.com/kubernetes-csi/external-provisioner/blob/b377ea40edb757a7c3d8abb7058f701844ebf867/cmd/csi-provisioner/csi-provisioner.go#L298

**Comment by ywd1988** [comment]
> https://github.com/ceph/ceph-csi/blob/200fbdbf28591c404a85888d8bfc9561fa23dbb8/internal/rbd/driver/driver.go#L107 @ywd1988由于驱动程序不支持ControllerServiceCapability_RPC_PUBLISH_UNPUBLISH_VOLUME，因此它将打印信息，https://github.com/kubernetes-csi/external-provisioner/blob/b377ea40edb757a7c3d8abb7058f701844ebf867/cmd/csi-provisioner/csi-provisioner.go#L298

Is there any solution?

**Comment by zhucan** [comment]
it's a normal informations, no any bad effects, what do you want to do?

**Comment by ywd1988** [comment]
> 这是正常信息，没有任何不良影响，您想做什么？

![image](https://github.com/rook/rook/assets/92080991/883e53dc-e755-4cb8-bef8-880a05e99c29)
Is the slow creation of PVC related to this?

**Comment by zhucan** [comment]
![image](https://github.com/rook/rook/assets/13997135/bd2f4642-98a9-456d-b80c-f2843c31de57)
before create pvc, I think the external-provisioner not ready, because of  leader election.

**Comment by Madhu-1** [comment]
These are just the logs that don't seem to be abnormal. leader election timeouts can be configured once https://github.com/rook/rook/pull/13573 is merged, Closing this one as nothing suspicious, feel free to reopen if you think so
