### ISSUE TITLE
Duplicates series on Prom alert Rules CephOSDFlapping and CephPGImbalance while monitoring several clusters

### ISSUE THREAD

**Issue by kennux75** [rook/rook#13575]
Hello, 

Not sure if it's a bug in a prom ql rule or a config issue in my system regarding labels, but here is my situation:

- I've got a k8s cluster, with a rook-ceph cluster in a namespace rook-ceph, monitored with a service monitor, by prometheus in another namespace "prometheus". So in prometheus, I normally have all my "rook-ceph" metrics.
- In the prometheus configuration, I've a scraping job pointing to a manager of an external ceph cluster (on prem, not in k8s) named external-cluster.

So I have some series of ceph metrics with labels from kubernetes (1st cluster rook-ceph) and ceph metrics with different number of labels from the external-cluster.

**Bug Report**
With the last localrules.yaml file, I've got 2 prom alert rules with the error:
"found duplicate series for the match group {ceph_daemon="osd.0"} on the right hand-side of the operation: "

The impacted rules are
CephOSDFlapping
CephPGImbalance

Because I think I have different numbers of labels between the two series from both clusters. 

I can solve the error by changing the promql query and adding the job label in the on operator:
(rate(ceph_osd_up[5m]) * on (ceph_daemon, job) group_left (hostname) ceph_osd_metadata ) * 60  > 1

Same modification in the on (ceph_daemon, job) operator in the CephPGImbalance rule will correct the error.

It reminds me this issue: https://github.com/rook/rook/issues/13274 
Is there a way to make those rules run correctly without changing the localrules.yaml? adding or ignoring labels in scraping job config? 
Or is it possible to add this label in localrules.yaml to include to possibility of monitoring several clusters? 

Thank you very much

**Comment by arichard42** [comment]
On my part I have solve this issue by adding the following to my helm cluster-values.yaml 👍 

cephClusterSpec:
...
  annotations:
    all:
      prometheus.io/scrape: "false"
...

This will force all pods to not be scraped by prometheus directly as the mgr prometheus module is active.

I have also tried to add this annotation on mgr module only but if found out that there was still duplicates between osd pods and the mgr prometheus module. Also adding this annotation for the osd module seems to be ignored. This is why I end up using "all".

Alain

**Comment by kennux75** [comment]
Hello Alain,

Thanks for your reply. You mean your prometheus does not scrape anymore your local ceph cluster in k8s? and you added a specific scrape job to monitor your local ceph cluster in k8s? 
Or you monitor only external clusters?

**Comment by travisn** [comment]
@11qu1d Have you tried the suggestions in previous comments? It will help to fix this if we're clear what the generalized solution is for localrules.yaml. Can you share what fix works for you?

**Comment by jmolmo** [comment]
@kennux75 , @arichard42 ,  @11qu1d , @travisn : 
For the moment Rook does not have support for monitor multiple clusters. Although Probably it will be a good new feature for Rook, something to discuss in the Rook Community.

The monitoring multicluster support is a feature being implemented in this moment for baremetal Ceph clusters (installed using cephadm). 
Basically the idea is to use [Prometheus servers federation](https://prometheus.io/docs/prometheus/latest/federation/) in order to have one prometheus getting the metrics from other clusters (each cluster need to have their own monitoring stack up and running).
**To avoid problems with "duplicate series"** the solution is to introduce the cluster fsid in the alert rule. This is done because the _label cluster_ is introduced in the Prometheus configuration, and this label is used in the alert expression, for example, the  _CephOSDFlapping_ alert expression for multicluster is rendered for the cluster "6a765cea-ca9a-11ee-8d6a-5254009cc347" as:

> [(rate(ceph_osd_up[5m]) * on( "6a765cea-ca9a-11ee-8d6a-5254009cc347", ceph_daemon) group_left(hostname) ceph_osd_metadata) * 60 > 1](https://github.com/ceph/ceph/blob/adf4aca563c21106de1248a73fbef5a2bde5d7ab/monitoring/ceph-mixin/prometheus_alerts.libsonnet#L255)

As you can see, the concept to avoid the duplicate series error, is basically what @kennux75  used as solution for his multicluster monitoring problem (he used the job to differentiate series). 
I think we cannot manage this as a simple issue/bug. It is really a new feature which will need some reflection, study and a proper desing for the k8s envs and the Rook operator.

_Note about Multicluster support in rook:_

If it is decided to add monitoring multicluster support to the rook orchestrator it will be needed to implement a way to change automatically the Prometheus configuration, the alert rules file,  and also warn the users consuming the metrics about this new possibility ( for example, Grafana dashboards can be impacted and/or improved)
Another possibility is to provide documentation in order to explain the changes needed.


_Ceph PRs related with the multicluster monitoring solution:_
[monitoring Multicluster support ](https://github.com/ceph/ceph/pull/55495/)
[monitoring multicluster support for alerts](https://github.com/ceph/ceph/pull/56849/)
[prometheus federation config for multicluster monitoring ](https://github.com/ceph/ceph/pull/54964)

**Comment by travisn** [comment]
Perhaps the namespace label could be added to the rules as defined in the [helm chart](https://github.com/rook/rook/tree/master/deploy/charts/rook-ceph-cluster/prometheus). If multiple Rook clusters are installed, the helm chart would replace the namespace seemlessly. 

There has been much discussion in the past about whether the Rook operator should reconcile the rules, but we ended up at the current solution which has the rules separately from Rook, either installed with the helm chart or the localrules.yaml directly. For more details see #9837.
