### ISSUE TITLE
Ceph version detect job and rook-discover should respect HostNetwork setting

### ISSUE THREAD

**Issue by NewbieOrange** [rook/rook#13571]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently the ceph and csi version detection jobs do not respect cluster's hostNetwork setting. This feature should make both detection jobs respect the hostNetwork setting (e.g. set `hostNetwork` to `true` in spec).

**What is use case behind this feature:**
In prod we have some kubernetes cluster without cluster IP provider (no virtual IP is available, only hostNetwork can be used for pods). Rook currently still creates the detection jobs without hostNetwork even if the cluster is hostNetwork, thus the job pods failed to create on nodes and the cluster creation cannot proceed.

**Comment by NewbieOrange** [comment]
Also rook-discover daemonset is not using hostNetwork. edited the title

**Comment by Madhu-1** [comment]
@NewbieOrange @travisn This means all the pods should use the host networking. example csi provisioner (rbd/nfs/cephfs) should also use hostnetworking which is not the case today.

**Comment by BlaineEXE** [comment]
We could also use a different named network mode like `network.mode: "host-strict"`. It seems to me like the `network.requireHostNetwork` setting might have strange behavior alongside other network modes that aren't `mode: "network"`.

**Comment by NewbieOrange** [comment]
> @NewbieOrange @travisn This means all the pods should use the host networking. example csi provisioner (rbd/nfs/cephfs) should also use hostnetworking which is not the case today.

Indeed. Also the rbd and cephfs plugin daemonsets, which I currently have to manually edit their specs to hostNetwork.

**Comment by Madhu-1** [comment]
> > @NewbieOrange @travisn This means all the pods should use the host networking. example csi provisioner (rbd/nfs/cephfs) should also use hostnetworking which is not the case today.
> 
> Indeed. Also the rbd and cephfs plugin daemonsets, which I currently have to manually edit their specs to hostNetwork.

csi daemonset pods run with the host networking by default.

**Comment by obnoxxx** [comment]
A quick look through the code (with `git grep -i ishost\(`)  seems to tell me that the CephCluster's HostNetwork setting is already correctly propagated to most of the ceph component pods, specifically rbd, mgr, mon, osd, and mds. So I guess it is really mostly about the jobs mentioned in the title of the issue.

@travisn , @BlaineEXE , @Madhu-1 , @NewbieOrange  - agree so far?

I'll have to do more digging.


I'm also wondering if this shouldn't be categorized as bug rather than feature request given that it describes a certain behavior that is not as expected and should be fixed

**Comment by BlaineEXE** [comment]
> I'm also wondering if this shouldn't be categorized as bug rather than feature request given that it describes a certain behavior that is not as expected and should be fixed

I think this is a good question to ask. I also think that it's an inconsequential place to be getting stuck for this issue in particular. I think it makes sense that this user would likely consider it a bug. However, other users might consider it a bug to put **everything** on the host network without concern. K8s' software defined network provides security by isolating pods from the host network. The fewer pods use host networking, the smaller the attack surface. I consider it a useful feature of Rook that it only puts **necessary** pods on the host network to keep the attack surface as small as possible.

Admittedly, we are talking about a 2-3 pods per node compared to nodes which may be running 6-12 other pods on average. But that is still 50% to 25% of the attack surface reduced, which is commendable.

I proposed in [this comment](https://github.com/rook/rook/issues/13571#issuecomment-1904275063) to create a new network mode `network.provider: "host-strict"`, and both Travis and OP have given it a thumbs-up. I take that to mean that Travis and I are both in agreement and that OP thinks it will accomplish their needs as well.

We are planning to resolve this with new development, rather than adjusting existing behavior. Therefore, I think `feature` is the slightly better descriptor because it clarifies what we are developing in response.

**Comment by BlaineEXE** [comment]
> A quick look through the code (with `git grep -i ishost\(`) seems to tell me that the CephCluster's HostNetwork setting is already correctly propagated to most of the ceph component pods, specifically rbd, mgr, mon, osd, and mds. So I guess it is really mostly about the jobs mentioned in the title of the issue.

I think there are other components as well:
- we should check CSI pods
- we should check the discover daemon pod

We should also look through the code to find all of the ancillary daemons as well to make sure they follow. RGW, cephfs and rbd mirror daemons, and COSI driver.

The cmd-reporter jobs are short-lived, so you may not be seeing them in your manual testing.

We should consider how to e2e test this as well. I think it makes sense to figure out how to develop a test that will fail if any pods in the rook-ceph namespace have `hostNetwork: false`.
If it's possible to create a minikube node that doesn't have a CNI, that would be the easiest. That should mean that any pods without host networking will fail. TBH, I'm not sure that is possible.

The next option I can think of is to create a special Validating Admission Policy that rejects any pods that use `hostNetwork: false`. https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/. This option and the one above would make the CephCluster deployment fail.

We can also see if it's possible to machine parse the output of `kubectl watch -o json pods`. If so, we can look at the pod list from a deployment and then inspect all the items. In this scenario, the CephCluster might still deploy correctly, but we can verify if any pods deployed using `hostNetwork: false`.

There may be other ways as well.

I was thinking that it might not make sense to run this test with every PR since it is such an uncommon use-case. But it probably is useful to develop an e2e test nonetheless. Maybe it would make sense to run this in nightly tests. We could also test this manually and say that the operating mode is supported on a best-effort basis. Once the new `host-strict` provider is implemented, it will be a lot easier for any users experiencing problems to make quick bug fixes to any gaps we missed. @travisn thoughts on e2e testing?

**Comment by BlaineEXE** [comment]
FYI: I found another place in the code where we need to change the host mode: https://github.com/rook/rook/blob/69ae9569cd5ced302c960edc638ff71bf09b0cf0/pkg/operator/ceph/cluster/cleanup.go#L72
