### ISSUE TITLE
Add Minimum and Maximum kubernetes version for the releases.

### ISSUE THREAD

**Issue by smyja** [rook/rook#13632]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Update the documentation with a table showing rook releases and their kubernetes version support. The older documentations just state the minimum version with no maximum version.
**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
This is a common question, sounds good to clarify in the docs. 
Currently in quickstart.md and prerequisites.md we have this:
```
## Minimum Version

Kubernetes **v1.22** or higher is supported.
```
I'm thinking this format:
```
## Kubernetes Version

Kubernetes versions v1.22 through v1.29 are supported.
```
Instead of trying to create a table of all K8s versions fo previous Rook versions, the [K8s versions](https://rook.io/docs/rook/latest/Getting-Started/release-cycle/#k8s-versions) indicates approximately 6 K8s versions are supported from the min version. 

The K8s versions tested in previous versions may also be reconstructed from the history of [.mergify.yml](https://github.com/rook/rook/blob/master/.mergify.yml). For example, in the release-1.8 branch, we see that the min and max version of K8s tested were v1.16 and v1.22:
```
      - "check-success=TestCephSmokeSuite (v1.16.15)"
      - "check-success=TestCephSmokeSuite (v1.22.2)"
```

**Comment by smyja** [comment]
> This is a common question, sounds good to clarify in the docs.
> 
> Currently in `quickstart.md` and `prerequisites.md` we have this:
> 
> ```
> ## Minimum Version
> 
> Kubernetes **v1.22** or higher is supported.
> ```
> 
> I'm thinking this format:
> 
> ```
> ## Kubernetes Version
> 
> Kubernetes versions v1.22 through v1.29 are supported.
> ```
> 
> Instead of trying to create a table of all K8s versions fo previous Rook versions, the [K8s versions](https://rook.io/docs/rook/latest/Getting-Started/release-cycle/#k8s-versions) indicates approximately 6 K8s versions are supported from the min version.
> 
> The K8s versions tested in previous versions may also be reconstructed from the history of [.mergify.yml](https://github.com/rook/rook/blob/master/.mergify.yml). For example, in the release-1.8 branch, we see that the min and max version of K8s tested were v1.16 and v1.22:
> 
> ```
>       - "check-success=TestCephSmokeSuite (v1.16.15)"
>       - "check-success=TestCephSmokeSuite (v1.22.2)"
> ```

That would be great.

**Comment by parth-gr** [comment]
@travisn `Rook expects to support the most recent six versions of Kubernetes.` 
It looks me 7 for the above cases, for 
rook 1.13 =>  1.23-1.29 = 7 
rook 1.12 => 1.22 -1.28 =7

**Comment by travisn** [comment]
@parth-gr Frequently it is rounded up to the 7th release if a K8s release comes out around the time of the Rook release.

**Comment by parth-gr** [comment]
Okay

**Comment by travisn** [comment]
The docs for 1.12 and 1.13 have been updated. Going forward we will also document this in future releases. For support versions in previous releases, please see the versions tested as defined in the [.mergify config](https://github.com/rook/rook/blob/master/.mergify.yml).
