### ISSUE TITLE
Default user get unlinked after linking new user to the S3 bucket using radosgw-admin

### ISSUE THREAD

**Issue by Kuanting888** [rook/rook#13686]
Hi, 

I have created an ObjectBucketClaim called 'rook-ceph-retain-bucket-1' in Kubernetes, and the S3 bucket is created with default user called 'obc-default-rook-ceph-retain-bucket-1'. 
Now I use radosgw-admin to create a user called 'userA'. However, when I try to use 'radosgw-admin bucket link' to link the bucket to userA, I realize although userA now has the access to the bucket, the default user can no longer access to it. 

Is this expected behaviour? If so, is there any way to have multiple users to access to one S3 bucket?

My ultimate goal is to have a S3 bucket with the following directory
--> /mystuff1
--> /mystuff2
--> /others
       --> /others/userA
       --> /others/userB
and default user can access everything, whereas userA can only access /others/userA and userB can only access /others/userB
Is this doable?

Thank you.

**Comment by fayak** [comment]
Can we re-open this ?

**Comment by travisn** [comment]
@BlaineEXE thoughts?

**Comment by BlaineEXE** [comment]
Today, if you want to do more complex user:bucket relationships than the 1:1 relationship set up by OBCs, you will have to manually create the buckets and users. 

OBCs were never intended to support complex use-cases like this. 

Even COSI, which will have 1:many/many:1 relationships likely won't support the use case described by OP due to how complex it is.

In the OBC and COSI realm, this must be implemented by multiple buckets. One bucket for multi-user access, and separate buckets for single-user access. This is the same expectation as how PVCs would be used today.
