### ISSUE TITLE
reclaimSpace job not working

### ISSUE THREAD

**Issue by akash123-eng** [rook/rook#14094]
Hi ,

We are trying to use ReclaimSpace job with rook 1.12 and ceph 17.2.5.
Followed steps given below :
(https://rook.io/docs/rook/v1.12/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/#csi-addons-controller)]
now rbdplugin and provisioner pod has csi-addon sidecar and csi addon pod in csi-addons-system namespace running fine.
But when we create a ReclaimSpace job for rbd volume with Read Write Once mode it failes and shows message  in reclaimSpaceJob
"Failed to make node request node client not found for nodeID"

there are no errors in provisioner pod and plugin pod where pvc is attached.
In csi-addon-controller pod there are logs "PANIC no leader found for driver rook-ceph.rbd.csi.ceph.com" Lease.coordination.k8s.io "rook-ceph-rbd-csi-ceph-com-csi-addons"

Please help to fix this

**Comment by Rakshith-R** [comment]
Hey @akash123-eng 

Can you confirm that csi addons side car image and csi addons Controller image versions are the same ?

Can you paste the logs from both csi addons Controller and Sidecar

**Comment by akash123-eng** [comment]
@Rakshith-R for csi sidecar image being used is k8s sidecar:v0.7.0 and in controller I don't see sidecar image but controller image is latest 
I.e csiaddon/k8s-contoller:latest and kube-rbac-proxy image is v0.8.0 as given in the manifests

**Comment by Rakshith-R** [comment]
Please use the same versions in both Sidecar and Controller.
Preferably use Controller version corresponding to the default csi addons Sidecar provided by that rook version

**Comment by akash123-eng** [comment]
So controller image is same as k8s sidecar ?
So in our case k8s sidecar image is 0.7.0 So can you please give exact docker image for controller ?

**Comment by Rakshith-R** [comment]
> So controller image is same as k8s sidecar ? So in our case k8s sidecar image is 0.7.0 So can you please give exact docker image for controller ?

Whatever side car default version is used in rook version. You can use the version 0.x.y for controller. 
If sidecar is 0.7.0, then controller should be 0.7.0

**Comment by szczepl** [comment]
I have synced both to 0.5.0, but the error is still there:


```
    Message:               Failed to make node request: node Client not found
    Observed Generation:   1
    Reason:                failed
    Status:                True
    Type:                  Failed
  Message:                 Maximum retry limit reached
  Result:                  Failed
```

What I'm missing here?

**Comment by szczepl** [comment]
This is solved - I can have both operator and sidecar now synced. But this is not working due to:

`[root@ams-rlwy04-snd01 ~]# oc logs csi-rbdplugin-cp825 -n rook-ceph -c csi-addons
I0113 11:36:11.083980 2993464 client.go:79] Probing CSI driver for readiness
E0113 11:36:11.095576 2993464 csiaddonsnode.go:92] failed to create CSIAddonsNode rook-ceph/csi-rbdplugin-cp825: failed to create csiaddonsnode object: csiaddonsnodes.csiaddons.openshift.io "csi-rbdplugin-cp825" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-plugin-sa" cannot create resource "csiaddonsnodes" in API group "csiaddons.openshift.io" in the namespace "rook-ceph"
E0113 11:41:11.102608 2993464 csiaddonsnode.go:92] failed to create CSIAddonsNode rook-ceph/csi-rbdplugin-cp825: failed to create csiaddonsnode object: csiaddonsnodes.csiaddons.openshift.io "csi-rbdplugin-cp825" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-plugin-sa" cannot create resource "csiaddonsnodes" in API group "csiaddons.openshift.io" in the namespace "rook-ceph"
E0113 11:46:11.134080 2993464 csiaddonsnode.go:92] failed to create CSIAddonsNode rook-ceph/csi-rbdplugin-cp825: failed to create csiaddonsnode object: csiaddonsnodes.csiaddons.openshift.io "csi-rbdplugin-cp825" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-plugin-sa" cannot create resource "csiaddonsnodes" in API group "csiaddons.openshift.io" in the namespace "rook-ceph"
`

So I think what is wrong here. I have applied all rbac and crds...

**Comment by Madhu-1** [comment]
Please apply the RBAC from latest releases branch of Rook

**Comment by szczepl** [comment]
The solution was:

`[root@ams-rlwy04-snd01 ~]# cat csiaddon-serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-csiaddonsnode-custom-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonsnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-csiaddonsnode-custom-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-csiaddonsnode-custom-role
subjects:
- kind: ServiceAccount
  name: rook-csi-rbd-plugin-sa
  namespace: rook-ceph
`

After that, all has started:

`[root@ams-rlwy04-snd01 ~]# oc get CSIAddonsNode -n rook-ceph
NAME                  NAMESPACE   AGE   DRIVERNAME                   ENDPOINT                                   NODEID
csi-rbdplugin-62phx   rook-ceph   93s   rook-ceph.rbd.csi.ceph.com   pod://csi-rbdplugin-62phx.rook-ceph:9070   ams-xxxx-ops03.xxxx.okd
csi-rbdplugin-d682v   rook-ceph   94s   rook-ceph.rbd.csi.ceph.com   pod://csi-rbdplugin-d682v.rook-ceph:9070   ams-xxxx-ops02.xxxx.okd
csi-rbdplugin-kc8dl   rook-ceph   95s   rook-ceph.rbd.csi.ceph.com   pod://csi-rbdplugin-kc8dl.rook-ceph:9070   ams-xxxx-ops04.xxxx.okd
csi-rbdplugin-kqxwz   rook-ceph   94s   rook-ceph.rbd.csi.ceph.com   pod://csi-rbdplugin-kqxwz.rook-ceph:9070   ams-xxxx-ops01.xxxx.okd
`

**Comment by Madhu-1** [comment]
> BTW, All is working now, but it seems to stick to `"@midnight"` even if I annotate storage class or namespace, to any other schedule (of course minimum scheduling is 24h or more). So I annotated some namespace to "0 4 * * *" but when I list reclaimspacecronjobs, it shows again `"@midnight"`. 


its supposed to get updated when you update it on the SC, can you please open an issue at https://github.com/csi-addons/kubernetes-csi-addons 


> And the only way to have custom schedule is to set annotate particular reclaimspacecronjob with: csiaddons.openshift.io/state=unmanaged - and modify the schedule by patching?

Yes that's correct. if you want to have a custom schedule per reclaimspacecronjob, its the way to go https://github.com/csi-addons/kubernetes-csi-addons/blob/main/docs/reclaimspace.md#annotating-reclaimspacecronjob
