### ISSUE TITLE
1 slow ops, oldest one blocked for 1880444 sec, mon.e has slow ops

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#14126]
Hi Team,
we have installed rook-ceph in kubernetes cluster, and we are using hostbased deployment of rook-ceph, we have 3 workernodes attached the to the disk and recently we have issue on one of the workernode, we have restared the workernode.

after workernode has restared we can see the status below in rook-ceph, how can we resolve this issue

cluster:
    id:     cc9da5b7-2e86-4abc-971a-701ce9b3d532
    health: HEALTH_WARN
            1 slow ops, oldest one blocked for 1880444 sec, mon.e has slow ops
 
  services:
    mon: 3 daemons, quorum c,e,f (age 3w)
    mgr: a(active, since 3w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 3w), 3 in (since 3w)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 3.05k objects, 516 MiB
    usage:   3.2 GiB used, 1.8 TiB / 1.8 TiB avail
    pgs:     65 active+clean
 
  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu
* Kernel (e.g. `uname -a`): Linux master1 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: its on premises 
* Rook version (use `rook version` inside of a Rook Pod): v8.1.1
* Storage backend version (e.g. for ceph do `ceph -v`): v16.2.10
* Kubernetes version (use `kubectl version`):v1.21.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): on premises cluster
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
cluster:
    id:     cc9da5b7-2e86-4abc-971a-701ce9b3d532
    health: HEALTH_WARN
            1 slow ops, oldest one blocked for 1880444 sec, mon.e has slow ops
 
  services:
    mon: 3 daemons, quorum c,e,f (age 3w)
    mgr: a(active, since 3w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 3w), 3 in (since 3w)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 3.05k objects, 516 MiB
    usage:   3.2 GiB used, 1.8 TiB / 1.8 TiB avail
    pgs:     65 active+clean
 
  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr

**Comment by vadlakiran** [comment]
please find the attached logs

**Comment by vadlakiran** [comment]
[Uploading mon-e.log…]()

**Comment by vadlakiran** [comment]
attached the operator logs and mon-e logs please let me know how to resolve, its production issue,
we have bloked, due to this we are not able to take backup of it, 
we have mounted pvc to this rook-ceph we are not able to go inside pvc from pod, getting permision denied due to this we are not able to take backup

please this high priority issue

**Comment by travisn** [comment]
Are you saying this issue is preventing you from taking backups?
```
1 slow ops, oldest one blocked for 1880444 sec, mon.e has slow ops
```

It is just a health warning, so it is surprising if it is blocking the IO. If it is just mon.e with the problem, you could try scaling down that mon and [fail it over](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor) to see if a new mon will help.

**Comment by vadlakiran** [comment]
@travisn yes due to this we are not able to take backup because we are using the persistant volumes to take backup, is there any way we can modify the permisions to access the PVC ?

**Comment by vadlakiran** [comment]
@travisn every 45 sec operator will monitor the mon's right it should be resolve by operator, why its not doing it,
is there any thing i have to enable to self heal with operator ?

**Comment by travisn** [comment]
You can try the [direct mount tools](https://rook.io/docs/rook/latest/Troubleshooting/direct-tools/)

**Comment by travisn** [comment]
> @travisn every 45 sec operator will monitor the mon's right it should be resolve by operator, why its not doing it, is there any thing i have to enable to self heal with operator ?

Are you referring to the [mon failover](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor)? As long as mons are up, this is a different issue.

**Comment by vadlakiran** [comment]
@travisn  yes, if mon fails automatically operator pod resolve the issue it should comeup right ?

regards mount issue: if i want to try with directmount tools , how i can confirm that specific workernode, we have issue with sepcific workernode, we are using sharedfilesys as type

**Comment by travisn** [comment]
> @travisn yes, if mon fails automatically operator pod resolve the issue it should comeup right ?

Yes, a mon will failover by default after 10 min if it is out of quorum. The doc linked previously explains more.

> regards mount issue: if i want to try with directmount tools , how i can confirm that specific workernode, we have issue with sepcific workernode, we are using sharedfilesys as type

If you want to mount it from a specific worker node, you could create the direct tools pod with a node selector.

**Comment by vadlakiran** [comment]
@travisn rbdplugin-provisioner is mounting emptyDir, what it write in the emptyDir ?

**Comment by travisn** [comment]
Can you provide the following?
- What is the latest output of `ceph status`? to show if ceph is healthy
- Have you checked the [CSI troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/)?
- The CSI provisioner is only used for new volumes. If you are having problems with existing volumes, it is not related to the provisioner.
- What exactly is the issue? IO from cephfs or rbd volumes is not working? Please summarize the issue, and perhaps @Rakshith-R can take a look if related to CSI.

**Comment by occ** [comment]
I'm hitting a similar issue on a freshly setup cluster. Please LMK if I should open a new bug instead.

Hardware:
2x10Gbps bonded network connections
3x4TB NVMes per node (first NVMe has a 200GB root partition, rest is dedicated to ceph. Remaining two NVMes are fully dedicated to OSDs)
96 GB RAM per node
11 nodes

Servers are running NixOS 23.11 (`Linux oecs3 6.1.91 #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 09:56:25 UTC 2024 x86_64 GNU/Linux`)

Our rook configuration doesn't have anything complicated. 3 OSDs/node and 3 mon daemons for the cluster, constrained to run on the first 3 servers.

Symptoms I see:
* mons failing healthchecks (mostly because of ceph commands timing out)
* mons eventually get replaced (at the moment we're running mon.{d,e,f} because a,b, and c were destroyed.
* slow mons seem to use 100% of a single core. All mons get into this state eventually (and get replaced).
* very often I see "slow_ops" messages in the logs, coming from the mons.
* cluster is constantly in an unhealthy state - never recovering.

I just tried debugging by attaching strace to the mon process using 100% CPU on a single core. strace log is filled with close() calls (millions of them within a minute or so), with no open or other calls. Sample below:

```
close(640694286)                        = -1 EBADF (Bad file descriptor)
close(640694287)                        = -1 EBADF (Bad file descriptor)
close(640694288)                        = -1 EBADF (Bad file descriptor)
close(640694289)                        = -1 EBADF (Bad file descriptor)
close(640694290)                        = -1 EBADF (Bad file descriptor)
close(640694291)                        = -1 EBADF (Bad file descriptor)
close(640694292)                        = -1 EBADF (Bad file descriptor)
close(640694293)                        = -1 EBADF (Bad file descriptor)
close(640694294)                        = -1 EBADF (Bad file descriptor)
close(640694295)                        = -1 EBADF (Bad file descriptor)
close(640694296)                        = -1 EBADF (Bad file descriptor)
```

Note that this is a fresh cluster with no workload.

Hope this helps

**Comment by occ** [comment]
I noticed similar issues reported. As pointed out in this [comment](https://github.com/coreos/fedora-coreos-tracker/issues/329#issuecomment-623009008) the issue seems to stem from `LimitNOFILE=infinity`.

More specifically, for our setup, NixOS 23.11 (or -unstable) hasn't gotten the patch from upstream containerd (see: https://github.com/NixOS/nixpkgs/blob/a8695cbd09a7ecf3376bd62c798b9864d20f86ee/nixos/modules/virtualisation/containerd.nix#L87).

For people using NixOS, this seems to work:

```
  virtualisation.containerd.enable = true;
  systemd.services.containerd.serviceConfig = {
    LimitNOFILE = lib.mkForce null;
  };
```
