### ISSUE TITLE
Support options to always use LVM mode even if the disk is allow for raw mode

### ISSUE THREAD

**Issue by chenyuanrun** [rook/rook#14151]
In allowRawMode@pkg/daemon/ceph/osd/volume.go , rook prefer raw mode for disk if it is allowed. In some case we want always use lvm mode to prepare osd (as the name of disk may chang across reboot),  can we add a option (something like preferLvm) and use lvm mode if this option is provided?

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
If the disk is labeled, the raw mode is expected to be stable for OSDs even if the disks are renamed on reboot. We wanted to avoid LVM mode because there were challenges with stability with the LVs and proper provisioning and shutdown. Given our negative experiences with LVM in the past, I would be concerned with enabling LVM mode unless it's absolutely necessary. @satoru-takeuchi Additional thoughts?

**Comment by satoru-takeuchi** [comment]
@travisn I also hesitate to add this feature. LVM mode sometimes has pitfalls in container environment.
