### ISSUE TITLE
MTU alerts don't resolve with changed MTU.

### ISSUE THREAD

**Issue by KellenRenshaw** [rook/rook#14415]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Getting ongoing alerts for CephNodeInconsistentMTU despite the MTUs being the same. Context is a cluster that had the MTU changed from 1500 to 9000. Cluster is healthy.

**Expected behavior:**
Alerts should resolve once all nodes have a consistent MTU.

**How to reproduce it (minimal and precise):**
Deploy a Rook Cluster with Prometheus monitoring enabled, using an MTU of 1500. Ensure that Prometheus/Alertmanager pick up the Rook/Ceph rules. Change the MTU on all cluster nodes to 9000. Alerts happen during the changeover, but don't resolve once all nodes are on the same MTU.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04
* Kernel (e.g. `uname -a`):  6.5.0-41-generic #41~22.04.2-Ubuntu
* Cloud provider or hardware configuration: Baremetal server.
* Rook version (use `rook version` inside of a Rook Pod): 1.14.6
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.2
* Kubernetes version (use `kubectl version`): 1.29.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by ronnyaa** [comment]
anyone have any idea how to resolve this manually ? 
or how to find out where it get's the median from ? 
all interfaces have this error after updating 18.2.2 to 18.2.4
i have 33 alerts of Node has a different MTU size (9000) than the median of devices named ens1f0np0.
I expected all interfaces to have 9000
where is the median picked up from ?    

the source give no useful information whatsoever since it is a link to http://127.0.1.1:9095/graph?g0.expr=node_network_mtu_bytes+%2A+LOONG link

**Comment by miroslavkohutik** [comment]
I had a similar issue today. I added a new worker node to my cluster that had a different interface name (`enp7s0` as opposed to `enp1s0` on the other worker nodes). The only other node with an `enp7s0` interface is the etcd node, which indeed uses a different MTU (1450 vs 9000 on the worker nodes).
The ceph alert rule calculates median MTU for all interfaces with the same name, so the median for `enp7s0` changed to 5225 and the alert started firing.
The interesting thing is that the alert fired for all 200+ interfaces, even the unique ones like calib3dcf44sad1, which can't have an inconsistent MTU, since the median has to be the same as the value on the unique interface.
I couldn't align the MTU values on the two `enp7s0` interfaces in my case, so I ended up renaming the interface on the new node to `enp1s0` and that resolved all the alerts.
