### ISSUE TITLE
Should fixed nodeName be avoided in favor of anti-affinity rules (re: Mon pod is stuck with a node-selector of a terminated node)

### ISSUE THREAD

**Issue by bdowling** [rook/rook#14531]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

As reported in #6663 I find that mon pods are stuck pending due to the nodeSelector when removing nodes.  I probably didn't wait 10 minutes, but if that is indeed suppose to fix itself in 10 minutes -- why wait 10 minutes?

**Expected behavior:**

deployments should be configured with anti-affinity rules instead of rigid nodeSelectors so they can come back more quickly.
The only case where this could be problematic is small clusters with < replicas of the daemons.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS 
* Kernel (e.g. `uname -a`): Ubuntu 22.04.3 LTS   5.17.0-051700-generic 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.13.4
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.1
* Kubernetes version (use `kubectl version`): v1.28.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): IKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
In environments where nodes are changing, it's recommended to use the [cluster-on-pvc clusters](https://rook.io/docs/rook/latest/CRDs/Cluster/pvc-cluster/) so that mons can be portable between nodes. With the default [host-based clusters](https://rook.io/docs/rook/latest/CRDs/Cluster/host-cluster/), the mon must be tied to the node since it has persistent metadata on the host path.
