### ISSUE TITLE
secure endpoint for RGW admin ops endpoint

### ISSUE THREAD

**Issue by ideepika** [rook/rook#14544]
We don't want to expose the /admin api on the public object-gateway endpoint, for this in native Ceph the workaround that is used is to dedicate admin endpoint to specific RGW instance that is internal only and disable admin ops endpoint on all the other RGW instances.

In Rook the problem arises when we try to disable the admin ops 
When we try to disable this using this condig option https://docs.ceph.com/en/latest/radosgw/config-ref/#confval-rgw_enable_apis
If we disable admin, the rook reconciliation will fail with cosi user not found

Since s3 API is using root "/" that means all, since a lot of Rook code uses admin ops API, we can't disable it and not have issues with various components at present. 

We can look into introducing an option to enforce all API calls to be done using radosgw-admin to overcome this issue and use Ceph's workaround or I am open to suggestions from the team.

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by ideepika** [comment]
@arttor @travisn @BlaineEXE

**Comment by BlaineEXE** [comment]
I think this is a good thing to bring up for security hardening. I've spent a lot of time the past couple months looking into RGW, admin ops, and TLS. This feels like a natural extension of that.

Because this feature is focused on security, I think it will be best if we focus on a TLS-first design.

It should be fairly straightforward to add a set of options to the CephObjectStore to allow users to enable and configure what I might call an "admin gateway". This gateway should be able to have placement, resource request/limits, labels, etc. applied to it. It will obviously need a Service to allow for consistent connections from Rook. 

Each RGW itself can only "advertise" a single certificate. Because of K8s's dynamic environment, and because the service endpoint will be unique, many users may want/need a separate cert for the admin RGW. For TLS-first, the CephObjectStore's admin gateway config should thus also include the 2 TLS related configmaps for cert and CA.

I reworked the internal methods that Rook uses to "get" the admin ops endpoint recently, so I think it will be a little easier to make the changes needed to redirect Rook's admin ops traffic when this feature is enabled. This aspect of the work will be similar to the new `advertiseEndpoint` in execution.

I'd like to briefly discuss external object stores as well. Rook's current assumption is that the externalEndpoint supports admin ops connections. We have the opportunity here to consider what the CephObjectStore API would look like for an external Ceph cluster with a separate admin ops endpoint. I think it would be best to have that work be done separately from this work, but I think it's worth exploring the surface of this topic to ensure compatibility with potential future work.

Tangentially: As for the "cosi user not found" issue, I have been reconsidering having the object store controller create that user automatically since it is somewhat troublesome like this. IMO, it might be best to have the COSI driver install option require users to create the CephObjectStoreUser for COSI as we did in the past to keep things simple and pluggable.

**Comment by BlaineEXE** [comment]
Yes. I think a design doc will be best. 

One of the things we should make sure to plan is how this interacts with (or doesn't interact with) #14646 for ops logging. If the ops log is used for admin ops API logging, we should make sure to include that log container.

I think this also should allow for resource request/limit changes. I suspect that an admin ops RGW can use fewer resources than a client one. I'd prefer to see this as part of the initial feature PR. The default assumption should be to reuse the `spec.gateway` resources.

I'd suggest leaving different placement settings (affinity/antiaffinity/etc.) for a follow-up design if you want to have different placement. The default assumption should be to reuse the `spec.gateway` placement settings. Different placement might affect hostNetwork=true users in ways they don't expect.

**Comment by arttor** [comment]
Fixed in #15064
