### ISSUE TITLE
CephObjectStore data pools should have bulk flag set by default

### ISSUE THREAD

**Issue by dvanders** [rook/rook#14770]
RGW data pools are expected to be large, so mark them as "bulk" so that the PG autoscaler will treat them accordingly (see https://docs.ceph.com/en/reef/rados/operations/placement-groups/) In short, it will precreate a full number of PGs, so that the cluster works with optimal performance from day 1.

CephFS volumes already do this by default for its data pools [1] the same logic should apply for Object. 

[1] https://github.com/ceph/ceph/blob/main/src/pybind/mgr/volumes/fs/operations/volume.py#L84-L86

**Comment by dvanders** [comment]
One clarification: actually if the RGW is left to create the pools itself, it does the right thing: https://github.com/ceph/ceph/pull/51497

So another solution here for Rook to stop creating RGW pools -- let RGW create what it needs and expect it to do the right thing.

**Comment by BlaineEXE** [comment]
This seems like good advice we should incorporate. To make sure we're capturing all components of this, I have some follow-up questions: 
- is "bulk" appropriate only for `data` pools and not for `data-non-ec` pools? 
- is the "bulk" recommendation good/valid always or only for very large S3 stores?
- are there any other nuances to the "bulk" recommendation that I should be asking about?

**Comment by dvanders** [comment]
Copied from #14769 14769

Check the pools created here: https://github.com/ceph/ceph/pull/51497 and flags.

default.rgw.buckets.data: bulk
default.rgw.buckets.index: pg_autoscale_bias 4
default.rgw.buckets.meta: pg_autoscale_bias 4

other rgw pools don't need special flags.

IMHO bulk is correct for data always.

One thing to be aware of when moving to these defaults is their impact on multi-instances of CephObjectStore.

If a single Ceph cluster will server multiple RGW instances, then it will need to divide the "100 PGs per OSD" across all those instances. But this will have some interesting effects at bootstrapping time:

1. deploy instance A
   -- all pools created, PG autoscaler sees the bulk flag on A.data, gives it a large number of PGs.
2. deploy instance B
    -- pools for B are created, PG autoscaler now sees the 2nd pool with a bulk flag, and starts scaling down the number of PGs for A.data to account for that.

Decreasing pg_num on a cluster is supported, no operational issue there. But some operators might be suprised to see the PG nums changing.

**Comment by BlaineEXE** [comment]
This seems like a low effort fix and good to have. I'd like to set this as a must-have for 1.16 release to push for it to get completed. This could be pushed back to the backlog if necessary though

**Comment by BlaineEXE** [comment]
Anthony and Kyle are of the opinion that the autoscaler's recommendations are far too conservative for production clusters, especially since Bluestore is much better at memory management than Filestore was.

The autoscaler (by default) starts with the minimal number of PGs and scales up as data is used in the cluster. This keeps resource usage low in trivial clusters, but lower PG nums equivocate to lower performance. Fewer PGs means less parallelism when reading/writing data, and less parallelism means lower performance. The `bulk` flag makes the autoscaler start with the max number of PGs, and the autoscaler then decreases only if the PG usage starts to skew too much.

Their recommendation is that `bulk` should be the default for all pools. This is even especially true for the RGW index pool which typically has very few PGs because it has very little data in it. But by increasing the PG count, the metadata can be accessed more quickly, increasing S3 speed. index and other meta pools are also used to speed up small data access, which tends to be how most highly-used object stores are used in the real world.

They also recommend raising the autoscaler's target pg count from default 100 to 200 (possibly even higher for SSD/NVMe drives).

Anthony has a PR to upstream Ceph to double several settings' default values, and he's recommended that these are good recommendations for Rook users. He and Kyle have expressed that the Ceph project can be very conservative, and it may be quite some time before it is approved, and even longer before it's backported, suggesting that Rook may benefit users by getting ahead a little: https://github.com/ceph/ceph/pull/60492/files 

Ceph has an option to make all new pools bulk by default, which we might use to Rook's advantage.

- name: osd_pool_default_flag_bulk
  type: bool
  level: advanced
  desc: set bulk flag on new pools
  fmt_desc: Set the ``bulk`` flag on new pools. Allowing autoscaler to use scale-down mode.
  default: false
  services:
  - mon
  with_legacy: true
  
This might be a good candidate for making into a best practice recommendation for user configs.
