### ISSUE TITLE
Create a controller that will monitor and update the status of the mirroring

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14855]
**Is this a bug report or feature request?**
* Feature Request

Currently cephblockpool CR have a monitoring setting
```
  statusCheck:
    mirror:
      disabled: false
      interval: 60s
```

Which runs every one minute and collect the mirroring status,
But with increase of need to rados-namespace and its mirrroing we need to monitor the rados-namespace mirroring,
But following the same design we can end up with too many go-routines running periodically

**What should the feature do:**

Instead of having `statusCheck` running with a separate CR it  should be done under one controller and that will update the status of all the CR's or just keep a well formated status,

```
pool1 status: healthy
     r1: warning

pool2 status: warning
    r2: warning
``` 

**What is use case behind this feature:**

To avoid bottlenecks in operator performance

**Environment**:

**Comment by travisn** [comment]
Some considerations:
- If status is too verbose, there are too many statuses to query, or the status is being requested too often, we should consider not collecting it because it becomes too expensive. There could potentially be many rados namespaces so it could be too expensive to query the status.
- In reality, very likely there will be a very small number of pools or rados namespaces mirrored. So we could just document that if they have too many they should increase the status update interval, or disable the status checking.
- What do the commands look like for querying mirroring status of rados namespaces? Can we query the status at the pool level for all rados namespaces in that pool? If that were the case, the status could just be on the pool, even for the rados namespaces. We could also just use the existing goroutines and not worry about more goroutines for rados namespaces.
- If the mirroring status does need to be queried separately from pools anyway, I'd recommend we create one goroutine for each rados namespace in the rados namespace controller. Even though it's another goroutine for each rados namespace, it will be acceptable as long as the assumption above for the second bullet is true.

**Comment by parth-gr** [comment]
So the query the status, commands are

pool: `rbd mirror pool status {pooName}`
rados-namespace: `rbd mirror pool status {pooName}/{rados-namespace}`

Algorithm:
1) Get all the mirrored block pool names
2) Get the status of each Blackpool one by one and update the cephblockpool CR status.
3)  Query rados namespaces for each mirrored block pool, filter out the mirrored rados namespaces
4) Now one by one query the `status` for each rados namespace and update the rados namespace CR status

All steps will unify the status in one go-routine removing the performance gap for creating multiple go-routines,

We can keep the whole process per Blackpool in the Blackpool reconcile,
Plus if we keep it in the separate `status` controller which can be started once we discover if Blackpool is configured for monitoring the benefit is either we can store the all the status at same place
```
pool1 status: healthy
     r1: warning

pool2 status: warning
    r2: warning
```

We can update the CR's with the defined values but we will separate the overload from the main controller.

Even we can include other statuses and monitoring check like `cephfilesystem and subvolume groups` with this

**Comment by travisn** [comment]
To capture today's discussion, the latest proposal I'm understanding includes:
- Each CR should have its own status, for both block pools and rados namespaces. 
- Block pools do not need the rados namespace status rolled up.
- Goroutines are very low overhead, so we likely want a goroutine per rados namespace, started by the rados namespace controller.

**Comment by parth-gr** [comment]
Fixed by https://github.com/rook/rook/pull/14896
