### ISSUE TITLE
Partial implimentation of revisionHistoryLimit #12722 ??

### ISSUE THREAD

**Issue by reefland** [rook/rook#14902]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

As per feature request on revisionHistoryLimit #12722, I see the entry has been added to the operators `values.yaml` here:

https://github.com/rook/rook/blob/8491c427f1f714470ae2440dfce1a38fd2959e50/deploy/charts/rook-ceph/values.yaml#L642-L643

I set this in my operator's `values.yaml`:
```
# The revision history limit for all pods created by Rook. If blank, the K8s default is 10.
revisionHistoryLimit: 3
```
Restarted the operator and many of the deployments did switch from 10 to 3, but not everything.

**Expected behavior:**

I expected the following Deployments to also be switched from 10 to 3:
* `rook-ceph-exporter-*`
* `rook-ceph-crashcollector-*`
* `rook-ceph-tools`
* `rook-ceph-operator`
* `rook-discover`
* `csi-cephfsplugin`
* `csi-rbdplugin`
* `csi-cephfsplugin-provisioner`
* `csi-rbdplugin-provisioner`

These still show:
```
spec:
  ...
  revisionHistoryLimit: 10
  ...
```

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu 20.04.4
* Kernel (e.g. `uname -a`): 5.15.0-107-generic
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.15.4, go: go1.22.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 19.2.0 (16063ff2022298c9300e49a547a16ffda59baf13) squid (stable)
* Kubernetes version (use `kubectl version`):  v1.30.5+k3s1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): K3S
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):  HEALTH_OK

**Comment by obnoxxx** [comment]
@reefland, Thanks for testing the feature that you had requested and thanks for reporting the incomplete implementation here!

I am sorry  that your experience was not quite as expected  and started looking into it!

I can confirm (from testing with CRs instead of helm)  that it is nor correctly implemented for:
* exporter
*  crash-collector
* mon
* mgr
* osd
* csi provisioner deployments.
* toolbox

I am particularly puzzled because my original imlementation patch  **did** cover mgr, mon, osd, and exporter codepaths.

Anyway, looking into fixing this now.

**Comment by reefland** [comment]
> I am sorry that your experience was not quite as expected and started looking into it!

No worries. I appreciate you working on it.

**Comment by obnoxxx** [comment]
Additionally confirmed the setting not to be propagated to the daemonsets `csi-cephfsplugin`and `csi-rbdplugin`.
