### ISSUE TITLE
Add Option to enable Ceph REST API

### ISSUE THREAD

**Issue by f0** [rook/rook#1606]
**Feature Request**

*What should the feature do:*
Add an Option to enable Ceph Rest Api 

*What would be solved through this feature:*
Monitoring Agents like metricbeat, using the Ceph Rest API for mointoring, and with this enables they would work out of the box

**Comment by taxilian** [comment]
In case someone else stumbles across this like I did while looking for a solution -- in the current rook deployment you can access the REST api via the ceph dashboard which you can enable using rook. (`/api`)

**Comment by Mihai-CMM** [comment]
@taxilian  thanks . Might you want to detail a bit please. For example i have the url exposed through an ingress like ceph-myenv.test.int  if i try  ceph-myenv.test.int/api  i get {"status": "404 Not Found", "detail": "The path '/api' was not found.", "request_id": "3be9f82a-a1eb-4025-83aa-4e52ea87534c"}

**Comment by taxilian** [comment]
Yep, sounds like it's working! ;-) That's not a valid endpoint on the REST
api, from what I can see.  See https://docs.ceph.com/en/quincy/mgr/ceph_api/

I haven't played with it, but if I do a GET /api/cephfs I get a "401
unauthorized", which indicates that it is hitting the API but since I
haven't authenticated I can't use it. Knowing how to access the API doesn't
mean you don't need to learn how to use it correctly for it to be useful
;-) I haven't thus far needed to actually use it so I haven't spent any
time on it yet. -- I thought I was going to need it, then ended up deciding
to solve the problem a different way.

**Comment by Mihai-CMM** [comment]
Ha you are right . Thanks :)
