### ISSUE TITLE
Restoring mon quorum page should not be first entry in docs navigation tree

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1682]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

The new "Restoring Mon Quorum" page in the docs does not have any navigation/hierarchy information, so it is listed as first in the docs navigation tree.  See the attached screenshot.

It should be placed correctly underneath the Advanced Configuration or Common Issues section.
![screen shot 2018-04-27 at 7 16 41 am](https://user-images.githubusercontent.com/4313439/39367336-4df58234-49eb-11e8-996c-f401e54a8b8d.png)

**Comment by jbw976** [comment]
Does anyone know the full supported syntax for controlling the navigation tree on the docs site (https://github.com/rook/rook.github.io)?

Are multiple levels of indentation supported?  In the existing docs, I only see indentation as a boolean.
```
---
title: Advanced Configuration
weight: 76
indent: true
---
```

**Comment by travisn** [comment]
@jbw976 i understand that only one level of indentation is supported in the hierarchy. 

For this topic specifically, i was not sure it was ready to be included in the docs since it is such an advanced topic, so it was unintended that the docs picked it up from the subfolder. But until we make the docs more flexible such as a better hierarchy, agreed that we should add it to the advanced section
