### ISSUE TITLE
Add support for Dynamic Database Provisioning

### ISSUE THREAD

**Issue by bassam** [rook/rook#1704]
**Feature Request**

What should the feature do:
With CockroachDB now added to the Rook project, we need to enable a dynamic database provisioning similar to dynamic volume provisioning in Kubernetes. The goal is that application developers need not care about which service (managed services or in-cluster implementation) is providing the database for them. Cluster admins should be able to specify a DatabaseClass that includes details of the implementation. 

Initial support should include RDS, CloudSQL, Aurora, as well as CockroachDB, Vitess, and others.

Design document coming /cc @jbw976

**Comment by deitch** [comment]
Thanks for the link to this issue via twitter.

I have a real use case to which I would love to apply this now. Obviously, it isn't ready, so we will work around. Hopefully, our practical use case will help in definitions.

We have services that require a backing data store (in our case, Postgres, but it could be anything). We actually provision them via RDS, but, again, it could be anything. Ideally, our world would look like this:

1. Service declares dependency on a Postgres database with a particular name
2. When applied:
    1. The operator (as configured via rook) determines how to provision a database. It might be a database instance (on an existing RDS), or might be a dedicated database server (RDS)
    2. If a user and pass are not provisioned, it gets provisioned and then placed in a kube secret in the correct namespace for the requesting service

The abstractions are what keep the service from knowing whether it is Postgres running in kube, RDS, GSQL, or something else entirely.

I am somewhat unsure if the declaration should be a separate yml `Kind` of type `Postgres`, or something like a `PVC`, which really is intended as a volume.

Some key points:

* the ability to decide at the admin level if we are fulfilling requests for databases with another database in an existing RDS (or set one up if none exists) vs creating an RDS per service. I imagine serverless Aurora might impact this
* the consuming service needs to be able to specify where it will find the credentials. We could go with convention over configuration, or have it specify in its request where it expects them.
* we have initialization SQL which a service declares in its `sql/` dir (parallel to its `kubernetes/` deploy dir). We need to think of a sane way to deploy it. I suspect init containers, which would put it out of scope of rook, but it might make sense to have it part of the requirement declaration.

For now, we create the databases with a combination of:

* terraform for the RDS as a whole
* manual creation of the particular database for each new one
* update terraform for each one to use kube provider to stuff credentials into a secret
* consume the secret in the service (which probably is the only thing we are doing right here)

We are migrating towards making it part of our CD system, but a CRD declarative makes much more sense.

**Comment by hunter** [comment]
Will this be something different to Open Service Brokers?

**Comment by tonya11en** [comment]
@hunter this will be different to open service brokers (OSBs).

The OSB API is essentially giving a cluster operator a workflow that looks something like:
* Ask the service catalog API server what services are available and the associated plans for those services.
* Initiate the provisioning of a new managed service instance from that list.
* Bind to that managed service instance (credential details) and consume it.

OSB is just a  way provision and bind services to an application across multiple providers. Rook **could** be a service broker for storage like ceph/minio/cockroachdb, but we're trying to accomplish something different here from a service broker like the cloud vendors.

Our aim is to create storage abstractions to allow applications' storage needs to be portable across multiple environments, which is not exactly a high priority for a cloud vendor or anybody else who would support the OSB API. In the context of this feature request, we want application developers to say "here is my application spec, it needs a database with these properties, and N buckets with those properties." The reason for implementing things like DatabaseClass/BucketClass which are analogous to StorageClass, is that Rook can dynamically provision the database or bucket and just give it to the application to consume, in **any environment**. Using OSB, we wouldn't have these types of abstractions **and** it's not portable since we'd have to make our own buckets and databases a different way for each broker.

**Comment by deitch** [comment]
> Our aim is to create storage abstractions to allow applications' storage needs to be portable across multiple environments

This is something I have been trying to understand. So is the assumption that to use an OSB, an app would need to use the programmatic API, whereas with Rook (or any other such CRD/Operator), you would just do it declaratively? If so, the CRD/Operator _could_ use the OSB under the covers, but wouldn't necessarily need to?

I have been working on an open source database provisioner, whenever I can find time. It helps a client of mine (but outside of my working hours with them, hence OSS), and those have been my motivations.

**Comment by bassam** [comment]
> This is something I have been trying to understand. So is the assumption that to use an OSB, an app would need to use the programmatic API, whereas with Rook (or any other such CRD/Operator), you would just do it declaratively? If so, the CRD/Operator could use the OSB under the covers, but wouldn't necessarily need to?

correct. we think `PersistentDatabase` and `PersitentBucket` should be abstractions just like `PersistentVolume` today. Obviously, Databases vary a lot but you can find lots of commonalities if you normalize on the popular open source options like mysql and postgres.

> I have been working on an open source database provisioner, whenever I can find time. It helps a client of mine (but outside of my working hours with them, hence OSS), and those have been my motivations.

Can we collaborate? :-)

**Comment by deitch** [comment]
OK, thanks, makes sense. I think I see where Rook is going now.

> Can we collaborate? :-)

Sure. I am a little overloaded - I spend most of my time either doing DevOps transforms for clients or working on product strategy for other clients, not to mention time spend on WorksOnArm and AccelerateWithOptane, so OSS work is a side for me (LinuxKit too, and other projects I have released). I will try to find time to do some of it over the next few weeks, and when there is what to share, let's collaborate.

FWIW, my approach is first to have it provision databases in an already-existing database server (or what looks like one from a client perspective), so it doesn't need any real cloud API knowledge, and only then expand to actual database API provisioning. E.g. it assumes you have a DB `somewhere` - GSQL, Azure SQL, Aurora/RDS, your own, who cares - and creates a database and a server in there. Later, will expand.

My approach to the declarative part was having a CRD of `Kind: Postgres` or similar in a given `api`, but I could see making it a `DatabaseClass` instead.

**Comment by Bessonov** [comment]
Activity!

**Comment by Bessonov** [comment]
....

**Comment by Bessonov** [comment]
.... I hope you like this senseless message .... I vote against stale bot.

**Comment by travisn** [comment]
@Bessonov The bot certainly helps remind about old issues that needs attention...
@jbw976 Is this design still planned? Seems like attention to dynamic db provisioning has been at the Crossplane level.

**Comment by Bessonov** [comment]
@travisn I'm sure that most issues get closed by stale bot because watching people just give up. But just because they are closed, it doesn't mean that nobody interested in them or they are resolved. For this reason I give up to contribute to istio at all. Just don't want to fight against their istio bot.

**Comment by jbw976** [comment]
Hey there @Bessonov, thanks for your interest in this issue. I definitely see the value in this scenario, in fact we've dedicated an entire project to provisioning of resources beyond volumes in a dynamic, portable, self-service, separation of concerns approach in the [Crossplane project](https://crossplane.io/).

I don't see this issue getting much traction within Rook anymore, since there is a lot of foundational effort required to get all the machinery in place.  If you're interested in this scenario, I recommend taking a look at [Crossplane](https://crossplane.io/) and joining the conversation with the community there.  Happy to understand your scenario and get your feedback there, hopefully that project has what you're looking for.  Thanks for your contribution to the discussion at Rook and hopefully [Crossplane](https://crossplane.io/) too!

**Comment by travisn** [comment]
Closing based on the latest discussion that Rook is not planning the database provisioning.
