### ISSUE TITLE
Rook should not enable experimental multi-filesystem flag by default

### ISSUE THREAD

**Issue by batrick** [rook/rook#1720]
This is related to #1027 which we are backporting.

The Ceph team does not consider multifs stable yet and we're not even certain it will be stable for the N release. Whatever service Rook is providing that creates multiple file systems needs to be considered experimental.

cc @travisn

**Comment by travisn** [comment]
since multiple file systems will be considered experimental for some time still, agreed that we should disable multiple file systems by default. This could be done by an environment variable to the operator similar to [these](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-operator.yaml#L186). If false, the operator would only create the first file system that is requested and ignore requests for more file systems. If true, the operator would allow creating multiple file systems as before.

**Comment by ajarr** [comment]
@travisn  can you please add the 'ceph' and 'filesystem' labels to this issue
