### ISSUE TITLE
Refactor integration test code to accomodate multiple backends

### ISSUE THREAD

**Issue by tonya11en** [rook/rook#1788]
**Feature Request**
=

As it stands now, there is a single namespace and set of files for all integration tests for all Rook back-ends. As more back-ends are implemented, this scheme becomes unsustainable. I'm filing this issue to track the following efforts:

**Multi-backend integration test design**
-

This includes investigation into common abstractions and a workflow for adding new integration tests for new backends. We should make heavy use of function arguments and closures here, since everybody has to create operators, storage resources, etc.

**Refactor current integration tests**
-

This means any Ceph, Minio, and Cockroachdb integration tests that exist should adopt the new design and workflow.

**Documentation regarding integration tests**
-

Self-explanatory.

**Comment by yanniszark** [comment]
I think this is still relevant and very important.
Lately, I have been using the existing tools to write integration tests and while they get the job done in simple tests, they can be difficult to extend. 
Some changes that have to be made imo:
* Tests should use clients made for go and not invoke kubectl. Using kubectl makes error checking a lot more frustrating. Some restrictions I have noticed are:
   * Using kubectl, you can't easily check if a delete failed because the resource doesn't exist, in which case you don't want to fail the test.
   * If you want to get information about an object in the cluster, you have to parse the text output of kubectl to get the info you want. 

The main advantage I see kubectl is offering is creating all resources at once without having to call a different client for each kind. To have the best of both worlds, I recommend that rook uses the `controller-runtime` library for integration tests. It provides a client that can be called with any `runtime.Object` and should let us delete a lot of the current code.
