### ISSUE TITLE
Use ceph osd safe-to-destroy instead of own logic

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1824]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing:
Yes, currently this code[1] is used to determine if it is safe to remove an OSD (Pod).

What should the feature do:
Use `ceph osd safe-to-destroy <osd-id>` instead of our own logic, as Ceph is probably in the better position to decide if an OSD is ready to go.

What would be solved through this feature:
Ceph decides if it is safe to remove (/destroy) an OSD that should be removed from the cluster.

Does this have an impact on existing features:
No, it even improves the OSD removal process by utilizing Ceph "functions" directly.

[1] https://github.com/rook/rook/blob/master/pkg/daemon/ceph/osd/agent.go#L557-L627

Relates #1766.

**Comment by jbw976** [comment]
It would be good to have a better/clear understanding of what the `safe-to-destroy` subcommand does under the covers.  The OSD agent logic linked above in this issue is about synchronization of the orchestration process, checking to make sure that rebalancing of data has started and has finished so the operator knows when the next step in orchestration can be started.  I don't know if `safe-to-destroy` gives insight at that particular granularity and can answer questions like that, so more research will be needed.
