### ISSUE TITLE
Rook Osd are not starting on new Slave Nodes.

### ISSUE THREAD

**Issue by deveshk0** [rook/rook#1949]
After adding the new slave in kubernetes 
Rook OSD is not starting,

Giving this in log

Provisions and runs the osd daemon
 Usage:
 Flags:
      --admin-secret string           secret for the admin user (random if not specified)
      --ceph-config-override string   optional path to a ceph config file that will be appended to the config files that rook generates
      --cluster-name string           ceph cluster name (default "rookcluster")
      --config-dir string             directory for storing configuration (default "/var/lib/rook")
      --fsid string                   the cluster uuid
  -h, --help                          help for osd
      --mon-endpoints string          ceph mon endpoints
      --mon-secret string             the cephx keyring for monitors
      --private-ip string             private IP address for this machine
      --public-ip string              public IP address for this machine
 Global Flags:
      --log-level string   logging level for logging/tracing output (valid values: CRITICAL,ERROR,WARNING,NOTICE,INFO,DEBUG,TRACE) (default "INFO")

Please help

**Comment by deveshk0** [comment]
Hi @travisn 
I am running v0.8 version of rook opeartor.
when i initially started i had 5 machine in cluster. after that i added 3 more machine to the kubernetes cluster, now osd daemon on these new nodes is failing. It keeps on crashing.

The attached log is from osd daemon from new nodes where it is crashing.

I didn't restarted the cluster. when i added new slave nodes. osd daemon automaticallys started on these new nodes but it is crashing.

![sc](https://user-images.githubusercontent.com/20398273/43298684-a2a3ba00-9174-11e8-909b-bc778762a198.png)
![newsc](https://user-images.githubusercontent.com/20398273/43298719-d65208ca-9174-11e8-81be-2f240a8cdae6.png)

**Comment by travisn** [comment]
@deveshk0 It looks like you are running the `rook/ceph:master` image from 24 days ago. When you tried to start the three new nodes, you actually started a newer version of `master` on those nodes. The `master` image changes daily, so it really shouldn't be used except for temporary test clusters. The build changed and running different versions of master caused the issue. We have attempted to make this more clear in the documentation recently. 

You could attempt to follow the [upgrade guide](https://rook.io/docs/rook/v0.8/upgrade.html) to upgrade to the 0.8 build. Note that upgrades from master are not fully supported, but there is a good chance you can get it to work. We would recommend in the future you only run official builds such as `v0.8.0` instead of the master builds.

**Comment by travisn** [comment]
@deveshk0 were you able to resolve this? If not, please let us know in the slack channel. Please reopen if you see this issue again on the 0.8 build.
