### ISSUE TITLE
"rbd map" hangs in toolbox

### ISSUE THREAD

**Issue by lbogdan** [rook/rook#2021]
As stated in the [docs](https://rook.io/docs/rook/v0.8/direct-tools.html), `rbd map` hangs (while still succeeding) when running it in the toolbox:
```sh
# Map the rbd device. If this command appears to hang, ctrl-c and check if it actually completed successfully by continuing.
rbd map replicapool/test
```

Because I was a bit annoyed by this, I decided to look into it. With a bit of help from #ceph-devel on IRC, I found that, after mapping the block image, "rbd map" [waits for an udev add event](https://github.com/ceph/ceph/blob/master/src/krbd.cc#L182-L251) for the /dev/rbd*X* block device. Using `udev monitor` inside the toolbox I noticed it didn't receive those events (while `udev monitor` on the host was receiving them). Googling around, I [found out](https://dummdida.tumblr.com/post/121087781445/re-udev-events-in-a-container) that the only way to get a container to receive udev events is to run the container with `--net=host`. Changing https://github.com/rook/rook/blame/master/Documentation/toolbox.md#L47 to `hostNetwork: true` fixed the hanging issue.

So, my suggestion is to change `hostNetwork: true` in the toolbox documentation (maybe with a comment that setting it to `false` will make `rbd map` hang), and refine the already existing hang comment. If you agree, I can create a PR.

**Comment by jbw976** [comment]
Looks like a similar line of thinking from a very old (and since closed) issue on this same topic: https://github.com/rook/rook/issues/481#issuecomment-298372871

A PR to use hostNetworking in the toolbox should be fine @lbogdan.  Please do try some other scenarios in the toolbox and make sure there are no unexpected regressions:
https://rook.io/docs/rook/v0.8/toolbox.html
https://rook.io/docs/rook/v0.8/direct-tools.html

**Comment by lbogdan** [comment]
I tried all the toolbox scenarios, everything worked as expected.

I also created the PR, I'm not really sure about the comments / wording, though. Please let me know.
