### ISSUE TITLE
Helm chart for cluster provisioning

### ISSUE THREAD

**Issue by maver1ck** [rook/rook#2109]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I'd like to have helm chart for cluster creating. Both for sc and cluster itself
https://rook.io/docs/rook/master/block.html
https://github.com/rook/rook/blob/master/Documentation/ceph-quickstart.md#create-a-rook-cluster

**What is use case behind this feature:**
I can have all the parts of the env managed by helm

**Comment by kfox1111** [comment]
This could be useful.

**Comment by Bessonov** [comment]
@stale bot leave it open

**Comment by travisn** [comment]
With #2820 merged, we can now plan on adding the cluster spec to the existing rook-ceph helm chart instead of creating a whole new chart. This will be a great simplification since users generally want to manage a single cluster with a single operator. 

We can leverage the changes in #1676 and now apply it to the existing helm chart and we will be most of the way there. The cluster crd has changed quite a bit since that PR was opened, so we will also need to update to the latest crd schema.

**Comment by Bessonov** [comment]
Activity!

**Comment by Bessonov** [comment]
Happy New Year!

**Comment by maver1ck** [comment]
2 years later ? :)

**Comment by galexrt** [comment]
My plan would be to just have it be a "wrapper" for the CephCluster object in the values.yaml and keeping it separate to the rook-ceph-operator Chart so we can rely on the operator like that as a dependencies.

**Comment by maver1ck** [comment]
@galexrt 
There is such a wrapper ready.
https://github.com/helm/charts/tree/master/incubator/raw

**Comment by galexrt** [comment]
@maver1ck Yeah I know that one, but we need one specific for the Rook CephCluster object to be able to easily add "easy to use options / toggles" later down the road.

I'll start the chart as a specific for CephCluster wrapper and later on as users will hopefully contribute to it so that "easy use options" (e.g., "this is a test cluster" toggle, etc) can be added to it.

**Comment by maver1ck** [comment]
If you need any testing please let me know.

**Comment by galexrt** [comment]
To update on this issue, I'm in the process of writing a design document to move all Helm charts to a separate repo, so the Helm charts are able to "move" / release without being bound to the Rook releases directly.
The Helm charts have the `appVersion` which can / should be used then to indicate the Rook version they are targeted for.
I should have that document finally ready tomorrow / weekendish for review.
