### ISSUE TITLE
Draining a rook node automatically before reboot

### ISSUE THREAD

**Issue by kcao3** [rook/rook#2147]
Hello,
I am currently having issue while rebooting a CentOS7-based node. It turns out this is one of the common Rook issues: 
https://github.com/rook/rook/blob/master/Documentation/common-issues.md#node-hangs-after-reboot

The node needs to be drained before reboot. 
After the successful drain, the node can be rebooted as usual. 

IMHO, this is a really pain if a k8s node has to be drained manually. Does anyone know any tool to do this in a systematically way? 

I have found this daemonset config: https://github.com/rook/rook/blob/master/cluster/examples/coreos/before-reboot-daemonset.yaml
However, I suspects this only works with coreos.

**Comment by anguslees** [comment]
It's almost never safe to just reboot a k8s node locally without some sort of external coordination.  Consider what would happen to distributed consensus services (like rook's mon servers) if they all rebooted simultaneously.

I respectfully suggest you switch your workflow/tools to either:
- reboot "externally" using a script that does `kubectl drain` + `ssh reboot` + `kubectl uncordon`
- "request" a reboot locally rather than just run the command immediately.  Then run something like `https://github.com/weaveworks/kured` or coreos' `update-agent` to actually perform the reboot, at a time when it is deemed safe (and after draining the node).

Of course there will always be "uncontrolled" reboots due to power outages or hardware issues.  Rook/ceph should certainly be made to recover from those where possible.
