### ISSUE TITLE
Specify block device by id

### ISSUE THREAD

**Issue by Vanuan** [rook/rook#2158]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Currently devices can be specified like these:

```
    nodes:
    - name: "server"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdb"
      - name: "sdc"
```

I'd like to be able to specify them like this

```
    nodes:
    - name: "server"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "disk/by-id/ata-xxx"
      - name: "disk/by-id/ata-yyy"
```

**What is use case behind this feature:**

I believe this will allow hotswapping disks in any order.

On the other hand, disk replacements would require configuration to be changed.

**Environment**:

**Comment by jbw976** [comment]
hi @Vanuan thanks for your suggestion, I think this is being tracked in #1228 already, take a look at that.  The ceph OSD orchestrator under the covers points Ceph at the specific/unique UUID for the device, so even if the device name changes from say sda to sdb, the OSD will never start using the wrong device.  So data integrity will be protected.

However, as #1228 gets into, the user experience here is what needs to be improved.  Allowing the user more options for selecting devices by more "stable" identifiers would definitely be an improvement.  I'm going to close this issue here and keep tracking with #1228.
