### ISSUE TITLE
Tag release branch after updating versions in yamls

### ISSUE THREAD

**Issue by calder** [rook/rook#2162]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
YAMLs at the `v0.8.2` tag should pin only `v0.8.2` container images. Instead, they pin `v0.8.1` images: https://github.com/rook/rook/blob/v0.8.2/cluster/examples/kubernetes/ceph/operator.yaml#L292

**Expected behavior:**
YAMLs at version X should pin container images at version X.

**How to reproduce it (minimal and precise):**
Read the source.

**Environment**:
All.

**Comment by calder** [comment]
To clarify, the bug isn't that this specific version is wrong. It's that the process used for bumping versions and creating version tags makes this possible.

**Comment by jbw976** [comment]
you are totally right @calder, thanks for opening an issue on this. @galexrt has mentioned this a couple times too.  one way to deal with this would be to bump the versions of the yamls before we tag the release branch, that would work for patch builds, but I don't think that would work for the first creation of the release branch since that tag and branch creation comes directly off of master (which we wouldn't want to put specific version numbers into).  we need a more complete solution for this.

**Comment by galexrt** [comment]
@TimJones Not really as most users directly pull the manifests from the repo.
To break it down: the git tag is made before the yamls have been updated to use the new tag.

**Comment by TimJones** [comment]
@galexrt I see.
It feels a bit hacky to me, but would a sed + commit command in https://github.com/rook/rook/blob/v0.8.2/build/release/Makefile#L100-L111 work?

**Comment by calder** [comment]
AFAICT this was never addressed.

**Comment by calder** [comment]
Still an issue, just a minor one.
