### ISSUE TITLE
Shared FS client path restriction

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2164]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Since multiple filesystems are not recommended, there should be a way to restrict namespaces tp accessing only certain folders in Ceph FS. This is supported by ceph: http://docs.ceph.com/docs/mimic/cephfs/client-auth/#path-restriction but rook is not allowing to provide credentials for the mount.

**What is use case behind this feature:**
Allow multiple users use same ceph filesystem and protect their data from each other

**Comment by galexrt** [comment]
As a first thing to implement a kind of restriction here, as we talked in the community meeting adding a parameter to the StorageClass to control the user and the key/secret that used to do the mounting should be enough to help @dimm0 solve their problematic with their (NFS) workaround.

**Comment by travisn** [comment]
wait, scratch my last comment... As discussed in slack, we're not using an SC for filesystem. We probably have to just add the username/secret to the Flex volume settings.

**Comment by galexrt** [comment]
@dimm0 and I had a chat about this issue and we came to the following way to implement this feature as follows:

Two (security) modes (flag/env var on operator, will be given to rook-ceph-agent DaemonSet):
1. Any (default) - just use admin as the current behavior
2. Restricted - User must set id and secret name (secret is per namespace) for mounting

PVC/Volume parameters are used to set `mountUser` and `mountSecret`. Agent will try to fetch Secret in the namespace the volume mounting is requested in.
Example (Restricted mode):
Namespace A has Ceph Key Secret, user A can mount volume as long as user specifies id/user and secret name. Agent will check if secret exists in the namespace A and continue mounting if so.

Default Secret name `rook-ceph-mount-secret`.
For 1nd mode: Rook Ceph Agent will always check if the secret exists. If it exists it will be used, if not admin account is used.
For 2nd mode: If no secret is specified in the parameters, check for default secret and use it if exists, otherwise fail because of missing secret.

**Comment by travisn** [comment]
Some questions on the proposal:
- Why do we need a default secret name? Is this just a convenience to have a default so it doesn't have to be specified on the volume? I'd lean towards not having a default. Kubernetes resources usually follow a pattern of being very explicit.
- Since the secret must be accessible by the agent, we will need a RoleBinding for each namespace where the privilege is needed by the `rook-ceph-system` service account, right? Or at least in the examples we would want to limit the namespaces that the operator gets access to with the secrets, rather than giving access to secrets in all namespaces.

**Comment by galexrt** [comment]
@travisn to your points:
1. It would be just for convenience but yes as you wrote Kubernetes pattern is if being very explicit.
2. I added RBAC roles in the doc section. The user can either create a ClusterRoleBinding and is good to go or use a RoleBinding per Namespace.

I will update my previous comment with these changes.

**Comment by dimm0** [comment]
I was thinking about this and two questions came to my mind:
1. When ceph will make multiple filesystems available, and we'll want to separate ours to a fast (NVMEs) one and large (spinning drives), or to separate regions etc, will you have to redo this? Will users be able to choose which filesystem the secret belongs to?
2. Would it be possible to specify credentials for different mountpoints of the same cephFS in the same namespace? Will those need to have the same key?

**Comment by dimm0** [comment]
@galexrt Could you please look at these questions?

**Comment by galexrt** [comment]
@dimm0
1. You specify the name of the filesystem in the flexvolume parameters/StorageClass so the "credentials" will only be used for the flexvolume mount/StorageClass. No, the code is to "simply" use `mountUser` and get the `mountSecret` contents during the mount process. If there are multiple filesystems, the `fsName` parameter changes, which goes through the same mounting process.
2. Yes, you can do that, but security kind of goes away with that. Ceph Secret key A with access to `/foo` and Ceph Secret B with access to `/bar` in namespace A. The user could use both of those secrets as `mountUser` and/or `mountSecret` parameters (as they are in the same namespace A as the secrets and Pod mounting the storage).
