### ISSUE TITLE
Add Kubernetes 1.12 to Jenkins tests

### ISSUE THREAD

**Issue by travisn** [rook/rook#2168]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
With the release of K8s 1.12, we need to test rook on 1.12 as part of our integration tests in jenkins.

**Comment by jbguerraz** [comment]
@mickymiek is actively working on it now

**Comment by mickymiek** [comment]
I ran integration tests on all test suites on a single node k8s 1.12.0 cluster using kubeadm
`BlockCreateSuite` and `NfsSuite` passed, all others failed

`CockroachDBSuite`: https://gist.github.com/db39dd5434e181350ad978b09673e229

`HelmSuite`: https://gist.github.com/1801b0f2d171b4b26950d81cc91cbd87

`SmokeSuite`: https://gist.github.com/03cc3db06c923c28122bd87465c4a0d6

`UpgradeSuite`: https://gist.github.com/721edec26a27fa29bdee794d81cbca8e

`BlockMountUnMountSuite`: https://gist.github.com/2f84e2850595705fe50f5643a6835c86

When creating the cluster with `tests/scripts/kubeadm.sh up` with `KUBE_VERSION=v1.12.0` I noticed CoreDNS was crashing (https://gist.github.com/mickymiek/361d182d57e636949468a59fd82c8938) whereas it doesn't with` KUBE_VERSION=v1.11.3` (probably due to the plugin loop being in the 1.12 Corefile and not in 1.11). I don't know yet if this issue is related to my environment or kubeadm.

I'm wondering if it might be the cause of all the suites failing, but when running the tests on a 1.11 cluster tests still fails with the same errors except for `BlockCreateSuite, NfsSuite, CockroachDBSuite`.

If you guys have an idea what could be causing these errors, please let me know. I'll investigate more in depth tomorrow and keep you guys up to date :-)
