### ISSUE TITLE
rook tool support for Object Storage

### ISSUE THREAD

**Issue by jbw976** [rook/rook#229]
The `rook` tool needs some support (UX) for object storage that will be surfaced by `rookd` with the following tickets:
https://github.com/rook/rook/issues/164

The underlying rook/ceph internals should not be exposed, but some experience for adding, removing and managing object storage and buckets should be added.

For example:
```
rook objectstore create
rook objectstore delete
rook objectstore bucket create
rook objectstore bucket delete
```

**Comment by hunter** [comment]
Any thoughts on how to handle the user management? The `rgw-admin` CLI has some fairly confusing usability (getting a list of users, S3 vs Swift subaccounts, etc) so definitely could do with some improvement.

**Comment by jbw976** [comment]
We haven't thought too deeply about user management for RGW yet @hunter, but as is the general spirit of rook, some abstractions over the underlying ceph implementation will make things easier for rook users.  Feel free to share any specific ideas you may come up with and we are always accepting pull requests too :)

**Comment by hunter** [comment]
Not sure how useful I'd be contributing Go code but happy to help out with ideas.

From our experience building out a few Dashboards around Ceph, we've found that most of our users haven't really had a use for the Swift APIs. Most would prefer to use the S3 gateway since there are more tools that will use it. We found it easier to just create a user with generated secrets for S3/Swift and hide the details of subaccounts.

On the UX side, the use of options in the `radosgw-admin` CLI tool always seems to lead to confusion. None of the command usage/help return valid options so it is difficult to know what options to use for each command. The Rook CLI seems to have this covered with decent subcommands and help but wanted to raise one of the most frustrating parts of using RGW.

Generally the minio `mc` client has a very nice CLI interface so would be great to see similar functionality built in to the rook CLI (bucket management, file upload, mirror/sync, etc). An `mc` json config generator may be a useful (transitionary?) feature to avoid having to reinvent the wheel?
