### ISSUE TITLE
shared cephfs flexvolume not mounted in pod when running kubelet under atomic

### ISSUE THREAD

**Issue by jeblair** [rook/rook#2371]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After running the quick-start and registry example on, the cephfs shared filesystem is not mounted as a volume in the registry pod.  Inside the registry pod, /var/lib/registry is on the host's root filesystem.

**Expected behavior:**
/var/lib/registry should be the shared filesystem ("myfs" from the quick-start).

**How to reproduce it (minimal and precise):**
* Deploy Kubernetes with 1 master and 3 minions using OpenStack Magnum
  * Note: Magnum deploys kubernetes using fedora atomic, so kubelet is running in a container
* Run the quick-start CRD with FLEXVOLUME_DIR_PATH=/var/lib/kubelet/volumeplugins
  * Note: Magnum deploys kubelet with --containerized and --volume-plugin-dir=/var/lib/kubelet/volumeplugins
* Exec a shell in one of the registry containers and note that the backing device for /var/lib/registry is /dev/mapper/atomicos-root rather than the ceph filesystem.

The logs from the rook-agent report:

    flexdriver: mounting ceph filesystem myfs on /var/lib/kubelet/pods/196f0791-fcde-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store
    cephmon: parsing mon endpoints: a=10.254.17.237:6790,b=10.254.147.23:6790,c=10.254.185.202:6790
    op-mon: loaded: maxMonID=2, mons=map[a:0xc000bdf860 b:0xc000bdf8a0 c:0xc000bdf8e0], mapping=&{Node:map[c:0xc000be34d0 a:0xc000be3410 b:0xc000be34a0] Port:map[]}
    flexdriver: mounting ceph filesystem myfs on 10.254.17.237:6790,10.254.147.23:6790,10.254.185.202:6790:/ to /var/lib/kubelet/pods/196f0791-fcde-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store
    flexdriver:
    flexdriver: ceph filesystem myfs has been attached and mounted

The filesystem is not mounted inside the registry pod, nor is it mounted on the minion node.  However, it does appear inside the atomic runc container that kubelet is running in:

    10.254.17.237:6790,10.254.147.23:6790,10.254.185.202:6790:/   74G     0   74G   0% /var/lib/kubelet/pods/196f0791-fcde-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store

**Environment**:
* OS (e.g. from /etc/os-release): Fedora 27 (Atomic Host)
* Kernel (e.g. `uname -a`): 4.15.17-300.fc27.x86_64 #1 SMP Thu Apr 12 18:19:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Vexxhost, OpenStack magnum
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.9.0
* Kubernetes version (use `kubectl version`): 1.11.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenStack magnum
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by emonty** [comment]
This also seems related to #1921

**Comment by travisn** [comment]
@jeblair @emonty it looks like the flex driver is configured since it mounted, however since kubelet is in a container there is another step needed. The [flex volume config](https://rook.io/docs/rook/v0.9/flexvolume.html) topic mentions this in the Rancher section, so it looks like the docs need to be updated. Does that work for you?

**Comment by emonty** [comment]
@travisn Thanks - trying now - if it does, I'll push up a doc update.

**Comment by emonty** [comment]
Ok. So ... if I look at the mounts on all of the minions, I see what looks like the cephfs mounted into a volume for the pod:

```
minion-0:
10.254.14.93:6790,10.254.11.181:6790,10.254.18.2:6790:/ on /var/lib/kubelet/pods/7db08e79-fda0-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store type ceph (rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=myfs,wsize=16777216)
minion-1:
10.254.11.181:6790,10.254.18.2:6790,10.254.14.93:6790:/ on /var/lib/kubelet/pods/7db09842-fda0-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store type ceph (rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=myfs,wsize=16777216)
minion-2:
10.254.14.93:6790,10.254.11.181:6790,10.254.18.2:6790:/ on /var/lib/kubelet/pods/7db0357a-fda0-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store type ceph (rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=myfs,wsize=16777216)
```
If I write files to /var/lib/registry in each registry pod:

```
kubectl -n kube-system exec -it kube-registry-v0-g5mfh touch /var/lib/registry/g5mfh
kubectl -n kube-system exec -it kube-registry-v0-9gc99 touch /var/lib/registry/9gc99
kubectl -n kube-system exec -it kube-registry-v0-z9nk8 touch /var/lib/registry/z9nk8
```

I can see those files in the pod-specific directory that claims to be a cephfs mount on each minion - but only the file that was associated with the particular registry pod:
```
[fedora@opendev-tbu64tqms7nw-minion-0 ~]$ sudo ls -ltra $(sudo runc exec -t kubelet mount | grep image-store | awk '{print $3}')
total 0
drwxr-x---. 3 root root 25 Dec 11 23:57 ..
-rw-r--r--. 1 root root  0 Dec 12 16:28 z9nk8
drwxr-x---. 2 root root 30 Dec 12 16:28 .

[fedora@opendev-tbu64tqms7nw-minion-1 ~]$ sudo ls -ltra $(sudo runc exec -t kubelet mount | grep image-store | awk '{print $3}')
total 0
drwxr-x---. 3 root root 25 Dec 11 23:57 ..
-rw-r--r--. 1 root root  0 Dec 12 16:28 9gc99
drwxr-x---. 2 root root 30 Dec 12 16:28 .

[fedora@opendev-tbu64tqms7nw-minion-2 ~]$ sudo ls -ltra $(sudo runc exec -t kubelet mount | grep image-store | awk '{print $3}')
total 0
drwxr-x---. 3 root root 25 Dec 11 23:57 ..
-rw-r--r--. 1 root root  0 Dec 12 16:28 g5mfh
drwxr-x---. 2 root root 19 Dec 12 16:28 .
```

So it seems like there is a directory in /var/lib/kubelet/pods for the pod, and that it is what is visible inside of the pod. But that somehow it's not actually the cephfs mount. Or maybe something else local is getting mounted on top of it somehow?

**Comment by emonty** [comment]
Just a followup comment - because the above one may have actually muddied the waters:

In the kubelet container, we see the cephfs mounted on the pod storage directory:

/var/lib/kubelet/pods/581cf8c5-fe32-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store

If I write a file to that dir while in the kubelet container, it correctly writes to cephfs. If I jump to another minion, attach to the kubelet container there and then look in the corresponding cephfs dir, the file is there - so the cephfs is getting mounted and is getting mounted onto the right dir - from the POV of the kubelet. That's good.

But - the corresponding dir on the host is *not* the cephfs - it's just the mount point, and that's what the actual pod container sees. So if I write a file into /var/lib/registry in the pod container, it goes in to /var/lib/kubelet/pods/581cf8c5-fe32-11e8-aeef-fa163eb20d90/volumes/ceph.rook.io~rook/image-store
on the host and not into the cephfs that is mounted on top of it in the kubelet container.

**Comment by emonty** [comment]
#2376 is a stab in the dark. I verified that in our environment the kubelet container is configured to mount /var/lib/kubelet as rshared. Also - other bind-mounted volumes below /var/lib/kubelet, such as the tmpfs volumes for secrets, ARE properly propagating to be visible on the host as expected, so one would imagine it has something to do with the actual mounting operation itself.

**Comment by zcourts** [comment]
We appear to be having the same issue on bare metal with kubelet running natively. 

I tried:
```
mountPropagation: Bidirectional #HostToContainer
```
on the `volumeMount` which in turn required

```
          securityContext:
            privileged: true
```
on the deployment container's decl.

otherwise I was getting
```
Error: release mariadb failed: Deployment.apps \"mariadb\" is invalid: spec.template.spec.containers[0].volumeMounts.mountPropagation: Forbidden: Bidirectional mount propagation is available only to privileged containers
```

I was under the impression that `mountPropagation: Bidirectional` is equivalent to setting `rshared` on the mount, at least according to https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation which I think means that PR #2376  isn't really a fix.

Also, in that PR, does that then mean the container will become or require privileged mode? I was willing to try privileged mode to see if it worked as a temporary workaround but I that's optional surely?

I still haven't worked this out. One other thing I changed was the pool from xfs to ext4 (prior to 0.9.0 that was default) but that still hasn't helped, have now re-installed the cluster from scratch and gotten back to the same point. 
```
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
```
where `/bitnami/mariadb` us the path in the volumeMount...

Any suggestions on other things to try or other info I can provide to help debug?

**Comment by galexrt** [comment]
@zcourts The `mkdir` error is from the application inside the pod, right?
Have you tried running `sleep 3600` as the command of the Pod and then execing into to see if the container is running as the correct user (`id` and `whoami` commands).
If the Pod runs as a non-root user (`ID != 0`), it is okay that you can't access the mount as default perms on mounts are `root:root`. To fix that you need to set `fsGroup` in the securitycontext of the Pod(s) accordingly.

**Comment by zcourts** [comment]
@galexrt thanks for getting back. I didn't try that. It was part of an investigation work to do an upgrade which I parked to work on something else. I'll go back to it on Mon. as we do need to get around to the upgrade in short order. I'll let you know if that was indeed the problem next week.
