### ISSUE TITLE
mounting volume issue with kernel<3.15

### ISSUE THREAD

**Issue by sanverm2** [rook/rook#2396]
There is mounting volume issue with kernel<3.15 mentioned in the following URL:  

https://github.com/rook/rook.github.io/blob/master/docs/rook/v0.7/common-problems.md#volume-mounting

The workaround proposed is: 
```
If uname -a shows that you have a kernel version older than 3.15, you'll need to perform one of the following:

    Disable some Ceph features by starting the rook toolbox and running ceph osd crush tunables bobtail
    Upgrade your kernel to 3.15 or later.

```

Is this limitation still present in rook ceph or is has been fixed?

**Comment by BlaineEXE** [comment]
This limitation is in Ceph, which often uses newer kernel features to improve security and/or performance. I would not consider the solution quoted as a workaround, because the behavior in Ceph is intentional.

[This Ceph doc](http://docs.ceph.com/docs/master/rados/operations/crush-map/#which-client-versions-support-crush-tunables3) shows which kernel versions are supported by various versions of Ceph. According to these Ceph docs, Rook will support kernel versions 4.5 and later without needing to set crush tunables.

**Comment by galexrt** [comment]
Closing as question has been answered.
