### ISSUE TITLE
v0.9.0 binaries don't run on ARM64

### ISSUE THREAD

**Issue by jkowalski** [rook/rook#2406]
On ARM64:

```
$ uname -a
Linux kube-rpi3bp-01 4.9.80-hypriotos-v8 #1 SMP PREEMPT Thu Apr 26 17:51:07 UTC 2018 aarch64 GNU/Linux
```

the following commands fail:

```
$ docker run rook/ceph:v0.9.0
standard_init_linux.go:190: exec user process caused "no such file or directory"
$ docker run rook/ceph:v0.9.0@sha256:06738bd64a1d4143cefa7d9cec99dbdbe710872ffa5b5e15ffdf5a05858b7126
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

I verified that on the same ARM64 machine, other multi-arch images work fine.

For comparison, on AMD64 both of these work fine:

```
$ docker run rook/ceph:v0.9.0
Usage:
  rook [command]
...
$ docker run rook/ceph:v0.9.0@sha256:2405c3cdb1e10cdc4025b46e55b2e428d03d999f85fec9c1261eff0e40c374b5
Usage:
  rook [command]
...
```

BTW. I got the `sha256` IDs by examing manifest for `rook/ceph:v0.9.0` and it appears to have two platform-specific manifests, but there's something wrong with ARM64 version.

```
$ docker manifest inspect rook/ceph:v0.9.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1163,
         "digest": "sha256:2405c3cdb1e10cdc4025b46e55b2e428d03d999f85fec9c1261eff0e40c374b5",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1163,
         "digest": "sha256:06738bd64a1d4143cefa7d9cec99dbdbe710872ffa5b5e15ffdf5a05858b7126",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by jkowalski** [comment]
BTW I found some old images on docker hub - the last one that appears to be working is `rook/ceph:v0.7.0-146.gcd2b699`

```
$ docker run rook/ceph:v0.7.0-146.gcd2b699
Usage:
  rook [command]
...
```

But the next one after it does not:

```
$ docker run rook/ceph:v0.7.0-148.gcf5b605
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

**Comment by kfox1111** [comment]
Went and tried to use rook v0.9.0 on arm64 and hit the same issue today. Very interested in trying out 0.9.0 on my arm64 cluster.

**Comment by travisn** [comment]
@jkowalski @kfox1111 Could you confirm the following?
- If you use the image directly from the repo `rook/ceph-arm64` instead of relying on the manifest to pull the correct arch, do you see the same behavior? It would be helpful to rule out whether it's a manifest issue.
- Do you see this issue in v0.8.3? I'd be surprised if we haven't had any reports of this in the 0.8 release cycle.

@BlaineEXE The just from `v0.7.0-146.gcd2b699` to `v0.7.0-148.gcf5b605` that @jkowalski mentioned when he observed it stopped working was seven months ago when we changed the base image to centos. Could you take a look? However, I seem to recall that an arm issue was fixed before we released v0.8 and that we confirmed it was working then.

As part of the integration test efforts in the next release, I wonder if we could add an AWS Graviton instance to the mix.

**Comment by BlaineEXE** [comment]
The arm issue may be related to this PR which Seb and Erwan don't seem to be looking at despite my clarification and request for re-review: https://github.com/ceph/ceph-container/pull/1273

**Comment by jkowalski** [comment]
> @jkowalski @kfox1111 Could you confirm the following?
> 
> * If you use the image directly from the repo `rook/ceph-arm64` instead of relying on the manifest to pull the correct arch, do you see the same behavior? It would be helpful to rule out whether it's a manifest issue.

@travisn not sure what you mean - https://hub.docker.com/rook/ceph-arm64 is a 404

> * Do you see this issue in v0.8.3? I'd be surprised if we haven't had any reports of this in the 0.8 release cycle.

I haven't used rook until few days ago when I decided to try it on my multi-arch cluster (3 x amd64 + 6 x arm64)

**Comment by zdoherty** [comment]
On an arm64 machine, reproducing the error on the v0.9.0 release container and exporting the filesystem:
```
# uname -m
aarch64
# docker run -it --name=toexport rook/ceph:v0.9.0
standard_init_linux.go:207: exec user process caused "no such file or directory"
# docker export toexport > fs.tar
# tar -xOf fs.tar etc/os-release | head -n2
NAME="CentOS Linux"
VERSION="7 (Core)"
```

Checking the architectures of the bins/libs in the container:
```
# tar -xf fs.tar usr/bin/bash && file usr/bin/bash
usr/bin/bash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=765c505bb8a234fcd64ede405fa7fcb25734f06a, stripped
# tar -xf fs.tar usr/local/bin/rook && file usr/local/bin/rook
usr/local/bin/rook: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=eUK_Zy_PFLpvnCxGl0hW/H4RJ-ZN448IA0uz72S3j/qqiWvxB0mDm4NA7m-yBW/rpxqWnoX2S2ByqkheQjx, stripped
```

The rook binaries are the right architecture, but the base image isn't. The Dockerfile for the rook/ceph image is based off of `ceph/ceph:v13`, which supports multiple architectures, but my guess is the build server is amd64.

You'll still hit this issue running `docker build --platform=linux/arm64` with an amd64 builder, but on the build machine instead of when you run the container. It can't execute `RUN` commands in an arm64 container. I'm not too sure how easy ARM is to emulate.

Running the ARM build on a matching host should just work.

**Comment by kfox1111** [comment]
I was able to deploy an arm64 cluster yesterday with rook successfully. Thanks again for fixing this. :)

**Comment by BlaineEXE** [comment]
Thanks for the confirmation @kfox1111 :)
