### ISSUE TITLE
Modified crush maps support

### ISSUE THREAD

**Issue by Amos-85** [rook/rook#2514]
when creating a new tree in the crush map for ssd hosts and osd's the state doesn't saved after restart osd deployments.

support it as an advanced topic for rook deployments will be appreciated.

@travisn has commitment in rook slack channel to support it.

**Comment by ssube** [comment]
The device classes appear to be usable with the current version of rook, provided that the block pool uses a custom crush_rule (where rook will not reset the class). The rule only needs to differ on the class:

```
rule home-rust {                      
        id 3                          
        type replicated               
        min_size 1                    
        max_size 10                   
        step take home                
        step choose firstn 0 type osd 
        step emit                     
}                                     
rule home-rust-class {                
        id 4                          
        type replicated               
        min_size 1                    
        max_size 10                   
        step take home class hdd      
        step choose firstn 0 type osd 
        step emit                     
}                                     
```

Then `ceph osd pool set home-rust crush_rule home-rust-class` will associate the pool (all run from the toolbox). This method seems to survive operator restarts, although I have not tested it across pool CRD updates.

**Comment by unsubtleguy** [comment]
Adding a question/ I just got bitten by this :laughing: : 

Under https://github.com/rook/rook/blob/master/Documentation/advanced-configuration.md#separate-storage-groups it doesn't warn users regarding this behaviour - and OSDs will be re-added to the crush-root rather than any modifications.

Should a warning be added for the interim to the documentation?

**Comment by drakonstein** [comment]
Since Luminous it has been against recommended guidelines to use multiple CRUSH roots as opposed to using device classes for CRUSH placement rules.  The above documentation should be replaced with instructions for device classes and creating CRUSH rules to utilize them.

However, more to the point of this ticket, there is a ceph.conf option osd_crush_update_on_start that is required to set to false if you are using additional roots to manage things like this.  That said, only pre-luminous clusters should use multiple roots and this option while Luminous and later clusters should be using device classes and CRUSH rules.
