### ISSUE TITLE
[ceph] having ceph-mgr with a replica of 2 (with node anti-affinity) is not working

### ISSUE THREAD

**Issue by rsd35410** [rook/rook#2538]
I'm using rook v0.9 and I can't succeed to have the 'ceph' dashboard pod with a replica of 2 (and node anti-affinity) in order to always have the GUI available in case of a node become down.

I'm using the Helm chart for deploying the "Ceph Operator": https://rook.io/docs/rook/v0.9/helm-operator.html
I'm also using the rook cluster deployment explain here: https://rook.io/docs/rook/v0.9/ceph-quickstart.html#create-a-rook-cluster

When I tried to edit/change the replica of the "rook-ceph-mgr-a" deployment, two "rook-ceph-mgr-a" pod are creating, but the access of the ceph dashboard always return an error after login.

What is the correct way to achieve "ceph dashboard" deployement with a replica of 2 ?

Thanks

**Comment by galexrt** [comment]
@rsd35410 Currently Rook Ceph only runs one MGR Pod/instance due to previous issues with some modules, so it is not supported to scale up the service manually right now.

There is/was an issue to look into running more than one Ceph MGR though right now, it is not seen as a priority as Kubernetes will in normal cluster reschedule a Pod from a failed node in around 5m and 40s.

**Comment by galexrt** [comment]
As you want to have more than one MGR running, I'm going to close this in favor of #1796. #1796 is looking into running (at least) two MGRs.
