### ISSUE TITLE
min_size calculation is wrong 

### ISSUE THREAD

**Issue by ramkiperiy** [rook/rook#2543]
**RFE Request**
Rook always creates ceph pools with min_size value 1 irrespective of whatever the replica size.

The min_size should be calculated based on the replica size.
i.e. min_size = ceiling(size - (size/2))

**Comment by noahdesu** [comment]
+1 to choosing a good default. since this is directly related to tolerance and risk choices it might be a good candidate for exposing through the crd. being configurable could also be useful for development environments (e.g. its the choice in vstart)

**Comment by leseb** [comment]
Why don't we just let Ceph's default? And then use the toolbox to tune that if necessary? I'm personally not a big fan of exposing anything and everything in the CRD.

**Comment by noahdesu** [comment]
It looks like at least in the latest version of Ceph a value of 0 will default to the min-min/2 default.

**Comment by travisn** [comment]
So rook would need to set min_size to 0 in order to get the default min-min/2? I do tend to agree with @leseb that Ceph should be picking the default here and advanced users can run a ceph command to change it.

**Comment by noahdesu** [comment]
it looks like in luminous/mimic/nautilus, the default that ceph will use is:

```
default pool size = 3
default min size = 3 - (3/2) = 2
```

this means that for a simple dev cluster with 1 osd, I/O will be blocked using _only_ defaults on the rook side. this doesn't currently happen because rook appears to change these defaults in `pkg/operator/ceph/config/defaults.go` to:

```
osd pool default size     = 1
osd pool default min size = 1
```

it seems like we should (1) remove these default and use the ceph defaults and (2) create (if they do not already exist) a clear demarcation of `xxx.yaml` files in the examples directory that default for testing and for production. the testing variants can simply use the standard ceph configuration override mechanism or explicitly set the size of a pool in the pool crd.

Can someone quickly explain what `DefaultLegacyConfigs` is in `https://github.com/rook/rook/blob/master/pkg/operator/ceph/config/defaults.go#L84` that is settings the `default [min ]size = 1`?

**Comment by travisn** [comment]
Ah, that's where the default of 1 comes from. The replication size is required in the pool yaml, and we have separate [test](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/pool-test.yaml#L13) and [production](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/pool.yaml#L17) example yamls, which seems sufficient. So we can just remove these default settings, right? 

The DefaultLegacyConfigs should be fine if we remove these defaults since it would only affect new pools created. @BlaineEXE could provide more context on that implementation though.

**Comment by leseb** [comment]
Again, yes, please let's not enforce/set `min size` in any way. Just let Ceph do it and the dev/admin change it if necessary.

**Comment by galexrt** [comment]
We still need this if it hasn't been implemented yet.

@leseb do you know if has this already been implemented in a config rework / improvement PR?

**Comment by agaoglu** [comment]
@leseb I'd suggest the same (letting ceph handle the min_size) for EC pools if that's possible. Currently it's [set](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/pool.go#L236) to data chunk count and even if we change it to something else, it's reset the next time operator runs. We've already got bitten by it once.

**Comment by travisn** [comment]
Agreed rook just shouldn't set the min size so Ceph can set its calculated default and it can be overridden by the admin as needed. I was thinking we removed it a while back, but looks like it's still there: `OsdPoolDefaultMinSize:  1`

**Comment by leseb** [comment]
Closing for #4638
