### ISSUE TITLE
Ceph CSI feature parity: StorageClass

### ISSUE THREAD

**Issue by rootfs** [rook/rook#2650]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

New CSI StorageClass that is compatible with existing Rook Block/File StorageClass. Rook operator can have its own provisioner that is able to resolve Pool and Filesystem CRD in StorageClass.

**To do**:
- [ ] Support for different metadata and data pools in RBD StorageClass (#3763)

**Comment by lbogdan** [comment]
I'm a bit confused of how would that work, though. Will rook provision PVs backed by RBD images (which it already does, for `StorageClass`es with `provisioner: ceph.rook.io/block`, so will it also do it for `provisioner: csi-rbdplugin`? If yes, how would you tell the CSI RBD provisioner to ignore those? Or you wouldn't run the CSI RBD provisioner at all?), instead of the ceph CSI plugin?

**Comment by rootfs** [comment]
@lbogdan see #2729

**Comment by travisn** [comment]
I believe this is already done with the automation of mons in the ceph-csi storage class.

**Comment by lbogdan** [comment]
I'd argue the feature parity is incomplete, as you still can't define a `StorageClass` having different metadata and data pools using the CSI provisioner, see https://github.com/ceph/ceph-csi/issues/199 .

**Comment by travisn** [comment]
@lbogdan Agreed that the feature parity is not there yet. Would you mind opening a new ticket for that specific issue? Having a general ticket like this is too hard to track the remaining work.

**Comment by lbogdan** [comment]
@travisn Isn't this a https://github.com/ceph/ceph-csi issue, though? I guess I'm a bit confused as to how the responsibilities for the rook ceph CSI plugin are distributed.

**Comment by travisn** [comment]
Right, this is a ceph-csi feature to implement, though a new feature in ceph-csi will need some integration work with rook in order to be made available. Typically this would be an update to the example yaml and documentation. So there will be a corresponding change in rook to track with the csi feature.

**Comment by lbogdan** [comment]
Added #3763 and updated this PR's description with a to-do list.
