### ISSUE TITLE
Ability to specify ceph version

### ISSUE THREAD

**Issue by firaxis** [rook/rook#2686]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
You should be able to specify ceph version to deploy

**What is use case behind this feature:**
If you are using some sort of centralized log storage, your docker shouldn't produce output in stdout/json-file, so ceph-detect fails to determine ceph version,  e.g.

> E | op-cluster: unknown ceph major version. failed to extract ceph version. failed to parse version from: Error response from daemon: configured logging driver does not support reading

**Environment**:
I'm using graylog, and docker is being executed with "--log-driver=gelf", so I get an error like above.
Previously, I've used rook v0.8, and used next spec, so it worked. But it is not working with v0.9
> spec:
>   cephVersion:
>     image: ceph/ceph:v12
>     name: luminous

It will be great if you can bring back ability to specify ceph version in case of ceph-detect output can't be caught.
Thanks.

**Comment by BlaineEXE** [comment]
It would be helpful if you could show the output of what `ceph version` and `ceph -v` are for the Ceph that you are running. We'd like to be able to support things we haven't yet seen.

**Comment by firaxis** [comment]
> [root@rook-ceph-tools /]# ceph -v
> ceph version 12.2.7 (3ec878d1e53e1aeb47a9f619c49d9e7c0aa384d5) luminous (stable)
> [root@rook-ceph-tools /]# ceph version
> ceph version 12.2.7 (3ec878d1e53e1aeb47a9f619c49d9e7c0aa384d5) luminous (stable)

The issue is that rook-ceph-detect-version container doesn't produce output, because it's sent to graylog. So rook can't detect the version.

**Comment by BlaineEXE** [comment]
@travisn I want to make sure my answer here is correct, but I believe there will be many more issues with Rook if output is not sent to `stdout`. Rook uses `stdout` from running Ceph commands to interact with the Ceph cluster.

**Comment by travisn** [comment]
The difference in this case is that the operator starts another pod, then looks at the pod's output. I don't believe we have other cases where this pattern is followed. Everywhere else, we're capturing the stdout from starting a process, rather than a pod.

**Comment by BlaineEXE** [comment]
It seems like a pattern that we might want to reuse in the future. If Rook can't get stdout, how else could it get the output of running a command in a container?

**Comment by BlaineEXE** [comment]
^ Perhaps using `kubectl exec ...` functionality is the right way to do this? We could start a deployment or a job (or deployment?) with a long sleep command (five minutes?), and `kubectl exec <the deployment's container> -- ceph version` to get the version, and then delete the deployment?

**Comment by travisn** [comment]
Since the creation of the operator, I've been trying to avoid `kubectl exec` because it feels ssh-like and non-k8s-native. However, I can't think of another way to accomplish this either. It would also require a rule to be added to the rbac for `pods/exec`, which would be preferable to avoid.

**Comment by BlaineEXE** [comment]
> It would also require a rule to be added to the rbac for pods/exec, which would be preferable to avoid.
Agreed.

I do have one more thought, but I'm not sure if it will actually work. I considered that we might be able to create an empty configmap key and mount it read-write into the container and do `ceph version > /my/ceph/version/result/file.txt`. The operator could read the configmap afterwards assuming that writing to the configmap file in the container would make changes to the configmap in kubernetes.

Further looking suggests this is a bad idea...
- Might require setting a feature gate: https://github.com/kubernetes/kubernetes/issues/62099#issuecomment-378770047
- Might be problematic https://github.com/kubernetes/kubernetes/issues/62099

I wonder if it's standard for log aggregators like Graylog and Fluentd to prevent the container from outputting to `stdout`. It seems to me like preventing output to `stdout` would be a poor decision, but I don't have enough context around this really.

**Comment by BlaineEXE** [comment]
Looking at the Kubernetes docs for jobs, I don't find an indication that the stdout is intended to be used for communicating data. The k8s doc below suggests a work queue using RabbitMQ or something similar to send work items *to* the jobs. I presume that the reader is expected to assume that the same thing should be used to get information *from* jobs, but I can only guess.

https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/

**Comment by phlogistonjohn** [comment]
Two (wacky) thoughts:
1. Instead of going in for the heavyweight approach of setting up a message queue, perhaps the pod could run a single-url http server that exports the output of `ceph --version`. Once rook has queried the pod it can tear it down (or perhaps a job could still be used... just have the binary self-terminate after some timeout)
2. If the needed check is more binary (apologies, I have only skimmed the code), the spec could specify version requirements that would be checked by a liveness / readiness probe. If the probe fails then rook will know the image lacked the required ceph version(s).

I also am happy to hear that rook doesn't rely on exec'ing commands. In Heketi we've seen some scalability and performance issues related to that mechanism. If it does become something rook uses I'd suggest keeping it to a minimum as possible.

**Comment by leseb** [comment]
Can't we simply inspect the container image instead? We do trust our builds, don't we?

We currently have this in our Ceph images:

```
"CEPH_VERSION=mimic",
"CEPH_POINT_RELEASE=-13.2.2"
```

We could easily enhance this if needed.

The only caveat is that this wouldn't work for people using other images or a different build mechanism than the one provided by https://github.com/ceph/ceph-container.
In the end, Ceph images provided by https://github.com/ceph/ceph-container are "trusted" images by the Ceph team. If someone wants to build a custom image they can/should use the build system from ceph-container.

This approach might sound less robust and puts a lot of confidence in our builds, but the builds have been running quite decently for months now.

Thoughts?

**Comment by leseb** [comment]
More thoughts, since this is not affecting everyone perhaps the image inspection could be used as a best effort instead of primary detection. If the detection fails then we try to inspect the image.

**Comment by travisn** [comment]
@leseb Are you saying to use a `docker inspect` command to look at the version instead of running `ceph version`? That does seem reasonable to expect those image properties. However, I'm not seeing how this would help the problem where the operator needs to start a job and collect the logs to get the output, since the logs may not be available. Or are you saying the operator could inspect the image remotely without running a job?

**Comment by leseb** [comment]
@travisn Yes, I'm suggesting to use something similar to `docker inspect` (if docker is being used or the equivalent for other runtimes) but I'd think there is a lib for this in k8s that can inspect for us without caring about the container runtime :). I'm suggesting to do this as a fallback option in case the ceph version we return is empty.

I guess what my suggestion fixes is the current issue, not the broader problem with logs being eaten by any syslog/graylog/centralized logs.

**Comment by BlaineEXE** [comment]
@phlogistonjohn 
> * Instead of going in for the heavyweight approach of setting up a message queue, perhaps the pod could run a single-url http server that exports the output of `ceph --version`. Once rook has queried the pod it can tear it down (or perhaps a job could still be used... just have the binary self-terminate after some timeout)

This idea seems like it might be feasible and a reasonable amount of effort and complexity, even if still more complex than ideal. Thank you for the input about scaling performance with `exec`s.

I would like to solve the general "centralized logs" case all in one go when we go in for this fix. I'd rather not rely on the `CEPH_VERSION` env var being available not because we don't trust our `ceph/ceph` builds but because I think it's important to allow users to use custom containers if they want to without getting gotcha'ed by not having the env var present in their build.

**Comment by travisn** [comment]
@leseb If docker inspect worked without needing to pull an image, it would be ideal, but since docker inspect requires pulling the image I'm not seeing how it would help.

Another approach is modeled after our OSD daemons, credit to @BlaineEXE . I believe it would solve all the issues around this. The "version detect" job will be run with two containers.
1. The first container will copy the `rook` binary to an EmptyDir volume mount
1. The second container will then:
   - The same volume is mounted that would give access to the `rook` binary
   - Launch the ceph/ceph image, but the command would be `rook ceph version`
   - rook would execute a process for `ceph version` (or even simpler if we can read the env vars `CEPH_POINT_RELEASE` and `CEPH_VERSION`). 
   - The stdout from `ceph version` would be captured and saved in a configmap
1. The operator would read the version from the configmap

**Comment by noahdesu** [comment]
@travisn this is probably obvious to everyone but me, but is this 3 step 2 container process for getting the ceph version a means to avoid stdout being eaten by docker logging?

The use of `exec` does seem quite attractive. It appears (in this specific instance) to be no less antithetical to k8s-native-purity than container inspection, and the mechanism would also be general enough to handle scenarios in which operational decisions depend on knowing which binary versions are running in a container rather than simply which version is configured in the crd, though if such scenarios exist/may exist I'm not sure.

**Comment by dsavineau** [comment]
> @leseb If docker inspect worked without needing to pull an image, it would be ideal, but since docker inspect requires pulling the image I'm not seeing how it would help.

@travisn maybe I'm out of context there but did you consider to use skopeo [1] instead of docker in order to inspect container images remotely ?

[1] https://github.com/containers/skopeo

**Comment by travisn** [comment]
To summarize some separate discussion:
- Need investigation to know if there is any way to not have the logs be removed from the pods by graylog, or other tools. This seems broken if it changes the k8s behavior of logs being available.
- If we do make a change, we should keep it simple and not so involved change as my [earlier comments](https://github.com/rook/rook/issues/2686#issuecomment-470378105). Even better if we could inspect an image remotely to get the environment variables declared in the image for the version info. Or at least to do this in a k8s-native way rather than adding another dependency. @dsavineau I haven't looked at skopeo to see if that's a possibility.

**Comment by BlaineEXE** [comment]
@travisn and @firaxis, my k8s sysadmin friend says
> the ideal there is that you run the command like so; `command | tee > /var/log/file-for-greylog.log` so the logs show up in both places for both use cases.

**Comment by leseb** [comment]
@BlaineEXE I don't think we need the `>` but anyway. So IIUC, we execute something like `ceph version | tee ceph_version.txt` and then we read the `ceph_version.txt`'s content? But at this point, the container stopped so how do we retrieve the content of this file?
I have the impression I'm missing something...

However, this complicates things a little bit since we now log inside the container too so we would have to implement log rotation etc... not ideal IMHO. That's why if we go with the `tee` option then let's just do it for this use case.

**Comment by BlaineEXE** [comment]
@leseb that's not how I interpreted it. From my understanding: The believe the root issue is that stdout is being sent to graylog in the user's environment, which is problematic, because we expect stdout to exist. What should be happening is that graylog collect logs for applications via `tee` so that it doesn't clobber stdout.

**Comment by leseb** [comment]
It seems not everyone is on the same page :).

@firaxis how was graylog setup? My understanding was that it replaced the logging mechanism of the container runtime. This means that for instance the journal log engine of Docker is not journald anymore but graylog. In that case, any logs from the container (stdout/stderr) are swallowed by graylog thus not visible if you request the container logs (because they can't be read/served from graylog).

@BlaineEXE the latter was my understanding.

Typically, graylog would have to configured to watch and read logs from the containers BUT keep intact the default container log engine (journald). With that you avoid all the problems.

**Comment by firaxis** [comment]
@leseb the kubernetes cluster being deployed by kubespray, where I specify docker_log_opts, e.g.
> docker_log_opts: "--log-driver=gelf --log-level=warn --log-opt=env=kube --log-opt=gelf-address=udp://graylog.instance:12220 --log-opt=labels=kube --log-opt=tag=kube"

And it comes to systemd drop-in into Environment=DOCKER_OPTS=bla-bla
So, yes, any logs are being redirected to graylog.
> $ docker logs 180fd5aa852e
Error response from daemon: configured logging driver does not support reading

It's a docker configuration, and yes, it's possible to collect logs from syslog, but I can't say it's a convenient way. I'll have to deploy and configure additional daemon at each k8s node.

**Comment by leseb** [comment]
Based on all the answers above, I believe the image inspection is still a valid fallback in case we can not get anything from the logs, as the best effort. I haven't found anything in Kubernetes to help us doing this so I guess @dsavineau option with podman is nice. That means however including the podman binary in our image...

**Comment by BlaineEXE** [comment]
I think that image inspection isn't a very robust solution, and it also involves including the podman binary. I would sooner implement the store-version-into-configmap solution which would fix any problems and not rely on the presence of tags or a specific tag format on the image.

**Comment by leseb** [comment]
@BlaineEXE I thought we were against the configmap solution because it'll require more RBAC?

**Comment by BlaineEXE** [comment]
I know we were against the `exec` solution because it would require more RBAC. If we use the `rook-ceph-system` role for the version job, then no extra permissions would be required to use the configmap. If that role can't be used, I think we might want to create a job role that would have configmap get/create/update permissions. The operator already has all these configmap permissions, so I don't *think* either option is any worse that what exists currently.

**Comment by yanchicago** [comment]
Will this issue be resolved in the upcoming 1.0?

**Comment by leseb** [comment]
@yanchicago no.
