### ISSUE TITLE
Add CRD sample yamls to clarify usage 

### ISSUE THREAD

**Issue by travisn** [rook/rook#2700]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The sample files under `cluster/examples/kubernetes/ceph` currently cause confusion and user error in the following ways:
- Only a single example is provided for most CRDs even though there are many use cases
- The examples are tedious to read with the comments that explain all the possible settings
- The examples are only for test environments, for example with replication of 1, or where mons can be on the same node

To improve this structure, the suggestion is as follows:
- Separate out the RBAC settings in the yaml from the basic operator deployment and cluster CRD. The RBAC is largely independent from the operator and cluster crd settings. This will allow us to create multiple samples without copying the rbac everywhere. For example, we would now have `operator-rbac.yaml` and `cluster-rbac.yaml`.
- Multiple operator samples can be created:
  - `operator.yaml`: The most common operator settings
  - `operator-openshift.yaml`: The operator that works by default on openshift
  - `operator-with-csi.yaml`: The operator that allows for early testing of the csi driver (until fully - 
- Cluster CRD samples could include:
  - `cluster.yaml`: The basic settings for a production-level cluster. Replication 3, mons on different nodes, etc.
  - `cluster-test.yaml`: The basic settings for a single-node (minikube) cluster. Replication 1, single mon, etc
  - `cluster-minimal.yaml`: A cluster than only starts a single mon and mgr. Other daemons can be started later, such as through the ceph dashboard that drives updates to the cluster crd
  - `cluster-nautilus.yaml`: Test cluster that runs the currently unsupported nautilus image
  - `cluster-specific-devices.yaml`: Shows how to specify nodes and devices by name 
  - `cluster-nvme.yaml`: Shows that you would want multiple osds per device for high performance nvme
  - `cluster-metadata-device.yaml`: Shows how to specify a metadata device
  - And so on... 
- Multiple pool examples. Object and file could also follow this pattern since they have similar pool settings.
  - `pool.yaml`: Production example with replication 3
  - `pool-test.yaml`: Test example with replication 1
  - `pool-ec.yaml`: Erasure coding example
- Docs would need to indicate to install the operator-rbac.yaml and cluster-rbac.yaml as new steps, so a basic cluster would be 4 steps instead of 2. 
- Docs would be updated to point to the new samples.

**Comment by leseb** [comment]
One thing that bugged the first time I looked at `cluster.yaml` is the amount of pre-requisite user don't care about. For instance, if we take https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-minimal.yaml, which is supposed to represent a minimum cluster then all of that https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-minimal.yaml#L1-L155 does not represent the cluster. The cluster itself is only ~17 lines.

I agree with you, we should hide these role/rolebinding etc things from the user as much as possible and only let them describe what is necessary (cluster related things).

I'm thinking of writing a tool for this that will generate cluster YAML files based on user's input.

Thoughts?

ps: I'd rename `cluster-nautilus.yaml` to `cluster-ceph-dev.yaml` maybe so that we don't pin a specific version of Ceph?
Overall the proposition looks good.

**Comment by travisn** [comment]
Helm charts would generally be the way to approach simplifying the settings, but if you already have a tool, it would certainly be useful to share.
