### ISSUE TITLE
Set dynamic number of mons based on node count

### ISSUE THREAD

**Issue by travisn** [rook/rook#2740]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The desired number of mons could change depending on the number of nodes in a cluster. For example, three mons would be the min number of mons in a production cluster with at least three nodes. If there are five or more nodes, the number of mons could increase to five in order to increase the failure tolerance to two nodes.

This could be accomplished by settings in the cluster CRD:
```yaml
  mon:
    count: 3
    preferredCount: 5
```

If the number of hosts drops below the preferred count, the operator would reduce the quorum size to the smaller desired count.

Increasing and decreasing the number of mons is already implemented in the quorum health check, so it is only a matter of teaching it to understand the preferred count.

**Comment by leseb** [comment]
I'm not sure it's necessary to introduce a new variable for this, it might confuse users. IMHO we could try to solve that without user's input. Also, I believe the operator should do what we believe is the right thing to do.
I can see there is a use case, I'm just not sure it's realistic and we have ways to improve that without asking users. I believe one added value to the proposal is to not edit the `count` if the platform grows?

They are not so many cases to handle in the end:

* if `count: 1` do nothing
* if `count: 3` do nothing, do your best.
* if `count: 5` do your best to keep 5 mons, if we lose one, drop to 3 and log this in the operator. Once we can re-establish the desired 5 mons, scale up to 5 again, log in the operator.
* if `count: 7`, hum should we refuse that?

**Comment by travisn** [comment]
While we want to do everything automatically we can in the operator, the CRD is where we need to expose some flexibility in what state the admin desires. In this case, the admin might desire a different number of mons depending on his tolerance for loss. It's the solutions built around rook that will understand the requirements and set the CRD settings appropriately. 

Originally in the crd we didn't expose the mon count and tried to set it automatically. Then users requested the ability to make it explicit, so it was added.

**Comment by noahdesu** [comment]
Exposing a configuration setting for the number of monitors (i.e. `count`) makes total sense, but I tend to resonate with the comment by @leseb that `preferredCount` may not be required. Perhaps I'm not understanding the requirement exactly, but for me the source of misunderstanding stems from this statement:

> If the number of hosts drops below the preferred count, the operator would reduce the quorum size to the smaller desired count.

In a cluster where it makes sense to have `count=5`, if node failures occur such that 2 monitor pods cannot be scheduled (e.g. given the constraint of one monitor per physical node) then why dynamically change Ceph's view of having a new `count=3` monitors (which is how I'm interpreting the statement `the operator would reduce the quorum size`)? Operating with 3 out of 5 in this case, until the hardware can be replaced / fixed, would seem to be the _exact_ use case of having Paxos in the first place.

**Comment by travisn** [comment]
In your example, the operator would be making things more stable by reducing the quorum to 3... If you have 5 mons and 2 are offline, you cannot tolerate any more mons going down. If the operator then removes the 2 offline mons and reduces the quorum size to 3, then the cluster would be able to tolerate another mon going down. When the nodes are repaired or replaced, then the operator could increase the quorum size again to 5. Any holes in that approach? 

I'm thinking the default value for `preferredCount` should be `count + 2`. The operator would just take care of the mons, automatically growing and shrinking as the node count allows. We wouldn't need to surface the preferredCount in the yaml examples either, but we could document it for users who want to override the behavior.

**Comment by noahdesu** [comment]
I don't see any reason why the scenario you're describing would be problematic from a correctness point of view in isolation, and indeed the failure tolerance benefit is compelling. The issue I'm trying to surface for discussion (or maybe just my education) is that even though the operator can respond instantaneously where a person may be delayed in their response, the same underlying decisions exist. And replacing humans with machines makes me nervous :)

Generally my thinking is that a person can observe that one or more machines has actually failed and either replace the hardware then, or in 3 days... _or_ perform the reconfiguration we are discussing. However, I'm getting fever dreams thinking about how the operator is subject to the same exact set of issues that could cause a monitor to be removed from the quorum in the first place, like a network partition. Since k8s and ceph are co-located, this is a bit like asking why ceph's paxos cluster can't reconfigure itself?

In any case, a more practical concern might just be using very conservative timeouts for this type of configuration change.

> We wouldn't need to surface the preferredCount in the yaml examples either, but we could document it for users who want to override the behavior.

Ahh, that's a good idea and makes sense!

**Comment by leseb** [comment]
Glad to read that we are not going to add another option in the CRD :).
