### ISSUE TITLE
Takeover existing cluster

### ISSUE THREAD

**Issue by hunter** [rook/rook#278]
I'm not sure if you want feature requests at this stage of development but in testing out the recent releases, it would be useful to have some way to take over an existing Ceph cluster.

Some background: I deployed 0.1.1 on a dev environment that was running ceph-docker. The containers were running Jewel with `hostnetwork` and a single OSD pod running per node. After stopping the existing containers, I launched rook following the demo examples and pointing to the existing OSD FileStore device on each node. Rook formatted the devices with BlueStore and started the cluster. I wasn't sure if it would use the existing OSD data, error out or reformat.

Not sure how feasible it would be to check for existing OSD devices (in FileStore since BlueStore already seems to be detected) and import the existing `/var/lib/ceph` monmap, osdmap, etc and generate the required etcd and `/var/lib/rook` data along with any re-symlinking.

**Comment by travisn** [comment]
Rook doesn't currently have plans to support an upgrade path for existing ceph clusters. The thought is that clusters could support a migration of the block, file, or object through a data path. Trying to pick up on the cluster configuration would be a monumental task with all of ceph's knobs and dials and custom configurations out there. Approaching this one from a data migration instead of a config migration seems like the way to go.

**Comment by travisn** [comment]
closing this as a non-goal for now, though we will definitely keep it in mind
