### ISSUE TITLE
support for installing rook using helm

### ISSUE THREAD

**Issue by bassam** [rook/rook#284]
We should make `helm install rook` possible

**Comment by hunter** [comment]
I had started on a helm chart earlier. It's not really close to usable yet but thought I'd commit early for discussion...

https://github.com/AcalephStorage/charts/tree/rook/incubator/rook

**Comment by bassam** [comment]
@hunter nice. would be great if you can get some form of this up in a PR.

**Comment by bassam** [comment]
I dont believe this is needed anymore. We're pursuing deep integration with Kuberentes through TPRs and operator.

**Comment by hunter** [comment]
There is some use for still having a helm chart. Helm currently supports upgrading TPRs (which won't land in K8s until 1.6) but really the benefit is encapsulating the resources and configuration. For example, etcd-operator has a chart - https://github.com/kubernetes/charts/tree/master/stable/etcd-operator

If I get some time in the next week I'll see if I can update the old chart I had to support the new operator.

**Comment by luxas** [comment]
This would be awesome to have.

/cc

**Comment by hunter** [comment]
I've updated the chart I had to use the new operator, still located here: https://github.com/AcalephStorage/charts/tree/rook/incubator/rook

I've not had a chance to test it yet so unsure if it works

**Comment by bzub** [comment]
Cool @hunter, I might be able to give it a spin later today.

**Comment by bzub** [comment]
Sorry for the delay.  The chart doesn't install because there's some ordering that's needed to deploy rook-operator.  The rook-operator pod has to spin up first and create the ThirdPartyResource before rook-cluster.yaml's `rook.io/v1beta1` API is recognized as valid.

Even when I added the annotation to make the Cluster resource a "post-install" hook, I still got this error:
```
Error: apiVersion "rook.io/v1beta1" in rook/templates/rook-cluster.yaml is not available
```

So, I think a Job resource or something needs to block the install until rook-operator has created the TPR.  I haven't investigated this much at all yet.  Maybe the etcd-operator chart has clues.

**Comment by kzap** [comment]
no updates on this?

**Comment by hunter** [comment]
@kzap I've raised a new PR for the Operator - #688.

More work needed on a chart for the Clusters

**Comment by jbw976** [comment]
We have helm support in Rook now.

**Comment by kminehart** [comment]
Question for you guys:

Any reason you're hosting your own charts repo instead of merging this chart into github.com/kubernetes/charts ?

**Comment by bassam** [comment]
@kminehart we eventually would like to publish to the official charts repo. A few things that motivated our own repo initially, 1) we can rev it quicker, 2) we can support different release channels (master, alpha, beta and stable).
