### ISSUE TITLE
Support multiple tolerations for all pods on rook-ceph deployment

### ISSUE THREAD

**Issue by yan636** [rook/rook#2896]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Looked at the code, it seems only one toleration can be specified for all rook-ceph pods ( rook v0.9.3 ). If not, please clarify.

**What is use case behind this feature:**

We need rook to be deployed on a node with several taints. Note "Toleration for all taints" is not an option for us. 

"worker-01": {
    ...
    "node_taints": ["key_1=value_1:NoExecute", "key_2=value_2:NoExecute"],
    ...
}

**Environment**:

**Comment by invidian** [comment]
That should actually be very simply to do. I'd add new environmental variable `AGENT_TOLERATIONS` which would have YAML array of tolerations. Then in Go code simply unmarshal it and append to spec.

**Comment by yanchicago** [comment]
Thanks for quick action. Could you specify the user interface/configuration? Also could you please enhance it for other pods as well: operator, mgr, mon, osd, detect, rgw?

**Comment by invidian** [comment]
>Thanks for quick action. Could you specify the user interface/configuration?

What do you mean?

>Also could you please enhance it for other pods as well: operator, mgr, mon, osd, detect, rgw?

- For operator, it's already possible.
- Detect and agent nodes are covered by my patch.
- mgr, mon and ost, are supported from cluster CRD
- I'm not sure about rgw, but it seems it also supports `placement` configuration, so I'd expect to support tolerations as well.

**Comment by nabokihms** [comment]
@invidian has great idea to make config map with operator settings and mount it to operator pod.

Seems good. @BlaineEXE @galexrt I can prepare the PR, if it's all right.

**Comment by BlaineEXE** [comment]
I would counter propose that the agent and discover options added to the operator CRD rather than a ConfigMap unless there are known reasons why a config map would be preferable. @travisn ?

**Comment by BlaineEXE** [comment]
Related: #3238

**Comment by invidian** [comment]
@BlaineEXE what CRD exactly you talk about here? Would you like to create CRD for Discovery and Agents then?

**Comment by nabokihms** [comment]
A think there is no reason to create additional crd for agents and discovers. It leads us to billions of crd in future.

We can describe agents and discovers settings in Cluster CRD. Seems good for me.

**Comment by invidian** [comment]
IIUC, agents and discovers are scheduled by the operator. There is no need to create Cluster CRD to get those deployments running. Would Cluster CRD change those deployments then? If so, maybe they shouldn't be created at all until at least one Cluster object is created?

(I'm just trying to understand where would it be placed and why)

**Comment by nabokihms** [comment]
Steps:
* Describe New crd format
* Deploy the crd
* Deploy the operator
* Operator wait for crd with settings in rook namespace
* Operator deploy agents and descovers

**Comment by nabokihms** [comment]
If steps ok, I will work on it.

**Comment by invidian** [comment]
What would be the benefit of CRD over ConfigMap? I think watching, validation etc can be done already with ConfigMap? Structure validation with kube apiserver then?

**Comment by travisn** [comment]
I don't see a CRD as needed for the operator. If we have settings that indicate the overall behavior of the operator, the settings should be available when the operator is launched. There are several ways I'm thinking this could be improved:
- A configmap could be defined that contains all of the operator settings. It would be created before the operator (as part of operator.yaml). 
- If the settings are updated, the operator could ideally watch for the configmap changes so that an operator restart is not necessary.
- By some convention, the settings in the configmap could map to the env var settings currently defined, so that we could have backward compatibility. This could be similar to rook's mapping of [command line options to env vars](https://github.com/rook/rook/blob/master/pkg/util/flags/flags.go#L93) when launching rook pods.
- We need documentation around these settings. All we currently have is the comments in operator.yaml

But we should track this as a separate issue, since #2985 already takes care of the original description of this issue.

**Comment by nabokihms** [comment]
#2985 cover my case. Thanks to @invidian. I created the issue about config map for future.

**Comment by BlaineEXE** [comment]
Travis' comment here is really important I think and this is the largest reason **not** to use a configmap, and I think this reason is quite good. I'm against using a configmap if there are other options available.
> If we have settings that indicate the overall behavior of the operator, the settings should be available when the operator is launched.

I spent some time looking at the etcd and Prometheus operators, and I think the way Prometheus does it makes sense. https://github.com/coreos/prometheus-operator/blob/master/example/non-rbac/prometheus-operator.yaml 

The operator itself is configured using commandline flags. And the way Rook is written, may parts of it can use flags and environment variables as inputs (e.g., `--my-flag` is the same as `MY_FLAG`). The benefits of using commandline flags is that it becomes easy to do input sanitization before running the operator for invalid inputs, which is something we might not be doing now.

**Comment by BlaineEXE** [comment]
Travis brought something up in today's huddle meeting that I thought was a good idea: since we are moving toward a 1-operator-1-cluster model for Rook-Ceph, I think it makes sense to include the discover daemon and agent in the cluster CRD.

On a similar note, I've been noticing that our CRD is acting as a passthrough for a lot of Kubernetes configurations. Tolerations, affinities, anti-affinities, and a new PR for priorities. Every time we have to add handling for the new type. I am wondering if it's possible for us to use the k8s public API to automatically parse and apply things like this, even as new options appear in Kubernetes. This seems like it really might be a stretch, but we might consider changing our approach to make sure it continues to be easily exentsible for us to add new types.

**Comment by BlaineEXE** [comment]
Also, @nabokihms and @invidian I really appreciate your help tracking the issues related to the larger topic here and your patience while we talk about the best way to proceed in Rook. I'd like to see multiple-toleration support done and ready in Rook v1.1 if possible.
