### ISSUE TITLE
Is rook robust enough againt a container escape?

### ISSUE THREAD

**Issue by jimmyjones2** [rook/rook#2969]
It's great that rook now support encrypted ceph volumes, but does it protect against enough of the realistic threats to cluster?

From my understanding of ceph (which is almost certainly incomplete) all the mon pods will know all the decryption keys, and each OSD pods will know its own. In addition all the mon pods will know the shared secrets for cephx authentication. 

Therefore if there is a container escape (0-days for Linux privesc [retail at ~$50k](https://zerodium.com/program.html)) on a node running mon, the attacker will be able to read any volume. If the escape is on a node not running mon, they'll have access to any volume that is hosted by the OSD running on that node. In addition, they'll have access to all volumes used by pods on that node (however I think this is unavoidable).

If the above is correct, would it be possible to support client side encryption? Then access to mon or OSD would not give you access to the data, a container escape on a node would only give you access to volumes used by pods on that node.

**Comment by travisn** [comment]
@liewegas What are the thoughts on Ceph support for client-side encryption? I'm not aware of it today.

**Comment by liewegas** [comment]
In openstack there is some support for this via cinder/nova and (i think) barbican for key management.  Basically it's just dm-crypt layered in at the side side with some automation to make it transparent.

At a high level this seems like it would be pretty straightforward for RWO RBD PVs, since there is already some generic kubelet infra that is laying down the file system, and/or some ceph-csi infra to set up dm-crypt on the mapped rbd before mounting.  Kubernetes/etcd could also be used for storing the secrets for those client volumes.

For cephfs it's a bit harder.  There is something called ecryptfs that adds a layer of encryption over any linux file system.  I'm not sure if anybody has tried it over cephfs, but in theory it should all Just Work.  Not sure what performance looks like in this case.

We've never seen a mon (or osd) issue that would enable escape into the container.  But I would expect to see one in the osd before in the mon, and the osd won't have access to other osds' keys.  Also, it's worth nothing that with a single osd you won't have access to full volumes, just the objects stored by that one osd, which will be generally be r/nths of all volumes in the pool (if there are n osds and replication factor of r).

**Comment by jimmyjones2** [comment]
For block devices, I agree it would make sense to do it at the kubelet level, so all block types could benefit from encryption. The added benefit of secrets in etcd is lots of effort has already been put into protecting that - only kubelets hosting the relevant pod are allowed to retrieve the secret and you've got various options for secret encryption with KMS.

I hadn't particularly focussed on vulnerabilities in mon or osd, but you make a good point. I was more thinking about there being a vulnerable webapp somewhere in the cluster that got compromised, then the attacker using a container escape (such as CVE-2016-5195, CVE-2017-5123, CVE-2019-5736) to then gain access to the mon/osd process if it happens to be co-located on the same node. Or just buy and use a 0-day Linux escape for $50k if the data is valuable enough.

I admit this could be me being a security geek and preaching about defence in depth etc, but some of the clients I've worked with would have concerns about this.

From a quick search, looks as if Gluster supports [client side encryption](https://github.com/gluster/glusterfs-specs/blob/master/done/GlusterFS%203.5/Disk%20Encryption.md), maybe this is something that is best implemented by Ceph?

**Comment by jimmyjones2** [comment]
This is still an issue

**Comment by travisn** [comment]
@humblec @ShyamsundarR @Madhu-1 Is client-side encryption in the csi driver a possibility?

**Comment by Madhu-1** [comment]
@travisn there is a  design doc in [1] and WIP PR in [2]  for the rbd block device encryption with LUKS

[1] https://github.com/ceph/ceph-csi/pull/448
[2] https://github.com/ceph/ceph-csi/pull/697

**Comment by Madhu-1** [comment]
ceph/ceph-csi#697 is merged in  master and  expected to be in release v2.0.0, but it is available for testing  if someone wants to test it out

**Comment by travisn** [comment]
Closing since CSI v2.0.0 is released per @Madhu-1 's comment with the client-side encryption being available.

**Comment by jimmyjones2** [comment]
@travisn I don't feel this is resolved - there is currently a single password per storageclass so some of the above risks are not mitigated, see https://github.com/ceph/ceph-csi/pull/448#issuecomment-586452360

**Comment by travisn** [comment]
@jimmyjones2 How about if a different issue is opened for each area of concern? It's difficult to track if an issue is completed if it involves multiple areas. For example, I see questions in the areas of the CSI driver, mons, and OSDs. 

Regarding the mons and osds, I'm not following how the volumes would be compromised if there is a container escape to the mons or osds. The data in a pool is spread across virtually all OSDs.
