### ISSUE TITLE
stable and reliable kubernetes environment

### ISSUE THREAD

**Issue by jbw976** [rook/rook#299]
There are many options for how we bring up a kubernetes environment for development and testing, we are currently using a fork of coreos-kuberentes: https://github.com/rook/coreos-kubernetes/tree/rook-demo

There are other options too, such as kops, kubeadm, etc.

We should work on getting a stable and reliable kubernetes environment.

**Comment by jbw976** [comment]
We'll see if coreos-kubernetes reliability is improved since @travisn just merged from upstream to our fork, which picked up 1.5.1.

**Comment by jbw976** [comment]
Using the beta channel for coreos-kubernetes and rook v0.2.2 has felt fairly stable today.
https://github.com/rook/coreos-kubernetes/commit/e30b3ed5a5e210c47db1f9228620de0741f19d32
https://github.com/rook/rook/releases/tag/v0.2.2

We may be able to just keep using coreos-kubernetes instead of making more investments in this milestone.  We should update this ticket if anyone sees any issues with running the config from above.

**Comment by bassam** [comment]
The path I'm considering is to start with bootkube and change it as follows:

- use rkt instead of docker
- support for parallels desktop (minor)
- run k8s master components on all nodes (i.e. remove label master)
- use etcd-operator by default
- run in HA mode all the time
- add support for calico 
- add support for multiple networks

**Comment by kokhang** [comment]
Some updates:

**BootKube:**
Deployed multi-node cluster using bootkube and using the self-host-kubelet flag. The deployment succeeded and did not see @bassam's bug (https://github.com/kubernetes-incubator/bootkube/issues/251). This might have been fixed by removing the `nsenter` code and using the --containerized flag in kubelet.

Everything was self hosted except for etcd. There is an on-going work to get that self-hosted as well. https://github.com/kubernetes-incubator/bootkube/issues/284

** Kubeadm: **
Deployed a multi node kubernetes cluster on ubuntu machines using kubeadm successfully. Last friday, the self-hosted kubernetes feature got merged and i started trying it (https://github.com/kubernetes/kubernetes/pull/40075).

The initial bootstrapping worked and i got kube-api, control manager and scheduler self-hosted. However, when i tried to join a node to the cluster, it was failing with certificate issues.
`[csr] Created API client to obtain unique certificate for this node, generating keys and certificate signing request
failed to request signed certificate from the API server [cannot create certificate signing request: the server could not find the requested resource]`
This issue happens because the certificate signing API of kubernetes was moved to Beta. Here is where is being tracked. https://github.com/kubernetes/kubernetes/pull/39638.

I will create a custom build of kubeadm and cherry-pick the above PR and see how it goes.

**Comment by kokhang** [comment]
**Update from SIG meeting**
kubeadm at head will not work now until it is promoted to beta. A lot of its dependencies have moved to beta (certificate signing,  etc) and kubeadm only works with alpha dependencies. It would be a month from now until 1.6 releases which will have beta kubeadm.

Meeting nodes from the SIG meeting:
_The Certificates API went beta => v1.5 kubeadm can’t join new clusters, kubeadm at HEAD can’t join v1.5 clusters
[mikedanese] The contract with alpha features... semi-major bugs in 2 cases. Decided that alpha features are not upgradeable; clusters running alpha features are not upgradeable.
TODO: email out to devel users group.
When we release 1.6 kubeadm it will be work with 1.6 kubernetes.
We are doing stabilization work, bringing dependent APIs to beta
_
