### ISSUE TITLE
Ceph: Recognise osd when reattached to a different machine/place.

### ISSUE THREAD

**Issue by rohantmp** [rook/rook#3095]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Recognize an osd by the content on the disk.
**What is use case behind this feature:**

A machine/node goes down, but its disk is reattached to another node and rook/ceph handles it automatically. This would be useful if a node is reprovisioned using the cluster-api.

**Environment**:

AWS: This could be useful with osds on ebs volumes being attached to new ec2 instances
Baremetal: The node is reprovisioned with the content of the disks intact.

**Comment by rohantmp** [comment]
@liewegas I'm assuming this will require changes in ceph. Is RADOS where I should create an issue?

**Comment by travisn** [comment]
@rohantmp This will work in theory already. Since Rook is using `ceph-volume` to provision the OSDs it is expected that it will recognize the existing OSD even if the device is moved to another node as in this scenario. Did you test this out and observe that it did not work? If so, do you have logs from the osd prepare job on the node where you expected the OSD to be recognized?

**Comment by rohantmp** [comment]
Oh sorry, I thought this was not yet implemented.
