### ISSUE TITLE
Ceph Nautilus does not use msgr2 protocol if port is 6790 after upgrade from 0.9.3 to 1.0.0

### ISSUE THREAD

**Issue by sinqinc** [rook/rook#3104]
Bug Report

After upgrade from Rook 0.9.3 to 1.0.0 Ceph complain that monitors can't use msgr2 protocol.

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2079.3.0
VERSION_ID=2079.3.0
BUILD_ID=2019-04-22-2119
PRETTY_NAME="Container Linux by CoreOS 2079.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

* Kernel (e.g. `uname -a`):
Linux coreos201 4.19.34-coreos #1 SMP Mon Apr 22 20:32:34 -00 2019 x86_64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration:
CloudSigma
* Rook version (use `rook version` inside of a Rook Pod):
1.0.0
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
RKE (Rancher)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
2019-05-03 02:57:32.538 7f8a0f7fe700 -1 --2- 10.42.0.0:0/345491633 >> v2:10.43.180.58:6790/0 conn(0x7f8a10155690 0x7f8a10153670 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=1 rx=0 tx=0)._handle_peer_banner peer v2:10.43.180.58:6790/0 is using msgr V1 protocol
HEALTH_WARN 3 monitors have not enabled msgr2

**Comment by sinqinc** [comment]
According to http://docs.ceph.com/docs/master/rados/operations/health-checks/?highlight=backfillfull%20ratio

If a monitor is configured to listen for v1 connections on a non-standard port (not 6789), then the monmap will need to be modified manually.

**Comment by travisn** [comment]
I also just repro'd this when upgrading from 0.9 to 1.0, then from mimic to nautilus. This upgrade scenario was tested, but missed the health warning after the upgrades.
```
[root@minikube /]# ceph -s
  cluster:
    id:     b02807da-986a-40b0-ab7a-fa57582b1e4f
    health: HEALTH_WARN
            3 monitors have not enabled msgr2
    ...  
```

**Comment by travisn** [comment]
To enable msgr2 and clear up this health warning, per discussion on #3051 it looks like we need to first failover the mons in order to get them onto the default msgr1 port. We will need to add manual steps to the upgrade guide if/until we get it automated.
@leseb @liewegas any other suggestions to workaround the default port issue after upgrade?

For each of the mons running on the non-default port (all of the mons running previous to Rook v1.0):
1. Cause the mon to fail by setting the replicas on the mon deployment to zero. For example, if your mon is named mon-a:
```kubectl -n rook-ceph edit deploy rook-ceph-mon-a```
1. Find the line with `replicas: 1`, change it to `replicas: 0`, then save and exit the editor
1. Wait for 5-10 minutes for the operator to fail over the mon. You will see messages in the operator log that the mon is down and will be failed over after a timeout.
1. After the timeout, a new mon will be started and the old mon deployment will be automatically removed
1. Confirm in the toolbox that all mons are in quorum: `ceph status`
1. Repeat steps 1-5 for each of the old mons
1. After all the mons are updated, if you still see the health warning run the following in the toolbox: ```ceph mon enable-msgr2```

**Comment by conet** [comment]
@travisn are you sure that the above steps work? I ran them for one mon and it fails to join the quorum list after step 4, probably because it tries to connect to the old mons using the new `6789` port while they are still using `6790`, any ideas how to get around this?

**Comment by conet** [comment]
I figured it out by adding both `6790` and `6789` to the service definitions during this process.

**Comment by travisn** [comment]
@conet I don't see why it would be necessary to add both ports to the service definition. When the new mons start they will be listening on 6789, while the old mons will be listening on 6790. I would expect that these single ports on their respective services would be sufficient. A couple other users also verified the original steps worked for them, but I must be missing something.

**Comment by sinqinc** [comment]
@conet did you replace all mon deployment?

**Comment by conet** [comment]
@travisn I think the explanation for why I needed to manually add the `6789` port to the old mon service definitions so that the new mon would join the quorum is that, contrary to [your guide](https://github.com/rook/rook/pull/3145/files#diff-3de4d43beba101be122197d34b432653R268) I was already running Nautilus. So it might be a good idea to mention this case. As I said, running Nautilus with mons on `6790` gave me the warning `3 monitors have not enabled msgr2` which made me run the failover procedure you described. Once the first mon was recreated it would not join quorum because it was trying to access the other mon services on port `6789` (they were still on `6790`) once I edited their service definitions and added an extra `6789` -> `6789` port mapping it managed to join quorum then I was able to proceed. @sinqinc after that I managed to replace all mon deployments.
