### ISSUE TITLE
Rook allows mounting ReadWriteMany rook-block volumes

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3200]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When creating a ReadWriteMany PVC for rook-block volume, it successfully starts

**Expected behavior:**
Give an error saying it can only be used by a single pod at a time

**How to reproduce it (minimal and precise):**
Create a PVC with ReadWriteMany mode

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.0
* Kubernetes version (use `kubectl version`):
1.14.1

**Comment by tombarron** [comment]
Is this a *raw* block volume [1] ? Since k8s 1.13 raw block volumes which have no filesystem on them are supported.  These can be "mounted" RWX  -- there is no filesystem and it's up to the users to access them by offset rather than POSIX path and to coordinate among themselves to avoid corruption and races.  Admittedly this is different than the general purpose RWX access supported by NFS, GlusterFS, CephFS, Manila, etc. where there is a POSIX filesystem and it's safe to use it from multiple mounts on multiple worker nodes by apps that do not coordinate except in the normal way (write in my own spots on the filesystem).

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support

**Comment by dimm0** [comment]
I'm talking about the ceph RBD devices, which can only be written to by a single client, and get corrupted on simultaneous writes

**Comment by dimm0** [comment]
Fixed in csi
