### ISSUE TITLE
Rook should properly clean up when CRs and/or operator are deleted

### ISSUE THREAD

**Issue by JohnStrunk** [rook/rook#3222]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When the CRs managed by rook are removed either by deleting them specifically or by deleting their containing namespace (which may also contain the rook operator), rook should properly clean up persistent state.
- The devices used should have LVM info removed so that they can be used again by rook/ceph or another application
- Persistent state on nodes (e.g. /var/lib/rook, /etc/ceph, etc.) should be deleted so that rook/ceph can be re-installed without manual intervention

**What is use case behind this feature:**
Currently, there is significant manual cleanup required if rook is uninstalled, leading to a poor user experience. Particularly in environments where Rook is deployed via OLM, it is expected that the operator and associated resources should install/uninstall with ease.

**Environment**:

**Comment by leseb** [comment]
I think having a purge been triggered when the CR goes away is really risky.

**Comment by travisn** [comment]
Agreed on the riskiness of doing it automatically. Instead of an automatic purge, I'm thinking it would be a job that the user would need to be triggered separately. The admin would have to very consciously create the purge job. For example: `kubectl create -f purge-ceph-persistent-data.yaml`. 
1. If the operator or CRDs still exist, abort
1. The yaml would take as input the `dataDirHostPath` and node labels to filter on.
1. Start a job on each node
   1. Purge the dataDirHostPath if it exists
   1. Clean up all devices with ceph LVs 

Alternatively if the admin really really wants things purged when a CRD is deleted, the operator could trigger this job when a CRD is deleted that has a property such as `reallyReallyPurgeDataWhenCRDIsDeleted: true`. The operator would need to wait for the daemons to be removed before starting the job. This also assumes the operator isn't removed at the same time as the CRD.

**Comment by travisn** [comment]
Reopening until implementation is complete instead of just the design
