### ISSUE TITLE
Need to allow setting multiple tolerations, affinities, and anti-affinities for all resources

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#3238]
**Is this a bug report or feature request?**
* Bug Report

Rook should allow setting multiple tolerations, affinities, anti-affinities, priorities, etc. for all daemons. This includes `discover` and `rook-ceph-agent` as well as the Ceph daemons.

https://github.com/rook/rook/pull/2985 has an environment-variable-based solution to the issue, but I believe we should support this use case using the operator CRD, as the existing env var pattern Rook uses is pretty hacky.

I consider this a bug, because it seems obvious that users need to support multiple taints/affinities for all resources Rook creates, and we don't currently do this.

**Comment by laevilgenius** [comment]
Csi daemons also need this. AFAIK, currently there is no mechanism to set tolerations and affinities for them.

**Comment by travisn** [comment]
@laevilgenius Could you open a new issue for the CSI driver? This issue is really about finding a better way to expose the configuration than the env settings, but it's not clear at least to me how to do that since we don't have an operator crd.

**Comment by travisn** [comment]
Here is a thought on how we might approach this. It is still a bit hacky, but it allows for full specs for tolerations/affinity/anti-affinity to be specified... If we agree on this, no need to open a separate issue for the csi driver to implement the existing env vars hack.

The flex agent and csi drivers are delayed starting until the first cephcluster CR is created. At that point, the `startSystemDaemons()` method is called so that they can be started. 

The CephCluster already has a `placement` for the ceph daemons, under which there is a daemon name such as mon, mgr, osd. We could look for the `agent` or `csi` as daemon names. The placement would be applied to the daemons according to that spec, which can have node affinity, pod affinity, pod anti-affinity, or tolerations. The CephCluster spec is already passed to the `startSystemDaemons()` so the pattern is already there.

The hacky part is if there are multiple ceph clusters. Only the first cluster would be used for the `placement` info for the csi and agent daemons. If their placement is specified in other cluster CRs it would be ignored. 

This does not help us with the discover daemon since it started immediately with the operator.
@BlaineEXE @laevilgenius wdyt?

**Comment by laevilgenius** [comment]
@travisn I didn't put much thought into it, but what if we create a separate CRD for partial pod template overriding? That would allow to change other things too, such as resources.
(Inspired by elasticsearch's [approach](https://github.com/elastic/cloud-on-k8s/blob/c523e1045c11283136193a6e1c87925d29d15eb4/config/samples/elasticsearch/elasticsearch.yaml#L17).)

**Comment by travisn** [comment]
@laevilgenius I see the `placement` in the cephcluster CR as very similar to the elasticsearch example since we aggregate that placement to the pod spec. 

I'm leaning towards using the existing cephcluster CR instead of creating a new CR for these reasons:
- There is only one CR per operator. What if they create multiple CRs in the same namespace as the cluster? We're back to the problem of multiple CRs
- Another CR would be one more step to setup the cluster. Though we could include it into the same cluster.yaml so it would at least be transparent to the user
- Majority of clusters won't need to set placement. The default CR would just be blank in the default case.

**Comment by BlaineEXE** [comment]
I have some scattered thoughts:

We have also talked about disabling the multi-cluster behavior in Rook. It's been a while though, and I'm not sure if  some of the rationale might have changed since then. But that could be a way to make the problem space a little simpler for us.

We have talked about the Ceph CSI drivers needing to not be duplicated if there are multiple Rook operators. Is this still an issue for us? If it is, we may still need to solve it, and at that point, I'm not sure we gain much from supporting the multi cluster use case. The flex drivers may be similar.

If we do keep the multi cluster functionality, I feel like the hacky part Travis mentioned makes it a not very good solution.

I think the discover daemonset could be one-per-ceph-cluster. I don't think it would have the possible interference issues that CSI & flex drivers might have if there were multiple discover pods on a host, but I'm not certain about that. Discover should only have read access to the host system, yes?

**Comment by laevilgenius** [comment]
@travisn I had in mind something more like [PodPreset](https://kubernetes.io/docs/concepts/workloads/pods/podpreset/), but with ability to override a pod template entirely. It can be seen as more advanced feature few users would use. I agree, though, that a multitude of such CRs would make a mess.

But if we don't keep the multi cluster functionality, then cephcluster CR is probably the way to go.

**Comment by invidian** [comment]
Not stale

**Comment by travisn** [comment]
- #4817 is the start to exposing the env vars on the operator with a configmap. This is also going to be done for other env vars so we have a complete solution. 
- Multiple tolerations are supported on all the daemons now. For example, [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L130-L137) is an example of the discover daemon and multiple tolerations.

@BlaineEXE Shall we close this issue?
