### ISSUE TITLE
ceph: PV created with 500M always in pending state

### ISSUE THREAD

**Issue by mmack** [rook/rook#3391]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Block device is never in ready state

**Expected behavior:**
PV should become ready

**How to reproduce it (minimal and precise):**
1. Create a PVC with "storage: **500M**"
2. wait until the end of the world. Ceph created the block device, but the PV is never getting ready.
3. Create another PVC with "storage: **500Mi**" and it works

rook version: rook-ceph-v1.0.0-143.g9b7eff4
os: coreos stable

**Comment by noahdesu** [comment]
I can confirm this is happening locally. I suspect it is a matter of a mismatched sizes during the binding process. Still trying to figure out how all that works.

**Comment by nabokihms** [comment]
https://github.com/rook/rook/issues/2922
Same problem here

**Comment by noahdesu** [comment]
thanks @nabokihms i was looking for that ticket. i think i know what's happening, so maybe we can get a fix in quickly.

**Comment by noahdesu** [comment]
I believe that the issue here is caused by rook's rounding of PV sizes.

`500M = 500,000,000 bytes`

however, when the PV is created after Rook adjusts the size, the quantity for the PV is

`quantity={i:{value:499122176 scale:0} = 499,122,176 bytes`

and according to the documentation on PV/PVC binding, the PVC will wait around for a sufficiently large PV.
