### ISSUE TITLE
Automate CRD changes propagation 

### ISSUE THREAD

**Issue by umangachapagain** [rook/rook#3860]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently, changing a CRD requires changes to be made at multiple places. It would be good to add some kind of automation that takes care of this. Also, we could add tests which notifies that CRD has been changed and is out of sync in one of these files. This could be added to CI.

**What is use case behind this feature:**
Makes changing of CRDs a smoother process and adds validation to notify users without any delay.

**Environment**:

**Comment by leseb** [comment]
I'm not sure I understand correctly, can you give an example? Thanks!

**Comment by umangachapagain** [comment]
If you look at https://github.com/rook/rook/pull/3788/files , it was a simple change to PrinterColumn which required manual changes to 4 different files. This is duplication of work and error prone if not aware of the files being affected. @travisn and I were discussing about the possibility of adding some kind of automation/templating to make this simpler or at least a test to notify that more changes are required without requiring one of us to come online and comment about it. 
What do you think?

**Comment by leseb** [comment]
Got it, I was discussing that with @travisn too, especially in the context of the CI.

**Comment by travisn** [comment]
The challenge here is that there are really different formats to take into account:
- Example manifests: We may have multiple example manifests with different settings depending on the scenario. For example, we have multiple examples of cluster.yaml. 
- Helm chart: Adds processing for inserting variables
- Integration tests: Needs to test different parameters

Ideally we would update a template in a single place, then the dev could run `make manifests` to generate the other locations that need to be updated. 

common.yaml is the logical place to start here since it doesn't really have settings that users need to adjust other than perhaps the namespace. But it's still not clear how we can really simplify the developer's life here without spending a crazy amount of time on a tool that generates all these different formats for us.

**Comment by umangachapagain** [comment]
Agreed that automating this is a much bigger problem than I thought. 

Maybe we should start with something simple like
> Ideally we would update a template in a single place, then the dev could run make manifests to generate the other locations that need to be updated.
>
But, there's another problem I see. How do we differentiate CRD changes vs Other changes (like name or namespace)? Maybe the make target should just `Suggest` the users that some files might need to be updated if intentional changes to CRD were made (with a diff of CRD files possibly?). This could probably be a part of Build Script.

**Comment by umangachapagain** [comment]
https://github.com/rook/rook/issues/3868#issuecomment-531908929
https://github.com/rook/rook/issues/3868#issuecomment-531912228

Looks like other resources also need similar checkpoint.
