### ISSUE TITLE
Publish CI container for release branch

### ISSUE THREAD

**Issue by champtar** [rook/rook#4002]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If all integration tests pass, publish the containers build by the CI also for release branch, not just for master

**What is use case behind this feature:**
I just wanted to pick up a fix without waiting for a new release
https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-3964/2/pipeline

**Comment by travisn** [comment]
@champtar the release builds for interim merges to the release branch will actually publish the images after the integration tests pass. If you're looking recently, we have been unlucky enough to be hit by about every random integration test failure, preventing any interim builds from being published. I've triggered the build to skip the integration tests and you should see new containers published in the next 20 minutes.

Due to the frequent CI issues there was some debate about when to publish the images. In `master` we ended up publishing the images before the integration tests, but in the `release` branches we still wanted to wait for integration tests to pass.

**Comment by champtar** [comment]
Hi @travisn, in the jenkins link everything is green but nothing was published it seems.
Does "Publish if Release" means publish if there is a tag or publish if it's from a release branch ?

**Comment by travisn** [comment]
Can you see the image now? Perhaps the view was out of date.
`rook/ceph:v1.1.1-31.g325131e`

**Comment by champtar** [comment]
I see it on dockerhub https://hub.docker.com/r/rook/ceph/tags?page=1&name=1.1.1
will try tomorrow, thanks

**Comment by travisn** [comment]
The release images should be there when the CI passes. Please let me know if you're not seeing this.
