### ISSUE TITLE
Helm chart optional crds

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#4037]
I have seen many cases where crd's and helm don't play well with each other. Having helm to manage the rest of the chart still makes a lot of sense. It allows easy overriding of images, resource requests, etc.

Please provide a value that can disable the management of crds in the helm chart.

**Comment by kfox1111** [comment]
kind of relevent kind of not. the crds need to be ported to work with helm3. helm3 has an option to skip crds. So maybe we skip this for helm2 and just make it a part of porting to helm3?

**Comment by kfox1111** [comment]
helm's been all over the place even after helm 3 with regards to CRD's. I'd be much more comfortable if CRD's were completely disable-able.

**Comment by travisn** [comment]
Due to the [Helm issues](https://github.com/helm/community/blob/f9e06c16d89ccea1bea77c01a6a96ae3b309f823/architecture/crds.md) of managing CRDs, I'm inclined to remove the CRDs from the helm chart completely. With the move to apiextensions v1 (see #6424), each release will likely have a schema update to the cluster CR for any new property that is added to the schema. Since Helm won't ever update the CRDs, we would anyway need a mechanism to update the CRDs in later updates to the helm chart.

Therefore, I propose the following:
- Remove CRDs from the helm chart
- Move the CRDs from `common.yaml` to a new file `crd.yaml`
- Helm installation flow would be:
   1. kubectl create -f crd.yaml
   2. Install the helm chart
   3. Create the CRs such as `cluster.yaml`, `pool.yaml`, etc
- Helm upgrade flow would be: `kubectl apply -f crd.yaml` and then update the helm chart for the new rook release
- Non-helm installation flow would add a new step:
   1. `kubectl create -f crd.yaml` # new step
   2. `kubectl create -f common.yaml -f operator.yaml`
- Non-helm upgrade flow would also add a new step for `kubectl apply -f crd.yaml` whenever there is a new property added (majority of releases, even patch releases)

While I am not excited about adding another step to install, this appears necessary for working with the Helm charts. During development, this also reduces the amount of duplication since the schema no longer needs to be updated in the helm chart.

@BlaineEXE @leseb @satoru-takeuchi @kfox1111 @invidian thoughts?

**Comment by BlaineEXE** [comment]
I think your analysis seems correct based on what I found when I was doing similar Helm research. It's unfortunate, but I think it makes sense for us.

An alternative is to start incrementing our CRD versions more often so that helm can deploy new CRD versions when we have them, but... I think that will be a gigantic development headache to support updating resources to new versions.

As an aside, even if the general consensus is that we should not do what Travis suggests, I think we should still consider having a `crd.yaml`. That can still simplify our update process in my opinion if you always `kubectl apply -f crd.yaml` for every install or update.

**Comment by BlaineEXE** [comment]
This topic is also possibly of interest to @shaas and @mgfritch

**Comment by invidian** [comment]
>@BlaineEXE @leseb @satoru-takeuchi @kfox1111 @invidian thoughts?

I think it would still be valuable to ship CRDs with the chart, so newcomers to rook have an easy way to try it out, just do `helm install` etc. Also for automation, if you wrap Helm charts with e.g. Terraform, having to run `kubectl apply` before or having to implement 2nd way of automating things isn't great. IMO it most likely end up with people maintaining their own copies of the charts.

I've seen some K8s operators update the CRDs themselves, so then user don't have to apply them manually before upgrading. Maybe that would be something to consider? Obviously that involves higher privileges for the operator, so there is some trade off here.

**Comment by BlaineEXE** [comment]
That is a good point that the operator can apply the new CRDs... I don't love it from a privileges standpoint. Is there a way to allow Rook to read/write only certain CRDs? I would feel okay about this strategy if that were the case.

**Comment by travisn** [comment]
@invidian Good point, there is still value in shipping the CRDs with the chart so the casual user can try it out more easily. Adding privileges for the operator to update them automatically is also tempting. Perhaps we can make it optional for the operator to create/update the CRDs automatically. If someone doesn't want to grant that privilege, they could turn it off. This just means the default settings would request the privilege to create/update CRDs. 

> That is a good point that the operator can apply the new CRDs... I don't love it from a privileges standpoint. Is there a way to allow Rook to read/write only certain CRDs? I would feel okay about this strategy if that were the case.

@BlaineEXE Since the CRDs are a cluster-wide resource, the privilege would be for any CRD, with no way to restrict it.

**Comment by travisn** [comment]
On a related note, the csi snapshotter sidecar 2.x required the privilege to create/update CRDs (RBAC created by rook [here](https://github.com/rook/rook/blob/release-1.4/cluster/examples/kubernetes/ceph/common.yaml#L1606-L1608)), but the 3.x snapshotter removed that privilege and requires the admin to create the snapshotter CRDs now as described in the rook docs [here](https://rook.github.io/docs/rook/v1.4/ceph-csi-snapshot.html).

**Comment by BlaineEXE** [comment]
I think it's probably safest to require the admin to create CRDs for Rook, even if it is a little more annoying. I think the snapshotter change is an indication this is the right path for us to follow.

**Comment by travisn** [comment]
@BlaineEXE Agreed, where I've landed on #6556 is that the CRDs will be installed by the admin and the operator will never automatically create or update them. The CRDs will be installed by the helm chart. During any upgrade of helm or non-helm installs, the admin will need to apply the updated CRDs.

**Comment by ml8mr** [comment]
> The CRDs will be installed by the helm chart. During any upgrade of helm or non-helm installs, the admin will need to apply the updated CRDs.

@travisn Are the CRDs you are removing from templates/resources.yaml going to remain with the chart? For example, in a /crds subdirectory? That would allow initial installs to consume the CRDs and leave them in a place admins could easily find them for an upgrade later on.

**Comment by travisn** [comment]
> > The CRDs will be installed by the helm chart. During any upgrade of helm or non-helm installs, the admin will need to apply the updated CRDs.
> 
> @travisn Are the CRDs you are removing from templates/resources.yaml going to remain with the chart? For example, in a /crds subdirectory? That would allow initial installs to consume the CRDs and leave them in a place admins could easily find them for an upgrade later on.

Yes, the CRDs will still be included with the chart in the /crds subdirectory. I understand that updating the helm chart will update the crds locally on disk, but they won't be applied to the cluster since they already exist. I am not sure where helm's local charts are extracted, but hopefully it's predictable. More on CRDs in helm [here](https://helm.sh/docs/topics/charts/#limitations-on-crds).

**Comment by ml8mr** [comment]
> I am not sure where helm's local charts are extracted, but hopefully it's predictable.

Yes, after pulling the chart locally, the workflow should include exporting to a local directory. By default, this is just a subdirectory which matches the chart name. The chart should be easy to install at that point (using a -f to point to local modifications).

Helm3 charts can contain any number of files which are not necessarily installed with the chart. Has there been a discussion around including the sample manifests in some kind of 'example' subdirectory? This would make these manifests easier to find, and would avoid the problem of keeping docs in sync. (For example, the snapshotter docs referenced above point to [this page](https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1#usage) which includes a bad link to the snapshot CRDs.)

**Comment by kfox1111** [comment]
you can pull the entire chart like:
```
helm pull rook/rook-ceph --untar
```
and it should show up under rook-ceph

**Comment by ml8mr** [comment]
> you can pull the entire chart like:
> 
> ```
> helm pull rook/rook-ceph --untar
> ```
> 
> and it should show up under rook-ceph (under the current directory where helm pull was executed)

That works for helm2 repos, but for [OCI-based registries](https://helm.sh/docs/topics/registries/), you have to manually export the chart after pulling it down. (The OCI approach is the only one which supports additional files, such as an example subdirectory.)

**Comment by kfox1111** [comment]
ah. true. I think that is three commands at present. one to enable oci, a second one to pull the chart, and a third to export it. There was talk about simplifying that at some point...

I thought extra directories were preserved in the tars. as you can pull them in from templates.

**Comment by travisn** [comment]
> Helm3 charts can contain any number of files which are not necessarily installed with the chart. Has there been a discussion around including the sample manifests in some kind of 'example' subdirectory? This would make these manifests easier to find, and would avoid the problem of keeping docs in sync. (For example, the snapshotter docs referenced above point to this page which includes a bad link to the snapshot CRDs.)

@ml8mr Makes sense to add the example subdir, we haven't discussed that. Want to open a new issue for that for follow up?

**Comment by ml8mr** [comment]
> @ml8mr Makes sense to add the example subdir, we haven't discussed that. Want to open a new issue for that for follow up?

Sure. That should be a dedicated discussion anyway.

**Comment by travisn** [comment]
@kfox1111 @ml8mr @invidian @BlaineEXE To follow up on the approach, we won't be able to move the CRDs from the `templates` to `crds` folder. In the upgrade path this is not supported and actually results in the CRDs being deleted and destroying the Rook cluster as I found in my testing [here](https://github.com/rook/rook/pull/6556#issuecomment-725051024). There is a lot of helm discussion and it may still change in the future, but see https://github.com/helm/helm/issues/8163 for more references on this history.
 
Therefore, for the helm3 converstion in #6556, we need to keep the CRDs in the `template` folder.

I also propose we not split out crds.yaml from common.yaml. During non-helm patch upgrades, we can just document to update common.yaml so that both the CRDs and the RBAC can be updated in patch releases now.

**Comment by kfox1111** [comment]
Hmm... I seem to remember there being an annotation you can set on objects to cause helm not to manage them further.

Perhaps there could be a period of time where templates/crds are kept but annotated as unmanaged. Then after some time, and a very stern warning in upgrade documentation to ensure one of those is upgraded through first, they get removed from templates and moved to the helm3 dir?

**Comment by kfox1111** [comment]
Back to my original request though, simply wrapping the CRD's in templates in an {{- if .Values.crds.enabled }} would help those of us not wanting to deploy them with helm to be able to not do so, so no other folks run into this issue.
The default can be true for backwards compatability and the install instructions can recommend setting it to false and loading the crds manually.

**Comment by travisn** [comment]
@kfox1111 Right, I'll add the option to disable the CRDs while I'm updating #6556.

**Comment by ml8mr** [comment]
@travisn Thanks for pointing out the interesting upstream discussions on this topic. Given those complexities, I think @kfox1111 suggestion would be helpful.

**Comment by BlaineEXE** [comment]
After a brief discussion, Travis and I think we should continue to have CRDs separated out into `crds.yaml`. While this is an extra bit of text to follow in the installation, this will help us with upgrades so that we can merely keep `crds.yaml` up to date and not have to worry about also keeping an `upgrade-from-vX.Y-crds.yaml` file. As a bonus, users like @kfox1111 will have the `crds.yaml` file to reference without having to separate the CRD content from other content in `common.yaml`.

**Comment by travisn** [comment]
@kfox1111 I want to make sure the crds are installed by default if the setting is not found in the values.yaml. Do you know the syntax? If the crds.enabled is not in values.yaml, I get an error that crds is nil. Or is it fair to just require the helm setting in values.yaml?

**Comment by kfox1111** [comment]
values.yaml inside the chart is essentially the defaults. If you set it in there, it should be overridable by the users with their own values files. If they don't override it, it comes from the charts values.yaml.

**Comment by travisn** [comment]
Ah right, will rely on the defaults inside the chart, thanks.

**Comment by ml8mr** [comment]
> If the crds.enabled is not in values.yaml, I get an error that crds is nil. Or is it fair to just require the helm setting in values.yaml?

Unfortunately, when you test for a key.value in a template, if the parent key (crds in this case) isn't defined, you encounter that nil error. In other words, values.yaml will have to contain crds.enabled=xxx.

**Comment by travisn** [comment]
Ok, final changes pushed to #6556.

**Comment by kfox1111** [comment]
https://helm.sh/docs/howto/charts_tips_and_tricks/ has a section:
"Tell Helm Not To Uninstall a Resource"
Should be like:
```
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
[...]
```

**Comment by kfox1111** [comment]
It should be safe to use even when helm's not used. so maybe we should just add it to crds.yaml?

**Comment by travisn** [comment]
For the casual user, it's helpful to keep the default behavior of uninstalling the CRDs. Or why would the casual user not want them uninstalled with the chart?

**Comment by kfox1111** [comment]
/me shrugs.

I'd take it the other way. I'd much rather it be a little messy and leave behind some crds, then risk accidentally destroying a valuable storage cluster by mistake.

Is installing rook-ceph, standing up a single cluster, then completely removing rook-ceph very common? is it something that adding an extra step of kubectl delete -f crds.yaml would be too onerous?

**Comment by travisn** [comment]
> /me shrugs.
> 
> I'd take it the other way. I'd much rather it be a little messy and leave behind some crds, then risk accidentally destroying a valuable storage cluster by mistake.
> 
> Is installing rook-ceph, standing up a single cluster, then completely removing rook-ceph very common? is it something that adding an extra step of kubectl delete -f crds.yaml would be too onerous?

Good point, anything to risk accidentally removing a production cluster. We anyway have an uninstall guide so one more step wouldn't cause a headache. I'll just keep #6556 as is, and we can consider that separately. Want to open a new issue?
