### ISSUE TITLE
mon failover

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#4126]
in rook 1.1.2 with hostnetworking true, I'm trying to force a failover of a mon. I made the mon unschedulable by unlabeling the node it was running on and killed the pod. the operator is not failing the mon to start a new one but waiting forever. there is still a quorum in the mons though.

**Comment by travisn** [comment]
@rajatsingh25aug Can you see if you can repro this? thanks

**Comment by rajatsingh25aug** [comment]
cc @kfox1111  @travisn 
Here's what I did.

So I drained a worker node on which a pod was running and apart from mon pods, i.e  `rook-ceph-crashcollector-ip-10-0-153-129-784b675f69` and `rook-ceph-mon-a-567bdbf85f`, all other pods got schedules to different nodes. 
I think the reason being for this is because not more than one MON is supposed to run on a specific node. And that is why the MON pod is in pending state and will wait until and unless there is no new worker node is found on which no MONs are running.

**Comment by kfox1111** [comment]
I believe the setup at the time was:
8 nodes
3 initially labeled for mons.
hostnetworking true.
I labeled an additional one of the 8 nodes with the mon label so it could be used. It did not contain a mon.
I then unlabeled one of the inital mon labeled nodes and deleted the mon from it.
The mon did not get recreated on the new node. active mon count stayed at 2.

**Comment by jmolmo** [comment]
@kfox1111 , it would be nice to have information about what happened in the moment that you have the pending mon pod. (basically the output of a kubectl describe pod command, and the operator log).
In any case it seems that something prevents to schedule the mon pod in any of the remaining nodes, as @rajatsingh25aug has stated, only one monitor can run in each node,  so there was theorically 6 other nodes where the monitor could be scheduled. Other possible reason could be that in the remaining nodes there wasn't enough resources to run a new pod.
Have you modified your "cluster.crd" with new placement setting for the monitors?. 
When you talk about labeling/unlabeling to place monitors, what is exactly what are you doing?, because by default is not needed to do any kind of labeling to distribute monitors.

**Comment by rajatsingh25aug** [comment]
@kfox1111 , try to describe the pod by `oc describe pod <podname>` and you can see the error of why it's in the pending state.
You can post the same error message here and then we can have a more precise idea of what happening.

cc @jmolmo

**Comment by kfox1111** [comment]
The cluster has not existed in this state since mid October. Its in production now so I can reproductive it at the moment. I filed an issue since I saw a problem. Sorry I can't debug it further.

When I looked, I could not see any reason for it to not failover. I believe that it did have enough resources to launch, but it didn't attempt to. This is trying to remember 3 months ago though. so please use the appropriate amount of salt. :)

I set a node label on nodes that could get mons via kubectl node label <nodename> mon=v1. Just to more carefully place the mons where I wanted them. I set the appropriate node selectors in the cluster custom resource.

**Comment by rajatsingh25aug** [comment]
> The cluster has not existed in this state since mid October. Its in production now so I can reproductive it at the moment. I filed an issue since I saw a problem. Sorry I can't debug it further.
> 
> When I looked, I could not see any reason for it to not failover. I believe that it did have enough resources to launch, but it didn't attempt to. This is trying to remember 3 months ago though. so please use the appropriate amount of salt. :)
>  I'm sorry but I didn't understand this, can you please explain a little?.
> I set a node label on nodes that could get mons via kubectl node label mon=v1. Just to more carefully place the mons where I wanted them. I set the appropriate node selectors in the cluster custom resource.

Do you want us to close this issue?.
Thanks

**Comment by kfox1111** [comment]
I filed it, as it was a bug I saw. Others may see it as well eventually if its not explored/fixed. I bothered to file an issue because I wanted to provide feedback on my experience to help fix the issue. You can ignore the feedback, and close the issue. But in my thinking, the underlying issue probably will remain.

**Comment by travisn** [comment]
I believe #4216 was actually the fix for this issue. The fix is in a v1.1 patch release and the v1.2 release since this issue was opened. But if we see a repro please do re-open.
