### ISSUE TITLE
rook edgefs vs ceph write performance

### ISSUE THREAD

**Issue by matti** [rook/rook#4140]
**Is this a bug report or feature request?**
* Bug Report (performance), continuing from #4111 

**Deviation from expected behavior:**

edgefs is significantly slower, see microbenchmark:

`time tar -xof linux-1.0.tar.gz`:

- rook+edgefs: 18s (3 replicas)
- rook+ceph: 0.6s (3 replicas)

and for completeness (c/p from #4111):

- AWS EFS (100mb/s provisioned): 28s
- elastifile.com (performance mode): 22s 
- rook+edgefs: 18s
- nfs server pod + EBS: 5s
- rook+ceph: 0.6s
- local disk: 0.3s

**Comment by mykaul** [comment]
@matti  - is there anything in Rook, or is it an EdgeFS issue (that might need to be filed there, not here?)
What are you using for Ceph? RBD or CephFS, btw?

**Comment by matti** [comment]
CephFS.

I'm not sure if it's EdgeFS only as I use both through Rook

**Comment by dimm0** [comment]
I saw the same... I was getting 6K IOPS on cephfs cluster, spinning drives + NVME journal, and maximum of 2K IOPS on edgefs, NVMEs only

**Comment by dyusupov** [comment]
@matti with relaxedDirUpdates: true, I reliably getting 6s (3 replicas) - this is still a safe option to use, can sustain data center power failure and gets us closer to EBS+NFS native performance. The local disk, as well as cephfs data points, are likely invalid as they both do heavy in-memory write-back caching, i.e. a bit different use cases.

@dimm0 it looks like a different issue (i.e. not single-threaded tarball extraction), we should move your issue over to https://github.com/Nexenta/edgefs. I appreciate more details in there and thank you for your continuous support as usual!!!

**Comment by matti** [comment]
@dyusupov but... 6s is not a good result, it makes edgefs unusable for many scenarios.

**Comment by matti** [comment]
@dyusupov also, can you help me to find a better way to get a local data point that you would be happy with. My local usecase is single threaded tarball extraction.

**Comment by matti** [comment]
and could you share your entire setup, would be easier for me to replicate the same number. We had relaxed dir updates on and still got 18s, not 6s

**Comment by dyusupov** [comment]
@matti use EdgeFS iSCSI CSI PVs if you need a better local write cache and do not care about durability or multi-user access.

Alternatively, if you really need to stick to NFS for such scratch-pad like use case, you can further reduce this down to like 3s if you set --sync-put=1 option on the NFS holding bucket so that it will only need to store 1 replica synchronously and 2 would go asynchronously.

There is another unsafe option that will likely get you even closer to sub 1s. It has to be set on the edgefs target pod hosts where NFS gateway will be running. In /var/lib/edgefs/.etc/ccow/ccow.json tenant section set sync_put_commit_wait=0. This option only works with newer EdgeFS images >= 1.2.83 and enables memory-only commit for writes.

**Comment by matti** [comment]
I believe these options can not be tuned through the kubernetes rook operator.
