### ISSUE TITLE
OSD is keep getting crashing while running integration test

### ISSUE THREAD

**Issue by thotz** [rook/rook#4215]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
integration tests are timing out and hence failing because osd is not coming up.

**Expected behavior:**
integration test able to pass

**How to reproduce it (minimal and precise):**

- minikube start --vm-driver=none
- run `make test-integration` in the rook repo

**File(s) to submit**:

* stdout while running test (please note I have interrupted the test manually )
https://paste.fedoraproject.org/paste/Ek00kPQVlSRXFiJjVAMY0g

* Operator's logs, if necessary

https://paste.fedoraproject.org/paste/7f3dVcUCmYCBPHr-EtTEpA

* Crashing pod(s) logs, if necessary
debug 2019-10-29 10:35:58.290 7f5e7824adc0  0 set uid:gid to 167:167 (ceph:ceph)
debug 2019-10-29 10:35:58.290 7f5e7824adc0  0 ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable), process ceph-osd, pid 8516
debug 2019-10-29 10:35:58.290 7f5e7824adc0  0 pidfile_write: ignore empty --pid-file
debug 2019-10-29 10:35:58.353 7f5e7824adc0 -1 missing 'type' file and unable to infer osd type

* osd prepare minikube log
https://paste.fedoraproject.org/paste/M1OjzFnGbtvwZE~XiMgHFg

**Environment**:
* OS (e.g. from /etc/os-release): minikube(rhel 7)
* Kernel (e.g. `uname -a`): 3.10.0-957.21.3.el7.x86_64
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): master
* Storage backend version (e.g. for ceph do `ceph -v`): v14.2.4-20190917
* Kubernetes version (use `kubectl version`): client 1.15.0, server 1.16.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): minikube
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN Reduced data availability: 16 pgs inactive

Please note if I am running manually (not via integration test frame work) everything works(osd is coming up properly) fine in my set up.
 I have run integration test bit back on rook 0.9 version using the same environment

**Comment by travisn** [comment]
@thotz I believe this will actually be covered by #4205. As a workaround try removing [this line](https://github.com/rook/rook/blob/master/tests/framework/installer/installer.go#L85) that assumes you're running the tests from a mac.

**Comment by thotz** [comment]
My machine is rhel 7 box, not a mac

**Comment by egafford** [comment]
Issue #4205 affects any user of the integration tests who:
a) Is running the tests in a virtualized environment like Minikube and
b) Is _not_ running them on a Mac (where runtime.GOOS == "darwin")
So your Minikube on RHEL7 environment would hit that issue (I found it in my Minikube on Fedora30 env). Hopefully the fix for issue #4205 will resolve this, by setting the default base test directory to a safe value whether the kubernetes master is local or in a virtual machine.

In the meantime, as Travis suggested, modifying [this function](https://github.com/rook/rook/blob/master/tests/framework/installer/installer.go#L85) may clear this issue up for you. To do this, you should change the function to this, or to a logical equivalent:
func init() {
    createBaseTestDir = false
    baseTestDir = "/data"
}
If this doesn't fix your problem, you've run into another issue which we should investigate and resolve separately. Please let us know if that's the case.

**Comment by thotz** [comment]
@egafford: It worked thanks, hence closing the issue
