### ISSUE TITLE
Support iscsi Server CRD

### ISSUE THREAD

**Issue by woohhan** [rook/rook#4334]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
We have Rook-Ceph RBD for block storage with great scalability and durability. But the only problem is performance. If we do not care durability but care performance, using Ceph is not best idea. We have NFS Server CRD and I think we can offer iscsi server CRD too. 

**What is use case behind this feature:**
Kubevirt can use storage class in k8s. we can provision the root block storage for VM with rook-ceph or rook-nfs. We can add rook-iscsi CRD for this. It is simple like the rook-nfs CRD.

**Environment**:

**Comment by WoohyungHan** [comment]
If this is worth, I wish I could work on it. Thanks.

**Comment by dyusupov** [comment]
meanwhile, there is Rook EdgeFS support for iSCSI + CSI

**Comment by travisn** [comment]
@WoohyungHan Have you tested the performance on a pool with replication of 1 [instead of 3](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/pool.yaml#L17)? As long as the rbd kernel driver is available on the client, I would think this would be highest performance rather than adding iscsi. @dillaman, other perspective on iscsi?

**Comment by leseb** [comment]
The only thing I know is that containerizing iSCSI is hard, even though I did it here https://github.com/ceph/ceph-container and it's working. Also, configuring iSCSI gw from containers is not possible yet AFAIR because the gwcli client cannot do it from within a container. Things might (have?) certainly changed.

**Comment by WoohyungHan** [comment]
> @WoohyungHan Have you tested the performance on a pool with replication of 1 [instead of 3](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/pool.yaml#L17)? As long as the rbd kernel driver is available on the client, I would think this would be highest performance rather than adding iscsi. @dillaman, other perspective on iscsi?

@travisn I agree that rbd client would be higher performance rather than iscsi, and decreasing replication number can increase rbd performance. however, It still slow than raw device. Ceph has more write amplification to keep consistency object data with its metadata.

I believe that in the near future kubevirt will be the most popular VM orchestration framework, and using Ceph is enough in most of case. but If we do not care about durability but do care with performance we can just provision iscsi server with raw device. (like NFS)

**Comment by WoohyungHan** [comment]
> The only thing I know is that containerizing iSCSI is hard, even though I did it here https://github.com/ceph/ceph-container and it's working. Also, configuring iSCSI gw from containers is not possible yet AFAIR because the gwcli client cannot do it from within a container. Things might (have?) certainly changed.

@leseb Could you please explain what makes it hard? I think we can just provision iscsi target like nfs's case... or I underestimated it?

**Comment by dillaman** [comment]
> The only thing I know is that containerizing iSCSI is hard, even though I did it here https://github.com/ceph/ceph-container and it's working. Also, configuring iSCSI gw from containers is not possible yet AFAIR because the gwcli client cannot do it from within a container. Things might (have?) certainly changed.

Assuming you are using LIO, you actually cannot truly containerize it since it's a kernel-hosted iSCSI target. The only thing that Ceph iSCSI containerized was the support daemons for configuring the LIO configfs (pulls its config from the Ceph cluster and has a REST API) and tcmu-runner for bridging from LIO to librbd in userspace. Neither of these two things would apply to a LIO target that was serving out a local disk as an iSCSI LUN in a non-fault-tolerent way.

**Comment by WoohyungHan** [comment]
@dillaman If I understand correct, you are saying that we have an userspace nfs server(nfs-ganesha) but not for iscsi. So if we try to deploying iscsi server, it's not real 'containerized' because it is kernel-hosted server. am i right?

If so, Could you please explain what problem can be expected? and nevertheless how do you think about supporting iscsi deploying with rook? I think we can start like nfs case...

```yaml
# iscsi CRD
kind: IscsiServer
name: rook-iscsi-target
spec:
  dataPvc: {pvcName}
---
# storage class for consume iscsi server
kind: StorageClass
parameters:
  iscsiTargetName: rook-iscsi-target
```

**Comment by BlaineEXE** [comment]
I'm trying to understand this a bit more. Is this feature requesting that `rook/ceph` deploy an iSCSI server that connects to Ceph, or is it proposing creating a new `rook/iscsi` operator?

**Comment by leseb** [comment]
The intent is to deploy [ceph-iscsi-gateways](https://docs.ceph.com/en/mimic/rbd/iscsi-overview/).

**Comment by richardelling** [comment]
Unfortunately, ceph-iscsi-gateways requires kernel LIO, which makes it a bit unfriendly to implement generically. There are other userland iSCSI solutions well suited to containers, but they aren't ceph-iscsi-gateways. It would be cleaner to have rook/iscsi since it will bring along kernel dependencies.

**Comment by logan2211** [comment]
Maybe it would be possible to use a userland iscsi containers to expose an RBD block PV as a target?
