### ISSUE TITLE
rook ceph Operator failed to  create MDS pods

### ISSUE THREAD

**Issue by manavtidhan** [rook/rook#4440]
yes

**Is this a bug report or feature request?**
It is a Bug Report

**Deviation from expected behavior:**
yes
**Expected behavior:**
rook operator should create the mds pods as soon as filesystem.yaml is created
**How to reproduce it (minimal and precise):**

to create cephfs

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): RHEL7
* Kernel (e.g. `uname -a`): 3.10.0-957.1.3.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 14.2
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.14.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  Docker UCP
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] :(https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN

++++++++++++++++++++++++++++++++=

Filesystem.yaml

apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs-crd
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
  dataPools:
    - replicated:
        size: 1
  metadataServer:
    activeCount: 1
    activeStandby: true

+++++++++++++++++++++++++++++++++++

kubectl exec -it rook-ceph-tools-6488545f5b-gv442 ceph status -n rook-ceph
  cluster:
    id:     641ee880-a44e-4b81-b905-403e4b5b9b2a
    health: HEALTH_WARN
            crush map has legacy tunables (require firefly, min is hammer)

  services:
    mon: 3 daemons, quorum a,b,c (age 42h)
    mgr: a(active, since 12d)
    osd: 2 osds: 2 up (since 12d), 2 in (since 12d)

  data:
    pools:   1 pools, 100 pgs
    objects: 1.91k objects, 6.0 GiB
    usage:   16 GiB used, 84 GiB / 100 GiB avail
    pgs:     100 active+clean

  io:
    client:   67 KiB/s wr, 0 op/s rd, 1 op/s wr

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

kubectl get cephfilesystems.ceph.rook.io -n rook-ceph
NAME   MDSCOUNT   AGE
myfs   1          3h11m

++++++++++++++++++++++++++++++++++++++++++++++++++++
NO ERROR/LOGS SHOWING IN OPERATIOR POD

**Comment by travisn** [comment]
@manavtidhan Can you share the operator log? It should show why the filesystem was not created.

**Comment by manavtidhan** [comment]
Hi @travisn ..I don't know but its very strange that there is no single log for the event " kubectl create -f filesystem.yaml" in operator pod.

**Comment by manavtidhan** [comment]
but there is repeated logs in operator pod

op-cluster: device lists are equal. skipping orchestration

**Comment by sp98** [comment]
@manavtidhan can you please share the complete rook-ceph operator log here. That would help to debug the issue.

**Comment by manavtidhan** [comment]
[operator_log.txt](https://github.com/rook/rook/files/3938159/operator_log.txt)

**Comment by manavtidhan** [comment]
any solution please???

**Comment by travisn** [comment]
@manavtidhan The operator log is not complete. You could try restarting the operator (by deleting the operator pod) to get a fresh log. Sometimes that will also help get the operator going again in the small chance it was stuck on something else. After the restart, the log should also show something about processing the filesystem. There must be some error since it doesn't look like the filesystem pools were created either.

What version of rook are you running? Newer versions have changed some of that logging to debug-level so it won't fill the logs so much.

**Comment by manavtidhan** [comment]
@travisn curretly lot of apps are using the block storage from the rook-ceph block class so by restarting the operator pod can disrupt the rook-ceph storage ? or is it safe to restart the pod?.

version of Rook: 1.0.2

**Comment by travisn** [comment]
@manavtidhan The operator pod only creates/manages the cluster, but is not on the data path so it is safe to restart.

**Comment by manavtidhan** [comment]
[operator-log-latest-after-restart.txt](https://github.com/rook/rook/files/3943470/operator-log-latest-after-restart.txt)
@travisn - After restart the operator pod ..still there is no log created for filesystem.yaml and there is no mds pods as well.

**Comment by manavtidhan** [comment]
kubectl get pods -n rook-ceph
NAME                                  READY   STATUS    RESTARTS   AGE
prometheus-rook-prometheus-0          3/3     Running   578        17d
rook-ceph-agent-nrvdh                 1/1     Running   9          34d
rook-ceph-agent-xr2p2                 1/1     Running   22         53d
rook-ceph-mgr-a-7979578677-zj2vs      1/1     Running   1          17d
rook-ceph-mon-a-77ff455c55-hj2jv      1/1     Running   0          17d
rook-ceph-mon-b-65b9b59d99-5jz4w      1/1     Running   0          17d
rook-ceph-mon-c-557996b659-nvjw4      1/1     Running   0          17d
rook-ceph-operator-5dcd7646b6-s2s5d   1/1     Running   0          3h45m
rook-ceph-osd-0-76d4dc45df-fkj27      1/1     Running   0          17d
rook-ceph-osd-1-667b77678b-cvrjl      1/1     Running   1          17d
rook-ceph-tools-6488545f5b-gv442      1/1     Running   1          17d
rook-discover-dq6zx                   1/1     Running   83         34d
rook-discover-x9rls                   1/1     Running   26         

am i missing any required pods like csi-pods ???

**Comment by travisn** [comment]
From the log it appears there are two nodes that are not responding to starting osds:
```
2019-12-10 07:08:41.660185 I | op-osd: waiting on orchestration status update from 2 remaining nodes
```
That would be preventing the operator from continuing to configure the OSDs. Did those nodes ever complete? If you've removed those two nodes or we otherwise want to unblock the operator, you may need to delete a configmap manually that the operator is waiting for. The configmaps are named `rook-ceph-osd-<node>-status` and are just temporary state used while the operator is waiting for the osds to be configured.

**Comment by manavtidhan** [comment]
@travisn i have deleted the config maps and then also restart the operator . but there is no logs showing in operator log ....no effect on operator logs and no pods of mds when creating the filesystem.yaml.  One thing I wonder is there any CSI pods should be there?

[operator-log.txt](https://github.com/rook/rook/files/3953408/operator-log.txt)

**Comment by rmartinez3** [comment]
I was having issues of mds not being created as well. However my case was because I set resource limit for osd. 

`failed to create cluster in namespace storage. failed to start the osds. refuse to run the pod with 1024mb of ram, provide at least 2048mb`

That one issue caused the fs creation logic to not even start. 

Don't think its related to your issue but just some input.
