### ISSUE TITLE
kubernetes: add rook support to kubeadm

### ISSUE THREAD

**Issue by bassam** [rook/rook#453]
from @luxas:

I think we should focus on integrating rook with kubeadm (https://kubernetes.io/docs/getting-started-guides/kubeadm/), I expect kubeadm to be the base building block for most kubernetes deployments in the future (http://blog.kubernetes.io/2017/01/stronger-foundation-for-creating-and-managing-kubernetes-clusters.html)

Bare-metal is the perfect usage for rook IMO, of course we should try to solve the GKE issues as well, but they have the GCE Persistent Disk feature that works OOTB already, something we really miss on bare metal.

**Comment by luxas** [comment]
I've done rook manifests for this already and am working on a guide to set these things up end-to-end

Work in progress, you can follow it here: https://github.com/luxas/kubeadm-workshop

Rook-specific parts: https://github.com/luxas/kubeadm-workshop/tree/master/demos/storage/rook

What I had to change:
 - I had to add RBAC rules to the operator and make it run under a specific ServiceAccount.
 - I had to disable the `persistentvolume-binder` controller in controller-manager, create a new container image environment for the controller-manager that binds Ceph PersistentVolumes (something Rook relies on). Since the `persistentvolume-binder` controller exec's out to `rbd` _in the container_, and the controller-manager container is based on `busybox` where `rbd` is present, it's not possible to go with the official image for this task.
   - See: https://github.com/luxas/kubeadm-workshop/blob/master/images/storage-controller-manager/Makefile

I can contribute this work to the v0.4 release, no need to remove it from the milestone

**Comment by kokhang** [comment]
Hi @luxas, i am building a Rook volume plugin that will remove the dependency of `ceph-tools` (https://github.com/rook/rook/issues/432) so hopefully we dont have to build a dedicated controller-manager image for rook to work. 

One question i have is how would all these fit with kubeadm. Will kubeadm treat and manage things like storage and networking as first class resources?

Thank you very much for doing this by the way :)
