### ISSUE TITLE
Support k8s v1.11 and other versions still supported by cloud providers and major distros

### ISSUE THREAD

**Issue by ron1** [rook/rook#4548]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The Rook support policy for k8s versions should be based on the kubernetes support policy as well as the support policies of the cloud providers and major distros. The Kubernetes project maintains release branches for the most recent three minor releases. (https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions). At the time of this writing, the supported Amazon EKS Kubernetes versions are: 1.12.x, 1.13.x, and 1.14.x (https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html). Red Hat OpenShift v3.11 based on k8s 1.11 is scheduled to be supported until June 2022 and OCP 4.1 based on k8s 1.13 will likely be supported through March 2020 ((https://access.redhat.com/support/policy/updates/openshift).

Intermediate k8s versions that are no longer supported by cloud providers and major distros need not be supported by Rook. For example, k8s 1.12 may no longer be supported by any cloud providers and major distros in the Rook 1.3 time frame. If that is the case, then Rook 1.3 need not waste resources testing against k8s 1.12. At some point during each Rook release cycle, the current k8s support landscape should be assessed and the list of supported k8s versions should be defined for the upcoming release.

**Comment by travisn** [comment]
Before I dive into what versions Rook might be able to support, here are some overall thoughts on what we've done in Rook to increase compatibility with different versions of Kubernetes. We've been in the journey for a while since about K8s 1.5 and here is where Rook has landed:
1. Rook is dependent on the K8s [client-go API](https://github.com/kubernetes/client-go), which gives Rook the ability to target many different versions of K8s. Rook should be able to target any version of K8s that is supported by client-go. Thus far I am not aware of any exceptions to that rule. At the same time we are at the mercy of the client-go API. If there becomes an incompatibility in the API at some point with older versions of K8s, Rook will also become incompatible. Today Rook probably runs all the way back to K8s 1.9, although we haven't run our tests there anytime recently to confirm. 
1. When new features are added to K8s, Rook can obviously only build on those features in newer versions of K8s. In this case we have added version checks in to the codebase so the feature is disabled in older versions of K8s. For example, the Ceph-CSI driver requires at least K8s 1.13 and cannot be enabled on older versions. Still, Rook can be run on older versions as long as you do not depend on the newer features. 
1. The philosophy for the minimum supported version for Rook has mainly been a factor of focusing the integration tests on more recent versions of K8s. Removing support for older versions hasn't been due to Rook having issues running there. So you will probably get really good mileage running Rook on older versions of K8s even if Rook says its minimum version has increased.

You certainly raise a good question about what makes sense going forward. Rook is running more and more in production and the K8s version might not be updated for a long time, particularly if the K8s distro supports it for a long time. Supporting production clusters is certainly of interest. With that in mind:
- As an upstream project, Rook cannot possibly support all the downstream distros of K8s and their lifetime. 
- After the minimum version of Rook is increased, older versions of Rook can still be run on the older versions of K8s. For example, Rook v1.1 will continue working on K8s 1.11. Patches to that release would also be tested on K8s 1.11 before release.
- If a patch is needed and Rook no longer supports the version of K8s, someone can fork that version of Rook and build their own release.

There is an overhead in running the tests for each additional version of K8s. For day-to-day development it doesn't make sense to run the tests on all the supported versions either. This is the proposal where I'm landing:
- For day-to-day development, the Rook `master` branch should continue running the tests against the most recent **five** releases of K8s. 
- For the release branch we can increase the test matrix. For now we could keep the minimum version of 1.11, which would give us the latest **seven** releases or even **eight** in the Rook 1.3 timeline. Realistically, adding support beyond this number of releases will require someone from the community to step up and contribute to the release process. 
   - The likelihood of something breaking on the older versions of K8s is low given other philosophy to support K8s versions mentioned above. Historically, at least breaking on older versions of K8s has not been an issue for Rook.

As far as versions of Rook that we can commit to support and release fixes when needed:
- Thus far, we can only been releasing patches for the latest minor version. For example, there have been no more patches to v1.0 since v1.1 came out. 
- We are to the point now where we should support patch releases to `n` and `n-1` minor releases. With the release of v1.2 this week, this means we will support patches to both v1.1 and v1.2. Of course, the bar for backporting to v1.1 is high since it has already been stabilizing for some time. This approach was discussed recently at a Rook community meeting.

**Comment by ron1** [comment]
@travisn Thanks for your detailed response.

I expect Red Hat to be that "someone from the community to step and contribute to the release process" and support k8s 1.11/OKD 3.11/OCP 3.11 for an extended period of time given the following barriers to moving off its legacy OKD/OCP 3.11 Kubernetes distros:

- in-place upgrades from OCP 3.11 to a follow-on OCP version, i.e., OCP 4, are not supported
- the OCP 4 control plane has a hard dependency on the proprietary, unfamiliar, and non-mainstream Red Hat CoreOS operating system
-  a quality OKD 3.11 follow-on release, presumably OKD 4, is still months away
- the OKD 4 control plan will likely have a hard dependency on the unfamiliar and non-mainstream Federa CoreOS operating system

**Comment by chaosaffe** [comment]
@ron1 I just wanted to make a note that the document you referenced is significantly out of date. The current Kubernetes release is `v1.17`, with the oldest supported release being `v1.14`. `v1.11` hasn't been in support for over a year now.

One of the many disadvantages of leveraging OKD/OCP is that while you do have some guarantees that the platform itself will be supported the vast majority of ecosystem projects will continue to move along with the K8s release cadence, expecting that new feature sets will be available and that users can transition to newer resources and methods. In general, this is the disadvantage of using a non-standard platform (which includes EKS). 

Back in `v1.11` CRDs were very limited and only in beta. Porting anything back that far would incur significant difficulty, and I doubt that the overall value is there. I think if the burden were to fall to anyone it would be the users who expect to find value in backporting the project, or more likely a fork of it.

**Comment by mykaul** [comment]
@ron1 :
- OKD 4 is closer than you think. Preview is already available - see https://github.com/openshift/okd/blob/master/README.md#getting-started
- Red Hat offers its customers a migration service from OCP (and OCS) 3.x to 4.x.
- I doubt the OKD4 will have a hard deps on an unafamiliar OS. Fedora CoreOS is a great OS. ;-)

@chaosaffe : 
- OCP cadence of release pretty much follows K8S.

Lastly, especially around storage (CSI for example), Kube is just maturing in its latest releases. I would not bother with earlier releases as they simply lack many features.

**Comment by ron1** [comment]
Hi @mykaul:

It's my understanding that an OKD 4 release that is a true upstream for an OCP 4 release (like OKD 3.11 is for OCP 3.11) is not that close since OKD 4 and FCOS depend upon Ignition v3, current OCP 4 releases depend upon Ignition v2, and Ignition v2 and v3 are incompatible. I suspect most OKD 3.11 users would not want to upgrade to OKD 4 in production until OKD 4 is a true upstream for OCP 4.

Unfortunately, the OCP 4.x migration service does not support in-place cluster upgrades/migrations. Instead, on-prem, bare metal users for example, will likely need to acquire additional hardware to simultaneously host both an OCP 3.x and an OCP 4.x cluster in order to accomplish the migration.

Fedora CoreOS may be a great OS once it is released. Unfortunately, it too is still in Preview. at last check. Once Fedora CoreOS is released, it's installed base will clearly be dwarfed by that of the operating systems underlying OKD/OCP 3.11, namely CentOS/RHEL 7.

The following post does a good job summarizing the reasons why a follow-on release to OKD 3.11 remains unavailable: https://lists.openshift.redhat.com/openshift-archives/users/2019-June/msg00043.html. Since Red Hat is a major contributor to Rook, since downstream OCS 4 is based on Rook, and since OKD/OCP 3.11 Rook users are great potential OCS 4 customers, it seems reasonable for Red Hat to fill this gap and test Rook on OKD/OCP 3.11 for an extended time period.

**Comment by ron1** [comment]
Since supporting and testing Rook against numerous k8s versions is costly, what would you think about minimizing such costs by supporting every 4th k8s version for an extended time period (say 2 - 2.5 years) and supporting other versions for 1 year only? In this case, existing k8s versions 1.11 and 1.15 would be declared Rook k8s long-term support versions such that k8s version 1.11 is supported until sometime between July and December 2020, k8s version 1.15 is supported until sometime between June and December 2021, etc? According to this scheme, the forthcoming Rook 1.3 release would no longer need to test against k8s version 1.12 and maybe even 1.13. It may make sense to slowly grandfather-in such a policy. WDYT?

**Comment by travisn** [comment]
With #4673 I'm proposing:
- Rook release branches will test older versions of K8s. For v1.2 this means testing back to K8s 1.11. For v1.3 we can consider keeping it at v1.11 as well. With each release we can re-evaluate.
- If we hit some issue with an older version of K8s, we will have to decide on a case-by-case basis if we can continue to support that version. Since Rook will add a version check in order to build on newer K8s features, this really should not be a concern. I can't think of adding a newer feature to Rook that wasn't just disabled if we were running on an older version. The best example of CSI which we already don't support on 1.12 or older.

**Comment by ron1** [comment]
@travisn Thanks much for your support!

**Comment by travisn** [comment]
Closing this as per discussion above we will keep running the integration tests on k8s 1.11 for some time. If there are more specific work items or requests for longer support we can track with separate issues.
