### ISSUE TITLE
placement doesn't work with OSD on PVC

### ISSUE THREAD

**Issue by zoetrope** [rook/rook#4582]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When I specified `podAntiAffinity` for `storage.StorageClassDeviceSets.placement` to distribute each OSD pods over the different nodes, it doesn't work correctly.

There were three worker nodes in my Kubernetes cluster and the DeviceSet's count is also 3. So OSD pods should be spread over each worker node. However, it wasn't.

This issue is similar to #4397, but the root cause would be different.

**Expected behavior:**

OSD pods should be placed as specified `placement`.

**How to reproduce it (minimal and precise):**

* Install Rook.
* Prepare some local persistent volumes for each worker node.
* Apply the following cluster.yaml

**File(s) to submit**:

* cluster.yaml
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
    allowUnsupported: false
  dashboard:
    enabled: false
    ssl: true
  network:
    hostNetwork: false
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 3
      placement:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
              topologyKey: kubernetes.io/hostname
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-storage
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
```

```
$ kubectl get node
NAME                     STATUS   ROLES    AGE   VERSION
rook-poc-control-plane   Ready    master   12m   v1.16.3
rook-poc-worker          Ready    <none>   12m   v1.16.3
rook-poc-worker2         Ready    <none>   12m   v1.16.3
rook-poc-worker3         Ready    <none>   12m   v1.16.3
```

Here rook-poc-worker{,2,3} is the worker nodes.

```
$ kubectl get pod -n rook-ceph -o wide
NAME                                    READY   STATUS    RESTARTS   AGE     IP           NODE               NOMINATED NODE   READINESS GATES
rook-ceph-osd-set1-0-data-qzw9v-jmb59   1/1     Running   0          9m30s   10.64.1.2    rook-poc-worker2   <none>           <none>
rook-ceph-osd-set1-1-data-g7cvh-7jd5r   1/1     Running   0          9m30s   10.64.2.3    rook-poc-worker3   <none>           <none>
rook-ceph-osd-set1-2-data-j8jk8-kkmkc   1/1     Running   0          9m29s   10.64.2.4    rook-poc-worker3   <none>           <none>
```

Although all OSD Pods should be in the different worker nodes from each other, we can see
an OSD pod is in rook-poc-worker2 and two OSD pods are in rook-poc-worker3.

**Additional Note**

I found that OSD pods are bound to the corresponding worker nodes with `nodeSelector`.
The logic to add `nodeLabel` is as follows.

```
for all OSDs
  Make a job to launch an OSD prepare pod.
  Run this pod and bind this to a worker node.
  Start an OSD pod and bind it to the node that the corresponding OSD prepare pod existed.
```

`placement` works well iff all OSD prepare nodes exist at the same time.
However, it doesn't since OSD prepare pods are launched via jobs and these are ephemeral.

IMHO, this problem can be solved by changing osd-prepare pods to initContainer of OSD pod.
If there is no strong reason to divide OSD prepare pod and OSD pod in OSD on PVC,

I'd like to fix this problem in this way. Any suggestion? @travisn

**Comment by satoru-takeuchi** [comment]
Copy-and-paste the result of the discussion with @ashishranjan738 in Rook slack.

He said his cluster works correctly with the following configuration.

Cluster CR:
```
apiVersion: v1
items:
- apiVersion: ceph.rook.io/v1
  kind: CephCluster
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"ceph.rook.io/v1","kind":"CephCluster","metadata":{"annotations":{},"name":"rook-ceph","namespace":"rook-ceph"},"spec":{"cephVersion":{"allowUnsupported":false,"image":"ceph/ceph:v14.2.5"},"dashboard":{"enabled":true,"ssl":true},"dataDirHostPath":"/var/lib/rook","disruptionManagement":{"machineDisruptionBudgetNamespace":"openshift-machine-api","manageMachineDisruptionBudgets":false,"managePodBudgets":false,"osdMaintenanceTimeout":30},"mon":{"allowMultiplePerNode":false,"count":3,"volumeClaimTemplate":{"spec":{"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"gp2"}}},"network":{"hostNetwork":false},"storage":{"storageClassDeviceSets":[{"count":3,"name":"set1","placement":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["rook-ceph-osd"]},{"key":"app","operator":"In","values":["rook-ceph-osd-prepare"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"portable":true,"resources":null,"tuneSlowDeviceClass":true,"volumeClaimTemplates":[{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"gp2","volumeMode":"Block"}}]}]}}}
    creationTimestamp: "2020-01-06T09:12:56Z"
    finalizers:
    - cephcluster.ceph.rook.io
    generation: 2496
    name: rook-ceph
    namespace: rook-ceph
    resourceVersion: "1037647"
    selfLink: /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephclusters/rook-ceph
    uid: 77bcc9de-0c5b-45bf-9166-8eef71dd97d6
  spec:
    cephVersion:
      image: ceph/ceph:v14.2.5
    dashboard:
      enabled: true
      ssl: true
    dataDirHostPath: /var/lib/rook
    disruptionManagement:
      machineDisruptionBudgetNamespace: openshift-machine-api
      osdMaintenanceTimeout: 30
    external:
      enable: false
    mgr: {}
    mon:
      count: 3
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: gp2
        status: {}
    monitoring: {}
    network:
      hostNetwork: false
      provider: ""
      selectors: null
    rbdMirroring:
      workers: 0
    removeOSDsIfOutAndSafeToRemove: false
    storage:
      config: null
      storageClassDeviceSets:
      - count: 3
        name: set1
        placement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd-prepare
                topologyKey: kubernetes.io/hostname
              weight: 100
        portable: true
        resources: {}
        volumeClaimTemplates:
        - metadata:
            creationTimestamp: null
            name: data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp2
            volumeMode: Block
          status: {}
  status:
    ceph:
      health: HEALTH_OK
      lastChecked: "2020-01-08T03:25:15Z"
    state: Created
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

OSD prepare job spec:
```
$ oc get jobs rook-ceph-osd-prepare-set1-0-data-2mfc2 -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-01-06T09:18:28Z"
  labels:
    app: rook-ceph-osd-prepare
    ceph-version: 14.2.5-0
    ceph.rook.io/pvc: set1-0-data-2mfc2
    rook-version: v1.1.0-beta.0.684.g47ddb504-dirty
    rook_cluster: rook-ceph
  name: rook-ceph-osd-prepare-set1-0-data-2mfc2
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    kind: CephCluster
    name: rook-ceph
    uid: 77bcc9de-0c5b-45bf-9166-8eef71dd97d6
  resourceVersion: "52478"
  selfLink: /apis/batch/v1/namespaces/rook-ceph/jobs/rook-ceph-osd-prepare-set1-0-data-2mfc2
  uid: 2f6bf6cb-3024-42f6-9304-c06faa450628
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 2f6bf6cb-3024-42f6-9304-c06faa450628
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-ceph-osd-prepare
        ceph.rook.io/pvc: set1-0-data-2mfc2
        controller-uid: 2f6bf6cb-3024-42f6-9304-c06faa450628
        job-name: rook-ceph-osd-prepare-set1-0-data-2mfc2
        rook_cluster: rook-ceph
      name: rook-ceph-osd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --
        - /rook/rook
        - ceph
        - osd
        - provision
        command:
        - /rook/tini
        env:
        - name: ROOK_NODE_NAME
          value: set1-0-data-2mfc2
        - name: ROOK_CLUSTER_ID
          value: 77bcc9de-0c5b-45bf-9166-8eef71dd97d6
        - name: ROOK_PRIVATE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ROOK_PUBLIC_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ROOK_CLUSTER_NAME
          value: rook-ceph
        - name: ROOK_MON_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: data
              name: rook-ceph-mon-endpoints
        - name: ROOK_MON_SECRET
          valueFrom:
            secretKeyRef:
              key: mon-secret
              name: rook-ceph-mon
        - name: ROOK_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              key: admin-secret
              name: rook-ceph-mon
        - name: ROOK_CONFIG_DIR
          value: /var/lib/rook
        - name: ROOK_CEPH_CONFIG_OVERRIDE
          value: /etc/rook/config/override.conf
        - name: ROOK_FSID
          valueFrom:
            secretKeyRef:
              key: fsid
              name: rook-ceph-mon
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CEPH_VOLUME_DEBUG
          value: "1"
        - name: CEPH_VOLUME_SKIP_RESTORECON
          value: "1"
        - name: DM_DISABLE_UDEV
          value: "1"
        - name: ROOK_CEPH_VERSION
          value: ceph version 14.2.5-0 nautilus
        - name: ROOK_DATA_DEVICES
          value: /mnt/set1-0-data-2mfc2
        - name: ROOK_PVC_BACKED_OSD
          value: "true"
        image: ceph/ceph:v14.2.5
        imagePullPolicy: IfNotPresent
        name: provision
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/rook
          name: rook-data
        - mountPath: /etc/ceph
          name: ceph-conf-emptydir
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /rook
          name: rook-binaries
        - mountPath: /dev
          name: devices
        - mountPath: /run/udev
          name: udev
        - mountPath: /mnt
          name: set1-0-data-2mfc2-bridge
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - copy-binaries
        - --copy-to-dir
        - /rook
        image: ashishranjan738/rook-ceph:latest
        imagePullPolicy: Always
        name: copy-bins
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /rook
          name: rook-binaries
      - args:
        - -a
        - /set1-0-data-2mfc2
        - /mnt/set1-0-data-2mfc2
        command:
        - cp
        image: ceph/ceph:v14.2.5
        imagePullPolicy: IfNotPresent
        name: blkdevmapper
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeDevices:
        - devicePath: /set1-0-data-2mfc2
          name: set1-0-data-2mfc2
        volumeMounts:
        - mountPath: /mnt
          name: set1-0-data-2mfc2-bridge
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-ceph-osd
      serviceAccountName: rook-ceph-osd
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/rook
          type: ""
        name: rook-data
      - emptyDir: {}
        name: ceph-conf-emptydir
      - hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ""
        name: rook-ceph-log
      - hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ""
        name: rook-ceph-crash
      - emptyDir: {}
        name: rook-binaries
      - hostPath:
          path: /dev
          type: ""
        name: devices
      - hostPath:
          path: /run/udev
          type: ""
        name: udev
      - name: set1-0-data-2mfc2
        persistentVolumeClaim:
          claimName: set1-0-data-2mfc2
      - emptyDir:
          medium: Memory
        name: set1-0-data-2mfc2-bridge
status:
  completionTime: "2020-01-06T09:20:40Z"
  conditions:
  - lastProbeTime: "2020-01-06T09:20:40Z"
    lastTransitionTime: "2020-01-06T09:20:40Z"
    status: "True"
    type: Complete
  startTime: "2020-01-06T09:18:28Z"
  succeeded: 1
```

I'll share him any of OSD pod spec later.

**Comment by ashishranjan738** [comment]
`OSD prepare jobs as init container`. This idea was brought up earlier as well. I think when we were discussing the design of storageClassDeviceSet. We felt some resistance regarding this.  Here is a link for reference https://github.com/rook/rook/pull/3306#discussion_r294336925

**Comment by tbool** [comment]
If in the podAntiAffinity rule there are matchExpressions for both rook-ceph-osd-prepare and rook-ceph-osd, then that rule only applies to nodes where both these pods are available, but as rook-ceph-osd-prepare is only a completed job these pods will disappear after a reboot of the node, in which case this podAntiAffinity rule has no effect anymore and OSD pods can ramdomly be scheduled on any node. This happened to me on a GKE cluster after a kubernetes version update.

Taking the matchExpression for the OSD-prepare pod out of the podAntiAffinity rule did the trick for me, OSD pods now always get scheduled on different nodes, but I did notice that some of the OSD-prepare pods now get scheduled on the same node. I am not sure how important it is that also the OSD-prepare pods are scheduled on separate pods...?

**Comment by satoru-takeuchi** [comment]
Quoted from the @ashishranjan738 message in Rook slack's:
> i think i misunderstood the issue. I thought the placements provided in the cephcluster are not getting applied to osd's but seems like its not the same, the podAffinities are getting applied correctly but still there are some situations when OSDs are landing up on the same node. 

Yes, the information in `placement` is reflected to OSD pod correctly. However, this information doesn't work by default. It's because the following logic as  @zoetrope wrote.

```
for all OSDs
  Make a job to launch an OSD prepare pod.
  Run this pod and bind this to a worker node.
  Start an OSD pod and bind it to the node that the corresponding OSD prepare pod existed.
```

It seems to be bypassed by setting `labelSelector` for both `ceph-osd-prepare` and `ceph-osd` as you did.

```
        placement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd-prepare
                topologyKey: kubernetes.io/hostname
```

However, I consider this workaround is hacky because of the following reasons.

- It heavily depend on the implementation. Once implementation changes, it would become useless and we should find other workaround.
- There would be race conditions. For example, a `ceph-osd` pod dies temporarily during other OSD's creation.

As a permanent solution, @zoetrope and I consider that changing `ceph-osd-prepare` pods to initContainer of OSD pod would be fine.

```
OSD prepare jobs as init container. This idea was brought up earlier as well. I think when we were discussing the design of storageClassDeviceSet. We felt some resistance regarding this. Here is a link for reference #3306 (comment)
```

Could you tell me the detail why initContainer is considered as an improper way? Although I read the link that you let me know, I couldn't understand the detail. Partly it's because the old PR's code is already disappeared by force-push.

**Comment by travisn** [comment]
The OSDs by design require a two-step process. The first step is the osd prepare job and the second step is the osd daemon. This design is described [here](https://github.com/rook/rook/blob/master/design/ceph/dedicated-osd-pod.md). We won't be able to change this approach. 

I believe the operator should be setting the same placement rules on the osd prepare pods as on the osd daemons. In this way, it shouldn't matter if the prepare pods are not all run at the same time. Can you confirm that you see the same placement on them? If not, this seems like the bug. If they are the same, then I'm still not understanding why k8s is not honoring the placement.

**Comment by xdsxc** [comment]
Ran into this issue myself today. I confirmed that the OSD prepare pod has the same affinity as the OSDs:

This is on the placement job pod:
```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
            - key: app
              operator: In
              values:
              - rook-ceph-osd-prepare
          topologyKey: kubernetes.io/hostname
        weight: 100
```

And on the OSD:
```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
            - key: app
              operator: In
              values:
              - rook-ceph-osd-prepare
          topologyKey: kubernetes.io/hostname
        weight: 100
```

It seems like the OSD prepare jobs complete so quickly that it is possible for the anti-affinity rules to be satisfied for the same hostname because by the time another job is scheduled, the previous job has already been completed.

Most of the jobs take less than 1s to run:
```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 14 Jan 2020 14:14:36 -0800
      Finished:     Tue, 14 Jan 2020 14:14:36 -0800
```

**Comment by zoetrope** [comment]
@travisn
> The OSDs by design require a two-step process. The first step is the osd prepare job and the second step is the osd daemon. This design is described here. We won't be able to change this approach.

We do not suggest to change the two-step process; what we meant is that, for OSD on PVC cases, the first step can be done with an initContainer instead of a separate prepare Job.

IIUC, the purpose of the prepare Job is to initialize OS block devices at once according to the given deviceFilter for OSD on _Node_ cases.  In OSD on PVC, a prepare Job initializes only a single PVC/PV. Therefore the Job can be replaced with an initContainer of the OSD Pod easily.

Doing so will resolve the scheduling problems, as explained by us and @xdsxc .  We believe OSD on PVC can become an excellent feature for the optimal automatic placement of OSDs in a data center if we can combine it with Pod anti-affinity and forthcoming topologySpreadConstraints.

Just as a reference, we have created a PoC to replace prepare Jobs with initContainers for OSD on PVC cases. https://github.com/cybozu-go/rook/pull/3

**Comment by leseb** [comment]
@zoetrope The problem with the initcontainer approach is that it'll rely on the "rook" binary, so if the operator is upgraded, a new image will be provided. The problem is that every deployment that has this image in its spec will get restarted even if the object actually didn't change.
This is something we are getting rid of in various places already.

**Comment by tbool** [comment]
I have been following this discussion for a while, and I noticed that the only reason we have this whole discussion is because there would be a "need" to bind OSD pods to the same node that the corresponding OSD prepare job once existed.

But is this dependancy really necessary?

Over the last week I have been experimenting  with a shared filesystem using the cluster-on-pvc.yaml in the examples directory, but with this podAntiAffinity rule:

```
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rook-ceph-osd
```

I use `requiredDuringSchedulingIgnoredDuringExecution` rather than `preferredDuringSchedulingIgnoredDuringExecution`, therefore it is slightly different from the rule in cluster-on-pvc.yaml, but the main difference is that I skipped the dependancy on the OSD prepare jobs.

I have started a cluster with this setting several times, and broke it down again at the end of the day, but despite the OSD prepare jobs sometimes getting scheduled on the same node I never saw any issues, and all OSD pods always got scheduled on different nodes, which I think is the main objective  creating a High Availability cluster.

So my question is: Do we really need this additional dependancy on the OSD prepare jobs?

**Comment by leseb** [comment]
When running on PVC, the prepare and the osd pod don't need to be running on host but we do require it so that we can compute the CRUSH location. Technically, if we were able to know the name of the host the osd would be running on, the prepare pod could run everywhere.
This is only true for PVC because blocks are attached/detached for each prepare/osd container.

**Comment by tbool** [comment]
But the current placement rule only states where the OSD pod is NOT supposed to run, not where it should/must run... 

Certainly on clusters with more nodes than OSD's and after some rescheduling of pods due to maintenance on the kubernetes cluster, over time it will be impossible to guarantee that a specific pod will still run on a specific node. Not to mention that is also very much against the kubernetes philosophy to have such a fixed relation between the two.

I run a kubernetes cluster on GKE, with autoscaling enabled. When load on the cluster is high new nodes will automatically be added to the cluster and when the load drops again nodes will automatically be removed. Which nodes the system will remove is decided by the system , probably defined by certain rules, but not something a user can influence. After some weeks probably none of the original nodes with which the cluster started will still be there, and all pods will probably have been rescheduled several times. So all nodeID's and all podID's will have changed. This will be the case for all cloud providers and for the majority of kubernetes clusters.

I don't know what a CRUSH location is, but I doubt very much that a solution that is based on a fixed relation between pod and node in kubernetes will ever work.

Maybe I am thinking too simple, I don't know much about Rook-Ceph yet, but isn't it possible to store that CRUSH location somewhere in ETCD and change it dynamically when something (podID and/or nodeID) changes? That I think would be the kubernetes-way to solve this.

**Comment by zoetrope** [comment]
@leseb 
Got it. So I understand that this is a limitation rather than a bug.
Should I add documentation that users must specify both `rook-ceph-osd` and `rook-ceph-osd-prepare` on `labelSelector` for placement?
