### ISSUE TITLE
Add ability to specify image tag for CockroachDB Operator

### ISSUE THREAD

**Issue by nfrush** [rook/rook#4591]
**Is this a bug report or feature request?**
* Feature Request

**Feature Request**

**Are there any similar features already existing:**
Ceph has a similar ability in the config.yaml currently

**What should the feature do:**
Currently, we can specify the images to use for the Ceph operator. There should be similar options for the CockroachDB operator

**What would be solved through this feature:**
I have custom compiled images to run CockroachDB on ARM64 (I currently do the same with Ceph) and being able to use the Rook operator to deploy the Cockroach cluster, but with my image, would be a huge plus

**Does this have an impact on existing features:**
I don't believe so

**Comment by ahilsend** [comment]
This is still relevant, can we reopen this?

**Comment by travisn** [comment]
@ahilsend Before we reopen the issue I'd like to consider a bigger question. The cockroachdb team has focused on support for their helm charts, but not an operator. As I understand they don't expect to need management beyond the static helm configuration. Can you comment about how you're using the cockroachdb operator and how you see it being helpful going forward? This would potentially aid to get the cockroachdb team more on board to support it and get the operator to stable status. We haven't seen community support to get it out of alpha stage since it was added to Rook. But if we can get more community support we would certainly like to make more of an argument for it. Thanks!

**Comment by ahilsend** [comment]
> @ahilsend Before we reopen the issue I'd like to consider a bigger question. The cockroachdb team has focused on support for their helm charts, but not an operator. As I understand they don't expect to need management beyond the static helm configuration. Can you comment about how you're using the cockroachdb operator and how you see it being helpful going forward? This would potentially aid to get the cockroachdb team more on board to support it and get the operator to stable status. We haven't seen community support to get it out of alpha stage since it was added to Rook. But if we can get more community support we would certainly like to make more of an argument for it. Thanks!

Thanks for your reply!
I initially started looking into the rook-cockroachdb operator, because I had good experiences with the ceph one. After looking further into it, I decided it was supporting too little. I considered contributing with some improvements, but wanted to try out the official helm chart first. And I was quite happy with it. It works well, and has a lot built-in - including TLS. 

Given that Cockroach DB setup is pretty simple, and doesn't require much cluster operations other than DNS based discovery, I am actually not sure a dedicated operator is needed.
