### ISSUE TITLE
security vulnerability with ceph dashboard

### ISSUE THREAD

**Issue by benwbooth** [rook/rook#4635]
## Content removed

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by jmolmo** [comment]
I have review the capture and what i can conclude is that there is a security breach in the CherryPy component of the dashboard because it allows to process http requests outside the application domain.
In Rook we cannot solve this problem. I pass this information to the Ceph dashboard team to inform about the problem

Details:
In TCP packets 1210, 12

TCP packet 1210: request directly the etc/passwd file:
-------------------------------------------------------------------------------
GET /../../../../../../../../../../../../etc/passwd HTTP/1.1
Host: monster.lbl.gov:7000
Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1
Accept-Language: en
Connection: Close
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
Pragma: no-cache
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*

TCP packet 1210: The request is accepted
-------------------------------------------------------------------------------
HTTP/1.1 200 OK
Content-Length: 1091
Content-Language: en-US
Accept-Ranges: bytes
Vary: Accept-Language, Accept-Encoding
Server: CherryPy/3.2.2
Last-Modified: Tue, 10 Dec 2019 11:07:09 GMT
Date: Wed, 08 Jan 2020 01:14:00 GMT
Content-Type: text/html;charset=iso-8859-1

TCP packet 1214: The /etc/passwd file is returned
-------------------------------------------------------------------------------
Not reproduced here

**Comment by travisn** [comment]
@benwbooth thanks for reporting the security issue, we are working on the fix. Since it is a security issue, content from the github issue is removed now. For future reference, we will soon have instructions for reporting security issues as described in #4395. Thanks!

**Comment by travisn** [comment]
This has been fixed in the Ceph [v14.2.7 release](https://docs.ceph.com/docs/master/releases/nautilus/#v14-2-7-nautilus)
