### ISSUE TITLE
how to upgrade from 1.1 to 1.2.x if rook  was deployed via helm

### ISSUE THREAD

**Issue by betonmoewe** [rook/rook#4664]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
* the documentation should describe the upgrade path from x to y if helm was used for deployment
**What is use case behind this feature:**
* Upgrading rook without cloning the rook git repository
**Environment**:

**Comment by betonmoewe** [comment]
Hi,

I have not found a description of how to upgrade from v1.1.x to v1.2x after rolling out rook with helmet without having to clone the project locally. the upgrade procedure is only based on rolling out by hand. Or is this not possible at all?

Best regards
betonmoewe

**Comment by mumrau** [comment]
Some documentation need to be added around this I confirm. 
On my end I took the opposite path because `ceph` obviously is an incredibly critical component, I'd rather be safe and upgrade throughout the documented procedures.

But at the end of the day, `rook-ceph` is the only component (except for the `kube-system` static components) that isn't managed through `helm` on my clusters.
