### ISSUE TITLE
Add support for nodeSelector or Node Affinity

### ISSUE THREAD

**Issue by luxas** [rook/rook#470]
Hi!

Are there plans to let the user select a set of nodes that the mons will be deployed on. As I see it now, they will be scheduled just "randomly" to some node.

But given the case I have two-three nodes with lots of disk storage and other nodes that may not have it, I'd like to be able to select which nodes the mons land on.

This should be possible to achieve with a) a nodeSelector field to the Cluster TPR or maybe even better b) letting the user set node affinity in the Cluster TPR.

Does this sound reasonable?

**Comment by bassam** [comment]
@luxas I think this is a great suggestion. We should have a placement policy be specified at the cluster TPR for both mon and osds. would be great if the defaults just worked.

**Comment by luxas** [comment]
Default could be "place on any node", and then you could override that with whatever you prefer

**Comment by luxas** [comment]
@bassam Has this been fixed recently? Is there any easy way to select a bunch of nodes with a label without specifying the names of each of them?

**Comment by travisn** [comment]
@luxas, we aren't using labels yet. There is the capability to use the hostname, see the comments in https://github.com/rook/rook/blob/master/demo/kubernetes/rook-cluster.yaml. Not quite where we need to be yet though

**Comment by jbw976** [comment]
That's correct @travisn @luxas, with the v0.4 implementation of the Cluster TPR, you can include storage nodes by adding their `kubernetes.io/hostname` label value to the Cluster TPR itself.  As discussed in https://github.com/rook/rook/issues/397#issuecomment-289156161, we are planning on allowing users to apply labels to each node they want included instead of specifying them in the TPR explicitly.  The design doc will be updated soon for v0.5: https://github.com/rook/rook/wiki/Storage-Configuration-Design

**Comment by alkar** [comment]
Additionally, it would be more than useful to be able to work with taints/tolerations (see the updated docs in https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature).

The use case:

Running a kubernetes cluster with 6 nodes, 3 of which have additional storage configured and perhaps enhanced network connectivity. I want these nodes to only ever run rook pods and rook pods to only ever get scheduled on these nodes. This will hopefully provide a better service for rook PVs consumers as rook services will be running on 'dedicated' hosts with enhanced capabilities and without noisy neighbours.

These 'special' storage nodes have `kubelet` start with `--register-with-taints=storage-node=true:NoSchedule` which means only pods that 'tolerate' the taint can be deployed on them.

It would be great if we could somehow specify that in the cluster spec so that the operator will spin up the cluster pods using the appropriate `tolerations` and `affinity` values in their spec.

(perhaps there's a use case to configure these values per pod type (OSD/MON/MDS) but as a first step I think a 'global' config would suffice)

Thoughts?

**Comment by travisn** [comment]
@alkar agreed, the taints and tolerations do seem like the right way to accomplish this. I was just looking at them recently for mon placement in #579, but they would certainly apply for all the services.

**Comment by alkar** [comment]
@travisn Yep, it looks kube is headed towards that direction when it comes to specialised nodes / dedicated hardware. Is this something you're actively working on at the moment?

**Comment by travisn** [comment]
It's high on my priority list, but it may take a couple weeks to get to this.

**Comment by kokhang** [comment]
@alkar, it seems this broke compatibility with k8s 1.5. I am reopen it. Could you provide a fix for 1.5?

**Comment by kokhang** [comment]
Im going to create a new issue for this instead

**Comment by alkar** [comment]
@kokhang I actually didn't think of that previously. Do you really want to support kube 1.5 moving forward?

**Comment by luxas** [comment]
@alkar It's totally ok as-is, see my comment in #791

**Comment by beatlejuse** [comment]
I think it's not working at the moment.
I used this guide to do it:
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-cluster.yaml
and I found that the following keys:

#  placement:
#    all:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: role
#              operator: In
#              values:
#              - storage-node

#    nodes:
#    - name: "172.17.4.101"
#      directories:         # specific directores to use for storage can be specified for each node
#      - path: "/rook/storage-dir"
# you can override the cluster wide resource requests/limits per node, but only
# when using `useAllNodes: false`!
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
#    - name: "172.17.4.201"
#      devices:             # specific devices to use for storage can be specified for each node
#      - name: "sdb"
#      - name: "sdc"
#      storeConfig:         # configuration can be specified at the node level which overrides the cluster level config
#        storeType: bluestore
#    - name: "172.17.4.301"
#      deviceFilter: "^sd."

just break everything. none of the pod was not deployed.
I have experienced more than 5 combinations of keys specified in this manual

**Comment by galexrt** [comment]
@beatlejuse Please create a new issue for the problems you are experiencing. Additionally please post which pods aren't spawning/deploying in the issue. Thank you!
