### ISSUE TITLE
Docs: Removal of OSD on directory, Filestore OSD and Rook legacy OSD support

### ISSUE THREAD

**Issue by leseb** [rook/rook#4724]
# What's changing in Rook 1.3?

With https://github.com/rook/rook/pull/4435, Rook is introducing a major refactor in the way OSDs are handled and configured. Essentially, this change will:

* remove support for Filestore OSDs
  * existing Filestore OSDs will continue to run if on a block device
  * creation of Filestore OSDs is not supported anymore
* remove support for osd running on directories
  * existing OSD running on a directory will continue to run
     * However, if the OSD deployment is deleted, Rook won't bring it up
  * creation of OSD on a directory is **not** possible anymore
* remove support for legacy Rook OSD (non-ceph-volume configured)
  * to identify the legacy Rook OSDs that would be affected, look for the existence of three partitions on a device with labels such as `ROOK-OSD0-BLOCK`
  * existing legacy rook osd will continue to run
    * However, if the OSD deployment is deleted, Rook won't bring it up
  * creation ofa legacy OSD is not possible since ~1.0 when ceph-volume was introduced

# What should I do?

We recommend you to:

* trash your OSDs one by one
* use partition (possible since https://github.com/rook/rook/releases/tag/v1.2.2) or a full block device to create new bluestore OSDs. Using `useAllDevices: true` is recommended and makes the whole experience easier to automatically create new OSDs. You must be running Ceph 14.2.8 or higher to achieve this since it contains a ceph-volume fix to create OSDs on partitions.
* wait for Ceph to recover
* move to the next OSD

# Am I impacted by this change?

You are not impacted if your OSDs are running on block devices and use Bluestore, otherwise, you are.

# What if I do nothing?

If you fall into the cases listed in the first part of the document your OSDs won't start anymore and your cluster will be unusable. It's highly recommended to act as presented in the second section.

**Comment by leseb** [comment]
Note, this issue is subject to change and edits will be made until https://github.com/rook/rook/pull/4435 gets merged.

**Comment by ntolia** [comment]
I can understand why this change is being made but the lack of OSDs running on directories will hurt quick experimentation (minikube, Docker Desktop, etc.) where it is harder (impossible?) to provision extra volumes or partition.

**Comment by leseb** [comment]
@ntolia there are options to attach block devices to a VM, it's easy when using the libvirt provider, also virtual box can do this for you so minikube is still relevant.

**Comment by ntolia** [comment]
@leseb Yes, I understand but one frequently doesn't have access to the VM (e.g., Docker Desktop on Mac) and this will make life more difficult and local tests more complicated in general. As I said, I understand the reasoning behind the change but did want to raise its potential impact on non-Rook devs.

**Comment by travisn** [comment]
Related to #3379

**Comment by travisn** [comment]
Let's leave this open to get it into the upgrade guide.

**Comment by trulede** [comment]
> @leseb Yes, I understand but one frequently doesn't have access to the VM (e.g., Docker Desktop on Mac) and this will make life more difficult and local tests more complicated in general. 

I'm trying Rook on MicroK8s ... and getting nowhere with it. It seems that already the storage/directories option in CephCluster is not getting picked up. OK.

Perhaps its possible to use a PVC? That would be handy.

**Comment by leseb** [comment]
> > @leseb Yes, I understand but one frequently doesn't have access to the VM (e.g., Docker Desktop on Mac) and this will make life more difficult and local tests more complicated in general.
> 
> I'm trying Rook on MicroK8s ... and getting nowhere with it. It seems that already the storage/directories option in CephCluster is not getting picked up. OK.
> 
> Perhaps its possible to use a PVC? That would be handy.

Yes, of course, you can use PVC :)

**Comment by trulede** [comment]
But the PVC needs to be `volumeMode: Block` right?

I tried this with MicroK8s and its microk8s-local storage class, however with Block mode the PVC would not create, with Filesystem it was OK ... but then the OSD Pod is stuck pending.

´The documentation suggests as much.

> In more dynamic environments where storage can be dynamically provisioned with a **raw block storage provider**, the OSDs can be backed by PVCs.

and 

> volumeMode: The volume mode to be set for the PVC. Which should be Block

OK, I've answered my own question :-)

**Comment by trulede** [comment]
I did finally get this working on a single node MicroK8s. To get it working it's necessary to add a Block device to your mk8s, in my case I mapped in a Virtual Box SCSI disk image (VMI iirc) and that did the trick. Loopbacks were not good, SDCard did not work for me either (not sure why). There might be other solutions.

The notes and config files are here:
https://github.com/trulede/mk8s_rook.git

**Comment by r0bj** [comment]
Hi, I'm trying to get rid of OSDs running on directories (which soon be deprecated) on my small test rook clusters but I'm hitting some issues:
1. I cannot use OSD on loop devices:
```
2020-03-19 00:52:06.921139 I | exec: Running command: lsblk /dev/loop0 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-19 00:52:06.923496 W | inventory: skipping device "loop0": unsupported diskType loop
```
2. I cannot use OSD on LVM devices due to https://github.com/rook/rook/issues/2047

So the question is what options do I have (except directories) to run rook in the environment with small dev hosts/VMs which do not have access to raw disks?
This question is probably also relevant to minikube and similar solutions.

**Comment by leseb** [comment]
> Hi, I'm trying to get rid of OSDs running on directories (which soon be deprecated) on my small test rook clusters but I'm hitting some issues:
> 
> 1. I cannot use OSD on loop devices:
> 
> ```
> 2020-03-19 00:52:06.921139 I | exec: Running command: lsblk /dev/loop0 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
> 2020-03-19 00:52:06.923496 W | inventory: skipping device "loop0": unsupported diskType loop
> ```

Yes, ceph-volume does not support loop dev AFAIR.

> 
> 1. I cannot use OSD on LVM devices due to #2047

Might be an option but needs testing.

> 
> So the question is what options do I have (except directories) to run rook in the environment with small dev hosts/VMs which do not have access to raw disks?
> This question is probably also relevant to minikube and similar solutions.

As explained earlier you can easily attach disks to Minikube (VirtualBox or Libvirt).

The best option currently is to use a partition.

**Comment by muhlba91** [comment]
Since we had the problem of our infrastructure cloud service not allowing us to create and attach multiple storage devices as well as the host system not being provisioned with LVM and the directory approach was so far the only easy way to get it working, I wanted to post our current solution (please bring in other ideas and approaches).

Unfortunately, loopbacks do not work and we found it rather difficult provisioning PVC in block mode in any way s.t. ceph-volume had a correct volume to use. To mitigate this we used, e.g. on Debian systems, `tgt` to expose a lun device (a simple image file created by `dd` or `fallocate`) and consume it on the same server with `open-iscsi`. This way we get a mount which can be selected by it's disk path filter or (starting from 1.3) by any other full path given.
Interestingly, ceph-volume - compared to e.g. using a loopback device or even creating a raid on a loopback device and exposing it through local-storage provisioner - detected this volume as usable and the cluster runs smoothly (so far).

However, due to this mapping of a file to an iSCSI disk and usage by ceph of such, I expect some performance degradation with more load from multiple consumers coming in. In my initial tests using `dd` performance was acceptable for our purposes. On a SSD storage with a 16GB memory machine I got a write performance (using `dd` with 500MB-20GB files) with CephFS of about 160-200MB/s and using RBD it was about 260-300MB/s.
Performing the same commands on the host system itself lead to a speed of about 360-390MB/s.

**Comment by fjudith** [comment]
Thank you for your feedback @muhlba91 .

Is it possible for you to share the workaround you implementend using `open-iscsi` ?

**Comment by muhlba91** [comment]
Sure. Please find below my workaround for Debian based systems using `tgt` and `open-iscsi`.

```
# install tgt and open-iscsi
apt-get install -y tgt open-iscsi

# assume we have want to store our iscsi disk image at /var/lib/devices and use a 100G disk.
# create the disk image
fallocate -l 100G /var/lib/devices/disk-001.img

# configure iscsi tgt
# we use CHAP authentication (bidirectional) and set the initiator address to only allow localhost to enhance iscsi security
tee /etc/tgt/conf.d/rook_iscsi.conf > /dev/null <<EOF
<target iqn.0000-00.node-001.local:rook>
  backing-store /var/lib/devices/disk-001.img
  initiator-address 127.0.0.1
  incominguser iscsi-user random_password
  outgoinguser iscsi-target random_password_out
</target>
EOF

# enable iscsi tgt service
systemctl enable tgt
systemctl restart tgt

# optionally, verify the target is working
tgtadm --mode target --op show

# configure iscsi initiator
iscsiadm -m discovery -t st -p 127.0.0.1
tee -a /etc/iscsi/nodes/iqn.0000-00.node-001.local\:rook/127.0.0.1\,3260\,1/default > /dev/null <<EOF
node.session.auth.authmethod = CHAP
node.session.auth.username = iscsi-user
node.session.auth.password = random_password
node.session.auth.username_in = iscsi-target
node.session.auth.password_in = random_password_out
EOF

# enable automatic startup and the systemd service
sed -i 's/node.startup = manual/node.startup = automatic/g' /etc/iscsi/nodes/iqn.0000-00.node-001.local\:rook/127.0.0.1\,3260\,1/default
systemctl enable open-iscsi
systemctl restart open-iscsi

# wait a few seconds to mount the device and verify
sleep 10
lsblk
```

Since I am using also a terraform module for bootstrapping our clusters automatically, this is one of the user-data scripts used for the nodes being OSDs and to distinguish the iscsi target I can automatically add the node name, although it can be the same on every node since we only mount on localhost.
However, the mount path for each device will now be:
`/dev/disk/by-path/ip-127.0.0.1:3260-iscsi-iqn.0000-00.node-001.local:rook-lun-<X>`, whereas `<X>` will be a number, starting from 1 in our case.

To use those devices, we can simply create a CephCluster similar to:
```
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  # your configuration
  # ...
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      storeType: bluestore
    nodes:
      - name: node-001
        devicePathFilter: ^/dev/disk/by-path/ip-127.0.0.1:3260-iscsi-iqn.0000-00.node-001.local:rook-lun-[\d]{1,}
```

Actually, with 1.3.0 we can also use the full device path for a device, which comes in handy when dynamically adding new devices and wanting to trigger an update automatically (e.g. through terraform):
```
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  # your configuration
  # ...
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      storeType: bluestore
    nodes:
      - name: node-001
        devices:
          - name: /dev/disk/by-path/ip-127.0.0.1:3260-iscsi-iqn.0000-00.node-001.local:rook-lun-1
          - name: /dev/disk/by-path/ip-127.0.0.1:3260-iscsi-iqn.0000-00.node-001.local:rook-lun-2
```

**Comment by traceypooh** [comment]
damn @muhlba91 thanks so much!
trying to rebuild main cluster this week, updating everything...
our VMs only have a single disk so was trying to loopback mount a disk-as-file setup (and ceph wouldn't go for it) but found your posts and doggedly tried to get a bunch of factors.  worked!

( https://gitlab.com/internetarchive/kre8/-/blob/master/persistent-volume/vm-mount-disk-for-osd.sh ) <= you, basically :)
