### ISSUE TITLE
 rbd: create volume failed, err: executable file not found in $PATH

### ISSUE THREAD

**Issue by valentin2105** [rook/rook#482]
Hi !

I have tried Rook in my k8s cluster based on Ubuntu directly with k8s binaries (without any containers).

All the components of Rook are running fine (3 mon, 5 osd, 1 operator and 1 rook-api).

When I create a PVC, and describe it, I got this : 

```
Failed to provision volume with StorageClass "rook-block": rbd: create volume failed, err: executable file not found in $PATH
```

I got the pkg ceph-common installed on each workers and the command "rbd" work fine from /usr/bin/rbd.

Any idea where I'm wrong ?

**Comment by bzub** [comment]
The rbd command is actually needed on the master nodes and in the $PATH for the master component services.

**Comment by valentin2105** [comment]
@bzub Ok thanks you !!

A small last question, Where the data created on Rook are present on the worker ? There is a volume mounted for theses pods (OSDs) ? 

Thanks 👍

**Comment by travisn** [comment]
@valentin2105 Good question, we need to add this to documentation. There are currently a few options.
- By default the data is created in a simple EmptyDir for experimentation. 
- If you set `useAllDevices=true` in the rook-cluster.yaml, the OSDs will look for devices automatically to use. However, be careful with that option since it is very aggressive to format devices.
- To select more specific devices, see #465 which was just merged this morning. However, we still need to publish a build with this change.

**Comment by valentin2105** [comment]
@travisn  Thanks for your answers.
