### ISSUE TITLE
Make Rook as a unified storage framework on K8s

### ISSUE THREAD

**Issue by huangwei0413** [rook/rook#4908]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
* Make Rook as a unified storage framework on K8s. Thus, all kinds of data services (including Redis, MQ, etc) use Rook as backing service.  

**What is use case behind this feature:**
* Nowadays, different data services use different solutions as underlying persistence technology. For example, MySQL may use PV/PVC on NFS, Kafka may use PV/PVC on local volume, and HBase may use some kind of disk cluster. It is expected Rook can provide a common facade for those data services and facilitate the whole storage management.  

**Environment**:

**Comment by mykaul** [comment]
Interesting wish, but too abstract. Rook can provide today an abstract management of PV and PVCs.
You might be asking for Rook to manage also local volumes?

**Comment by travisn** [comment]
Rook does not plan to provide a common API for different storage solutions. Each storage comes with its own unique needs. The places where storage benefits from commonality is already being done in the storage SIG with CSI, including PV provisioning, snapshots, etc. Rook really provides commonality for implementing storage operators, rather than providing commonality across the platforms.

**Comment by huangwei0413** [comment]
I am sorry if I make you confused. My point is, since Rook integrate with database services, like SQL (CockroachDB) and NoSQL (Cassandra). Will it also integrate with others, like In-Memory Store (Redis), Message Queue (Kafka)? I don't know if this is on the roadmap.

**Comment by travisn** [comment]
@huangwei0413 Others are welcome to join the project. It is all community driven. But it won't be on the roadmap until community members for those projects join the effort.
