### ISSUE TITLE
Support specifying several drives for ceph DB

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4999]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Support specifying several devices in `metadataDevice` field (which is already supported by ceph)

**What is use case behind this feature:**
In case we have a lot of spinning drives in a node, we might want a larger NVME DB storage than a single NVME can provide.

The issue was partly discussed in https://github.com/rook/rook/issues/3448#issuecomment-523037014 already

Also after talking to @travisn I found that rook is going to transition from LVM to raw devices, is that a correct statement?

@leseb

**Comment by leseb** [comment]
> **Is this a bug report or feature request?**
> 
> * Feature Request
> 
> **What should the feature do:**
> Support specifying several devices in `metadataDevice` field (which is already supported by ceph)
> 
> **What is use case behind this feature:**
> In case we have a lot of spinning drives in a node, we might want a larger NVME DB storage than a single NVME can provide.
> 
> The issue was partly discussed in [#3448 (comment)](https://github.com/rook/rook/issues/3448#issuecomment-523037014) already
> 
> Also after talking to @travisn I found that rook is going to transition from LVM to raw devices, is that a correct statement?

Yes, since we are moving toward running everything on PVs.

> 
> @leseb

**Comment by dimm0** [comment]
If I could just send a list of volumes to ceph-volume, it will figure out which ones to use for DB....
Now even that is not possible

**Comment by dimm0** [comment]
not stale

**Comment by dimm0** [comment]
unstale

**Comment by dimm0** [comment]
👀

**Comment by travisn** [comment]
> We're forced to buy the bigger NVMEs at the moment.. How does storageClassDeviceSet help?

Oh i missed this question earlier... The storageClassDeviceSet will create one OSD per db/wal/data device combination, so you no longer need to share the metadata devices with multiple OSDs. See the [storageClassDeviceSet examples in the docs](https://rook.github.io/docs/rook/v1.8/ceph-cluster-crd.html#using-storageclassdevicesets). 

In the cloud environments this is simple since the devices can be requested for any size. 

For on-prem, you obviously don't have the same number of metadata devices as data devices. In this case, you could partition the metadata device, create local PVs on the partitions, then use a storageClassDeviceSet to specify using those partitions from the corresponding storageClasses.

**Comment by dimm0** [comment]
Interesting! Got it, thanks!
