### ISSUE TITLE
Default PG count severely limits the number of pools in a small cluster

### ISSUE THREAD

**Issue by travisn** [rook/rook#5091]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In a small cluster such as 3 OSDs, the default PG count `mon_max_pg_per_osd` is very limiting for clusters since the default PG count changed from 8 to 32 in v14.2.8. Now all you have to do is create an object store and one block pool before you hit the pool limit when replicas.size is 3 for all the pools (the recommended default). 

As a workaround, the max PGs per OSD (default is 250) can be increased from the toolbox with the following command:
```
ceph config set mon mon_max_pg_per_osd 500
```

However, Rook users would like to avoid PG management to keep things simple, especially in common scenarios. 

@jdurgin What is your recommendation on how to deal with the new default. Increasing the max PGs per OSD seems like a temporary fix rather than a good recommendation.
 
**Expected behavior:**
Rook users should be able to create several pools, object stores, and filesystems on a basic cluster (3 OSDs) before hitting limits.

**How to reproduce it (minimal and precise):**

- Create a cluster on v14.2.8 or newer
- `kubectl create -f pool.yaml`
- `kubectl create -f object.yaml`

The object store will fail to be configured and rgw daemons will not start due to errors with pool creation.

**Comment by jdurgin** [comment]
I'd suggest rook set pg_num_min to rgw_rados_pool_pg_num_min (8 by default) when it is creating the rgw metadata pools.

In a small cluster (such as 3 OSDs) a larger number of PGs isn't so impactful, since the total number won't cause mgr bottlenecks and the CPU impact of peering isn't as important as with more OSDs/node. So increasing the threshold is not a bad option for a small cluster. You'd want to adjust it back down when the cluster grows larger though. So in that sense it is only a temporary fix.

A better option would be to set the minimum pg num on the rgw pools rook is creating similar to how RGW itself does it. When rgw creates the pools, it uses the ceph option rgw_rados_pool_pg_num_min to determine the metadata pools'  pg_num_min. This is set to 8 by default.

Since rook is often used for smaller clusters, where more parallelism for rgw metadata is unnecessary, this seems like a reasonable default.

**Comment by travisn** [comment]
@jdurgin Makes sense to go ahead and use the `rgw_rados_pool_pg_num_min` setting for the requested pg count on the metadata pools, thanks for the recommendation. 

Is there a similar concept for the cephfs metadata pool, or it is just for rgw? I'm not seeing such an option.

**Comment by jdurgin** [comment]
For cephfs it is hardcoded to 16.

There are a couple other metadata pool settings rook may want to duplicate. There's an option for rgw for each, and they're hardcoded again in cephfs.

```pg_autoscale_bias = 4``` -> treat metadata as 4x its size for autoscaling purposes
```recovery_priority = 5``` -> recovery metadata first, since it is required to access data

If rook is using the cephfs volume creation commands like ```ceph fs new```, these are set automatically: https://github.com/ceph/ceph/blob/octopus/src/mon/FSCommands.cc#L258

For reference the rgw settings are used here: https://github.com/ceph/ceph/blob/octopus/src/rgw/rgw_tools.cc#L65

**Comment by travisn** [comment]
> There are a couple other metadata pool settings rook may want to duplicate. There's an option for rgw for each, and they're hardcoded again in cephfs.

> pg_autoscale_bias = 4 -> treat metadata as 4x its size for autoscaling purposes
> recovery_priority = 5 -> recovery metadata first, since it is required to access data

What are the defaults? In this case I would hope the defaults would work for rook to reduce the need to dive into the detailed settings.

> If rook is using the cephfs volume creation commands like ceph fs new, these are set automatically: https://github.com/ceph/ceph/blob/octopus/src/mon/FSCommands.cc#L258

Correct, rook is calling `ceph fs new` so it sounds like we're covered already, thanks

**Comment by jdurgin** [comment]
> > There are a couple other metadata pool settings rook may want to duplicate. There's an option for rgw for each, and they're hardcoded again in cephfs.
> 
> > pg_autoscale_bias = 4 -> treat metadata as 4x its size for autoscaling purposes
> > recovery_priority = 5 -> recovery metadata first, since it is required to access data
> 
> What are the defaults? In this case I would hope the defaults would work for rook to reduce the need to dive into the detailed settings.

1.0 and 0 - I expect these will work for rook in most cases. Perhaps in the future rook could use an rgw command that would create the pools so rook wouldn't need to worry about any of these - @cbodley is there already such a command that creates the pools for rgw, similar to ```ceph fs new```?

**Comment by cbodley** [comment]
no, radosgw just autocreates pools when it tries to write something there. the relevant logic is in [rgw_init_ioctx()](https://github.com/ceph/ceph/blob/octopus/src/rgw/rgw_tools.cc#L42-L100). it looks like you can control how radosgw creates them by customizing the values of `rgw_rados_pool_autoscale_bias`, `rgw_rados_pool_pg_num_min`, and `rgw_rados_pool_recovery_priority`

**Comment by travisn** [comment]
@jdurgin Actually Rook creates the pools for cephfs before calling `ceph fs new`. This is similar to the pattern of creating the pools before the object store so that we can control the pool settings such as EC and replication. What's good about the `fs new` command is that it takes care of some things like the default pg count and application name for the pools.
