### ISSUE TITLE
ceph mds deactivate is not valid command

### ISSUE THREAD

**Issue by ashangit** [rook/rook#5278]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When scaling down number of mds instances rook try to execute this command `2020-04-15 20:20:37.941817 D | exec: Running command: ceph mds deactivate myfs2:1 --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/116420211`
But ceph mds deactivate does not exist anymore on ceph Nautilus at least.
It doesn't failed the scalee down but leads to some useless warn issue and useless command to be run with retry mechanism

**Expected behavior:**
Don't run this command and ensure current mechanism to down scale is adapt to Nautilus/Octopus ceph release

**How to reproduce it (minimal and precise):**

- create CephFilesystem with 2 metadata active server
- down scale metadata acctive server to 1

**Comment by BlaineEXE** [comment]
IIRC from looking back at the code, the scaling isn't needed for Nautilus+. @jan--f is the right person to say for certain I think.

**Comment by jan--f** [comment]
Unfortunately this is still necessary. Proper upgrades of multi-active MDS clusters is on the roadmap for pacific.

For nautilus and later the scale down is achieved by simply setting `max_mds` to one. This is a per filesystem command: `ceph fs set <fs_name> max_mds 1`

**Comment by rajatsingh25aug** [comment]
Hi, I started looking into this issue and I tried reproducing it. Can you guys please provide some clarification?.

 I created a `FileSystem` on my `rook-ceph` cluster  (on minikube and it's a single node cluster) with `mds` equals to 3.

I tried the above command by @jan--f to scale it down via the ceph toolbox. But my `ACTIVEMDS` wont change after firing the command below.
`ceph fs set myfs max_mds 1`

```
oc get cephfilesystem.ceph.rook.io                     
NAME   ACTIVEMDS   AGE
myfs   3           21m
```

Does this needs to be fixed?. Was the expected behaviour was that after firing the above command, the count should come down to 1?. 

Thanks.

**Comment by jan--f** [comment]
Hmm certainly no rook expert here, but this looks like output from rook or k8s? Can you check what ceph thinks about this? Just a `ceph -s` would do or alternatively `ceph fs status`.

**Comment by rajatsingh25aug** [comment]
> Hmm certainly no rook expert here, but this looks like output from rook or k8s?
This output is from the toolbox pod running in the rook ceph cluster.
 >Can you check what ceph thinks about this? Just a `ceph -s` would do or alternatively `ceph fs status`.
ceph -s shows `HEALTH_WARN` as I'm running a single node cluster over Minikube.

**Comment by jan--f** [comment]
I wasn't so much interested in the health status but rather the mds daemon line. Wondering if Ceph also still has 3 active MDS daemons in the cluster or if we're seeing a rook caused artifact.

**Comment by travisn** [comment]
@rajatsingh25aug When you run the ceph commands in the toolbox, the changes will not be reflected in the CRs. The "ActiveMDS" property in the CR will only show what the CR state is, rather than the ceph state.

During an upgrade, `client.SetNumMDSRanks()` is called with the last argument of `1`, meaning that the MDS daemons should be scaled down. When being scaled down, instead of calling `deactivate`, that method should set the max_mds to 1 as Jan mentioned. Then when the upgrade is completed, rook will call `client.SetNumMDSRanks()` again with the original number of mds daemons requested from the CR setting, and we should again set the max_mds to the original value.
