### ISSUE TITLE
ceph: upgrading helm chart from 1.3.1 to 1.3.2 fails

### ISSUE THREAD

**Issue by billimek** [rook/rook#5341]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When trying to upgrade the rook-ceph helm chart from 1.3.1 to 1.3.2, helm is failing with the following error,

```
dry-run upgrade for comparison failed: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: , name: psp:rook, existing_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole, new_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole" phase=dry-run-compare
```

If I manually delete the `ClusterRole/psp:rook`, the helm, upgrade will now proceed without error,

e.g. `kubectl -n rook-ceph delete clusterrole psp:rook`

Speculation that [this recent change](https://github.com/rook/rook/pull/5297/files#diff-86424e092115d22f58b9822e799d8fbcR500) may be related to the source of the error given that this behavior has not occurred with previous helm upgrades of the rook-ceph chart.

**Expected behavior:**

Helm upgrades would progress without error.

**Environment**:
* OS (e.g. from /etc/os-release): `k3os`
* Kernel (e.g. `uname -a`): `Linux k3s-0 5.0.0-43-generic #47~18.04.1 SMP Wed Apr 1 16:27:01 UTC 2020 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `bare metal`
* Rook version (use `rook version` inside of a Rook Pod): `1.3.1`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.6 (f0aa067ac7a02ee46ea48aa26c6e298b5ea272e9) nautilus (stable)`
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `k3s`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by travisn** [comment]
@binoue Please take a look at this. How can we avoid this issue during the upgrade? Looks related to #5297.

**Comment by binoue** [comment]
@travisn 

I will check immediately.

**Comment by binoue** [comment]
@travisn @billimek 

I checked helm source codes and issues.
This is probably the same issue as [this](https://github.com/helm/helm/issues/7697).

The problem is below
`helm upgrade` acts as follows:
- `helm upgrade` detects new resources between the old chart and the new chat.
- Before applying the new resources, check if they are already existing [here](https://github.com/helm/helm/blob/v3.1.3/pkg/action/upgrade.go#L220-L222). 
- If they exist, return an error [here](https://github.com/helm/helm/blob/v3.1.3/pkg/action/validate.go#L29-L48).

Therefore,
-  ClusterRole(v1) does not exist in the current helm chart, so the ClusterRole is defined as a new resource.
- Try to get the ClusterRole(v1) to confirm that the resource already exists
- Kubernetes returns the ClusterRole(v1) if it is deployed as ClusterRole(v1beta1).
- The step above fails and `helm upgrade` fails

The helm source code does not have an option to ignore the checking process, 
so the possible solutions are as follows:
- delete the clusterrole in advance of upgrading  
- roll back the ClusterRole group version to v1beta1 by the rook side

**Comment by travisn** [comment]
@binoue What about adding the annotations as described in the issue you linked in [this comment](https://github.com/helm/helm/issues/7697#issuecomment-613535044)? Does that not fix this?

**Comment by binoue** [comment]
@travisn 

Since helm v3.2.0 and  v2.16.6, the annotation becomes valid. 
So, if users can upgrade their helm version to the newest version of v3 or v2, I think the solution works fine.

**Comment by binoue** [comment]
@travisn 

Should I write this upgrade workaround(delete the ClusterRole or upgrade helm version and add annotation) on [helm-operator.md](https://github.com/rook/rook/blob/master/Documentation/helm-operator.md) or roll back the ClusterRole in the rook helm chart?

In my opinion, write the upgrade workaround on [helm-operator.md](https://github.com/rook/rook/blob/master/Documentation/helm-operator.md)  would be better.

**Comment by travisn** [comment]
@binoue Agreed, sounds good to document to use the latest release. Also the upgrade guide ceph-upgrade.md could mention this failure. thanks

**Comment by binoue** [comment]
@travisn 

Sorry for my late replay.
I took a vacation. I will make the PR mentioned in the comment above.

Thanks

**Comment by binoue** [comment]
@travisn 

I documented this workaround in #5445 .
For the documenting, I verified that it was valid with my Kubernetes by upgrading from rook v1.2.7 to v1.3.2 and  v1.3.1 to v1.3.2.
