### ISSUE TITLE
Create an out-of-tree volume provisioner in the operator instead of using kubernetes.io/rbd

### ISSUE THREAD

**Issue by luxas** [rook/rook#538]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/volume-provisioning.md has more information how to do that

I spoke to @bassam about this and described it in more detail, @bassam please fill in with more details.
(I'm having a limited time per issue I'm creating now)

**Comment by luxas** [comment]
examples here: https://github.com/kubernetes-incubator/external-storage

**Comment by kokhang** [comment]
Hi @luxas. Thank you for showing us this option. So the idea that you are suggesting is to provision/delete volumes using the external-provisioner and use the current RBD plugin for Kubelet to attach/detach the volume.

Doing the attach requires Ceph Monitoring endpoint. In RBD, users pass those in explicitly. Our vision with the in-tree is for the Rook plugin to discover these endpoint.

Is there an external attacher/detacher volume plugin in kubernetes just like the external provisioner?

**Comment by kokhang** [comment]
@bassam answered me my question. When provisioning a volume, the end result is a PersistentVolume object which contains a VolumeSource object. We can prepopulate the monitor endpoint in this object. 

I will create a design doc shortly illustrating the steps for this work.

**Comment by kokhang** [comment]
# Out-of-tree Volume Provisioner
## Background:
Currently, to provision and consume Rook volumes in Kubernetes, we use the existing RBD in-tree volume plugin. Although this works well, using the RBD plugin has the following limitation:

- It requires ceph-tools to be installed. The RBD plugin shells out to `rbd` command to perform all the volume operation (create, delete, mount, unmount). This creates a dependency on the `ceph-tools` package to be install in all the Kubernetes hosts as well as hosts that run the Control-manager.
- You need to specify the Ceph monitor endpoints when using RBD plugin. This is not ideal because user will have to parse of the ceph monitor endpoints which are created and managed by Rook. THe ideal solution is to have these endpoints auto-discoverable so the user doesnt have to specify them.
- Secret/user management. The RBD plugin requires the user to specify a ceph key file or a secret with the ceph user key. Ideally we would want Rook to manage that for the user.

We have explored creating an in-tree volume plugin for Rook but SIG-Storage and the Kubernetes community are moving into a solution in which all storage plugins would be out of tree. We have also explored using Flexvolume but, as its current state, it does not support dynamic volume provisioning.

The goal is of this proposal is to create a volume plugin that will handle all the limitations mentioned previously as well as being easily integrated and deployed within Kubernetes. It would also live out-of-tree (probably in the Rook repo as part of the Rook-operator) and it could be easily migrated to CSI plugin model once it is finalized.

## Usage

The Rook external provisioner is a dynamic PV provisioner that will be deployed and managed by Rook. 

The Rook external provisioner will work just like in-tree dynamic PV provisioners. A StorageClass object will specify Rook as the volume provisioner. Rook will then watch for PersistentVolumeClaims that ask for the StorageClass and automatically create PersistentVolumes for them. 

## Design

The proposal consists of creating a external-storage provisioning controller for Rook. This provisioning controller will manage and provide logic for creating and deleting a Rook volume. This controller will be created by the [Rook-operator](https://github.com/rook/rook/blob/master/Documentation/kubernetes.md). The Rook operator will watch for PVC provisioning events and it will handle them on behalf of Kubernetes.

The external-provisioner model provides an interface that needs to be implemented. The functions are `Provision` and `Delete`.

### Rook-Operator
When the Rook-operator is created, part of its responsibility is to register itself to Kubernetes as a external-provisioning controller. The Rook-Operator will watch for PVC create/delete volume events, handle these events and constructing all required information that Kubernetes needs to mount the volume; such as providing monitor endpoints and users secrets.
 
### Provision Function
The provision function will do the following:

- Parse PVC data to get volume information (name, size)
- Parse StorageClass arguments to get pool information
- Parse StorageClass arguments for user-secret name. If not provided, we could fall back to a default name. The user secret name will be the name of the Kubernetes secret that contains the user Ceph key used to map the volume. This function will look at the Pod's namespace for this user secret name.
- Get the admin secret from `GET rook-api/client`. This is the ceph credential to use to create/delete the volume. The monitor endpoints will also be provided by this API call.
- Contact the rook-api to create a block with all the information from the PVC and StorageClass.
- Create a PersistentVolumeSource object with all the information that Kubernetes will need to mount the block volume; such as user secret, monitor endpoint, image name and pool name).

### Delete Function
The function will parse the PersistentVolumeSource object provided by Kubernetes and contact the Rook-api to delete the block volume.

**Comment by bassam** [comment]
This looks very promising.

I would front load the PR to modify the rbd plugin so that it catches the next maintenance release. Also might be good to relax the need for modprobe at the same time. We might also need to fix the cephfs plugin in a similar way.

Can you please add some some examples of what the storageclass and pvc specs look like for this approach?

Also I think the operator should handle the provisioning itself. No need for a new deployment for the provisioner. This increases the priority for the operator to run HA and support the leader election pattern. An operator would need to be running now for dynamic provisioning to work.

**Comment by kokhang** [comment]
I actually prefer for the provisioner to run as a separate deployment (initiated by the operator). Just like how the operator is initiating the monitor/osd/rook api. This keeps the provisioner decoupled from the operator and the operator is not trying to do too much. Also, we could house the provisioner in https://github.com/kubernetes-incubator/external-storage, which is where all external provisioners are placed and supported by the Kubernetes community. This would be useful when CSI is ready to go. Our provisioner wont be too coupled with the operator and can be extracted out to follow the CSI model.

**Comment by kokhang** [comment]
Here is how i envisioned the storage class to look like:
```kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: rookblock
provisioner: rook.io/rookblock
parameters:
    pool: fastpool
```

The claim would look like:
```kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
  annotations:
    volume.beta.kubernetes.io/storage-class: rookblock
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi```

These is the same as how it would look if the provisioner was in-tree.

**Comment by bassam** [comment]
One of the advantages of this approach is that provisioner is versioned along with rook. If it were in an external repo then we would need to deal with version coupling and submitting PR upstream to `external-storage`. Not sure its worth it. CSI would give us the same freedom.

>This keeps the provisioner decoupled from the operator and the operator is not trying to do too much.

it would still be decoupled at a code level, just no need to start a new deployment. Think of it from a user's perspective -- the `rook-operator` is our "extension" to Kubernetes to support Rook including TPRs, volume provisioners, etc.

**Comment by bassam** [comment]
also does the claim need `volume.beta.kubernetes.io/storage-provisioner` annotation?

**Comment by kokhang** [comment]
I dont think so.. I think you can use the standard `volume.beta.kubernetes.io/storage-class`.  For example. https://github.com/kubernetes-incubator/external-storage/blob/master/ceph/cephfs/claim.yaml#L6 and https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/deploy/claim.yaml#L6.

I will confirm this once i start testing this.

**Comment by kokhang** [comment]
> If it were in an external repo then we would need to deal with version coupling and submitting PR upstream to external-storage
I dont think this is a big concern. I dont foresee the provisioner changing a lot. 

> the rook-operator is our "extension" to Kubernetes to support Rook including TPRs, volume provisioners, etc
I see TPR to be different than volume plugin. TPR is to extend the API. Volume plugin is to add more storage backend support to Kubernetes storage model. Also, you could argue you could use the provisioner without using the Rook operator.

If we house the provisioner where Kubernetes and its community expect it to be, this would bring more community involvement to the provisioner.

**Comment by bassam** [comment]
> I dont think this is a big concern. I dont foresee the provisioner changing a lot.

the point is that if changes in any slightly incompatible way we would need to deal with versioning issues. For example, Rook v0.6.0 must use provisioner v1.3.5 or newer. This is unnecessary complication, and yet another versioning issue that a user/admin has to deal with.

> I see TPR to be different than volume plugin. TPR is to extend the API. Volume plugin is to add more storage backend support to Kubernetes storage model. Also, you could argue you could use the provisioner without using the Rook operator.

I understand the logical separation. the deployment model can still be combined. The K8S controller manager, follows this pattern, and hosts 10s of provisioners and controllers.

 > If we house the provisioner where Kubernetes and its community expect it to be, this would bring more community involvement to the provisioner.

I don't think this is a big deal. With CSA the provisioners are going to live in separate repo respectively. Community involvement can still happen in the Rook repo which is the focus for all things rook related.

**Comment by luxas** [comment]
I think I agree with @bassam here. At least we can start developing a provisioner here and if we find out there would be a lot of benefits for having it in external-storage (which I doubt), then we can always move it there later.

But my understanding is that external-storage is for solutions like nfs that have no other logical place for k8s-specific PV provisioning.

**Comment by luxas** [comment]
Simplicity might be just the key here.
`kubectl apply -f rook-operator.yaml` once and you have everything you need
