### ISSUE TITLE
CephFS CSI part of volume name/UUID missing from PVC details

### ISSUE THREAD

**Issue by mattirantakomi** [rook/rook#5471]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Volume "second" UUID is not listed on PV/PVC details.

**Expected behavior:**

Volume "second" UUID should be listed in PV/PVC details.

**How to reproduce it (minimal and precise):**

Create PVC with the following YAML:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: test
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph
```

Describe PVC and PV
```
$ kubectl describe pvc test
Name:          test
Namespace:     test
StorageClass:  rook-ceph
Status:        Bound
Volume:        pvc-ff699511-acd3-49c8-ab3b-c25652eacc6f
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"test","namespace":"test"},"spec":{"accessM...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                 Age                From                                                                                                                             Message
  ----    ------                 ----               ----                                                                                                                             -------
  Normal  Provisioning           29s                rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-758f8fc98c-xg2fv_1dee786e-d528-4d54-89a1-12d1997b1be7  External provisioner is provisioning volume for claim "test/test"
  Normal  ExternalProvisioning   28s (x2 over 29s)  persistentvolume-controller                                                                                                      waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by system administrator
  Normal  ProvisioningSucceeded  28s                rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-758f8fc98c-xg2fv_1dee786e-d528-4d54-89a1-12d1997b1be7  Successfully provisioned volume pvc-ff699511-acd3-49c8-ab3b-c25652eacc6f
```

```
$ kubectl describe pv   pvc-ff699511-acd3-49c8-ab3b-c25652eacc6f
Name:            pvc-ff699511-acd3-49c8-ab3b-c25652eacc6f
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    rook-ceph
Status:          Bound
Claim:           test/test
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        1Gi
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            rook-ceph.cephfs.csi.ceph.com
    VolumeHandle:      0001-0018-rook-ceph-0000000000000001-211d8575-94df-11ea-9b70-ce3cc82ba7ff
    ReadOnly:          false
    VolumeAttributes:      clusterID=rook-ceph
                           fsName=rook-ceph
                           mounter=kernel
                           pool=rook-ceph-data0
                           storage.kubernetes.io/csiProvisionerIdentity=1589182355516-8081-rook-ceph.cephfs.csi.ceph.com
Events:                <none>
```

Create deployment with PVC attached with the following YAML. I'm using nginx image in this test just because it contains bash shell.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
        - name: test
          persistentVolumeClaim:
            claimName: test
      containers:
        - name: test
          image: nginx
          volumeMounts:
            - name: test
              mountPath: /test
```

Enter to test pod shell and check /test mount point:

```
$ kubectl exec -it deploy/test bash
root@test-597f7fffb5-t5gxp:/# cat /proc/mounts | grep test
10.128.31.221:6789,10.128.29.160:6789,10.128.30.213:6789:/volumes/csi/csi-vol-211d8575-94df-11ea-9b70-ce3cc82ba7ff/83891b7f-4352-47ed-9575-2ab151e8bbcd /test ceph rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=rook-ceph 0 0
```

Notice that `csi-vol-` UUID `211d8575-94df-11ea-9b70-ce3cc82ba7ff` is listed in as a part of `VolumeHandle`. But the second part/UUID of volume path `83891b7f-4352-47ed-9575-2ab151e8bbcd` is not listed in PVC details. 

This is a problem for us because we are not able to determine that "second part" of volume path without looking it up inside pod. And it could be that we are unable to do that if PVC and deployment is deleted (by an accident or purpose) and we have to restore that PVC from backup which contains full file level backup of whole CephFS.

**Environment**:
* OS (e.g. from /etc/os-release): `Amazon Linux 2`
* Kernel (e.g. `uname -a`): `Linux ip-10-128-9-190.eu-central-1.compute.internal 5.4.20-12.75.amzn2.x86_64 #1 SMP Thu Feb 27 20:41:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `AWS EKS, worker node EC2 instance type t3.large`
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.3.2, go: go1.13.8`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `AWS EKS`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by Madhu-1** [comment]
I don't think we need to consider this as a bug. Please open a separate feature request in cephcsi where we can discuss more about it.

**Comment by mattirantakomi** [comment]
https://github.com/rook/rook/issues/5472

**Comment by matti** [comment]
@Madhu-1 but in a previous version there was no second UUID - so I consider this a bug becauee it breaks the behavior

**Comment by Madhu-1** [comment]
@matti what was the previous version you are referring here? I want to verify it

**Comment by mattirantakomi** [comment]
Previous version was:

```
            - name: ROOK_CSI_CEPH_IMAGE
              value: "quay.io/cephcsi/cephcsi:v2.0.0"
            - name: ROOK_CSI_REGISTRAR_IMAGE
              value: "quay.io/k8scsi/csi-node-driver-registrar:v1.2.0"
            - name: ROOK_CSI_PROVISIONER_IMAGE
              value: "quay.io/k8scsi/csi-provisioner:v1.4.0"
            - name: ROOK_CSI_SNAPSHOTTER_IMAGE
              value: "quay.io/k8scsi/csi-snapshotter:v1.2.2"
            - name: ROOK_CSI_ATTACHER_IMAGE
              value: "quay.io/k8scsi/csi-attacher:v2.1.0"
            - name: ROOK_CSI_RESIZER_IMAGE
              value: "quay.io/k8scsi/csi-resizer:v0.4.0"
```

Rook version: `rook/ceph:v1.2.4`

**Comment by Madhu-1** [comment]
let me check and get  back

**Comment by Madhu-1** [comment]
here is my analysis

# Rook master

## Mount output from csi-cephfsplugin  
```
10.102.126.34:6789:/volumes/csi/csi-vol-45214d0e-94ee-11ea-b37a-465be7e9e3ba/425d910d-904e-4bb0-8af5-33a86b57b1f7 on /var/lib/kubelet/pods/bb06c9f5-e4b9-4e17-9170-924d4d63ae90/volumes/kubernetes.io~csi/pvc-7578f1bd-5679-4d1b-b464-5f85b7a1800b/mount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=myfs,wsize=16777216,_netdev)
```
## Command used by cephcsi to create subvolume
```
fs subvolume create myfs csi-vol-1c581ab2-94ef-11ea-99ee-b6b04eaa57ef 1073741824 --group_name csi --mode 777 -m 10.102.126.34:6789 -c /etc/ceph/ceph.conf -n client.csi-cephfs-provisioner --keyfile=***stripped*** --pool_layout myfs-data0
```

## Get subvolume path from toolbox pod
```
sh-4.2# ceph fs subvolume getpath myfs csi-vol-1c581ab2-94ef-11ea-99ee-b6b04eaa57ef --group_name csi
/volumes/csi/csi-vol-1c581ab2-94ef-11ea-99ee-b6b04eaa57ef/0075d55a-2729-431e-b6ff-f4acfcbf9b14
```
## ceph version
```
sh-4.2# ceph version
ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable)
```
# Rook v1.2.4

## Mount output from csi-cephfsplugin  
```
10.110.19.139:6789:/volumes/csi/csi-vol-d16926c9-94ff-11ea-82a4-0242ac110008 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89f0e34c-c67a-4810-aa15-6cb1f75bbb91/globalmount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=myfs)
```
## Command used by cephcsi to create subvolume
```
fs subvolume create myfs csi-vol-d16926c9-94ff-11ea-82a4-0242ac110008 1073741824 --group_name csi --mode 777 -m 10.110.19.139:6789 -c /etc/ceph/ceph.conf -n client.csi-cephfs-provisioner --keyfile=***stripped*** --pool_layout myfs-data0
```

## Get subvolume path from toolbox pod
```
sh-4.2# ceph fs subvolume  getpath myfs csi-vol-d16926c9-94ff-11ea-82a4-0242ac110008 --group-name csi
/volumes/csi/csi-vol-d16926c9-94ff-11ea-82a4-0242ac110008
```
## ceph version
```
sh-4.2# ceph version
ceph version 14.2.6 (f0aa067ac7a02ee46ea48aa26c6e298b5ea272e9) nautilus (stable)
```
from the above logs i can see subvolume path has be changed in Octopus, this is not something related to cephcsi , things are changed in cephfs itself. 

@joscollin @kotreshhr any specific reason why it has changed in ceph octopus?

**Comment by kotreshhr** [comment]
@Madhu-1 @mattirantakomi 
Yes, the subvolume path is changed in cephfs when the subvolume clone feature is introduced. But it should not cause any problems. The subvolume created with new version (with subvol clone feature) would return subvolume path with UUID and subvolume created in older version would return subvolume path with out UUID. I didn't quite understand how this is causing an issue at PV/PVC info ?

**Comment by mattirantakomi** [comment]
We have had full backup (done by Duplicity and stored on S3) of CephFS and all PVC details (kubectl describe pvc), so we have been able to know eg. "index.php" file full path on CephFS backed PVC. Full path is needed when doing file level restore with Duplicity from CephFS backup stored on S3.

`ceph fs subvolume getpath` command can't be used in case PVC is already deleted and we have to restore files from it from backup.

**Comment by kotreshhr** [comment]
@Madhu-1 Can the CSI layer fill in that information to be displayed in kubectl describe pv/pvc ?

**Comment by Madhu-1** [comment]
> @Madhu-1 Can the CSI layer fill in that information to be displayed in kubectl describe pv/pvc ?

Yes, we can add a subvolume path to CSI attributes in the PV spec. we need a  feature request in https://github.com/ceph/ceph-csi repo with details.

**Comment by mattirantakomi** [comment]
> Yes, we can add a subvolume path to CSI attributes in the PV spec. we need a feature request in https://github.com/ceph/ceph-csi repo with details.

https://github.com/ceph/ceph-csi/issues/1079

**Comment by joscollin** [comment]
@mattirantakomi This is not a bug in Ceph. It is called Subvolume Versioning.

@matti @kotreshhr @Madhu-1 
You guys are mixing up incompatible versions and claiming that there is a bug. The Versioned Subvolumes are introduced since v14.2.8 Nautilus with backward compatibility. Gather more knowledge about that before doing unnecessary fixes.

**Comment by Madhu-1** [comment]
> @Madhu-1 but in a previous version there was no second UUID - so I consider this a bug because it breaks the behavior

@joscollin please go through the issue, @mattirantakomi @matti explains why its a bug. as this is introduced in the patch release and its incompatible for someone has developed their own logic based on the subvolume get path

**Comment by Madhu-1** [comment]
> @mattirantakomi This is not a bug in Ceph. It is called Subvolume Versioning.
> 
> @matti @kotreshhr @Madhu-1
> You guys are mixing up incompatible versions and claiming that there is a bug. The Versioned Subvolumes are introduced since v14.2.8 Nautilus with backward compatibility. Gather more knowledge about that before doing unnecessary fixes.

@joscollin what is an incompatible version here? can you please explain more.

**Comment by joscollin** [comment]
@mattirantakomi @matti You need to use a version older than v14.2.8 Nautilus, if your software doesn't support subvolume versioning. However, unversioned subvolumes are backward compatible in the newer versions.

@Madhu-1 Please go through my previous reply.

**Comment by kotreshhr** [comment]
> @mattirantakomi This is not a bug in Ceph. It is called Subvolume Versioning.
> 
> @matti @kotreshhr @Madhu-1
> You guys are mixing up incompatible versions and claiming that there is a bug. The Versioned Subvolumes are introduced since v14.2.8 Nautilus with backward compatibility. Gather more knowledge about that before doing unnecessary fixes.

@joscollin 
Nope, this is not a mix up of versioning. And you are right there is no bug in cephFS. The CephFS handles upgrade scenarios of subvolumepath. 

The actual issue is in the consumer layer (kubectl describe pv/pvc) on which the backup mechanism relies on. Before subvolume versioning, only subvolume name was sufficient to construct the complete path. This is available in the output of kubectl describe pv/pvc. With subvolume versioning, since the UUID added to subvolpath is not exposed in the output of kubectl describe pv/pvc, they could not construct the path to backup. Hence they have opened feature request in CSI to display it as volume Attributes in the output of kubectl describe.

@Madhu-1 
It needs to be handled in CSI if the UUID is not present in subvol path, it won't be displayed in volume attributes.

This can be closed against CephFS as not a bug as feature request is opened against CSI.

**Comment by humblec** [comment]
later versions directly record the subvolume name in the volume attributes. Actually speaking I dont like to expose all the backend information to the consumer world especially when storage layer in kube is an abstraction.  However I want to understand the scenario some more better @mattirantakomi . That said, you are saying mentioning you can not retrieve the path in backend cluster when the pvc is deleted. I agree on this , but my question is why you cant record this in the backup itself while PVC is available ?

**Comment by matti** [comment]
still an issue, unstale

**Comment by guimou** [comment]
Hi @humblec 
As you wanted to know more about use cases, here is my scenario where I need this information:
- I'm working on an extension PoC for OpenDataHub.
- I want to provide a shared library of scientific apps/packages to many containers. It works really well with an RWX PVC with the ocs-storagecluster-cephfs storage class. I mount it read-only in the containers when they are spawned and they can then acces the library. It saves including GBs of libraries/applications inside the container images, or maintain lots of images to keep them smaller. Much easier to maintain and to provide reproducibility. Once the package is in the library, it's still accessible years after, not lost due to a container base image update with version change (reproducibility is really important in data science).
- Now, to provide the library, I have to populate it and maintain it regularly by adding new packages. This is a quite convoluted process which is way easier to do from a standard server than from a container (as the libraries are compiled from scratch, there is always some new OS packages to install/update, and rebuilding a container image everytime you have to do that is long).
- So I have created a VM directly in OpenShift, thanks to the Virtualization feature. But as it is now (someone correct me if I'm wrong), you cannot directly connect the "library PVC" to it as you do for containers. That's not really an issue, as I can directly mount the CephFS filesystem inside the VM (as described here: https://github.com/rook/rook/blob/master/Documentation/direct-tools.md#shared-filesystem-tools). That part is working perfectly.

Now the issue:
It's quite easy to find in the mounted filesystem where the "volume" corresponding to my PVC is. The path is something like:
`/volumes/csi/csi-vol-d614a4ea-67d2-11eb-a5c5-0a580a830949/94734876-f214-491f-8459-5804752efcc7`
The `csi-vol-d614a4ea-67d2-11eb-a5c5-0a580a830949` part can be found in the subvolume parameter of the corresponding PV. So I can extract it with a simple oc command and some parsing. Good.
But the `94734876-f214-491f-8459-5804752efcc7` part is not in this yaml file, nor accessible somewhere else in kubernetes. Meaning the only way to get it is to mount the filesystem from the root in the beginning, figure out what it is, then remount directly at this point. Granted, I could mount at the csi-vol-xxxx level, but then I have to navigate to a subfolder which I don't know the name in advance. So not really clean, not practical to automate this. If I had access to the full info from the YAML file, one k8s query, fetch the name, mount the volume, end of the story.
Granted, this may be a fringe use case, but this will be a great feature to add in the environment. So any way to make it easier to deploy it is welcome!

**Comment by humblec** [comment]
@guimou thanks for the detailed explanation. Indeed I see your use case. As mentioned earlier its kind of exposing all the details to the end user. however while we record this in the PV object, which is normally the admin property , I believe its OK. The UUID generation and may be its manipulation can change in future, so take a precaution while deriving the logic in your software , with that, lets expose it for now. Thanks !
