### ISSUE TITLE
Missing placement and resources for some daemon

### ISSUE THREAD

**Issue by leseb** [rook/rook#5546]
The placement and resources from the spec are incorrect for some daemons, outdated and not reflected for all the CRD. A bit of cleanup/enhancement is needed.

**Comment by leseb** [comment]
@vbnrh

**Comment by leseb** [comment]
If you look into github.com/rook/rook/pkg/apis/rook.io/v1, especially in these files:

* annotations.go
* keys.go
* placement.go
* priorityclasses.go
* resources.go

You will notice some inconsistencies like not all the daemons re equally present. This could mean some of the daemons are missing the above directives.
The goal is to homogenize the code and add/fix missing pieces.

**Comment by travisn** [comment]
Per discussion in huddle, the helper methods in `pkg/apis/ceph.rook.io/v1` for retrieving annotations, resources, and placement only apply to the settings in the CephCluster CR. Those artifacts that are from another CR such as RGW, CephFS, and rbd mirroring are less complex since they are individually applied in other CRs and don't need to be merged with the `all` specs. 

The only place I see that needs updating for consistency is to remove the `GetRGWAnnotations()` function that is not used anywhere.
