### ISSUE TITLE
Update docs with some advanced guidance

### ISSUE THREAD

**Issue by jbw976** [rook/rook#558]
@bzub has given the community some super useful advanced guidance and steps on the gitter channel https://gitter.im/rook/rook.  Some of this should be captured in an advanced docs section for when users need to go off the beaten path via the rook toolbox.

Also some useful info here: https://github.com/rook/rook/issues/554#issuecomment-292167563

**Comment by bzub** [comment]
Here's what I came up with: https://gist.github.com/bzub/e17273f3ab984f0a27b492f7ad47a5b3

Before I submit a PR I'd like feedback on where the documentation should go in the repo and suggested filename?  Other suggestions? @kokhang @jbw976 @hunter @travisn @bassam 

I also plan on adding:
- [ ] Links to relevant Rook/Ceph documentation inline
- [ ] Test the OSD info script and make it work with Filestore backed OSDs
- [ ] Add a Table Of Contents

**Comment by travisn** [comment]
Thanks @bzub for putting this together, this is great! A lot of good pointers here and workarounds for issues. Here are a few thoughts on the doc.

- To reference this doc from others, I would suggest:
    - Documentation/README.md: add a section similar to the Toolbox section
    - README.md, let's rename the "Troubleshooting Toolbox" section to "Advanced Configuration and Troubleshooting", then mention the toolbox and this new box. @jbw976 sound ok?
- I'd suggest saving it in Documentation/advanced-configuration.md. 
- Since the toolbox could be run in kubernetes or standalone environments, as much as possible I'd suggest you assume that they are already inside the toolbox. More of the commands won't need the prefix `kubectl -n rook exec rook-tools`, which perhaps makes it more readable, and makes it more re-usable for standalone.
- Reweight your OSDs: This is primarily necessary due to bug #477, right? Seems appropriate to mention the issue in the docs. We really need to get that fixed. 
- typo: "many most cases"
- you suggested running `rook node status`. Did you mean `rook status`?
- We should really make it easier to apply custom ceph config to the pods. Want to open an issue for that?
