### ISSUE TITLE
Setting bucket policies via rook for ceph object store

### ISSUE THREAD

**Issue by thotz** [rook/rook#5663]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add support for setting bucket policies via rook for ceph object store
**What is use case behind this feature:**
Currently bucket policies can be set on via s3 clients. But this object store user specific, with this feature it will more like admin specific in which policy can be applied to any bucket in the object store. 

**Environment**:

**Comment by galexrt** [comment]
@thotz what is the status of this issue?

**Comment by zerkms** [comment]
.

**Comment by electrical** [comment]
Following up on this after a discussion in slack ( https://rook-io.slack.com/archives/CK9CF5H2R/p1615168246331300 )
In my use case I want to create different buckets to hold different pieces of data but I have different users/apps that need access to the different buckets with different permissions ( read-only vs write access for example )

At the moment it's only possible to have ACL on the bucket directly which can work with some scripting around it.
It would be great if we could put ACL's on the user for example.
I do appreciate that ACL's aren't an easy thing to manage because you can view it from different angles, so happy to have a further discussion about it :-)

**Comment by ppoetz** [comment]
Would be really great to have this feature in a future release.
Our use-case is pretty simple: We need to have publicly accessible objects (Read) so our react app can access well known bucket urls to load its images. But the out-of-the-box bucket-claim is permissive and so we need an additional scripted k8s job which sets permissions right via some s3 client.

**Comment by thotz** [comment]
The COSI project(new upgrade for BucketClaims) initially planned to add bucket policies in their API path. But now they are not planning to implement the alpha version. Hence didn't move forward with this feature, waiting more COSI to map out their plan

**Comment by thotz** [comment]
Not planning work on this feature, hence closing it
