### ISSUE TITLE
Rook 1.2 Ceph OSD Pod memory consumption very high

### ISSUE THREAD

**Issue by alexcpn** [rook/rook#5821]
**Existing Related**
https://github.com/rook/rook/issues/5811
https://github.com/rook/rook/pull/2764 -->
https://github.com/ceph/ceph/pull/26856

**Is this a bug report or feature request?**
 Bug Report

**Deviation from expected behaviour:**
There is no guideline to set the rook-ceph pod memory limits. So we haven't set any. However, though the internal 
 osd_memory_target is set as the default 4 GB,** I could see in the ceph osd pool top command that it is taking 8 GB as resident set memory and more as virtual memory

```
**ceph config get osd.0 osd_memory_target 
4294967296 

https://ceph.com/releases/v12-2-10-luminous-released/   -- The bluestore_cache_* options are no longer needed.. They are replaced by osd_memory_target, defaulting to 4GB. BlueStore will expand and contract its cache to attempt to stay within this limit. 

```
Inside the OSD pod - top command
![image](https://user-images.githubusercontent.com/1157251/87397468-066f8f80-c5d2-11ea-9dd4-04483897cad6.png)

Grafana dashboard

Pod Name | Memory Usage | File System Usage | CPU | Network(I) | Network(o)
-- | -- | -- | -- | -- | --
rook-ceph-osd-2-bb5b46984-wkstx | 179.27 GB | 311.30 kB | 11.28% | 15 Tbps | 8 Tbps
rook-ceph-osd-0-7cf65bdb4d-xs2tw | 183.91 GB | 327.68 kB | 10.64% | 16 Tbps | 9 Tbps
rook-ceph-osd-1-6c7fd5b8bf-24bhk | 181.65 GB | 311.30 kB | 10.44% | 18 Tbps | 9 Tbps
rook-ceph-mgr-a-bbcf558b7-l4nqg | 702.88 MB | 202.21 MB | 4.74% | 413 Gbps | 93 Gbps
rook-ceph-mon-e-5b4bf84f4f-z6dn4 | 2.07 GB | 234.18 MB | 0.63% | 53 Gbps | 133 Gbps
rook-ceph-mon-d-57df95d979-8mtq2 | 1.73 GB | 213.33 MB | 0.43% | 62 Gbps | 5 Gbps
rook-ceph-mon-f-7c85d58c4f-488bc | 1.70 GB | 210.13 MB | 0.39% | 61 Gbps | 5 Gbps
rook-ceph-rgw-rook-ceph-objstore-a-5b9c8dcb54-qjkzr | 899.08 MB | 217.36 MB | 0.27% | 69 Gbps | 70 Gbps
rook-ceph-tools-9b657cbf-t2m9k | 42.56 MB | 258.05 kB | 0.07% | 8 Tbps | 7 Tbps

memory growth - Last 14 days

![image](https://user-images.githubusercontent.com/1157251/87398043-f60be480-c5d2-11ea-811a-b45de3b41865.png)

**Expected behavior:**
At the max the Ceph-OSD pod should take 4GB  for ceph-osd process and say may 1 or 2 GB more for other process running inside the pod

**How to reproduce it (minimal and precise):**
Running for few days observed this 

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS
* Kernel (e.g. `uname -a`):
(
* Cloud provider or hardware configuration:
HP Servers
* Rook version (use `rook version` inside of a Rook Pod):
rook 1.2
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable) 
* Kubernetes version (use `kubectl version`):
Kubernetes 1.16
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Custom
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

HEALTH_WARN crush map has legacy tunables (require firefly, min is hammer); 9 pool(s) have non-power-of-two pg_num; too many PGs per OSD (766 > max 250)

**Comment by alexcpn** [comment]
It seems grafana dashboard was wrong. Went into the node with the pod, found out the pod process id and it is taking only less

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND 
23748 167       20   0 6613980   1.1g  31748 S   0.7   0.9  54:57.30 ceph-osd 
--
sudo pmap -x 23748
23748:   ceph-osd --foreground --id 3 --fsid 14b73e8c-8d87-4887-9921-d83074868f71 --setuser ceph --setgroup ceph --crush-location=root=default host=da-cicd-enc1-bl12 --default-log-to-file false --ms-learn-addr-from-peer=false

---------------- ------- ------- ------- 
total kB         6613984 1173952 1142088

**Comment by alexcpn** [comment]
Right Grafana metrics calculation

```
To calculate container memory utilization we use:

sum(container_memory_working_set_bytes{name!~"POD"})
  by (name)
In the above query, we need to exclude the container who’s name contains “POD”. This is parent cgroup for this container and will track stats for all the containers in the pod.
```

 https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-3-container-resource-metrics-361c5ee46e66​​​​​​​

A Deep Dive into Kubernetes Metrics — Part 3 Container Resource Metrics
This is part 3 of a multi-part series about all the metrics you can gather from you Kubernetes cluster.

**Comment by JieZeng1993** [comment]
you closed this isuuse, then if you already resolve this problem, Could you tell how to resolve this problem?

**Comment by galexrt** [comment]
@JieZeng1993 From what I understand, @alexcpn "fixed" the issue by fixing the query for the graph used to monitor the memory usage of Kubernetes Pods (including the OSD Pods).

**Comment by raj-katonic** [comment]
Facing the same issue, every osd pod is consuming 4GB RAM on average. Please can anyone let me know why it needs so much ?

**Comment by travisn** [comment]
@raj-katonic Did you set memory requests/limits on the OSDs? See [this topic](https://rook.github.io/docs/rook/v1.8/ceph-cluster-crd.html#cluster-wide-resources-configuration-settings). The recommended memory is generally 4GB per osd in production, but smaller clusters could set it lower if needed. But if these limits are not set, the osd will potentially use a lot more memory since it is not aware of any limits.

**Comment by zhucan** [comment]
@travisn I have a question, why the default_osd_memory_target is 4G, but we need to set requests/limits on the OSDs？ And why ceph osd pod memory consumption very high more than 4G?

**Comment by zhucan** [comment]
@travisn I have a question, why the default_osd_memory_target is 4G, but we need to set requests/limits on the OSDs？ And why ceph osd pod memory consumption very high more than 4G?

**Comment by travisn** [comment]
I'm not sure about the `default_osd_memory_target`, the OSD must not respect that strictly like it will respect the `osd_memory_target` that is picked up by the OSD when the resource limits/requests are set.

**Comment by microyahoo** [comment]
@travisn I have noticed that `osd_memory_target` is 4G, but osd memory usage is far more than 4G when not set resource limits/requests like follows.
```
[rook@rook-ceph-tools-7ccf879b55-ljlsv /]$ ceph config get osd.10 osd_memory_target
4294967296
```
![](https://github.com/microyahoo/microyahoo.github.io/blob/master/images/rook/rook%20ceph%20osd%20high%20memory.png?raw=true&ynotemdtimestamp=1648520450059)

**Comment by travisn** [comment]
@microyahoo Did you try setting the resource limits? Setting the resource limits is the recommended way to have the OSDs respect memory usage instead of growing so large like that.

**Comment by microyahoo** [comment]
> @microyahoo Did you try setting the resource limits? Setting the resource limits is the recommended way to have the OSDs respect memory usage instead of growing so large like that.

@travisn No, I didn't set the resource limits. I'm just curious why the `osd_memory_target` setting doesn't take effect to control memory usage.

**Comment by huv95** [comment]
@travisn I am setting memory request/limits to 4G/16G but my osds (usually osds using hdd) often uses more than 80% of the limit. So should I increase the memory limit? If I keep it the same, will it affect performance?

**Comment by travisn** [comment]
> @travisn I am setting memory request/limits to 4G/16G but my osds (usually osds using hdd) often uses more than 80% of the limit. So should I increase the memory limit? If I keep it the same, will it affect performance?

IIRC the OSD will target usage of 80% of the limit, and attempt to not go very far over that. OSDs will basically ignore the requests, so you probably want to set your requests and limits closer for the OSDs. If you increase the memory limit, OSDs will go ahead and use more memory to attempt to be as efficient as possible. But you'll have to test your workloads to see how overall performance is affected in your cluster.

**Comment by joehou89** [comment]
out ceph cluster version is ceph 10.2.10 , however,  ceph osd memory is very high 9GB, and physical memory is 126GB in  each storage node ,  data just as follows:
 ATOP - rg2-ceph003                                       2025/04/21  11:31:26                                       -----------------                                       1839d20h58m49 elapsed
PRC | sys   15d05h  | user  64d19h |               |  #proc    588 | #trun	3  | #tslpi  52e3 |               |  #tslpu     8 | #zombie    0  | clones 428e7 |               |  #exit     73 |
CPU | sys     232%  | user     72% |  irq	5% |               | idle   2857%  | wait     35% |  steal     0% |  guest     0% |               | ipc  initial |  cycl initial |  curf 2.10GHz |
CPL | numcpu    32  |              |               |  avg1    2.67 | avg5    4.60  |              |  avg15   5.38 |               |               | csw 124404e8 |  intr 26191e7 |		 |
MEM | tot   125.4G  | free    2.4G |               |  cache   7.8G | dirty 144.4M  | buff    9.2M |               |  slab    1.4G | slrec 573.7M  |              |  pgtab 395.3M |		 |
MEM | numnode    2  |              |  shmem   4.0G |               | shrss   0.5M  | shswp   0.0M |               |  tcpsk   6.0M | udpsk   0.0M  |              |               |		 |
SWP | tot     0.0M  | free    0.0M |               |  swcac   0.0M |               |              |               |               |               | vmcom 454.0G |  vmlim  62.7G |		 |
PAG | scan 64789e6  | steal 6456e7 |  stall 4202e4 |               | compact 24e6  | numamig 89e8 |  migrate 15e9 |  pgin 19609e8 | pgout 2417e9  |              |  swin       0 |  swout      0 |
LVM | 3122757-pool  | busy	0% |  read   85995 |  write 172908 | KiB/r     15  | KiB/w     20 |               |  MBr/s    0.0 | MBw/s    0.0  | inflt      0 |  avq     6.45 |  avio 0.12 ms |
LVM | 7-659925b4e6  | busy	0% |  read   28048 |  write  26170 | KiB/r     16  | KiB/w     28 |               |  MBr/s    0.0 | MBw/s    0.0  | inflt      0 |  avq     1.35 |  avio 0.18 ms |
LVM | 7-fef5402e38  | busy	0% |  read   11727 |  write  82374 | KiB/r     13  | KiB/w     19 |               |  MBr/s    0.0 | MBw/s    0.0  | inflt      0 |  avq     4.36 |  avio 76.5 µs |
LVM | 7-dd6e3bb5e2  | busy	0% |  read    5020 |  write   9045 | KiB/r     22  | KiB/w     32 |               |  MBr/s    0.0 | MBw/s    0.0  | inflt      0 |  avq     1.73 |  avio 0.23 ms |
DSK |          sdl  | busy	3% |  read 15368e5 |  write 1144e7 | KiB/r    210  | KiB/w     16 |               |  MBr/s    2.0 | MBw/s    1.2  | inflt      0 |  avq     0.44 |  avio 0.33 ms |
DSK |          sdk  | busy	3% |  read 14932e5 |  write 1072e7 | KiB/r    213  | KiB/w     16 |               |  MBr/s    2.0 | MBw/s    1.1  | inflt      0 |  avq     0.94 |  avio 0.33 ms |
DSK |          sdg  | busy	2% |  read 14264e5 |  write 1118e7 | KiB/r    210  | KiB/w     15 |               |  MBr/s    1.8 | MBw/s    1.1  | inflt      0 |  avq     1.09 |  avio 0.31 ms |
NET | transport     | tcpi 83898e7 |  tcpo 17100e8 |  udpi 69478e3 | udpo 12136e4  | tcpao 3093e4 |  tcppo 1703e6 |  tcprs 2784e5 | tcpie     33  | tcpor 1094e6 |  udpnp 804036 |  udpie   9098 |
NET | network       | ipi 839095e6 |  ipo 171044e7 |               | ipfrw	0  | deliv 8391e8 |               |               |               |              |  icmpi 4145e4 |  icmpo 6273e4 |
NET | enp59s0   0%  | pcki 10930e8 |  pcko 99952e7 |  sp   10 Gbps | si   60 Mbps  | so   53 Mbps |  coll	0 |  mlti 5298793 | erri       0  | erro       0 |  drpi 1692485 |  drpo       0 |
NET | enp59s0   0%  | pcki 81769e7 |  pcko 69932e7 |  sp   10 Gbps | si   46 Mbps  | so   36 Mbps |  coll	0 |  mlti 5298810 | erri       0  | erro       0 |  drpi 5922636 |  drpo       0 |
*** System and Process Activity since Boot ***                                                                                                                      Unrestricted view (privileged)
   PID      TID    MINFLT    MAJFLT    VSTEXT    VSLIBS     VDATA   VSTACK    LOCKSZ     VSIZE     RSIZE     PSIZE     VGROW    RGROW    SWAPSZ    RUID        EUID          MEM    CMD       1/19
 91211        -    9607e7    2034e4     13.7M     15.3M     45.4G   132.0K      0.0K     46.2G      9.1G        0B     46.2G     9.1G        0B    ceph        ceph           7%    ceph-osd
106288        -    7313e7    1685e4     13.7M     15.3M     44.9G   132.0K      0.0K     45.8G      8.9G        0B     45.8G     8.9G        0B    ceph        ceph           7%    ceph-osd
 71230        -    9115e7    2011e4     13.7M     15.3M     44.8G   132.0K      0.0K     45.6G      8.7G        0B     45.6G     8.7G        0B    ceph        ceph           7%    ceph-osd
101240        -    1030e8    2366e4     13.7M     15.3M     44.9G   132.0K      0.0K     45.7G      8.7G        0B     45.7G     8.7G        0B    ceph        ceph           7%    ceph-osd
111296        -    9586e7    2216e4     13.7M     15.3M     44.6G   132.0K      0.0K     45.5G      8.5G        0B     45.5G     8.5G        0B    ceph        ceph           7%    ceph-osd
 66213        -    7306e7    1647e4     13.7M     15.3M     44.6G   132.0K      0.0K     45.3G      8.4G        0B     45.3G     8.4G        0B    ceph        ceph           7%    ceph-osd
 81213        -    8521e7    1943e4     13.7M     15.3M     44.5G   132.0K      0.0K     45.2G      8.4G        0B     45.2G     8.4G        0B    ceph        ceph           7%    ceph-osd
 76219        -    9371e7    2190e4     13.7M     15.3M     44.4G   132.0K      0.0K     45.2G      8.3G        0B     45.2G     8.3G        0B    ceph        ceph           7%    ceph-osd
 86210        -    7231e7    1430e4     13.7M     15.3M     44.4G   132.0K      0.0K     45.2G      8.2G        0B     45.2G     8.2G        0B    ceph        ceph           7%    ceph-osd
 53066        -    1285e5     41943     13.7M     15.3M     42.3G   132.0K      0.0K     43.0G      6.3G        0B     43.0G     6.3G        0B    ceph        ceph           5%    ceph-osd


how can I analyse this question ?  .

**Comment by travisn** [comment]
@joehou89 Did you see the [OSD requests/limits](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#cluster-wide-resources-configuration-settings)? This is recommended so the OSD memory does not increase to high. See also the helm chart values, which defaults to [4GiB for OSDs](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L302-L307).
