### ISSUE TITLE
Add toleration for csi-version detect pod

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#5879]
Currently, we don't have any toleration for the CSI version detect pod, we need to add toleration for it to schedule the pod on tainted nodes. 

cc @travisn do we need to apply CSI toleration or can we apply the same toleration we apply for ceph version detect pod?

**Comment by travisn** [comment]
Although we delay starting the CSI driver until the CephCluster CR is created, we actually don't use any of the settings in that CR to launch the CSI driver since the settings need to be independent of the cephcluster. Let's apply the tolerations from a CSI driver, for example the rbd csi driver tolerations.

**Comment by Madhu-1** [comment]
Thanks @travisn, sounds good, will send a patch soon.
