### ISSUE TITLE
Refactor End to End Integration Test

### ISSUE THREAD

**Issue by dangula** [rook/rook#626]
Need to do the following. 

- Dump Logs on Test failures(including test set up)
- Refactor Framework to use rook-api
- Clean k8s Utils - Done
- Clean up Running test suites.- Done
- Clean up dind script -
- Clean up slim down rook-infra image. 
- Clean up sleeps in start up script  Done
- Fix interface names to match go naming convention - Done
-Use pkg/util/exec to instead of exec_utils under test framework
- handle cases when exec status 0 with error  message

**Comment by travisn** [comment]
A few minor fixes for this readme: https://github.com/rook/rook/tree/master/e2e
- Extra semicolon after `run the following`
- The command to execute the smoke-test.sh script should be on its own line so it is more obvious to the reader
- The subheadings are not being formatted properly
- For improved readability, would be good to use ticks to quote filenames and paths, instead of quotes. 
- All commands that can be executed should be quoted, usually with triple ticks. In particular, the clean command is just inline
- Instead of "3 node cluster" --> "three node cluster"

**Comment by dangula** [comment]
rook_test_infra.go refactor list
1. add panic to copyImageToNode method
2. rename k8s_node1_container_name to node1ContainerName
3. Make sure go naming conventions are followed everywhere.
