### ISSUE TITLE
Prevent rook from recreating automatically removed OSDs from PVCs

### ISSUE THREAD

**Issue by okossuth** [rook/rook#6287]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Prevent rook from recreating automatically removed OSDs from PVCs

**What is use case behind this feature:**
In cloud environments it would be nice to be able to remove any OSD from a PVC without having rook recreate the removed
OSD automatically minutes later. This doesnt happen if the removed OSD is the one related to the highest index PVC affected.
IMHO that should be the case for any removed OSD from a PVC, like it would behave in bare metal environments.
**Environment**:
rook 1.4.4
Kubernetes 1.18.8
DigitalOcean managed Kubernetes

**Comment by travisn** [comment]
The names of the PVCs are predictable so that the operator can reconcile them consistently after restart. etc. If you are decrementing the count, the operator will stop reconciling the OSDs/PVCs with the highest index. If you remove any other OSD or PVC, the operator will create it again.

Instead of querying by PVC name, I could see Rook querying the PVCs for a label that matches a storageClassDeviceSet identifier. This would allow for holes in the incrementing names. As noted, I would expect this to be primarily an issue in bare metal environments where a local PV might go down and you need to remove it, but it isn't likely to be conveniently named with the highest index.
