### ISSUE TITLE
OSD crashlooping after bump to 14.2.11

### ISSUE THREAD

**Issue by ashangit** [rook/rook#6305]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When moving from ceph 14.2.9 to 14.2.11 some osd pods are crashlooping.
This is due to slow osd startup leading the livenessprobe to fail and finally killed the pod.
Removing the livenessprobe from it make them work fine.
For some of those osds once well startup re activating the probe works fine and for few we had to reinstall them so they respect the livenessprobe timeeout startup.
OSDs are running on HDDs

**Expected behavior:**
Not having osd crashlooping

Could we work on a way to disable the livenesspobe or configure the livenesspobe timeout?

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by TonyBogdanov** [comment]
I'm not part of the project, but I had this happen to me, so I decided to share some insight.

In my case the cluster uses 3 OSDs in replication mode backed by block storage created through PVCs (on a cloud provider). I did, just like you, update (in the manifests) to a newer Ceph version and quickly all OSDs started crash looping once restarted.

My understanding is that Ceph has a strict requirement about the structure of the data on the OSD storage medium, after all it has its own filesystem. That's why there's an init container called prepareosd or something like that. This is (imo) where raw empty block storage is formatted and, I assume, populated with some bootstrap data.

If the new Ceph version expects a different format, the prepareosd should make the necessary adjustments, alas that is probably not the case, if it is possible at all, without losing your data.

I did this when I didn't really have any data at all, so I just recreated it all, but I did wonder if it was possible to "migrate" the data by manually deleting an OSD along with its data, waiting for the operator to recreate it, this time with the new version of Ceph, and then waiting for data to get replicated from the ther two running OSDs before doing the same with them as well. It would be a bit tricky properly timing this manual intervention so that the operator doesn't break it though.

My advice would be, use Ceph as your storage provider, but also figure out how to keep backups for when things inevitably break.

**Comment by travisn** [comment]
@ashangit The osd liveness probe can be modified as in [this example](https://github.com/rook/rook/blob/release-1.4/cluster/examples/kubernetes/ceph/cluster.yaml#L235) or described [here](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#health-settings) in the docs.

**Comment by ashangit** [comment]
@travisn that's exactly what I was looking for sorry for missing this new 1.4 feature, I'm still running in 1.3 but will definitely take a look to 1.4
