### ISSUE TITLE
Does Rook support AWS EFS?

### ISSUE THREAD

**Issue by alisachen** [rook/rook#6333]
Does Rook support AWS EFS? Can i get an example?

**Comment by leseb** [comment]
If AWS EFS can be exposed through a StorageClass with was provisioner then yes when the cluster is configured to run on PVC. Looks like the answer is yes: https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/

So I'll just use set this https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml#L123 to the name of the StorageClass exposing EFS.

I'm closing since it looks like you have your answer.
Thanks!
