### ISSUE TITLE
How can I mount rook-cephfs to the host server?

### ISSUE THREAD

**Issue by NirvanaZA** [rook/rook#6434]
I had my ROOK deployed today, and created a cephfs. I hope not only k8s pods could mount it with pvc, also host machine can mount it with ceph-fuse, So that I can download those data handled by pods, and also hot upload some configs or something.
It's the very first time I use ROOK, I used to use native ceph for years, rook is amazing, but I didn't found a way to do this ,is there any chances? 
I had some ideas, like use NodePort instead of ClusterIP, or run a special pods to do this, but hope for a way more elegant.
Any help is useful! 
Many thanks.

**Comment by travisn** [comment]
@NirvanaZA You may need to use host networking as described in [this topic](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#host-networking). Another possibility is multus. The network addressibility is of course the challenge outside the K8s cluster since you can't use the built-in SDN.

**Comment by NirvanaZA** [comment]
> @NirvanaZA You may need to use host networking as described in [this topic](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#host-networking). Another possibility is multus. The network addressibility is of course the challenge outside the K8s cluster since you can't use the built-in SDN.

Thanks a lot
