### ISSUE TITLE
osd keeps hanging

### ISSUE THREAD

**Issue by Cobi** [rook/rook#645]
I have a couple of osds in my rook cluster that will periodically hang and the mons will mark them out and down:

```
2017-05-03 21:45:37.862340 mon.0 [INF] pgmap v1466841: 2148 pgs: 47 active+undersized+degraded, 526 stale+active+clean, 1575 active+clean; 462 GB data, 1828 GB used, 1309 GB / 3138 GB avail; 4004 B/s rd, 38796 kB/s wr, 1699 op/s; 55336/243884 objects degraded (22.689%)
```
```
ID WEIGHT  TYPE NAME          UP/DOWN REWEIGHT PRIMARY-AFFINITY
-1 3.06519 root default
-2 0.76630     host osd-gjh7x
 0 0.76630         osd.0           up  1.00000          1.00000
-3 0.76630     host osd-d9fql
 1 0.76630         osd.1         down  1.00000          1.00000
-4       0     host osd-m8c1r
-5 0.76630     host osd-03cl6
 2 0.76630         osd.2           up  1.00000          1.00000
-6 0.76630     host osd-f4n5k
 3 0.76630         osd.3           up  1.00000          1.00000
```

Restarting the down osd seems to make it better, but they shouldn't be hanging in the first place.  And if they do, at least rook should detect and restart them.

I've attached the docker logs from the container that hung:
[hung-osd.log.gz](https://github.com/rook/rook/files/974792/hung-osd.log.gz)

**Comment by bzub** [comment]
Hi @Cobi, regarding restarting the OSD: I suppose it depends on the issue the OSD is experiencing.  If they come back up for a period of time but then crash again (flapping) that's not a net-gain for the cluster.  So I think Rook should indeed restart a failed OSD, but enforce anti-flapping thresholds that perhaps keep a misbehaving OSD down until manual inspection can be performed.

Thanks for providing the full detailed log file.  There is one [Ceph discussion](https://www.spinics.net/lists/ceph-devel/msg34647.html) that Linux kernel RBD clients before Linux v4.3 could cause these errors.  Do your Kubernetes nodes happen to use a kernel previous to this version?

**Comment by jcarter-okta** [comment]
```
$ salt 'k8s-*' cmd.run 'uname -a'
k8s-m01.tblflp.zone:
    Linux k8s-m01.tblflp.zone 4.8.0-45-generic #48-Ubuntu SMP Fri Mar 24 11:46:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w01.tblflp.zone:
    Linux k8s-w01.tblflp.zone 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w03.tblflp.zone:
    Linux k8s-w03.tblflp.zone 4.8.0-46-generic #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w02.tblflp.zone:
    Linux k8s-w02.tblflp.zone 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w04.tblflp.zone:
    Linux k8s-w04.tblflp.zone 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Cobi** [comment]
```
$ salt 'k8s-*' cmd.run 'uname -a'
k8s-m01.tblflp.zone:
    Linux k8s-m01.tblflp.zone 4.8.0-45-generic #48-Ubuntu SMP Fri Mar 24 11:46:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w01.tblflp.zone:
    Linux k8s-w01.tblflp.zone 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w03.tblflp.zone:
    Linux k8s-w03.tblflp.zone 4.8.0-46-generic #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w02.tblflp.zone:
    Linux k8s-w02.tblflp.zone 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
k8s-w04.tblflp.zone:
    Linux k8s-w04.tblflp.zone 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Cobi** [comment]
Happened again today.
[hung-osd2.log.gz](https://github.com/rook/rook/files/977315/hung-osd2.log.gz)

**Comment by bzub** [comment]
I'd suggest bringing this up with the [Ceph team](http://ceph.com/help/) for better diagnostics.  I will open a ticket to add a Rook feature to restart down OSDs and implement anti-flapping protections.

In the meantime I can help with some basic tuning of your cluster in case this issue stems from some sort of bottleneck in node/networking resources.

First, are the nodes that run the problematic OSDs identical to the other nodes?  If so this may narrow down what to tune.

I would recommend [recreating your storage pool](https://github.com/rook/rook/blob/master/Documentation/advanced-configuration.md#placement-group-sizing) with fewer Placement Groups if it's not too inconvenient.  It would mean erasing your existing data or doing a backup/restore of the data, but it should improve the efficiency of your cluster.

Also, [Ceph recommends](http://docs.ceph.com/docs/master/rados/configuration/filesystem-recommendations/#filesystems) using btrfs or xfs for the underlying filesystem.  So if you're using ext4 it could affect performance.  Personally I've had no problems with btrfs.

Next time you see this issue please post a `dmesg -H` log from the node that OSD is running on.  This should show any potential hardware/kernel level issues.  A log from an OSD that doesn't see issues could be helpful as well since it might show communication issues with the problem OSD.

**Comment by DanKerns** [comment]
Could you try and reproduce this with Rook 0.5.1 (Ceph Luminous) and reopen if it's reproducable?
