### ISSUE TITLE
Quickstart: Network Filesystem (NFS) docs describe many more wrong step.

### ISSUE THREAD

**Issue by xiaods** [rook/rook#6480]
yes,  this is docs error about rook nfs

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
correct the step and update rook nfs docs

- [ ]  https://rook.io/docs/rook/v1.4/nfs.html

**Comment by galexrt** [comment]
@xiaods Could you add some information to this issue on which steps are wrong in the NFS documentation?

**Comment by xiaods** [comment]
missing provisioner.yaml

**Comment by xiaods** [comment]
"Create Openshift Security Context Constraints (Optional) " is a special section, it should be put at the end of documents as a reference section.

**Comment by xiaods** [comment]
it annoys the rook user.
```
❯ kubectl create -f sc.yaml
Error from server (AlreadyExists): error when creating "sc.yaml": storageclasses.storage.k8s.io "rook-nfs-share1" already exists
```

**Comment by xiaods** [comment]
follow design/nfs/nfs-provisioner-controlled-by-operator.md  it said:
the operator will create the provisioner deployment, but it not happened..

**Comment by darkn3rd** [comment]
I found at least two bugs when going through this documentation.  I could not have succeeded in this without the help of a generous person in slack.

In the step [create-and-initialize-nfs-server](https://rook.io/docs/rook/v1.4/nfs.html#create-and-initialize-nfs-server), it describes recreating `ClusterRole` and `ClusterRoleBinding` that is in already previously created in the step [deploy-nfs-operator](https://rook.io/docs/rook/v1.4/nfs.html#deploy-nfs-operator) when `creating provisioner.yaml`.   What's really confusing is that this needed by the provisioner, so why is it here again in a different name space from where the provisoner is deployed.

In the step [default-storageclass-example](https://rook.io/docs/rook/v1.4/nfs.html#default-storageclass-example), for the description of `nfs.yaml`, this will fail on popular cloud providers, like Azure-Disk with AKS, because the default storage provider does not support `ReadWriteMany`.  I think I may have had to change this with `gp2` on EKS as well.

**Comment by xiaods** [comment]
@darkn3rd thanks for your report, the docs indeed update asap. I have not found the `provisioner.yaml ` in the main branch, I need some time to investigate why missing this. the docs said the operator will create automate, but it has not happen

**Comment by darkn3rd** [comment]
@xiaods In https://github.com/rook/rook/blob/master/Documentation/nfs.md#deploy-nfs-operator, there's a code block:
```bash
git clone --single-branch --branch {{ branchName }} https://github.com/rook/rook.git
cd rook/cluster/examples/kubernetes/nfs
kubectl create -f common.yaml
kubectl create -f provisioner.yaml
kubectl create -f operator.yaml
```

The second to the last line in the code block has the `provisioner.yaml`.

**Comment by xiaods** [comment]
@darkn3rd  in my environment, when i `kubectl create -f provisioner.yaml` it raised not found the provisioner.yaml.  i have no idea which step can create the provisioner.yaml

**Comment by xiaods** [comment]
anyone can double-check the documents, and provide some results. I have no environment to testing

**Comment by xiaods** [comment]
v1.5 update and fix this issue.
