### ISSUE TITLE
I want to set deviceclass in the pool area created by cephfilesystem.

### ISSUE THREAD

**Issue by vdi-kakui** [rook/rook#6548]
I want to set deviceclass in the pool area created by cephfilesystem and clarify which OSD is being used.

However, when I put the deviceclass description in yaml of cephfilesystem, I get an error.

How to solve this problem. Or can you give me a command to check which osd the pool created by cephfilesystem is using?

**Comment by travisn** [comment]
@vdi-kakui Are you installing based on master? I see a bug there where the `deviceClass` is missing in the schema for pools of filesystems. Instead of master, try installing with the latest stable build. As in the quickstart guide: 
```
git clone --single-branch --branch v1.4.6 https://github.com/rook/rook.git
cd rook/cluster/examples/kubernetes/ceph
```

@subhamkrai Would you review the missing pool properties in the schema? thanks
