### ISSUE TITLE
Should Rook restart failed OSDs?

### ISSUE THREAD

**Issue by bzub** [rook/rook#667]
Restarting a `down` OSD could be beneficial when one-off issues cause it to hang indefinitely.  Correct me if I'm wrong, but I don't believe an OSD will currently get back `up` after being deemed `down` in many cases such as resource contention on the node or network disconnects.

If automatic restarts of OSDs is implemented it should come with some basic anti-flapping protection.  Repeated restarts should be counted and backed off/discontinued.  In terms of Kubernetes pods, this is already the [default behavior](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy), the only thing Rook would have to do is exit with a failure code so the Pod dies/restarts.  #508 would have bearing on implementation.

Brought up in #645.

**Comment by bryanapperson** [comment]
It actually will be marked as up if the network comes back up. However if it was down for more then 5 minutes(by default) and is marked out, then it will not be marked as in.

**Comment by jbw976** [comment]
@fury_twitter ran into a scenario that may make implementing this even more valuable.  some details from gitter can be found at https://gitter.im/rook/rook?at=59b2f98a162adb6d2e8088f3

**Comment by jbw976** [comment]
A couple thoughts on a simple implementation for this:
* A simple monitoring loop within the OSD pod that checks on the state of its OSDs (up/in) and if they are down/out for too long then just restart them
* Only bring down a single OSD at a time within a pod.  The OSD pod should manage this itself (as opposed to the operator) because restarting the entire pod to fix 1 OSD would be too disruptive.

**Comment by jbw976** [comment]
Assigning to @paha for now since I'm hoping he can pick this up this week.  @paha please reach out to me for any questions about this implementation or that part of the codebase in general. Thanks!
