### ISSUE TITLE
Make the service type modifiable

### ISSUE THREAD

**Issue by jc-lab** [rook/rook#6688]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Is to make the service type of the mon service modifiable. If so, can be accessed from outside of the cluster.

**What is use case behind this feature:**
Use rook-ceph from outside of the cluster **without host network**.

Optionally using [external-dns](https://github.com/kubernetes-sigs/external-dns), can be accessible also with SRV Record.

**Environment**:

**Comment by travisn** [comment]
@jc-lab What type of service do you suggest? Rook needs to have a constant ip address for each mon. If the ip address isn't from the `clusterIP` on the service, rook will need another way to look it up.

**Comment by jc-lab** [comment]
@travisn 

This is my use case.
Currently, the network is configured using Calico BGP.
However, Calico only advertise whose Service Type is LoadBalancer.

In the current rook, the service type cannot be changed, so unnecessary routing occurs, increasing the latency.

**Comment by travisn** [comment]
All you need is the ability to change the type of the service from ClusterIP to LoadBalancer? Can you try the following as a workaround in a test cluster to see if it works for you?
- Export the existing mons: `kubectl -n rook-ceph get svc -o yaml | grep rook-ceph-mon > mon-services.yaml`
- In mon-services.yaml:
   - Modify the type of the services in mon-services.yaml to be LoadBalancer instead of ClusterIP.
   - Make sure to keep the same `clusterIP` values so the mons continue to work
   - Delete the extra metadata so the services can be created again
- Delete the services: `kubectl -n rook-ceph delete svc -l app=rook-ceph-mon`
- Create the new LoadBalancer services: `kubectl create -f mon-services.yaml`

**Comment by jc-lab** [comment]
@travisn 
It's out now, so I can't immediately try the exact above.
However, when I changed the service type through "kubectl edit", rook-ceph-operator re-created the service and reset it.

**Comment by travisn** [comment]
> @travisn
> I'm outside now, so I can't immediately try the exact above.
> However, when I changed the service type through "kubectl edit", rook-ceph-operator re-created the service and reset it.

Right, you likely need to stop the operator (delete the rook-ceph-operator deployment) while testing this.

**Comment by jc-lab** [comment]
@travisn Yes, I have already tested it like that. It worked the way I wanted.
However, for scalability, when externalIP or loadbalancerIP is assigned, it should considered changing public ip by modifying mon deployment or watching configmap.
Of course, in a general environment, my first suggestion will work.

**Comment by travisn** [comment]
The public ip of a mon cannot ever be changed. Ceph requires the mon ip to be immutable. This has been the challenge of service types I have seen other than ClusterIP.

> Perhaps of course the first suggestion will work for most general environments.

Which suggestion?

**Comment by jc-lab** [comment]
I didn't know that mon couldn't change the IP permanently.

> Which suggestion?

Is to modify the service type.

**Comment by jc-lab** [comment]
Additionally...
In order to register Service into DNS(SRV Record) through by additional plug-in, the function of adding annotations is also needed.
