### ISSUE TITLE
Consider repackaging Helm Charts as Chart rook-ceph-crd for CRDs-only and Chart rook-ceph for all else including CRs

### ISSUE THREAD

**Issue by ron1** [rook/rook#6776]
**Is this a bug report or feature request?**
* Feature Request

Consider repackaging Helm Charts as Chart `rook-ceph-crds` for CRDs-only and Chart `rook-ceph` for all else including CRs.

**What should the feature do and What is use case behind this feature:**

According to [Helm 3 CRD best practices documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts), a best practice is to manage CRDs in a separate helm chart which gives administrators more control over the CRD deployment process.

So, rather than putting the CRDs and Operator in one chart and the CRs in another, why not put the CRDs in one chart and the Operator and CRs in another? Having the CRDs in their own chart makes this a possibility. For a cluster-wide app like Rook Ceph, there is no real need to deploy the Operator and CRs separately.

Define a `rook-ceph-crd` chart. Then include the main stream CRs in the `rook-ceph` chart where the `CephCluster` CR is mandatory and a few others are optional. Finally, describe how the [Helm 3.1+ post renderer](https://helm.sh/docs/topics/advanced/#post-rendering) can be used with kustomize to handle edge case CR scenarios. See minute 8:20 - 12:00 of YouTube KubeCon video https://youtu.be/SD6ItVS0Vg4 for a demo of this feature.

I believe there is agreement that multiple charts will eventually be required. My point is to put the CRDs into their own chart. Then just one more chart is necessary for everything else. Finally, rather than parameterizing every CR and every CR property in a helm chart resulting in helm chart sprawl, embrace kustomize as a post renderer for these kustomizations. Folks may need kustomize anyway to handle last mile kustomizations the `rook-ceph` chart does not anticipate.

Note that Helm-based GitOps tools like Rancher Fleet (https://github.com/rancher/fleet) and Replicated Ship already embrace using helm and kustomize together for maximum deployment flexibility. I know downstream Rancher embraces this approach of separating CRDs into their own charts. Now that SUSE has acquired Rancher Labs, is there value in packaging the upstream `rook-ceph` helm charts in a way that is compatible with how Rancher packages its helm charts? This packaging might accelerate inclusion of a `rook-ceph` Helm Chart in the [Rancher Helm Chart repository](https://charts.rancher.io/index.yaml) which in turn would be great for the `rook-ceph` community.

**Comment by jaxels10** [comment]
Hi @ron1. I wanted to join this conversation as I am right now sitting with the choice of how to install `rook-ceph` with helm charts. I read your post and first I have a question. Why doesn't it work as suggested in [method #1 in the helm chart docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) to just put the CRDs into a `crds` folder and then the CRs into the `templates` with the operator CRs? Our cluster is not in production but every test I have done so far with auto-deploying `rook-ceph` it works like a charm and the whole cluster works just fine. Maybe this only seems to be working because I don't know enough about it. I read in the Rook docs that the cluster CR should not be deployed until after the operator is already in a running state, but as I said, I have not encountered any issue with having everything in the same chart and the CRDs in `crds` and all other CRs in ´templates`.

**Comment by ron1** [comment]
Hi @jaxels10. Method #1 does work for day one installs. However, compared to Method #2, it is less flexible because 1). it couples crd management which is a cluster admin function with other functions that only require namespace-level privileges 2). it offers "no support at this time for upgrading or deleting CRDs using Helm". With Method #2, a cluster admin will likely have more flexibility when manually orchestrating a CRD version upgrade along with Operator and CR version upgrades.

**Comment by jaxels10** [comment]
@ron1 thanks a lot for your response. I agree that splitting the CRDs and the CRs into different charts seems to be the way to go. I have already done that in my project. I can definitely contribute with that. I have to look more into Kustomize before I am able to join a discussion on that. Would your proposal to use Kustomize have any influence on the structure of the Helm charts for Rook(other than not creating the helm chart sprawl you mentioned)?

**Comment by ron1** [comment]
@jaxels10 Thanks for the feedback. I proposed the optional use of Kustomize to avoid having to accommodate every possible CR configuration in the non-crd helm chart. I was thinking maybe that chart handles the Operator and one of either a CephCluster

**Comment by BlaineEXE** [comment]
I'm concerned about the practicalities of user updates by separating the helm charts. Sometimes updates to Rook require udpates to the CRDs, and if users do not update CRDs when updating Rook, they could encounter bugs.

To my understanding, this PR makes it so that CRDs won't be deleted by Helm, but they will still be updated.
https://github.com/rook/rook/pull/7167

**Comment by ron1** [comment]
Hi @BlaineEXE. The expectation is that the rook-ceph-crd and rook-ceph charts would be versioned together. This is a best practice that Rancher has adopted with their Operator-based charts including https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-logging, https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-monitoring, and other charts in repo https://github.com/rancher/charts/tree/dev-v2.5/charts.

**Comment by BlaineEXE** [comment]
I am concerned that this "best practice" is merely a workaround for Helm not having a good model for how to manage CRDs and is actually a "smell". I don't think we have a bad solution in Rook just because we don't follow what Helm has called here a best practice. For users who **don't** use Rancher for deploying charts, I think having one chart is a better experience for them. We eliminate one path of human error in their workflow by not giving the opportunity for Rook to update without the CRDs being updated. And in Rook we do a lot of testing to make sure that our updates work, and our updates sometimes require updates to CRDs to fix bugs, not just to add features.

**Comment by ron1** [comment]
@BlaineEXE It is my understanding that Rook Helm Chart users want to deploy more than just the Rook Ceph Operator via Helm. They also want to use Helm Charts to deploy CephClusters and other CRs. It is impossible to deploy CRDs and CRs that depend upon them via a single Helm Chart. So, this issue assumes that the simplicity of a single chart does not meet the requirements of Rook Helm Chart users. Does a re-read of the description of this issue in light of the above information make more sense?

**Comment by BlaineEXE** [comment]
We don't currently have any intentions of allowing Helm to deploy the CephCluster or any other CRs since that would mean duplicating parameters from those CRs to the Helm chart one-to-one. Currently, the Helm chart deploys CRDs, RBAC, and the Rook Operator, then the user can create CRs after. I think using kustomize makes sense for creating those CRs, but not Helm. 

I do see benefit to allowing the Helm chart to create RBAC resources in a different namespace from the Operator, but that is not the same as deploying the CephCluster itself.

**Comment by ron1** [comment]
@BlaineEXE I think most Helm users have these expectations of a chart. First, a helm install of a chart should result in the deployment of a fully-functional workload configured with reasonable defaults. Second, values.yaml files are available to customize the workload to satisfy 90+ percent os users. The current rook-ceph helm chart meets neither of these requirements.

Whether a helm chart embeds operators is an implementation detail. If a helm chart maintainer has to duplicate CR parameters to make the workload configurable via a values.yaml file, so be it.

The below comment was posted on Feb 15th in the #ceph slack channel. I think this represents what most rook ceph helm users want out of the chart.

> I can see that the only Helm charts available are the ones that bootstrap the Rook operator. I have in my project created Helm charts that will deploy the entire cluster with all the CRD's needed and the cluster.yaml. I can see it says that contributions are welcome for the Helm charts in Rook, so are you interested in me creating a pull request for the Helm chart or are you guys content with the way it is currently? :slightly_smiling_face:

**Comment by jaxels10** [comment]
@ron1 I can weigh in here a bit since I made the comment you quoted. 

I agree with you that most new users who use the Rook Helm charts will be looking for a solution that does not only bootstrap the operator. I, myself, was a bit confused, having first deployed my Ceph cluster following the standard Rook guide and everything deploying, to then trying to deploy a cluster through the Helm charts and only seeing the operator running. I thought it was unintuitive that I needed to go and also create the cluster.yaml file, before my cluster would launch. 

I then tried putting the cluster.yaml file into my Helm chart, but obviously that didn't work since you can't create CRs at the same time as the CRDs. I then went on to the Helm docs and found out you could create a ´crds´ folder that would create the CRDs before the templates. But wait, I couldn't delete or update them now. 

I am now pretty much back to square one again on this issue. I want to make it as easy as possible to update my current Rook version and Ceph version. I have therefore now created a second helm chart that deploys the cluster.yaml file, so I can keep the original Rook chart intact and thereby making it easier to update since I can just upgrade the Helm chart. 

@BlaineEXE I don't have much to contribute when it comes to an actual solution, but I do agree with @ron1 that the current state of the Helm chart is probably not what users are looking for. Perhaps the discussion that is being had here should be documented in the docs so people wanting to use the Helm charts knows about this issue.

**Comment by ron1** [comment]
@jaxels10 Thanks for your feedback.

Using a separate helm chart just for crds seems to be a common pattern for crd-based workloads and is how we deploy Rook Ceph today via helm and kustomize.

**Comment by jaxels10** [comment]
@ron1 That makes sense. How about when you update your Rook version. I assume you do it through the Helm charts? If so - every time there is an update, don't you need to "rearrange" the Helm chart to fit your structure before upgrading? 

I am trying to make updating the Rook version as easy as possible which is why I am trying to figure out the "best" way to structure my Helm charts for that.

**Comment by ron1** [comment]
Are you referring to patch version updates or minor version updates?

**Comment by jaxels10** [comment]
For example going from Rook 1.4.x -> 1.5.x

**Comment by ron1** [comment]
I would expect Rook helm chart maintainers to deliver a "rearranged" helm chart version with each quarterly rook version release. The new helm chart version would minimally expose CephCluster CR changes. It might make sense for CephFS and RGW to each have their own charts. It would be helpful to know what percentage of rook ceph users use file and object storage in order to make that decision.

**Comment by BlaineEXE** [comment]
I think I am hearing a proposal that Rook should have 3 helm charts: 
- CRDs
- Operator
- CustomResources (e.g. CephCluster)

I still like the idea of keeping the CRDs and Operator in one chart as we currently have them. I think this allows us to be more certain that users will definitely get updates to their CRDs when the Rook cluster is updated. I am hearing that some users like @ron1 use Rancher-managed charts which pair together separate CRD and Operator charts. I have some concerns, as mentioned, about having these be separate for the majority of non-Rancher users. Perhaps there is a way to have the Operator chart use the CRD chart as a child for users who don't want to manage the resources separately or have tooling that helps them do so.

I have some concerns about our ability to maintain Helm charts from a maintainer perspective. I really don't want maintainers to have to support every config from CRs when those will be largely duplicated 1-to-1; I think there are diminishing returns when CRs that are well-documented are concerned. However, I do hear that it is a good user experience to be able to deploy basic working configurations with Helm. My proposal on this would be to include only the basic CR configs via Helm that could get users up and running with a basic config. We would support post-rendering and/or kustomize for any additional config. I think this is the plight of all maintainers everywhere, but we also have many issues reported here and on slack that stem from users not reading documentation about the CRs they wish to configure. With Helm being an additional layer of indirection, I think we should use all of the Helm documentation tools at our disposal to link to documentation for users so that they are able to find the information they need easily when they wish to use post-rendering to modify CRs.

We also have this related request: https://github.com/rook/rook/pull/5573
As well as this: https://github.com/rook/rook/issues/6799
We should figure out what the appropriate strategy is for creating RBAC for the Operator and the CephCluster(s). Users might want to deploy CephClusters outside of the Operator namespace. Currently the Helm chart deploys RBAC in the Operator namespace that allows a CephCluster to run in the same namespace without need to add additional RBAC. But for users who wish to separate the namespaces and users who want to run multiple Ceph clusters, the experience for them is not simple. I see some options:
- Include the necessary RBAC for running a CephCluster CR in the CustomResources chart (this seems pretty necessary)
- For users who are used to using the current Helm charts, do we need to continue providing CephCluster RBAC in the Operator chart deployed with the Operator?
- When using the CephCluster chart, will Helm get upset if the Operator chart has already deployed CephCluster RBAC resources by the Operator chart?

We have also been considering generating some of the example manifests (`crds.yaml`, `common.yaml`, and `operator.yaml`) from the Helm charts. With any changes we make here, it seems reasonable to consider how we can make that more easily possible.

**Comment by ron1** [comment]
@BlaineEXE I think 3 charts is too many. The Banzai Cloud Logging helm chart variants provide a good example of a popular Operator-based Helm Chart with a primary CR like CephCluster. The two variants of this helm chart each use only 2 charts.

Variant #1:
It sounds like @BlaineEXE prefers choice one where the CRDs and the Operator are packaged in one chart and the Logging CR is packaged in another chart. In the case of Rook, the second chart would host the CephCluster CR instead of the Logging CR and could be augmented with a kustomize-based helm post-renderer to include additional Rook Ceph CRs. The sources for these two charts are available here:

Logging Operator chart - https://github.com/banzaicloud/logging-operator/tree/master/charts/logging-operator
Logging Operator Logging chart - https://github.com/banzaicloud/logging-operator/tree/master/charts/logging-operator-logging

Variant #2:
Choice two, which is the one proposed here, adopts the helm chart packaging style used by the Rancher variant of the Banzai Cloud Logging chart. In this case, the CRDs are packaged in one chart and the Operator and Logging CR are packaged in another. The sources for these two charts are available here:

Logging CRD chart - https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-logging/rancher-logging-crd
Logging chart - https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-logging/rancher-logging

What do you see as the strengths and weaknesses of each Variant?

**Comment by BlaineEXE** [comment]
In Banzai Cloud's case, it sounds like they have 4 Helm charts that they maintain independently.

I think it could make more sense in Rook to have 3 Helm charts (CRD, Operator, CR), and then have some parent charts that decide whether to combine them in ways that are best for users. I haven't played with parent/child charts, however, so this could be more complex than I am imagining.

https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by ron1** [comment]
What are the 4 Banzai Cloud Logging charts to which you are referring?

Also, what is the value of managing the Operator and CephCluster CR in separate charts? Is this to support multiple CephCluster CRs per k8s cluster with a single Operator watching multiple namespaces? Would it be more straightforward to support this use case by co-locating the Operator and the CephCluster in specific namespaces?

**Comment by BlaineEXE** [comment]
> What are the 4 Banzai Cloud Logging charts to which you are referring?

You linked to 4 charts from Banzai before. Operator, Logging, Rancher CRD, and Rancher Logging. 

> Also, what is the value of managing the Operator and CephCluster CR in separate charts? Is this to support multiple CephCluster CRs per k8s cluster with a single Operator watching multiple namespaces? Would it be more straightforward to support this use case by co-locating the Operator and the CephCluster in specific namespaces?

Yes. This is to support users who want one Rook Operator to manage multiple Ceph clusters.

We could force a 1:1 mapping from operator to cluster like you mention. On one hand this doesn't allow for a multi-tentant scenario where admins can create the operator and users can create clusters. On the other hand, I'm not sure this scenario is very practical currently. But since it is an officially-supported Rook feature today, I think we need to start from there. 

@travisn do we still have some thought about having the operator only manage one Ceph cluster at a time. I know we were talking about that possibility years ago.

**Comment by ron1** [comment]
Hi @BlaineEXE I apologize for the confusion.

Banzai distributes two charts to install Logging. The first Banzai chart applies crds and the operator. The second chart applies the Logging CR.

Rancher refactored the two Banzai charts into their own implementation. The first Rancher chart applies crds only. The second chart applies the operator and one or more Logging CRs.

The two charts from Banzai and the two charts from Rancher offer a compare and contrast of the different package approaches at play here: 1). crds+operator/crs vs. 2). crds/operator+crs.

Another possible advantage of the 1:1 operator-to-cluster mapping is it allows each Rook Operator to have its own set of custom configurables.

**Comment by travisn** [comment]
Before I get into thoughts about organization of the helm charts, first here are some higher level thoughts on Rook's resources and design concerns...

There are three basic categories of resources that need to be managed:
1. CRDs
2. Operator with all its related resources such as RBAC
3. CRs: CephCluster, CephObjectStore, CephFilesystem, CephBlockPool, CephObjectZone, and a number of others...

The CRDs and Operator must be versioned together. We just don't test them separately. If there is an update to the CRDs or RBAC, there is also an update to the operator. 

The main Rook use case is to run a single Rook operator that manages a single Ceph cluster. In more advanced cases, the single operator can be configured to manage multiple clusters that are each in a different namespace. 

In theory, another use case is that multiple Rook operators could be deployed that each manage their own cluster in their own namespace. However, I don't know how practical this really is, or if anyone is doing it today. It may be working, but I suspect there are bugs about watching for resources in all namespaces when the operator should only be watching its own namespace. This would mean an operator may try to manage aspects of another cluster that isn't intended. Also, the CSI driver is 1:1 with the operator. If we had multiple operators, there would be multiple CSI drivers, each with their own provisioner names and multiple volume plugins running on each node, which is rather wasteful of resources. While this has been designed to work in the CSI driver, IMO it's really confusing to support multiple storage provisioners in the same cluster. Therefore, I propose that we stick with a singleton operator and not attempt to get multiple operators supported with the helm charts. If there are concerns with this proposal, stop reading now since my design assumptions will not hold.

Assuming we support a single operator, this means we effectively treat the operator as a cluster-wide resource that is capable of managing multiple Ceph clusters. 

Now for the Helm organization... It seems we should have one chart for cluster-wide resources and one chart for Ceph-cluster-specific resources, meaning these two charts:
1. CRDS + cluster-wide RBAC + Operator
2. cluster-specific RBAC + CRs

Keeping the CRDs, RBAC, and operator in the same chart as today has the advantages:
- Upgrades are smooth since no change to the existing helm structure
- The CRDs, RBAC, and operator are all guaranteed to version together

Alternatively, if we included the operator with the CRs, we would be effectively saying an operator is created for each ceph cluster that is to be managed, which is back to the concerns above that I don't see practical. 

Regarding the chart for the CRs, it seems clear that a chart with the CephCluster CR would work well to contain the cluster-specific RBAC and configure the CR for a specific namespace. Multiple instances of the chart could be installed in different namespaces to get multiple cluster configurations. But I'm still not clear on how we effectively create a single chart that will work for all the optional CRs such as the filesystem, object store, rbd mirroring, cephfs mirroring, pools, etc. I'd say this has been the main reason the chart hasn't been created yet, though surely I'm missing the Helm design principles that would help here.

**Comment by BlaineEXE** [comment]
I see a potential option to benefit those who want the Rancher model and still give us what we need.
- Separate CRDs into a separate Helm chart
- In the Operator Helm chart, use the above CRDs chart as a child chart to version Operator and CRDs together as we do today. Provide an option to disable management of the CRDs child chart for the Rancher use-case requested.
- I think we can consider a CRs chart separately also, but my thoughts on this are a little less put together

**Comment by ron1** [comment]
Has Rook had success in the past upgrading crd versions with the crds and operator in the same chart? This seems to be a scenario that Helm 3 explicitly does not support. Did rook support helm charts back when rook ceph upgraded to v1 crds?

**Comment by travisn** [comment]
Rook has been on v1 CRDs since v0.9, while the helm chart was created perhaps back in v0.5. I don't recall hearing of any issues during that upgrade when the version was updated.

Rook's approach to the CRDs is that we will plan on keeping them at v1 and hold a backward compatibility promise. If there is a need to go to v2, it would be a major breaking change and we have no plans for such a change.

All that said, I'm open to changing the Rook helm charts if it fits with needs for the Rook community, the assumptions for those best practices just doesn't seem to line up with Rook's usage as in my previous comment. What are your thoughts on running one operator to manage one or multiple clusters?

**Comment by ron1** [comment]
@travisn Since the Rook Operator deployment is more complex than most, it probably makes to limit the number of Rook Operators per k8s cluster to one. Furthermore, it seems some users want to manage multiple CephCluster CRs per k8s cluster, each in its own namespace. In order to support these more complex deployments, it makes sense to separate the Operator helm chart from the Ceph Cluster CRs helm chart. Then the Ceph Cluster CRs helm chart can be applied multiple times to the cluster in different namespaces.

I would be hesitant to implement a CRD version upgrade in a combined CRD/Operator chart if Helm states it is unsupported. Of course, Rook can do its own testing of the chart upgrade and support the configuration itself. Since I have had good experiences managing CRDs in a separate chart, that approach is my recommendation.

**Comment by travisn** [comment]
@ron1 Thanks again for your perspective. What I'm still struggling with is the reason that the CRDs should be in their own chart instead of with the operator as it is today, since we treat the operator as a singleton and want it to be versioned with the CRDs. When researching the helm recommendations for CRDs a few months ago, the reasons to treat the CRDs differently and put them in the `crds` folder and/or in their own chart included:
- CRDs wouldn't be updated or removed by helm to prevent breaking changes. 
- If there are multiple consumers of the CRDs, there should be a single chart to install them, independent of the consumers.

Since neither of those apply to Rook, and Rook is working with upgrades in Helm 3 as is today, I'm not seeing the real need to separate the CRDs. IMO we need a technical reason beyond someone deciding it's a best practice. In the meantime, the chart does have an option[to skip installing the CRDs](https://github.com/rook/rook/blob/release-1.5/cluster/charts/rook-ceph/values.yaml#L11-L15) if it helps with the concern of managing CRDs separately,.

**Comment by billimek** [comment]
FWIW, The [Velero](https://github.com/vmware-tanzu/helm-charts) project helm chart is handling upgrading of helm-installed CRDs using a special kubernetes job, via this PR: https://github.com/vmware-tanzu/helm-charts/pull/246.

Granted, the job is leveraging the `velero` CLI, but it's an interesting take nonetheless and may provide some inspiration to this issue on the rook side.

**Comment by travisn** [comment]
With the new cluster chart coming in v1.7 I believe we've settled on the two charts:
1. Operator chart, including the CRDs and most RBAC
2. Cluster chart, including cluster-specific RBAC and the ability to create all the CRs 

If more discussion is needed we can reopen.
