### ISSUE TITLE
v1.4.8 cannot be installed using helm

### ISSUE THREAD

**Issue by dpaks** [rook/rook#6885]
**Is this a bug report or feature request?**
* Bug Report

https://charts.rook.io/release doesn't contain v1.4.8 but v1.4.7 and others. Hence, the following command fails.
`helm install rook-release/rook-ceph --version=v1.4.8 -n rook-ceph`
![image](https://user-images.githubusercontent.com/6995187/103194311-3f43bc80-4905-11eb-82bf-48c1e4bf0064.png)

**Comment by travisn** [comment]
@dpaks The helm chart is currently only pushed during Rook's "promote" pipeline, which is intended to make the latest helm chart available. After the v1.5.0 release came out, it was intended to be the latest helm chart to be available, rather than the v1.4 patch releases. But agreed that we should still make the patch releases all available when a specific version is requested.

**Comment by travisn** [comment]
@dpaks The helm v1.4.8 chart is now available, and will be available going forward for all patch releases, including scenarios that I mentioned in the previous comment. The concerns around the CI causing negative side effects with the `promote` pipeline were investigated and confirmed not to be an issue, and the chart is now published.

**Comment by dpaks** [comment]
Thanks, @travisn
