### ISSUE TITLE
100% CPU on one OSD

### ISSUE THREAD

**Issue by thephred** [rook/rook#705]
On a coreos-kubernetes vagrant cluster on a Mac OS X laptop I woke my laptop from sleep and later noticed that an existing rook cluster was using 100% CPU on on of my three cluster nodes.  It turned out to be an OSD.

**Comment by thephred** [comment]
Here is the log of the OSD that was exhibiting this behavior:
https://gist.github.com/thephred/edb2377c129841b6ec361ffbe54e049c

**Comment by bzub** [comment]
I believe that timing information is critical to Ceph monitor operations and probably OSD as well, so putting a ceph cluster's OSs into sleep mode should be expected to cause issues.  I don't think Ceph will support this use-case, but I could be wrong in the context of strictly debugging/testing.

**Comment by DanKerns** [comment]
Arguably for ease-of-use/experimentation/development reasons this would be a valuable use case to support. I wonder if there is a `ceph --reset-time-because-of-time-travel` kind of thing that you can use to get ceph back on the tracks. If there was the operator could invoke it in these situations.  I think it would be worth asking on one of the Ceph channels.

**Comment by travisn** [comment]
not sure i've seen this in luminous. please reopen if hit again.
