### ISSUE TITLE
Loopback devices aren't supported by Rook

### ISSUE THREAD

**Issue by matulek** [rook/rook#7206]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I've tried to create a cluster based on the loopback block device, not the physical disk. Rook disallows me to do that with 

**Expected behavior:**
Cluster finds and recognizes my loopback devices as usable by ceph.

**How to reproduce it (minimal and precise):**
Create cluster on nodes with loopback device (deviceType loop)

**File(s) to submit**:

Log fragment of the osd prepare pods:

```
2021-02-11 17:48:38.065370 D | exec: Running command: lsblk /dev/loop0 --bytes --nodeps --pairs --paths --output SIZE,R
OTA,RO,TYPE,PKNAME,NAME,KNAME                                                                                          
2021-02-11 17:48:38.073386 W | inventory: skipping device "loop0". unsupported diskType loop
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 8
* Kernel (e.g. `uname -a`): 4.18
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.5.6
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)
* Kubernetes version (use `kubectl version`): 1.19.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): ceph command freezes in almost all commands, 'health' is one of them

**Comment by leseb** [comment]
ceph-volume, the tool Rook is using to prepare OSD disk does not support loop devices. So in order to get support in Rook, you would need to explicitly open a request here https://tracker.ceph.com/, under the ceph-volume component.

I suspect using raw mode might be yet again the answer. See https://github.com/rook/rook/pull/4879, we should be able to merge this soon.

**Comment by matulek** [comment]
@leseb sorry, but looking at this file: https://github.com/rook/rook/blob/master/pkg/clusterd/disk.go#L37 I assume that this is the right repository.

**Comment by leseb** [comment]
The main issue with loopback devices is that we tell the lvm filter to ignore them when deploying a cluster on PVC. When dynamically attaching PV, kubelet also creates a loopback device, so if we don't ignore those in the lvm filter the OSD will be reported twice and ceph-volume will break.

It's not a scenario we intend to support at the moment since we are focusing on production scenarios. Allowing it could introduce regressions in the production deployment. That's something we cannot afford.

Don't you have disks or partitions you could use on your system instead?

**Comment by BlaineEXE** [comment]
I think it should be possible to create a loopback device and create a Kubernetes Local PersistentVolume (LPV) on it, then tell Rook to use that LPV via `storageClassDeviceSets`.

**Comment by matulek** [comment]
> The main issue with loopback devices is that we tell the lvm filter to ignore them when deploying a cluster on PVC. When dynamically attaching PV, kubelet also creates a loopback device, so if we don't ignore those in the lvm filter the OSD will be reported twice and ceph-volume will break.
> 
> It's not a scenario we intend to support at the moment since we are focusing on production scenarios. Allowing it could introduce regressions in the production deployment. That's something we cannot afford.
> 
> Don't you have disks or partitions you could use on your system instead?

unfortunately I don't, It's hard with this vendor to get additional block devices attached to their VPSes. I intend to try it, but I wanted to go on with my setup before I get them to do it.

> I think it should be possible to create a loopback device and create a Kubernetes Local PersistentVolume (LPV) on it, then tell Rook to use that LPV via storageClassDeviceSets.

Thanks, I'll try to do this.

> The main issue with loopback devices is that we tell the lvm filter to ignore them when deploying a cluster on PVC. When dynamically attaching PV, kubelet also creates a loopback device, so if we don't ignore those in the lvm filter the OSD will be reported twice and ceph-volume will break.

Thank you for claryfing, so it's not easy thing to do. I'm closing this issue then.

**Comment by leseb** [comment]
Just to clarify one thing, the LVM filter story is actually outdated, because we use a different method to prepare OSD on PVC (we call it RAW mode since there is no LVM layer anymore) then it should work if you create a local PV. You can take some inspiration from this script: https://github.com/rook/rook/blob/master/tests/scripts/localPathPV.sh

**Comment by agaoglu** [comment]
For anyone stumbling upon this, PV on a local loopback device doesn't work either.

```
2021-08-04 07:33:38.697167 I | cephosd: discovering hardware
2021-08-04 07:33:38.697173 D | exec: Running command: lsblk /mnt/set1-data-0zrvw5 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
failed to get device info for "/mnt/set1-data-0zrvw5": unsupported diskType loop
```

The difference is this type of prepare job crashes instead of just skipping the device.

Tried in 1.6.7 and 1.6.8 to make sure it's not related to LVM filtering.

**Comment by aholler** [comment]
Handling loop devices like partitions seems to work.

I've attached a patch for 1.7.1.

Best regards,

Alexander
[0001-WIP-ceph-allow-usage-of-loop-devices.patch.gz](https://github.com/rook/rook/files/6993666/0001-WIP-ceph-allow-usage-of-loop-devices.patch.gz)

**Comment by stevefan1999-personal** [comment]
Since filestore is dead, seriously though, allowing the use of loop devices could benefit a lot for testing environments that requires PVC support such as CI/CD pipelines where they usually do not have direct access to any redundant disks or partitions, and also benefits experimental clusters such as k3d. I have the idea of running Rook on top of OpenEBS, but that would introduce too much overhead

**Comment by agaoglu** [comment]
similar in my case. i tried to run a dev cluster using minikube-in-docker, on my laptop with no additional drives.

BTW, don't do that blindly with cluster-test.yml or sth. You may end up formatting your precious OS drives as bluestores.

**Comment by ben-wangz** [comment]
will loop devices be supported in later versions?

**Comment by leseb** [comment]
> will loop devices be supported in later versions?

There is no plan for this.

**Comment by BlaineEXE** [comment]
> similar in my case. i tried to run a dev cluster using minikube-in-docker, on my laptop with no additional drives.
> 
> BTW, don't do that blindly with cluster-test.yml or sth. You may end up formatting your precious OS drives as bluestores.

@agaoglu, Minikube with version 1.23 now supports adding extra disks to the deployment. This is for either hyperkit (mac) or kvm (linux) drivers.

**Comment by agaoglu** [comment]
@BlaineEXE yeah i know, but i had a few problems with kvm in my laptop, that's why i tried docker driver. I actually want to have a go at this but i guess it'll be good to know if there's a specific reason not to support them before starting.

**Comment by BlaineEXE** [comment]
@agaoglu, in my words, the short of it is that the `ceph-volume` subproject of `github.com/ceph/ceph` pushes back against supporting loopback devices. I agree that it would be a useful case for your and @stevefan1999-personal's use-cases, but it's not a case that ceph-volume intends to support, and Rook can't really work outside of that since we rely on it to provision disks for use as Ceph OSDs. 

From my observations several months ago, when one creates `Local Persistent Volumes` in Kubernetes, K8s uses loopback devices under the hood to point to the disks. This may be fine for ceph-volume since the underlying disk when I tested it was actually a disk and not something else, but it does at least tell me that it's not purely the `loopback` part that of `Local PVs` that ceph-volume doesn't like.

@satoru-takeuchi could speak to this a little more, but I think you might be able to get ceph-volume to play nice if you create a file to use as a `raw` disk image and put an LVM `vg` on it, then use that as a Local PV to Rook. If we can come up with a scenario like this that allows using fake disks, I would be more than happy to add the how-to to the Rook docs to help other users who have similar constraints like yourselves.

**Comment by satoru-takeuchi** [comment]
> I think you might be able to get ceph-volume to play nice if you create a file to use as a raw disk image and put an LVM vg on it, then use that as a Local PV to Rook.

It will work. And I recommend this way. And we will be able to use this way for host-based cluster if #7967 is merged.

**Comment by agaoglu** [comment]
I had some time to try this on my laptop but couldn't get very far. This is a rough outline

1. Create a 10G empty file with dd -> /store/loop0.img
2. Create a loopback device -> /dev/loop0
3. Create PV / VG / LV to have /dev/loopvg/looplv pointing to /dev/dm-1
4. Start minikube using docker driver
5. Locate lv device in minikube docker machine. no /dev/loopvg/looplv link but /dev/dm-1 is there.
6. Define a local PersistentVolume for /dev/dm-1
7. Create cluster using local storage class.

Kubelet creates another loop device and passes it to prepare pod, but it fails with something like:

```
2021-10-05 14:48:59.055991 I | cephosd: discovering hardware
2021-10-05 14:48:59.056000 D | exec: Running command: lsblk /mnt/set1-data-0kjn6z --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
failed to get device info for "/mnt/set1-data-0kjn6z": diskType is empty
```

I think I haven't reached as far as ceph-volume yet. But it doesn't seem like a prepare problem either. Because even if I can find the /dev/dm-1 in minikube machine, lsblk can't.

```
docker@minikube:~$ ls -al /dev/dm-1 
brw-rw---- 1 root 995 254, 1 Oct  5 14:09 /dev/dm-1
docker@minikube:~$ lsblk /dev/dm-1
docker@minikube:~$ echo $?
32
```

Since it's able to find it in other privileged containers, it seems like a problem with minikube. I'll retry with some alternatives.

**Comment by anoworl** [comment]
@agaoglu Thank you! I could do it using your method!
