### ISSUE TITLE
How to extend the ceph filesystem if we reach the maximum size of OSD disks ?

### ISSUE THREAD

**Issue by ahmedTouati** [rook/rook#7366]
I'm running a rook-ceph cluster with 3 OSDs which span 3 EBSs, everything is running as expected but we know that the maximum size of those EBSs is 16TBs, we presume that in the future we'll hit that limit, in this case, all OSDs will be filled up, we think of using more OSDs  with grouped replication but i don't know if that possible.

**Comment by travisn** [comment]
@ahmedTouati How did you create the OSDs? When running in AWS, it's recommended to use the `storageClassDeviceSets` as found in the cluster-on-pvc.yaml example. This way you can add more OSDs simply by increasing the `count` of the device set, instead of expanding the individual OSD size. 
For future questions, please see the [Discussions](https://github.com/rook/rook/discussions), it is preferred instead of opening an issue, thanks.

**Comment by ahmedTouati** [comment]
> @ahmedTouati How did you create the OSDs? When running in AWS, it's recommended to use the `storageClassDeviceSets` as found in the cluster-on-pvc.yaml example. This way you can add more OSDs simply by increasing the `count` of the device set, instead of expanding the individual OSD size.
> For future questions, please see the [Discussions](https://github.com/rook/rook/discussions), it is preferred instead of opening an issue, thanks.

@travisn we are using the **cluster-on-pvc.yaml** with **storageClassDeviceSets** already but what is the difference if we add additional OSDs since all data is replicated across them or you mean using more OSDs than the actual **Replicated Data Pool** ??
