### ISSUE TITLE
Implement the fsType parameter for rook.io/block volume provisioner

### ISSUE THREAD

**Issue by dimm0** [rook/rook#742]
The fsType parameter for specifying the filesystem type is implemented in older kubernetes.io/rbd provisioner, but not in the new rook.io/block. It would be useful to have it.

**Comment by kokhang** [comment]
@dimm0 Just FYI, this fsType would be obtained from the StorageClass. There is no way for normal users to specify the fsType in PVCs. The fsType can only be provided by admins in the StorageClass. I will make the changes so that the admin can specify the fsType from the storageclass.

Some background issues:
https://github.com/kubernetes/kubernetes/issues/37801 
https://github.com/kubernetes/kubernetes/pull/45345 -> This one was just merged 3 days ago.

**Comment by dimm0** [comment]
It worked! Thanks, appreciate it
