### ISSUE TITLE
ci: minikube setup on master branch fails

### ISSUE THREAD

**Issue by leseb** [rook/rook#7542]
See https://github.com/rook/rook/runs/2289475337?check_suite_focus=true

**Comment by leseb** [comment]
It's the same for all the other suites.

**Comment by subhamkrai** [comment]
for 
1. `flex suite` in k8s version test passed(v1.15.12, v1.16.15) but in all other version minikube setup failed https://github.com/rook/rook/runs/2291718450?check_suite_focus=true
2. `smoke suite` test passing for all except k8s v1.20.2 https://github.com/rook/rook/actions/runs/727486999 (failed because cluster in bad state)
3.  `multiclusterdeploy suite` passing for all k8s versions https://github.com/rook/rook/actions/runs/727486997
4. `helm suite` test started for all versions but test are failing. https://github.com/rook/rook/actions/runs/727486997
5. `upgrade suite` passing for all k8s versions https://github.com/rook/rook/actions/runs/727486998

**Comment by leseb** [comment]
Looks better now: https://github.com/rook/rook/runs/2295496503?check_suite_focus=true
