### ISSUE TITLE
Add rookctl subcommand to generate ceph configs

### ISSUE THREAD

**Issue by barakmich** [rook/rook#781]
This is already happening for toolbox in `toolbox.sh`, but it might be nice to canonicalize it into the tool, and allow other containers to grab the rook binary and configure their local environment to connect directly to Ceph.

**Comment by travisn** [comment]
@barakmich due to monitors being failed over when they are healthy, the list of monitor endpoints could change over time. So if you generate a config file, it will need to be re-generated over time if the mons fail. I'd recommend generating the config file with a script, similar to `toolbox.sh`, each time your pod starts. Or if you could clarify the scenario feel free to re-open the issue.
