### ISSUE TITLE
Reducing Ceph monitors based on placement, not first entry

### ISSUE THREAD

**Issue by prazumovsky** [rook/rook#7999]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
This feature allows to improve current way of removing Ceph Monitors, if desiredMonCount lesser than real number of Ceph Monitor deployments. The current state is removing first entry of monmap, which could be incorrect due to specified placement. The feature suggests to choose first of all such monitors that doesn't fit the placement and only if all monitors fit the placement, choose first entry. This will unlock flexible management of non PVC and/or host networking monitors.

**What is use case behind this feature:**
Let's image we have ceph cluster with 5 monitors (a,b,c,d,e) on 5 nodes with label "rook-ceph-mon=true", and the placement, which allow to spawn monitors only on nodes with label "rook-ceph-mon=true". Then we've got a message, that cluster will be reduced and nodes with monitors b and c will be destroyed in two weeks. We want to reduce number of monitors and remove monitors b and c before it happens (we don't want to get any unjustified errors of failed monitors or something like that in our ceph health history). So, what the first idea which could happen with us? Of course, we're removing "rook-ceph-mon=true" label from nodes with monitors b and c, and then reducing mon.count to 3. And what rook will do in such way? It will inspect that the number of desiredMonCount < real number of monitors and will remove 2 first entries of monmap (monitors a and b) - it's `pkg/operator/ceph/cluster/mon/health.go` healthCheck function: 
```
logger.Infof("removing an extra mon. currently %d are in quorum and only %d are desired", len(quorumStatus.MonMap.Mons), desiredMonCount)
      return c.removeMon(quorumStatus.MonMap.Mons[0].Name)
```

So new quorum will be c,d,e. After 2 weeks passed, nodes with b and c will be removed, so our cluster will loose 1 of 3 monitors - and will have a weak quorum d and e without necessary mon-c. It is incorrect and could be resolved at the previous step, when we could check that not all monitors fit placement, so remove them instead of first entry.

**Environment**:
Will reproduce on any rook installation.

**Comment by travisn** [comment]
@prazumovsky This is certainly a fair request to find a way to target removing specific mons. This has come up in the past also for scenarios where the number of desired mons doesn't change, but they just need to be migrated to other nodes.

The challenge is that mons are scheduled with "mon canaries pods" where we just wait for the K8s scheduler to decide where a mon should be placed, then we assign the mon directly to that node where the canary pod was scheduled. Since we use the K8s scheduler for new mons, we don't have an easy way to detect if existing mons still match the node affinity, tolerations, or other placement settings in the cluster CR.

Since this is a rare event to change the scheduling of mons or reduce the number of mons, the following steps will allow you to specify exactly which mons should be removed. While not ideal since it's not automated, does this work for you? (This requires #8011 to be fixed, which will be included in v1.6.4):

1. Scale down the operator so it doesn't interfere while making changes
```
kubectl -n rook-ceph scale --replicas=0 deploy/rook-ceph-operator
```
2. Manually remove the unwanted mons from the "data" element of the configmap "rook-ceph-mon-endpoints"
```
kubectl -n rook-ceph edit configmap rook-ceph-mon-endpoints
```
For example, if this is your original `data` entry for the mons:
```
data: a=10.102.202.92:6789,c=10.107.181.252:6789,d=10.97.63.221:6789,b=10.103.204.94:6789,e=10.103.206.96:6789
```
You can remove `a` and `e` by changing it to this:
```
data: c=10.107.181.252:6789,d=10.97.63.221:6789,b=10.103.204.94:6789
```
There is no need to update other fields like "mapping".

3. Change the desired mon count to 3
```
kubectl -n rook-ceph edit cephcluster
```
4. Scale up the operator again and watch the extra mons be removed after a minute or two
```
kubectl -n rook-ceph scale --replicas=1 deploy/rook-ceph-operator
```

**Comment by prazumovsky** [comment]
@travisn today I tried to play with this placement rules and stuck in this overminded variety of node chosing, also with this "canary" mechanic. It seems that kubernetes "...RequireDuringExecution" rules will help us a lot (the most hard-working case is handling affinity), but unfortunately it is not implemented yet :)

I paused in playing with placement rules and tried to play with current mon health logic.

Seems, next steps are working for me, but sounds a bit tricky:

Let's imagine we have mon nodeaffinity rules around specific node labels. We want to migrate monitor between two nodes.

1. Remove defined label from one node and add to another.
2. Run ceph CLI command "ceph mon rm <mon-letter-to-migrate>". As result desired monitor pod will be in crashloopbackoff.
3. Wait ~45 seconds. Health check for mon will start and will remove failed monitor. Also it will create new monitor on desired node.

Still sounds like slightly difficult issue to solve, so if there will be no other ideas (from me or community), I will close it as won't do.

**Comment by travisn** [comment]
Yes, that is an effective way to reschedule a mon. A perhaps less disruptive mon failover can also be triggered by scaling down the mon deployment. After some time (default 10 minutes) a new mon would be created and the old one would be removed. 
```
kubectl -n rook-ceph scale --replicas=0 deploy/rook-ceph-mon-a
```
