### ISSUE TITLE
Granular resource requirements distribution for OSDs with different deviceClasses

### ISSUE THREAD

**Issue by prazumovsky** [rook/rook#8007]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
This feature is a result of conversation about use case: https://rook-io.slack.com/archives/CK9CF5H2R/p1619725897181100

This feature provides more granular resource requirements distribution for raw devices OSDs by deviceClass. Currently CephCluster.spec.resources allows to specify resources requirements only for all osd deployments. This feature suggests to add additional keys for osds: osd-hdd, osd-ssd, osd-nvme, which will update resources section of corresponding osd deployments only for such OSDs, which placed on raw devices and equals to defined deviceClass. So resulting cephCluster.spec.resources section will be extended with the following keys:

```
spec:
  resources:
    osd-hdd: ...
    osd-ssd: ...
    osd-nvme: ...
```

which will be handled by rook and override `spec.resources.osd` key for hdd, ssd or nvme OSDs.
 
**What is use case behind this feature:**
Different device classes requires different cpu/mem resources, so there is less sense in specifying general `spec.resources.osd` template for all OSDs, better to align on different device classes.

**Environment**:
Any environment with OSDs on raw devices with different device classes and requirements on separate resources for each device class.

**Comment by travisn** [comment]
For this to work smoothly, the OSD prepare job would need to detect the device classes, instead of waiting for the OSD daemons to initialize the device class. As I recall, ceph-volume does not evaluate the deviceClass, but the detection is delayed until the OSD daemon is started. If we don't know the device class until after the daemon starts, it is too late unless we can restart the OSD again with the updated resources on the pod spec. 

Alternatively, the device class can be declared in the cluster CR with the `config.deviceClass` property (non-PVCs), or for OSDs on PVCs with the `crushDeviceClass` on the volumeClaimTemplate of the storageClassDeviceSet. This is not ideal especially in the non-PVC case since you would have to define the `config.deviceClass` for each specific device name. 

So I would propose we optimize detection of the device class in the osd prepare job, but if the device class is specified declaratively, it would override the auto-detection. Then we can append the device class to the `resources` as suggested above to give us `osd-<deviceClass>` for the resource key.
