### ISSUE TITLE
Rook-Ceph Storage less Performance 

### ISSUE THREAD

**Issue by Harisrini2020** [rook/rook#8273]
Hi,

 - I am trying out some performance test for storage with rook ceph. 
 - With default host based PV(Node directory), IOPS is very high.Whereas with rook ceph Cluster(Hostbased) IOPS are very low.
 - Eventhough I am using the local stroage(node), the read & wirte IOPS are very less in rook ceph.
 - Can I know why there is a huge difference. ?
 - Any other ways to increase performance of Storage ? 
 - Please find the details and results below.

### Test Procedure

 - I installed the rook operater and ceph cluster(host based).
 - Used 3 OSDs(total size 90GB) and 3 Mons. 
 - Deployed the Statefulset for each(read,write & RW ) for 30 GB using rook Storage Class.
 - Did the test with [FIO](https://github.com/axboe/fio)

### Cluster Details

 - Cloud Provider  : Azure
 - Volume Type : Standard_LRS(Standard HDD) 
 - Size of each PVC : 30GB 
 - Tool Used : [FIO](https://github.com/axboe/fio)
 - OSDs Used : 3 (each 30 GB)

### Results
| Operation| Rook-Ceph  | Default |
|--|--|--|
| Read |  286(4.5 MB/secs) | 8286(129 MB/secs) |
| Write | 380(6 MB/secs) | 556(9 MB/secs) |
| Read-write| 114(1.8 MB/secs)| 552(8.9 MB/secs) |

**Comment by travisn** [comment]
Comparing the local PV to a network software-defined storage system is not a fair direct comparison. The local PV is going to be much higher performance because it is just a local filesystem. Ceph has a network stack with multiple OSDs that gives you high data integrity, resilience, and replication to survive failure in a distributed system. Please see the [Ceph architecture doc](https://docs.ceph.com/en/latest/architecture/).

Ceph has higher performance when there are multiple clients reading and writing. Try using multiple instances of FIO to increase the test throughput.

> I installed the rook operater and ceph cluster(host based).

What do you mean they are "host-based"?

**Comment by Harisrini2020** [comment]
We have three types of Ceph Cluster in rook,

- PVC Based Ceph Cluster
- Host Based Ceph Cluster ( Node's local diectory)
- Stretch Ceph Cluster

In this, I used Host based Cluster.
