### ISSUE TITLE
mgr dashboard service support specifying serviceType and accessPort.

### ISSUE THREAD

**Issue by devlikai** [rook/rook#8399]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

ceph: mgr dashboard service support specifying serviceType and accessPort, in order to make dashboard service can access outside cluster.

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
@devlikai Does [this documentation](https://rook.github.io/docs/rook/v1.7/ceph-dashboard.html#viewing-the-dashboard-external-to-the-cluster) answer the question? Rook hasn't tried to support all the ways of exposing services external to the cluster because there are so many. Adding support for targeted scenarios like you opened for #8398 sounds good, but I just don't expect to expose all options.
