### ISSUE TITLE
Higher contrast colors for the docs

### ISSUE THREAD

**Issue by travisn** [rook/rook#886]
The docs on rook.io need a higher contrast. The gray and light blue text is hard to read on the white background. How about black text in place of gray, and dark blue in place of light blue? @marioava

**Comment by marioava** [comment]
These pages are in accordance with the pattern library that we are currently using throughout the Rook and Castle brands. The recent change was requested because the previous design did not match with the brand.. However, after checking contrast ratios with [this tool](http://webaim.org/resources/contrastchecker/) I found that we didn't score so well with some of our color choices. Matt and I have plans to update the pattern library and we will address this issue during that task. Thanks for calling that out.

**Comment by marioava** [comment]
Docs pages have been updated with darker text to increase contrast/readability.
