### ISSUE TITLE
Create OSD deployment before update.

### ISSUE THREAD

**Issue by jclab-joseph** [rook/rook#9532]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Create OSD deployment before update.

**What is use case behind this feature:**

1. There were 3 OSDs. & The pool's replicas are 3, and min_size is 2.
2. One of the OSDs died and became unusable.
3. So I changed CephCluster to add new OSD.
4. But I get the error below and I can't create a new OSD.
(OSD provisioned on the DISK, but no OSD deployment.)

```
2022-01-06 04:30:35.852794 I | util: retrying after 10s, last error: deployment rook-ceph-osd-0 cannot be stopped: Error EBUSY: 112 PGs are already too degraded, would become too degraded or might become unavailable
.
...
2022-01-06 04:30:47.652768 I | util: retrying after 10s, last error: deployment rook-ceph-osd-1 cannot be stopped: Error EBUSY: 112 PGs are already too degraded, would become too degraded or might become unavailable
...
(repeated)
```

Perhaps because updating an existing OSD takes precedence over creating a new one.

**Environment**:

**Comment by parth-gr** [comment]
`last error: deployment rook-ceph-osd-0 cannot be stopped:` why the other OSDs are stopping, doesn't seem like they are updating,

Can you describe your problem a little more, what you did for adding new OSD, why other OSD are stopping,
I may guess updating would be given precedence when we need to retain our data from the lost devices, instead of adding a new disk.
And also plz share the logs of the operator, can you also tell which rook version you are on.

**Comment by travisn** [comment]
@jclab-joseph To disable the checks for healthy OSDs during upgrade, set the `skipUpgradeChecks: true` in the cluster CR. This is not enabled by default to avoid upgrading if the cluster is in a bad state.

**Comment by jclab-joseph** [comment]
@parth-gr I changed placement while adding osd to CR. So osd update was triggered.
rook image version is `rook/ceph:v1.5.11`.

@travisn Currently, if even one OSD dies, downtime is caused by min_size.
So Wouldn't it be better to do something like the following instead of changing skipUpgradeChecks?

1. The rook-ceph-operator first creates a new OSD.
2. (ceph itself duplicates the degraded object to the new OSD.)
3. The rook-ceph-operator waits for a healthy state and updates the rest of the OSD.

**Comment by travisn** [comment]
Agreed that ideally the operator would create new OSDs before getting stuck updating existing OSDs, which perhaps could otherwise get into a healthy state if the new OSD was created first. The reality is that the OSD reconcile is a complex process so I don't expect that to change anytime soon. 

Another option is to reduce min_size to 1. This can be done on the pool with:
```yaml
parameters:
  min_size: "1"
```

**Comment by BlaineEXE** [comment]
@jclab-joseph The OSD code is designed so that it **should** create new OSDs before updating existing OSDs. However, it will also try to opportunistically update existing OSDs while waiting on new OSDs to be provisioned. I'd like to understand more about the scenario you are seeing so I can figure out where a possible corner case might be existing. 

1. Can you show us the CephCluster resource/manifest before and after adding the new OSD? If not, please at least include the resource/manifest after adding the new OSD.
2. Please get us the full operator logs with ROOK_LOG_LEVEL=DEBUG
