### ISSUE TITLE
Implement rate limit for Object User

### ISSUE THREAD

**Issue by leseb** [rook/rook#9569]
**Is this a bug report or feature request?**
* Feature Request

https://docs.ceph.com/en/latest/radosgw/admin/#rate-limit-management

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by thotz** [comment]
This can be applied to OBC if needed, OBC points unique ceph object user

**Comment by BlaineEXE** [comment]
I think we should consider applying this to OBCs out of scope and only focus on limits for users. Since OBCs are in sustaining development with intent to be deprecated in favor of COSI (which has no plans for rate limits currently, as far as I'm aware), we don't gain a lot by implementing this for OBCs.

That said, I think the OBC/COSI ability to request buckets by resource is the future, and I wonder how much benefit users will gain from implementing this for CephObjectUser. IMO, this is a fairly low priority item unless I'm failing to imagine a use-case with some criticality.
