### ISSUE TITLE
During Ceph upgrade, fix OMAP reporting

### ISSUE THREAD

**Issue by nyarly** [rook/rook#9691]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Update OMAP reporting as part of Ceph upgrades.

**What is use case behind this feature:**
I've just updated a few Rook 1.6 clusters from Ceph v14 to v16. The update completed cleanly, but now all my OSDs are reporting `BLUESTORE_NO_PER_POOL_OMAP` - from what I can tell I now need to scale each OSD to 0, run the repair for OMAP, and then scale back to 1. Since one of my clusters as 156 OSDs, I'm not relishing this task.

**Environment**:

**Comment by travisn** [comment]
In the past there have been examples of where OSDs needed to be repaired, but Ceph found a way to repair them automatically, for example see #3539. As discussed in that issue, it would be quite complex for rook to detect this case and perform the operation. I'm surprised we haven't had this issue reported previously though since it should have affected upgrades to octopus/pacific long before now. Instead of running the osd repair, you can also [suppress](https://docs.ceph.com/en/latest/rados/operations/health-checks/#bluestore-no-per-pool-omap) this warning. I see that there is a similar warning for Pacific for the per-pg omap reporting, so again we will have this issue.

@jdurgin Is it ok to suppress these warnings or is it detrimental to health in the long term? Running the repair automatically has its design challenges...

**Comment by jdurgin** [comment]
It's fine to disable the warning, the only impact is lack of finer-grained stats and missing some performance improvements for pg deletion.

Agree there are challenges to this sort of on-disk upgrade - at some point it'd be nice to have these sorts of time consuming upgrade steps automated in a way that doesn't impact the users of the cluster too much.
