### ISSUE TITLE
CSI: CSI driver deployment and daemon set must be cleaned up when no CephCluster CR exists

### ISSUE THREAD

**Issue by Rakshith-R** [rook/rook#9693]
Currently Rook deploy CSI driver deployment and daemonset when it detects a CephCluster CR. 
When CephCluster CR is deleted, the driver is not deleted. 

https://github.com/rook/rook/blob/d24eab2229a73a844ab8c5b3db9066e52051baee/pkg/operator/ceph/csi/controller.go#L108-L125

We should be cleaning up the driver deployment and daemonsets when number of CephCluster CR is zero.

---
Scenario where it can cause issue: 
- When CSIAddons controller is being used
- CSI driver pods create CSIAddonsNode CR, on which the controller sets finalizer
- If the namespace is deleted and CSIAddons controller is deleted before Rook operator 
- Then CSIAddonsNode CR will remain with finalizer blocking the deletion of namespace.

cc @travisn @leseb @nixpanic @Madhu-1

**Comment by Madhu-1** [comment]
Yes, this is one for the solution, and am not sure this is the right one. because we cannot enforce the dependency of other components which are outside of the ceph/rook on the Rook components.

This problem is because of adding the finalizers on the CSIAddonsNode object, if the namespace is deleted the order of deletion is not defined hence the `CSIAddons controller` might get deleted first and when csi pods are going down they have the ownerref on the CR which got created by them as the `CSIAddons controller` is already deleted and we have finalizers on the `CSIAddonsNode` CR the CR cannot be deleted and hence the csidrivers cannot be deleted.

IMO, this is the problem with the controller, and this needs to be fixed on the controller side, not at all on the storage provider's side.

one reason for adding a finalizer is to make sure we clean up the connection which is added in memory in the `CSIAddons controller`. as the controller is getting restarted/deletion no point in blocking the operation of CR deletion as the connections are already deleted and when the controller comes up if there are any CR's it will open the connection and store it. in the worst case if there is any race you might end up making one RPC call to an invalid connection and its fine as it's not frequent.

another idea is as it's the problem with the controller we can set some priority on the controller to make sure it gets evicted at last from the node (not sure it works but just a thought)

**Comment by Rakshith-R** [comment]
> Yes, this is one for the solution, and am not sure this is the right one. because we cannot enforce the dependency of other components which are outside of the ceph/rook on the Rook components.
> 
> This problem is because of adding the finalizers on the CSIAddonsNode object, if the namespace is deleted the order of deletion is not defined hence the `CSIAddons controller` might get deleted first and when csi pods are going down they have the ownerref on the CR which got created by them as the `CSIAddons controller` is already deleted and we have finalizers on the `CSIAddonsNode` CR the CR cannot be deleted and hence the csidrivers cannot be deleted.

Correction, the ownerRef does not have blockOwnerDeleteion set to true, so csidrivers will be deleted, only `CSIAddonsNode` CR will left with in terminating state with finalizer blocking deletion.

Keeping the CSIAddons part out of this, It still is a good idea to cleanup CSI driver deployment and daemonset when there is no CephCluster CR IMO. 
It will prevent unnecessary consumption of resources(2 provisioner pods and one plugin pod per node).

**Comment by Madhu-1** [comment]
> > Yes, this is one for the solution, and am not sure this is the right one. because we cannot enforce the dependency of other components which are outside of the ceph/rook on the Rook components.
> > This problem is because of adding the finalizers on the CSIAddonsNode object, if the namespace is deleted the order of deletion is not defined hence the `CSIAddons controller` might get deleted first and when csi pods are going down they have the ownerref on the CR which got created by them as the `CSIAddons controller` is already deleted and we have finalizers on the `CSIAddonsNode` CR the CR cannot be deleted and hence the csidrivers cannot be deleted.
> 
> Correction, the ownerRef does not have blockOwnerDeleteion set to true, so csidrivers will be deleted, only `CSIAddonsNode` CR will left with in terminating state with finalizer blocking deletion.
> 

:+1: great Thanks for the correction.  but what is the point in keeping the CRD when you have no users?

> Keeping the CSIAddons part out of this, It still is a good idea to cleanup CSI driver deployment and daemonset when there is no CephCluster CR IMO. It will prevent unnecessary consumption of resources(2 provisioner pods and one plugin pod per node).

It's a  different problem but we should not worry about that one. open a separate issue to track it. it might be done for a reason

**Comment by Rakshith-R** [comment]
Opened a new issue https://github.com/rook/rook/issues/9697, closing this one.
