### ISSUE TITLE
ceph orch osd rm

### ISSUE THREAD

**Issue by nyarly** [rook/rook#9695]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I'd like to be able to issue `ceph orch osd rm` and clean out OSDs for storageClassDeviceSets that have been removed from a CephCluster. If #8235 is being closed, which seems reasonable, a single command to remove the stray OSDs would be useful.

**What is use case behind this feature:**

I needed to update the arrangement of devices in our CephClusters. The result was effectively a full compliment of OSDs that are no longer associated to the CephCluster, which put the cluster into a warning state and prevent clean reconciliation, and that are surplus to requirements.

My current process is to `osd out` each one, wait for backfill to complete, scale to 0, and purge. Once they're all out of the cluster, I remove the deployments. It's several hours of toil.

**Comment by travisn** [comment]
@nyarly The recommended way to remove an OSD in rook is documented in the [OSD removal](https://rook.github.io/docs/rook/v1.8/ceph-osd-mgmt.html#remove-an-osd), and more specifically there is an example of how to use the [OSD purge job](https://rook.github.io/docs/rook/v1.8/ceph-osd-mgmt.html#purge-the-osd-from-the-ceph-cluster). Using the `orch` commands really doesn't seem like the right approach for Rook since it pushes K8s implementation into the Ceph mgr module. With the osd purge job it keeps everything in Rook.

**Comment by nyarly** [comment]
I'll need to look at the purge job; reviewing those docs, I'm not sure I can reduce the number of OSDs to 0 in a set.

What happened in my case as that I'd removed the sets entirely, leaving the OSD Pods orphaned. When I tried to recreate a set with a count of 0, the change was rejected because the count was not `> 0`. It's possible I could have created with 1 and then updated to 0; I wound up proceeding with the manual removal process from those docs.

Maybe I don't understand the architecture around `orch` modules - I had the impression they served as an interface to the orchestration system on the backend. I'm surprised then by the idea that the Kubernetes action would need to be in the Ceph module. My mental model is that `ceph orch osd rm` would send a request to Rook, which could then perform what would effectively be a little reconciliation task.

Also I feel the need to acknowledge that this feature request comes by way of high praise to the Rook project in general. I've just upgraded it twice and upgraded Ceph as well, and everything ran smooth as silk. Surely then, that wizardry could extend to retiring OSDs, right?

**Comment by travisn** [comment]
@nyarly Ok, so you really just want to remove all the OSDs in a device set? How about the following?
- Remove the device set from the cluster CR. The operator will error out as described in #8235 (temporarily)
- Remove each of the OSDs that were in the device set, according to the OSD removal instructions mentioned previously.
- The operator should no longer cause errors after the OSDs are removed.

Rook doesn't make it too easy to remove OSDs automatically since it could cause data loss if done unintentionally.

The `ceph orch` module doesn't manage creation of the OSDs, so having it manage the the removal of OSDs doesn't seem natural either, but I get your point that it would be a nice simple command.

**Comment by nyarly** [comment]
Okay; I'll stick with the approach I've been following so far, which is what you've laid out here.

It does seem like is, in part, the "delete" case of declarative configuration. When an OSD is missing its corresponding configuration, it's not clear how Rook should handle that - leaving it up to the human operator makes sense.

I'm understanding you to say "this might be nice to have, but it's not getting into scope." If that's accurate, feel free to close the issue.

**Comment by travisn** [comment]
In the early days of Rook the operator would automatically remove OSDs that were no longer part of the desired state in some scenarios (using devices explicitly listed in the `nodes` section). What we found is that even if those devices were removed from the cluster CR, sometimes it wasn't intentional, and then the operator would cause data loss by automatically removing the OSDs. So our approach is firmly now that removing OSDs must be intentionally triggered by the admin even if desired state was removed from the cluster CR. 

Good discussion, thanks for raising your views. I'll go ahead and close it for now.
