### ISSUE TITLE
Allow replica=1 replicated pools

### ISSUE THREAD

**Issue by mulbc** [rook/rook#9736]
https://github.com/rook/rook/blob/07f101e1576828c832fd76843f510b0de3b009bf/pkg/operator/ceph/pool/validate.go#L131

Allow for p.Replicated.Size == 1 and p.Replicated.ReplicasPerFailureDomain == 1 at the same time for replica=1 work

**Comment by travisn** [comment]
@mulbc Replica 1 pools are allowed today. Did you test this and see the error, or is this just from code inspection? This code path is not expected to error out with replica 1 since `replicasPerFailureDomain` defaults to 0 and is only expected to be set in stretch clusters where there are two replicas per domain. Though we probably should not have exposed that setting and just dealt with it internally for stretch clusters.

**Comment by mulbc** [comment]
I did face an issue here, because the minimum for this field is set to 1:
https://github.com/rook/rook/blob/3fc49f2b9a070b5c9a785b5d2db0af94334a5068/pkg/apis/ceph.rook.io/v1/types.go#L862

I did not use Rook-Ceph directly, but tried this with a modified version of ocs-operator.

It looks like I was just able to circumvent this issue by setting the reconcileStrategy to init.

**Comment by travisn** [comment]
It's also tagged with `+optional` so it doesn't need to be specified.

**Comment by BlaineEXE** [comment]
It seems like this is possible with Rook already today, so closing this issue.
