### ISSUE TITLE
An error starting an e2e test cluster needs more debug info

### ISSUE THREAD

**Issue by travisn** [rook/rook#979]
When the test cluster fails to start, whether failed mon or osd pods, the tests will time out waiting for the rook-api pod to start. A couple thoughts to improve this:
- The test could print the status of all the rook pods to the log
- The logs were not collected for the daemon pods.

There is also bug in `GetPodHostID()` where the podNames[0] can be the empty string. 
https://github.com/rook/rook/blob/master/tests/framework/utils/k8s_helper.go#L514

Then it leads to a crash in the test as seen in this build.
https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-975/14/pipeline

In the log, notice there is no argument for `kubectl get` before the `-o`. That means the `rook-api` pod was not found from the previous command.
```
Running command: kubectl get pods -l app=rook-api -o wide --no-headers=true -o name -n rook
Running command: kubectl get  -o jsonpath='{.status.hostIP}' -n rook
```

**Comment by dangula** [comment]
1)  log files collected in integration tests need to say what test the pod log is from and what env the pod log file was from (GCE or AWS).  when you look at the test artifacts its just a big mixed list with no indication of what each pod log is for besides the suite it belongs to.
2) cluster health should be checked after cluster setup before moving on with the test case steps.  if the cluster’s mons/OSDs aren’t running and functional then there’s no point in running the test case because we’ll just get red herrings.
