### ISSUE TITLE
Operator does not detect changes to configmap rook-config-override

### ISSUE THREAD

**Issue by stephan2012** [rook/rook#9802]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The Rook Ceph Operator does not detect changes to the Kubernetes ConfigMap `rook-config-override`.

**Expected behavior:**
The Rook Ceph Operator picks up changes in the ConfigMap `rook-config-override` and propagates them to the Ceph components.

**How to reproduce it (minimal and precise):**

Change the ConfigMap `rook-config-override`, e.g.,

```ini
    [mon]
    mon_data_avail_warn = 20
```

**File(s) to submit**: N/A

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS
* Kernel (e.g. `uname -a`): `Linux n0211 5.4.0-99-generic #112~18.04.1-Ubuntu SMP Thu Feb 3 14:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: on-prem
* Rook version (use `rook version` inside of a Rook Pod): `v1.8.5`
* Storage backend version (e.g. for ceph do `ceph -v`): `16.2.7`
* Kubernetes version (use `kubectl version`): `v1.23.4`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `kubeadm`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
The current documentation for the [custom ceph.conf](https://rook.github.io/docs/rook/v1.8/ceph-advanced-configuration.html#custom-cephconf-settings) indicates:
```
If the rook-config-override ConfigMap is created before the cluster is started, the Ceph daemons will automatically pick up the settings. If you add the settings to the ConfigMap after the cluster has been initialized, each daemon will need to be restarted where you want the settings applied
```
Commonly when there is a change to the ceph.conf, it only applies to a subset of the daemons and all of them don't need to be restarted. So there may be a difference in opinion for whether the operator really should automatically restart all the daemons. 

Instead of using the ceph.conf overrides, another approach is to apply a ceph setting in the toolbox with `ceph config set`, and the ceph daemons would pick up the setting automatically with no restart. Is that an option for you? Or can you provide more details on the scenario required?

**Comment by stephan2012** [comment]
Thanks for your feedback, @travisn.

Right, using the toolbox, I could apply almost any change. However, this is not convenient, error-prone, and not ideal when config changes must be applied automatically to many daemons in production systems. The operator is the natural place to push config changes to Ceph since it knows all components and their state. It feels wrong having to address this with the favorite automation tool.

Use-cases include simple, administrative changes (like setting warning or alarming threshold) and setting critical parameters (e.g., `bluestore_allocator`, `bluefs_allocator`) to work around bugs in Ceph OSDs and prevent crash loops on the next startup. 

Of course, restarting all daemons for every change could be much activity. However, a more sophisticated approach requires a more in-depth analysis of the config file by the operator.

**Comment by travisn** [comment]
Understood, it would be helpful on those occasions. Hopefully you're not needing this very often though if it's to workaround bugs.

A workaround could be to apply a change to the cluster that will cause a restart of the daemons that need to be restarted. For example, adding [labels](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L175-L181) will cause the daemons to be restarted. The labels can also be targeted at specific daemons to avoid the restart of all types of daemons if needed.

The operator could certainly implement the daemon restart by taking a hash of the configmap and adding it to the daemon pod specs, which would cause a restart in the expected rolling fashion. 

Though I'm inclined to document the workaround with labels instead of implementing it. Would the approach with labels work for you?

**Comment by stephan2012** [comment]
> A workaround could be to apply a change to the cluster that will cause a restart of the daemons that need to be restarted. For example, adding [labels](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L175-L181) will cause the daemons to be restarted. The labels can also be targeted at specific daemons to avoid the restart of all types of daemons if needed.

That would basically externalize the process of propagating changes to Ceph, but it seems feasible. 

> The operator could certainly implement the daemon restart by taking a hash of the configmap and adding it to the daemon pod specs, which would cause a restart in the expected rolling fashion.

Is there any reasonable way to propagate changes online, i.e., without restarts?

> Though I'm inclined to document the workaround with labels instead of implementing it. Would the approach with labels work for you?

Probably. Will test occasionally.

**Comment by travisn** [comment]
> > The operator could certainly implement the daemon restart by taking a hash of the configmap and adding it to the daemon pod specs, which would cause a restart in the expected rolling fashion.
> 
> Is there any reasonable way to propagate changes online, i.e., without restarts?

The only way for the ceph daemons to pick up changes to the ceph.conf overrides is by restarting the daemon. If you want to avoid the daemon restarts you would need to use the `ceph config set` command from the toolbox as mentioned earlier. The daemons pick up those updates without a restart.

**Comment by stephan2012** [comment]
Okay, applying a change to an annotation seems to work well.

@travisn, shall we close this issue or keep it as a feature request?

**Comment by travisn** [comment]
@stephan2012 I'm inclined to just add a note to the [ceph.conf override docs](https://rook.github.io/docs/rook/v1.8/ceph-advanced-configuration.html#custom-cephconf-settings) about how to use the annotations workaround. Let's keep this open until that's updated.

**Comment by stephan2012** [comment]
Thank you, @travisn!
