### ISSUE TITLE
Rook 1.8.6: creating OSDs with LVM?

### ISSUE THREAD

**Issue by spdfnet** [rook/rook#9831]
I see that now devices are used 'raw' and the infamous atari partition IDs are to stay.
But I don't seem to find a way to create OSDs with LVM, to keep existing production clusters sane.

~~I've also seen multiple partitions being created on some devices, similar to what happens when you want to keep RocksDB on the first sectors of a disk. But that just speculation on my part.~~
(lsblk doesn't like atari partitions)

Cluster storage configuration is as simple as it can get:
```
  storage:
    useAllNodes: true
    useAllDevices: true
```

Staying on 1.8.5 for the rest of the life of the cluster doesn't seem ideal.

**Comment by travisn** [comment]
> I see that now devices are used 'raw' and the infamous atari partition IDs are to stay.

The atari partition IDs are not expected on the latest rook and ceph releases. If you see some atari partitions, please do provide more details so we can troubleshoot it. 

> Staying on 1.8.5 for the rest of the life of the cluster doesn't seem ideal.

Again, more details will help understand the issue so we can get you past this.

**Comment by BlaineEXE** [comment]
There is nothing Rook can do to prevent the linux kernel from recognizing certain on-disk formats as atari partitions. This is because the linux kernel's implementation of atari support is more loose than the atari spec. However, Ceph has been patched and should not be negatively affected by the atari partitions any more. 

Unless you are seeing the Rook create more disks than it should, or if there are other issues with the Ceph cluster, this is not  bug for Rook itself.

If the tooling you use on your nodes is affected by the atari partitions, you will have to update the tooling, or you can create a single whole-disk partition on each disk which won't show up as atari partitions.

**Comment by spdfnet** [comment]
If that was not clear enough, Rook v1.8.5 creates new OSDs with LVM.
1.8.6 has a different behaviour that cannot be overridden.

**Comment by travisn** [comment]
@spdfnet Can you clarify the requirement to create OSDs with LVM? Our assumption is that it is not required in most scenarios.

**Comment by BlaineEXE** [comment]
And indeed LVM is not preferred since it adds more failure modes to running Ceph OSDs. Raw mode is preferred when possible to ensure OSDs are maximally stable.

**Comment by spdfnet** [comment]
I can see there is still logic to create LVM OSDs in certain circumstances, and the Rook project is maintaining those flows.

**Comment by travisn** [comment]
@spdfnet Is this about keeping track of which devices are in use by rook osds? If so, disks consumed for raw mode can be seen by looking at the disk label such as:
```
$ sudo blkid /dev/vdd
/dev/vdd: TYPE="ceph_bluestore"
```

Or is there another reason to require lvm? If there is a need we could allow overriding to use lvm instead of raw mode, but we have seen better stability with raw mode so we hesitate to support lvm when it otherwise doesn't need to be.

**Comment by spdfnet** [comment]
Given some other open issues in Ceph and this very same repo, the new behaviour is unreliable and not properly tested.

**Comment by travisn** [comment]
@spdfnet Which issues are you referring to? 

As a data point, OSDs on PVCs (following the cluster-on-pvc.yaml example) have always been on raw mode without issues.

**Comment by spdfnet** [comment]
> @spdfnet Which issues are you referring to?
The ones you are participating in and others, not hard to find.

Also, things like these... :
```
[Tue May 10 13:12:52 2022]  sdap: AHDI sdap1 sdap2 sdap4
[Tue May 10 13:12:53 2022]  sdaq: AHDI sdaq1 sdaq2 sdaq4
[Tue May 10 13:12:57 2022]  sdv: AHDI sdv1 sdv2 sdv4
[Tue May 10 13:12:58 2022]  sdcx: AHDI sdcx1 sdcx2 sdcx4
```
... basically confuse the OS, break some of the standard tooling and looks pathetic in the `ceph_volume.process` logs.
I know it was a Ceph decision, but who is using it in production after doing minimal tests?

**Comment by travisn** [comment]
The main issue with raw mode was really #7940 with the atari partitions. The fix had been fully validated, thus we reenabled the raw mode. 

What standard tooling is broken? Do you mean it's difficult to detect which devices are in use? There are other ways to detect devices in use as mentioned previously [here](https://github.com/rook/rook/issues/9831#issuecomment-1083626044). 

What is the issue with ceph-volume logging? It would be helpful to open a [Ceph tracker](https://tracker.ceph.com/) to improve that logging.

There are many users with it in production in raw mode. I know there are many production deployments using OSDs PVs (cluster-on-pvc example) since Rook v1.1 that have always used raw mode. Removing LVM has really simplified many issues around OSDs. The only issue I'm really understanding is with tooling if you're keeping track of the devices outside rook.

**Comment by BlaineEXE** [comment]
Also, just to reiterate, the AHDI partitions showing up are a Linux Kernel bug where Atari/AHDI detection is implemented to accept a more broad definition of an AHDI partition than the actual Atari spec. There are bug reports about this kernel behavior that go back 15+ years. It is neither a Ceph bug nor a Rook bug.

Additionally, the Atari code doesn't have an active maintainer that I am aware of, that kernel code is 20+ years old, and it would take years for a kernel fix to make it into upstream Ceph images. Because of those reasons, the Ceph community (including the Ceph creator, Travis, and myself) decided to implement the best workaround possible in Rook and in Ceph to at least make sure Ceph isn't affected.

If you wish to avoid the AHDI partitions showing up on your nodes, you have 2 options:
- run a Linux kernel on your nodes that is built with Atari support disabled
- patch the Linux Kernel Atari drivers to remove the bug, build that kernel, and run it on your nodes

**Comment by spdfnet** [comment]
Solved by upgrading to cephadm.
