### ISSUE TITLE
Discussion: Rook still creates resources that could be monitoring-implementation specific

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#9996]
Rook still creates CoreOS/Prometheus related ServiceMonitors for external clusters. ServiceMonitor, from my reading, still seems to be specific only to Prometheus, so we should consider whether it continues to be within Rook's purview to create and manage this resource.

Rook keeps this resource up-to-date when the active manager switches over. So there may be some reason to still keep it in Rook; however, I think this may still be setting a poor precedent.

Rook already creates and keeps up-to-date a service for the monitoring endpoint. For prometheus users, can we instead instruct them to configure prometheus to use the service instead of keeping a ServiceMonitor?

@travisn @leseb 

Related: #9837

**Comment by travisn** [comment]
From our [discussions a couple months back](https://github.com/rook/rook/pull/9503#issuecomment-1018910785), we had similar questions but I don't see it captured in that thread. The key point for me is that the PrometheusRule CR is static and will not change at runtime beyond any customization from a post-processor. However, the service monitor needs to be updated with label selectors to point to the active service. If it's not being updated by rook, it's not going to be updated dynamically according to the active mgr. Since labels need to be updated for the active mgr, that was an intentional solution for the mgr failover scenario. Not sure how a service could be used in place of a service monitor?

**Comment by BlaineEXE** [comment]
Yes. And I can see that happening in the code. This could still be a bit of a problem if other monitoring applications have their own version of ServiceMonitor. Then we might be obligated to do the same thing. I understand the utility as the code is written, and I certainly don't have full domain understanding, so I could be missing something. That said, it sill seems non-ideal to have Rook create resources that it doesn't really own unless it's absolutely necessary. So I wonder if we could do away with the ServiceMonitor.

The thing that suggests to me that it might be possible is that we already create a service for the manager. Inherently, prometheus scrapes an address at a given port. I believe ServiceMonitor is a concept for using prometheus in Kubernetes that helps auto-discover (sort of) applications that Prometheus can monitor. But it isn't critical for Prometheus itself. So I suspect it is also possible to configure Prometheus to use an address+port, which would allow it to use Rook's service, and then we would have no reason to manage outside resources. While this limits the (hand wavy) auto-discovery, it means that Rook isn't taking ownership of things outside of its purview.

**Comment by BlaineEXE** [comment]
To my point above, if Rook doesn't create a ServiceMonitor, I believe we can just instruct the user to create an **External**ServiceMonitor: https://jpweber.io/blog/monitor-external-services-with-the-prometheus-operator/

**Comment by travisn** [comment]
That blog is discussing how to monitor a service that is external to the k8s cluster. In this case, the monitoring endpoint is inside the cluster so it seems different. Also, that blog also creates a ServiceMonitor resource, so we're back to requiring a ServiceMonitor CR anyway. 

I don't see any design issue with treating specific types of resources as first class citizens. Prometheus is a core service that we want to integrate tightly with, so using its types seems very appropriate. If there is another service we need to integrate tightly with in the future, we can then use its types as well. 

We really still treat the PrometheusRule CR as a first class citizen, we just moved it to the helm chart instead of having the operator create it. But I don't see moving the ServiceMonitor resource to the helm chart since it requires a dynamic update.

**Comment by BlaineEXE** [comment]
I believe integrating tightly with Prometheus is fine. I also believe the Helm chart is the better place to do that. Using the ExternalServiceMonitor to point to the mgr Service doesn't require Rook to create the ExternalServiceMonitor, and I believe allowing users to choose whether to deploy that or not via Helm is a better design. There is no need to build that into the operator. By removing unnecessary points from the operator, we make it easier for users to choose what they want and don't without putting complex logic into Rook itself, we allow Rook to have reduced privileges, and we allow Rook to be used more compositionally as a part of a whole rather than forcing a monolith architecture.

**Comment by travisn** [comment]
Is there a resource type `ExternalServiceMonitor`? I don't see it in the blog. Or you're just referring to using a different approach where a static ServiceMonitor can be used to point to the mgr service? Sounds great if we can make the service monitor static, installed by the helm chart, and stop updating it from the operator code.

**Comment by BlaineEXE** [comment]
I must have gotten that confused with something else I was reading. Upon re-reading, it seems like ServiceMonitor should looks at k8s services and not pods, so it should be easy for users to create a ServiceMonitor themselves to point to Rook's mgr Service. And it should ideally continue work upon mgr failover with only a slight blip when the mgr converts the endpoint to point to the latest mgr. Something to test for sure.
